### ISSUE TITLE
Plans for supporting tvOS?

### ISSUE THREAD

**Issue by zenangst** [johnno1962/InjectionIII#1]
Hey!

It brings me joy to see that this project it still being actively maintained, stellar is the right word for all the effort that you put into this. Anyways... I was gonna try this out in a project and I quickly ran into the issue that there is no tvOS bundle which results in the following message appearing upon app launch:

```
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): no suitable image found.  Did find:
	/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection: mach-o, but not built for tvOS simulator
```

I bet this is not your top priority but I was just wondering if you see this happening on the horizon.

**Comment by johnno1962** [comment]
Ha, completely forgot. I’ve made what could be the necessary changes. Can you give it a testing?

**Comment by zenangst** [comment]
Seems like we are getting there, now I get a different error when saving a file:

```
Compiling /Users/{username}/Code/ProjectX/ViewController.swift

real	0m0.036s
user	0m0.003s
sys	0m0.030s
*** Re-compilation failed (/tmp/eval2.sh)
<unknown>:0: error: cannot open file '/var/folders/k5/9jl6w9bn5ql_x7zlv3_3cb3r0000gn/T/sources-98b805' (No such file or directory)
<unknown>:0: error: this mode requires at least one input file
 ***
```

**Comment by zenangst** [comment]
Tried doing some debugging and it seems like its looking for the wrong file, for a split second I can see that there is another file being generated in `/var/folders/k5/9jl6w9bn5ql_x7zlv3_3cb3r0000gn/T/` but it does not match the file that is referenced in the Xcode console. Hope that helps :)

**Comment by johnno1962** [comment]
: ( can you send me eval2.sh? injection at johnholdsworth.com

**Comment by johnno1962** [comment]
Is this the new build system or the old? WMO or not?

**Comment by zenangst** [comment]
@johnno1962 I sent you an email with some eval sample .sh files.

Here is some info about the project settings:

### Optimization Level
<img width="746" alt="screen shot 2017-11-22 at 08 57 03" src="https://user-images.githubusercontent.com/57446/33115947-2746018e-cf63-11e7-8429-5127baa8d8eb.png">

### Test scheme info
<img width="358" alt="screen shot 2017-11-22 at 08 59 10" src="https://user-images.githubusercontent.com/57446/33116031-7a763acc-cf63-11e7-9ede-fa2eda7df41a.png">

### Swift compiler general
<img width="450" alt="screen shot 2017-11-22 at 09 01 58" src="https://user-images.githubusercontent.com/57446/33116143-eefeac80-cf63-11e7-9a87-844c4684bf71.png">

### Shared workspace settings
<img width="509" alt="screen shot 2017-11-22 at 09 03 54" src="https://user-images.githubusercontent.com/57446/33116190-22eefb12-cf64-11e7-9d62-744099ecaf34.png">

Hope this helps!

**Comment by johnno1962** [comment]
Looks like > 128 files… not implemented as yet

**Comment by zenangst** [comment]
Ah that old beastie... I remember that :)

**Comment by johnno1962** [comment]
OK, wasn’t too bad… Can you try now?

**Comment by zenangst** [comment]
@johnno1962 works like a charm now, closing this issue! ⭐️

**Comment by johnno1962** [comment]
Excellent.. Anything else let me know. I added in the test running code as well.
