### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by Mosaics** [johnno1962/InjectionIII#100]
💉 *** Compiling /xxx/xxxx/xxxx/xxxxx.swift ***
💉 *** Re-compilation failed (/Users/xxx/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
<unknown>:0: error: error opening input file '/xxx/xxxx/xxxx/xxxxx.swift' (No such file or directory)
 ***

In fact, the file exists and is not duplicated.

My project is swift and object-c mixed programming.

AppDelegate.m  define

#if TARGET_IPHONE_SIMULATOR && DEBUG
  [[NSBundle bundleWithPath:@"/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle"] load];
#endif

swift extension file  define

extension UIViewController {
  // MARK: - only used for hot reload
  #if targetEnvironment(simulator) && DEBUG
    @objc func injected() {
      view.subviews.forEach({ $0.removeFromSuperview() })
      view.layer.sublayers?.forEach({ $0.removeFromSuperlayer() })
      viewDidLoad()
    }
  #endif
}

How can I solve this problem?

**Comment by johnno1962** [comment]
Sounds like a case sensitivity problem to me. The filename and path must match exactly.

**Comment by Mosaics** [comment]
> Sounds like a case sensitivity problem to me. The filename and path must match exactly.


now is this problem

/Users/xxx/xxx.h:12:9: note: in file included from /Users/xxx/xxx.h:12:
#import "ddd.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/xxx/App-Bridging-Header.h'
 ***
