### ISSUE TITLE
There's no way to show it

### ISSUE THREAD

**Issue by CreatSuns** [johnno1962/InjectionIII#101]
My emulator runs normally. I change the code, but I cannot change it after saving. The log I get is as follows
```
💉 *** Compiling /Users/lishihang/Desktop/asd/asd/ViewController.m ***
💉 Loading .dylib - Ignore any duplicate class warning...
objc[4037]: Class ViewController is implemented in both /Users/lishihang/Library/Developer/CoreSimulator/Devices/E60C148D-0324-4667-A03B-9C8C13C9B0EE/data/Containers/Bundle/Application/36260E11-54A9-4BD1-ACE8-8018F23DE36B/asd.app/asd (0x1093e7ce8) and /Users/lishihang/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval105.dylib (0x1271bd120). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning...
```

**Comment by zenangst** [comment]
hey @CreatSuns, If you look closer at the message you'll see that this should be ignored :)

Messages that have the prefix `💉` belong to `InjectionIII` whereas `Class ViewController is implemented…` belong to the system and is nothing that we can opt-out from showing.

**Comment by CreatSuns** [comment]
I can implement it but I have to declare the injected method. Is there any way I can inject it into real time without having to declare it?

**Comment by CreatSuns** [comment]
Thanks for your advice

**Comment by jayhe** [comment]
add an @objc
injected() method or subscribe to the `"INJECTION_BUNDLE_NOTIFICATION"`.
