### ISSUE TITLE
Injection connects but nothing happens after

### ISSUE THREAD

**Issue by tfang0252** [johnno1962/InjectionIII#102]
I have added below to didfinishlaunching
        #if DEBUG
        Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle")?.load()
        #endif

and this in my view controller  
@objc func injected() {
        viewDidLoad()
    }

I get the injection connected message but nothing happens when I change something and save the file

**Comment by zenangst** [comment]
That is interesting, just to make sure, it is monitoring the correct folder?
You can try and select the project folder again to see if that has any effect.

**Comment by tfang0252** [comment]
Yep found out that was the problem, thanks!

**Comment by zenangst** [comment]
@tfang0252 oh that is awesome! Mind sharing what it was? It might help someone else :)

**Comment by tfang0252** [comment]
Open recent didn't seem to select the right project, so I just did open project and selected the right one.

**Comment by zenangst** [comment]
@tfang0252 awesome, thanks for the info and enjoy injecting code at runtime :)
