### ISSUE TITLE
Injection does not work with Whole Module Optimization

### ISSUE THREAD

**Issue by chance395** [johnno1962/InjectionIII#103]
hello,I use the object-c but it returun
💉 *** Could not locate compile command for /Users/brain/Desktop/testtt/testtt/ViewController.m
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.) ***

I had saw the issues related  but all were swift projects ,can help me?
Mac OS :10.13.6
xcode：10.1
injectionlll :appstore 1.4

**Comment by zenangst** [comment]
@chance395 hello mate, mind sharing some more details about your implementation so that you can help us narrow the issue down?

**Comment by chance395** [comment]
ok, I creat a object-c project and had set in AppDelegate.m  as below ->
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
#if DEBUG
    // iOS
    [[NSBundle bundleWithPath:@"/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle"] load];
    
#endif
 
    return YES;
}

#import "ViewController.h"

@interface ViewController ()

@property (nonatomic,strong) UILabel *testLabel;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.testLabel =[[UILabel alloc]initWithFrame:CGRectMake(30, 100, 300, 30)];
    self.testLabel .backgroundColor =[UIColor redColor];
    [self.view addSubview:self.testLabel];
    
}

- (void)injected
{
    self.testLabel.backgroundColor =[UIColor blueColor];
    NSLog(@"dddd");
}

@end

// the is no another ViewController more  
the print-->>
💉 Injection connected, watching /Users/brain/Desktop/testtt/**
💉 *** Could not locate compile command for /Users/brain/Desktop/testtt/testtt/ViewController.m
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.) ***


the environment

Mac OS :10.13.6
xcode：10.1
injectionlll :appstore 1.4

@zenangst

**Comment by zenangst** [comment]
@chance395  Does your target collect code coverage details on your tests? If so, try disabling them for the current target.

Also, double check that the path is correct in terms of casing.

**Comment by bimawa** [comment]
@zenangst 
Have the same issue, where can I check it? And what do you mean under "Also, double check that the path is correct in terms of casing."?

**Comment by thinkWind** [comment]
> hello,I use the object-c but it returun
> 💉 *** Could not locate compile command for /Users/brain/Desktop/testtt/testtt/ViewController.m
> (Injection does not work with Whole Module Optimization.
> There are also restrictions on characters allowed in paths.
> All paths are also case sensitive is another thing to check.) ***
> 
> I had saw the issues related but all were swift projects ,can help me?
> Mac OS :10.13.6
> xcode：10.1
> injectionlll :appstore 1.4

我也遇到这个问题了，我这边的解决方法是：查看类文件所在路径是否有非法字符，特别是包含中文之类的字符。去掉非法字符即可解决。

**Comment by Liuruyong** [comment]
碰到同样的问题。我这边错误原因，同一个目录下有多个xcworkspace文件，关联到错误工程了。

InjectionServer.mm 192行， [self setProject:projectFile]; 这行加断点，发现工程不对。

**Comment by SSenocico** [comment]
Hi,
I just updated to Xcode 11.4 and I now I encounter the same issue...
![Screenshot 2020-03-26 at 11 56 42](https://user-images.githubusercontent.com/60232541/77633955-dfc11680-6f58-11ea-8be3-7372fb815a10.png)

**Comment by johnno1962** [comment]
Hey @zenangst, have upgraded to Xcode 11.4 yet? Is injection still working? The betas where fine.

**Comment by zenangst** [comment]
Yeah I'm using Xcode 11.4, been using it today. I'll do some more testing when life allows but initially everything seems fine.

**Comment by FarhanAmjad95** [comment]
Could not locate compile command for {Path}
here is my optimisation settings:

Mac OS : Version 13.6
Xcode：15.0
injectionlll :appstore Version 4.5.2

<img width="653" alt="Screenshot 2023-10-14 at 1 23 23 AM" src="https://github.com/johnno1962/InjectionIII/assets/32298468/3403648f-a889-4da8-ae14-659a2f9ddf66">

**Comment by johnno1962** [comment]
HI, what version of Xcode, InjectionIII app, iOS/macOS is this? Are you using the app or "standalone" injection? Are you able to post the path to the file or email it to github at johnholdsworth.com. Without the path it's difficult to say more. Please check through the list of possible causes it prints carefully.

**Comment by FarhanAmjad95** [comment]
Hi @johnno1962 I have downloaded the macOS app from appstore and not using JAR file. It's working perfectly fine with other small apps but it's not working with my large scale app.

Xcode：15.0
injectionlll :appstore Version 4.5.2

here is the complete error:

💉 ⚠️ Could not locate compile command for /Users/amjad.farhan/Documents/Repositories/ETA-131-Filters/EtisalatUAE/EtisalatUAE/Digital2022/Scenes/EShop/Presentation/EShopViewController.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
5. The source file is an XCTest that has not been run yet.
6. Xcode has removed the build logs. Edit a file and re-run.
Try a build clean then rebuild to make logs available or
consult: "/var/folders/vk/jj1tndy14xz23rq9ck82tqkc0000gq/T/com.johnholdsworth.InjectionIII/command.sh".

**Comment by johnno1962** [comment]
Hi, the only things I notice is your home directory has a '.' in it though if you say small projects work it wouldn't be that and you are trying to use injection for a project in the 'Documents' directory which isn't always reliable. Are you sure you're not using Whole module Optimisation" or Bazel? All I can suggest from this end is you send to github at johnholdsworth.com, the command.sh file it mentions and the perl script mentioned inside that.
