### ISSUE TITLE
Swift4)App is working when putting debugging code in different life cycle method

### ISSUE THREAD

**Issue by tai-dev** [johnno1962/InjectionIII#104]
Hi, Thank you for making this service. It is really convenient.

Im code newbie and studying iOS app using Xcode 10 and Swift4.0.

I’ve found that the injection app starts to work when putting debugging code ( in readme file ) into `applicationDidBecomeActive` instead of `applicationDidFinishLaunching` at Appdelegate.swift.

can’t understand why and can see some error message, but it is working.

i want to report this. thank you.

objc[4749]: Class SimpleSocket is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8428) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f418). One of the two will be used. Which one is undefined.
objc[4749]: Class Xtrace is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8478) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f468). One of the two will be used. Which one is undefined.
objc[4749]: Class ClassInThisBundleX is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c84f0) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f4e0). One of the two will be used. Which one is undefined.
objc[4749]: Class SnapshotString is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8518) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f508). One of the two will be used. Which one is undefined.
objc[4749]: Class SnapshotZipped is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8568) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f558). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobePath is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c85e0) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f5d0). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeRetained is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8630) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f620). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeWeak is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8680) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f670). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeIvar is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c86a8) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f698). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeMethod is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c86f8) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f6e8). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeArray is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8770) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f760). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeSet is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c87e8) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f7d8). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeView is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8838) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f828). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeDict is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8860) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f850). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeSuper is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c88d8) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f8c8). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeClass is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8720) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f710). One of the two will be used. Which one is undefined.
objc[4749]: Class Xprobe is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8950) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f940). One of the two will be used. Which one is undefined.
objc[4749]: Class BundleInjection is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c89a0) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f990). One of the two will be used. Which one is undefined.
objc[4749]: Class InjectionClient is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c89f0) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4f9e0). One of the two will be used. Which one is undefined.
objc[4749]: Class XprobeSwift is implemented in both /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10 (0x1296c8ce8) and /Applications/InjectionIII.app/Contents/Resources/tvOSInjection10.bundle/tvOSInjection10 (0x12ab4fcd8). One of the two will be used. Which one is undefined.
2019-02-01 20:34:33.539826+0900 test[4749:31625] Error loading /Applications/InjectionIII.app/Contents/Resources/macOSInjection10.bundle/Contents/MacOS/macOSInjection10:  dlopen(/Applications/InjectionIII.app/Contents/Resources/macOSInjection10.bundle/Contents/MacOS/macOSInjection10, 265): no suitable image found.  Did find:
/Applications/InjectionIII.app/Contents/Resources/macOSInjection10.bundle/Contents/MacOS/macOSInjection10: mach-o, but not built for iOS simulator
💉 Injection connected, watching /Users/mac/Documents/dev/react-native/todo/ios_todo/test/**
💉 Injection connected, watching /Users/mac/Documents/dev/react-native/todo/ios_todo/test/**

**Comment by zenangst** [comment]
Hey @tai-dev, you should only have to connect in the application did launch, that should be more than enough to establish the connection and keep it going.

**Comment by tai-dev** [comment]
thank you for quick response.
ok, i will change my code

thank you!
