### ISSUE TITLE
Array out of bounds in + (id)my_mappedObjectForCoder:(id)decoder withIdentifier:(NSString *)identifier

### ISSUE THREAD

**Issue by Gocy015** [johnno1962/InjectionIII#106]
Hi, me again.

I found another crash in `+ (id)my_mappedObjectForCoder:(id)decoder withIdentifier:(NSString *)identifier`, let me explain the situation.

1. Create a storyboard and create 2 view controllers in it, let say it's called Master, Child.

2. Drag a couple of views into both scenes, and create outlet to their .m files.

3. **Set Master to root view controller, and inside Master's viewWillAppear, add Child's view to it.**

```objc
// Master.m
- (void)viewDidLoad {
    [super viewDidLoad];
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MasterDetail" bundle:[NSBundle mainBundle]];
    self.childVC = [storyboard  instantiateViewControllerWithIdentifier:@"ChildViewController"];
}
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    if (!self.childVC.view.superview) {
        [self.view addSubview: self.childVC.view];
    }
}
```

This will stably reproduce crash in  `+ (id)my_mappedObjectForCoder:(id)decoder withIdentifier:(NSString *)identifier`, at line

```objc
else
            return remapper.output[[remapper.order[remapper.orderIndex++] intValue]];
```

I fully understand the cause of this crash: when "recording" the mapping (remapper.inputIndexes != nil), `_loadViewFromNibNamed: bundle:` will only go through phase `viewDidLoad`. When you actually try to display the newly refreshed VC, it will go through the whole view controller life cycle, any view in IB that instantiates after `viewDidLoad` will cause `remapper.orderIndex` to exceed its max value.

I was able to workaround this by adding another if:
```objc
else if (remapper.orderIndex < remapper.order.count)
            return remapper.output[[remapper.order[remapper.orderIndex++] intValue]];
```

however i believe this shouldn't be the fix, further more, i still do not understand why we need to hook these two mapping method. If i disable the hook, sometimes i get a crash saying "[<UIProxyObject 0x600000f009e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key"; sometimes i get a complain "Missing proxy for identifier UpstreamPlaceholder-6rU-25-hPh" but everything works fine.

what does these hooks do ?

**Comment by johnno1962** [comment]
Hi @Gocy015, not sure I can be much more help here. This is some pretty ropey code that is more of a “best effort” than a solution to the general problem. Remapping is necessary as compiled xib contain connection objects to initialise outlets and actions but unfortunately these get random identifiers each time the file is saved. Remapping attempts to record the order the connections are created the first time the nib is loaded so the names can be shuffled around to connect everything correctly when the nib is reloaded. Not sure how much time you want to spend on this. It will be a very difficult problem to solve if it is even possible at all. But if you do come up with a solution...
