### ISSUE TITLE
Crash when working with generics

### ISSUE THREAD

**Issue by nerdycat** [johnno1962/InjectionIII#107]
Hey guy, thank you for this very useful tool.
Recently I encountered a problem when working with generics.
Here is a very simple example:

    class BaseViewController<T>: UIViewController {}

    class ViewController: BaseViewController<String> {
        var someVariable = 100

        @objc func injected() {
            print("injected")
            print(someVariable)        //EXC_BAD_ACCESS
            someMethod()               //EXC_BAD_ACCESS
        }
    
        func someMethod() { }
    }

**Comment by zenangst** [comment]
Hey @nerdycat, mind sharing some crash logs with us?
Note that `InjectionIII` and generics don't always go hand in hand so there might not be something that can be solved.

**Comment by nerdycat** [comment]
@zenangst It simply crash with EXC_BAD_ACCESS without any logs.

**Comment by zenangst** [comment]
@nerdycat ah like that. Would you mind making a test project so that we can test the issue in isolation?

**Comment by nerdycat** [comment]
Sure.
After injected, select ViewController.swift file and press cmd + s to reproduce the issue.

[InjectionWithGenerics.zip](https://github.com/johnno1962/InjectionIII/files/2884342/InjectionWithGenerics.zip)

**Comment by johnno1962** [comment]
There are limitations working with injecting generics. The most success we’ve had with this is https://github.com/johnno1962/InjectionIII/issues/57

**Comment by nerdycat** [comment]
@johnno1962 I see, thanks.
