### ISSUE TITLE
Using INJECTION_BUNDLE_NOTIFICATION and not seeing changes at runtime in the simulator.

### ISSUE THREAD

**Issue by ion6** [johnno1962/InjectionIII#108]
I am testing this with the iPhone 8 simulator and XCode 10.1.   I downloaded Injection III today from the App Store, so it should be the latest.  Everything works fine in the sample project 'GettingStarted'.

I am working in large, mostly Obj-C workspace.  I have placed the notification observer in initWithFrame like so:

     [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(didInject:)
                                                     name:@"INJECTION_BUNDLE_NOTIFICATION"
                                                   object:nil];

didInject gets called, twice.  These are the contents of didInject:

    - (void)didInject:(NSNotification*)notification {
        NSLog(@"Inject #1!");
        self.backgroundColor = [UIColor red];
    }

If I build and run this code, the console prints the log command inside of *didInject*.  However, if I modify NSLog to read something like *NSLog(@"Inject Changed Input")* and change the backgroundColor of the view to green, I still see the original log and the color remains the same.

The console is initially reporting:
    💉 Injection connected, watching /Users/deepsun/Projects/iOS/BigCountry/**

If I save the file, I get this cautionary statement:
    objc[56803]: Class bcGalaxyView is implemented in both /Users/deepsun/Library/Developer/CoreSimulator/Devices/0F663CC0-656A-420B-819C-362C2EA087E8/data/Containers/Bundle/Application/EECED7C1-7CAC-4744-A38E-D226AA0051E9/BigCountryPro.app/BigCountryPro (0x111be37e0) and /Users/deepsun/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.dylib (0x13f25dba8). One of the two will be used. Which one is undefined.

I have read that listening for the INJECTION_BUNDLE_NOTIFICATION event should fix this, but it hasn't.  Similarly, if I use the class or instance method of *injection*, it is never called.

**Comment by zenangst** [comment]
@gyrocade hey mate, would you mind sharing a demo project where I could test this? That would help to figure out what is going wrong, thanks!
