### ISSUE TITLE
It seems not working for iOS 10

### ISSUE THREAD

**Issue by rickytan** [johnno1962/InjectionIII#109]
ATT

**Comment by zenangst** [comment]
@rickytan hey mate, mind providing some more information about your implementation?

**Comment by rickytan** [comment]
Well, it works perfectly on iOS 11 & iOS 12. But when I run my App on iOS 10 with injection enabled, the simulator will die, and must be reboot to resume. It is exactly the some code written in Objective-C.

**Comment by zenangst** [comment]
@rickytan are you using the same Xcode version when running iOS10 ?

**Comment by rickytan** [comment]
yeah.
![image](https://user-images.githubusercontent.com/1250207/53849679-9f13f980-3ff3-11e9-8d7a-20828d18211f.png)

I created a new demo project, it works on iOS 10. Perhaps some third-party lib my project use has hooked some API on iOS 10
