### ISSUE TITLE
Injection crashing after running injected code with class cast exception 

### ISSUE THREAD

**Issue by rene-dohan** [johnno1962/InjectionIII#111]
I just change anything in class ConversationController, save, open controller in app again and it crashes on same place with class cast that does not make sense.  To clarify , MyMessageConversationCell is implementing protocol MessageCell if that is not obvious.

```
💉 Injected 'Motorkari.ConversationController'
Could not cast value of type 'Motorkari.MyMessageConversationCell' (0x10f234240) to 'Motorkari.MessageCell' (0x116d2c090).
2019-03-05 12:03:04.111972-0600 Motorkari[6735:42048] Could not cast value of type 'Motorkari.MyMessageConversationCell' (0x10f234240) to 'Motorkari.MessageCell' (0x116d2c09
```

this is in ConversationController where it crashes ...
```
 func tableView(_ view: UITableView, cellForRowAt path: IndexPath) -> UITableViewCell {
        let message = table.data(for: path)
        let cellType = message.isMy ?
            MyMessageConversationCell.self : OtherMessageConversationCell.self
        return view.cellView(cellType, SyleComponentSwift.cellClear)
            .apply { ($0.cellView as! MessageCell).load(message, self) } //Crash here
    }
```

this is in extension ...
```
  public func apply(_ function: (Self) -> Void) -> Self {
        function(self)
        return self
    }
```

**Comment by johnno1962** [comment]
Hi, this is because the symbol for the version of the class which you are using in the cast is different from the version of the class where you are instantiating it (one is owned by you main package and one is owned by the dylib which carries the injection. You may be able to get around this by casting inside the class you are injecting or using a factory method

**Comment by rene-dohan** [comment]
You mean MessageCell protocol gets generated again and it is then not able to cast MyMessageConversationCell to it as it don't implement it anymore ?

**Comment by johnno1962** [comment]
No guarantees for how protocols will work - it’s a bit complicated, but when you inject a class there will be two versions of the class and you need to take this into account when you are creating new instances.

**Comment by rene-dohan** [comment]
I just moved definition of protocol to separate file and it works ! But injection should be able to handle this ... It's not good that for tool to work you have to change project file hierarchy or even code imho... Injection could recompile just affected source code or recompile also classes that implements that protocol ... You don't see this as feature improvement ?

**Comment by johnno1962** [comment]
Injection is what it is. You need to appreciate a bit about the internals of object files and dynamic loading at times to use it at times. There isn’t much that can be done about it without more support from Swift. Happy you’re up can running again.

**Comment by rene-dohan** [comment]
Well, sure I don't know internals was just thinking logically. I can use it but then maybe it would be helpful for others if this cannot be fixed, to really explain what is happening to people who try to use it, because it can appear as bugged and not working now and then... And when this happened I went first to read limitations in readme on Github, the i was thinking I cannot use it anymore and then I tried write bug here. Now I solved it , because you responded, but to run to thing like this, well it will happen anybody sooner or later. Anyway to put protocol to separate file was not a problem , but I know it will happen again to me for sure... As i don't have good memory for thing like this. Anyway thanks for your work and responses here. Its quite useful for me (when it works) to tune user interface details without rebuilding as I write everything programatically. Thanks !

**Comment by HiroshiHorie** [comment]
Having the same problem here... trying to solve this...

**Comment by everlof** [comment]
@johnno1962  I get this when using `observe`, like this 

```
private var boundsObserver: NSKeyValueObservation?

    private func setup() {
        boundsObserver = observe(\.bounds) { _, _ in
            self.update()
        }
    }
```

Is there a way to observe without this crashing due to this?

**Comment by everlof** [comment]
I couldn't create a small project replicating it, nor could I reproduce it again in my, these lines caused my project to crash before: 

   ```
 private var boundsObserver: NSKeyValueObservation?

    private func setup() {
        boundsObserver = observe(\.bounds) { _, _ in
            ...
        }
    }
```

It only crashed when a value was received in the observer. This was the error, unfortunately can't find the full stack trace.

```
Could not cast value of type 'Module.ContentNavigationBar' (0x1061daa80) to 'Module.ContentNavigationBar' (0x11cc106e0).
2022-06-16 14:07:28.153331+0200 Module[31428:1550190] Could not cast value of type 'Module.ContentNavigationBar' (0x1061daa80) to 'Module.ContentNavigationBar' (0x11cc106e0).
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode-13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/..../DerivedData/.../Build/Products/Debug-iphonesimulator:/Applications/Xcode-13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode-13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode-13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode-13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/..../Build/Products/Debug-iphonesimulator:/Users/david/.../DerivedData/.../Build/Products/Debug-iphonesimulator/PackageFrameworks
Could not cast value of type 'Module.ContentNavigationBar' (0x1061daa80) to 'Module.ContentNavigationBar' (0x11cc106e0).
CoreSimulator 802.6 - Device: iPhone 13 Pro (4D65F726-....-4C93-B56C-084EC06B9E18) - Runtime: iOS 15.4 (19E240) - DeviceType: iPhone 13 Pro
```

**Comment by johnno1962** [comment]
Thanks, that's useful information. When you get seemingly nonsensical crashes such as the following:
```
2022-06-16 14:07:28.153331+0200 Module[31428:1550190] Could not cast value of type 'Module.ContentNavigationBar' (0x1061daa80) to 'Module.ContentNavigationBar' (0x11cc106e0).
```
This is because the `Module.ContentNavigationBar` type/class must have been injected at some time in the past and there are effectively two versions of it in memory - the original and the injected type. Depending where the thing you are trying to cast came from and where you are casting it Swift may see only that they seem to be two different types. If you set the environment variable `INJECTION_DYNAMIC_CAST` in your scheme you can opt into code that "hooks" the function that implements casting and tries to do better but no guarantees.
