### ISSUE TITLE
Is Xcode 10.2 beta 4 supported ?

### ISSUE THREAD

**Issue by HiroshiHorie** [johnno1962/InjectionIII#112]
I get the following error:
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10

**Comment by zenangst** [comment]
@HiroshiHorie  I believe that we need to make a new build for that to work properly.
We tend to make new versions when new Xcode versions are released (that needs a new version of InjectionIII).

**Comment by HiroshiHorie** [comment]
Thank you!

**Comment by zenangst** [comment]
Hey @HiroshiHorie, we are working on making a version that supports Xcode 10.2.
In the meantime you can download a binary here - https://github.com/johnno1962/InjectionIII/releases/download/1.5/InjectionIII.zip
