### ISSUE TITLE
Support for Xcode 10.2

### ISSUE THREAD

**Issue by MedvedevMax** [johnno1962/InjectionIII#117]
First of all, thanks for a great work. InjectionIII has become part of my working flow and it's awesome.

Xcode 10.2 has been released yesterday, so looking forward for supporting it.

The error is pretty predictable:
```
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10, 265): Symbol not found: _$SBOWV
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 in /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10
```

**Comment by nilsnilsnils** [comment]
Same probleme here.
The path to the lib is correct

`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib`

**Comment by zenangst** [comment]
Hey @MedvedevMax and @nilsnilsnils, we aim to release a new version later today. Stay tuned!

**Comment by zenangst** [comment]
Hey @MedvedevMax @nilsnilsnils, a release is in the works. You can download a binary here while you wait for it to hit the app store. Thanks for your patience - https://github.com/johnno1962/InjectionIII/releases/download/untagged-a62806ef30a44ea4aa59/InjectionIII.zip

Did some testing myself and everything seems to be in order, please take it for a spin.

**Comment by MedvedevMax** [comment]
@zenangst Works like a charm. That you, that was super-fast.
You only forgot to mention that we now have to load `iOSInjection.bundle` instead of `iOSInjection10.bundle`.

**Comment by zenangst** [comment]
@MedvedevMax that is true, sorry about that. It was a part of this PR that I forgot to mention #119

**Comment by xjvtouch** [comment]
I got this error with Xcode 10.2: 

Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found

InjectionIII: 1.5
Xcode: 10.2 (10E125)
Simulator: iOS 12.2
Mac OS: 10.14.3 (18D109)

**Comment by xjvtouch** [comment]
> I got this error with Xcode 10.2:
> 
> Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection: dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/XCTest.framework/XCTest
> Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
> Reason: image not found
> 
> InjectionIII: 1.5
> Xcode: 10.2 (10E125)
> Simulator: iOS 12.2
> Mac OS: 10.14.3 (18D109)

Solved that after I rename the Xcode10.2.app with Xcode.app

**Comment by mushanlianshi** [comment]
💉 *** Compiling /Users/baletu/Desktop/svn/landlordPJ/Baletoo_landlord/Modules/Mine/Controller/MineViewController.m ***
💉 Loading .dylib ...
💉 *** dlopen() error: dlopen(/Users/baletu/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval103.dylib, 2): Symbol not found: ___llvm_profile_runtime
  Referenced from: /Users/baletu/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval103.dylib
  Expected in: flat namespace
 in /Users/baletu/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval103.dylib ***
I find this question  when I save my file

**Comment by zenangst** [comment]
@mushanlianshi Support for Objective-C is regretfully not the main focus for InjectionIII.
With this version of injection, we aim to improve the Swift experience.
Have you tried https://github.com/johnno1962/injectionforxcode this when working with Objective-C?

**Comment by johnno1962** [comment]
Objective-C should still work and InjectionIII is your best bet but is more susceptible to problems with spaces and non-ascii characters in the path to the project. For the problem you have disable collection of test coverage and you should be up and running again.

**Comment by zenangst** [comment]
@johnno1962 Oh, totally my bad. I have yet to test the Objective-C part as I only do Swift at work. Thanks for clarifying mate! 😎

**Comment by zenangst** [comment]
@MedvedevMax @nilsnilsnils @xjvtouch 1.5.1 is now available for direct download - https://github.com/johnno1962/InjectionIII/releases/tag/1.5.1

**Comment by benzai** [comment]
Awesome work! I had the same error in Xcode 10.2.1 and using the new build fixed it. Thanks for making hot reload possible in Xcode!! 🙏🙏
