### ISSUE TITLE
Symbol not found: ___llvm_profile_runtime

### ISSUE THREAD

**Issue by DanielAsher** [johnno1962/InjectionIII#12]
Hi Johnno,

thanks for this amazing project!

I've installed successfully and am using the AppDelegate method to start. The status icon goes from blue to green to amber. Xprobe works beautifully, but when I save a change I get this error:
```
Compiling /Users/danielasher/.../MyViewController.swift
Loading /tmp/eval1.dylib. (Ignore any duplicate class warning)
*** dlopen() error: dlopen(/tmp/eval1.dylib, 2): Symbol not found: ___llvm_profile_runtime
  Referenced from: /tmp/eval1.dylib
  Expected in: flat namespace
 in /tmp/eval1.dylib ***
```

Any clues?

thanks,

Daniel

**Comment by johnno1962** [comment]
I think tis is usually because you have “collect coverage data” turned on in the app scheme.

**Comment by DanielAsher** [comment]
I've verified that this is the case - coverage switched off and Injection is working beautifully! This is probably quite a common case, should I create a PR to add this to the README?

**Comment by johnno1962** [comment]
Yes, this has come up before as you can tell. Please Do!
