### ISSUE TITLE
pod中的代码无法修改

### ISSUE THREAD

**Issue by FrankiezZZ** [johnno1962/InjectionIII#121]
您好，pod lib create的工程，class文件在项目目录之外，代码注入失败，请问有什么解决办法吗，谢谢~

**Comment by zenangst** [comment]
Hey @FrankiezZZ, your best bet is to add the pod inside of the project and point to it with a path. It needs to be in the same or under one step inwards in your folder hierarchy.

```
- Xcode.xcodeproj
- Pod
```

```
- Xcode.xcodeproj
- Source
  - Pod
```

That should help to detect changes in your project when you save a pod related file.

**Comment by FrankiezZZ** [comment]
OK, Thank u ~

**Comment by zenangst** [comment]
@FrankiezZZ cheers!

**Comment by ylrs** [comment]
> 文件
![WX20190401-122318](https://user-images.githubusercontent.com/3962127/55303662-11082300-547a-11e9-8460-2e38545f1d0d.png)
假如以zu组件形式引用，使用的是本地分支，这时候怎么操作才能生效呢

**Comment by FrankiezZZ** [comment]
@ylrs 你可以试试把Pintu这个pod的目录暂时放到主工程目录下，开发完再挪出去。podfile里面改一下path。

**Comment by ylrs** [comment]
嗯，试了，但是这样会编译失败

**Comment by FrankiezZZ** [comment]
@ylrs 我刚刚试了一下，这个方案可以成功实时修改代码

**Comment by ylrs** [comment]
@FrankiezZZ OK了，谢谢
