### ISSUE TITLE
@objc func injected() not working

### ISSUE THREAD

**Issue by DanielAsher** [johnno1962/InjectionIII#13]
Hi again,

I have found `@objc func injected()` is not being called when a injection is taking place. I've set up a simple view controller hierarchy shown below:

<img width="392" alt="uiviewcontroller view debugger" src="https://user-images.githubusercontent.com/7915553/37624720-098c19ac-2bc1-11e8-8a78-5c55b8ce93e5.png">

Only after deleting the `@objc func injected()` function and re-injecting (i.e. Cmd-S) does the function run. Perhaps this detail is a clue.

"INJECTION_BUNDLE_NOTIFICATION" notifications are working well. I don't have much more info, so feel free to close if there is nothing to further to be done.

```
Compiling /Users/danielasher/Dev/Story/SoundingOutViewController.swift
Loading /tmp/eval3.dylib. (Ignore any duplicate class warning)
objc[3360]: Class _TtC9StoryView25SoundingOutViewController is implemented in both /Users/danielasher/Library/Developer/Xcode/DerivedData/StoryExercise-fzjqrtzvufnyynccigutynyemscx/Build/Products/Debug-iphonesimulator/StoryView.framework/StoryView (0x1059da1b0) and /tmp/eval3.dylib (0x128bd9bc0). One of the two will be used. Which one is undefined.
Injected 'StoryView.SoundingOutViewController', vtable length: 608
```

High Sierra
Xcode 9.2
Swift 4.0

**Comment by DanielAsher** [comment]
closing as no new information available.

**Comment by johnno1962** [comment]
You encountered a limitation of injected() method. To implement it, it sweeps all objects in the application to find instances of the class you’ve injected. This starts with a seed of your current viewController and application instance which misses things like singletons etc.
