### ISSUE TITLE
Injection fails

### ISSUE THREAD

**Issue by SujaySundaram** [johnno1962/InjectionIII#130]
💉 *** Compiling /Users/Xabc/Documents/test/Project/ViewController.swift ***
💉 *** Re-compilation failed (/Users/Xabc/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
<unknown>:0: error: missing required module 'NokNokLabs'
 ***

Injection fails in a particular project with this error.  Xcode 10.1 and this project has a combination of ObjectiveC and swift files but I am trying this on purely swift file. Where as when I try it out on a test project with only swift files, it works just fine.

**Comment by bobbyint** [comment]
Any updates on this?
