### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by shantj** [johnno1962/InjectionIII#131]
`/Library/Developer/Xcode/DerivedData/InjectionIII-fmjharowuyvvkyenegdrmbkoetqr/Build/Intermediates.noindex/InjectionIII.build/Debug/InjectionIII.build/Script-BBCA02321FB0F86E00E45F0F.sh: line 5: /Applications/Xcode101.app/Contents/Developer/usr/bin/xcodebuild: No such file or directory
`

I don't know why there is a Xcode101.app. I can't find where create this command.

Xcode version:10.2

**Comment by johnno1962** [comment]
You're trying to build the app from the repo? You'll need a copy of Xcode 10.1 at the path mentioned.

**Comment by shantj** [comment]
> You're trying to build the app from the repo? You'll need a copy of Xcode 10.1 at the path mentioned.

so what should I do if I want to run in 10.2 version? Is there any code I can rewrite to suppor 10.2 ?
