### ISSUE TITLE
What project directory to select when the main project and sub project are in the peer directory?

### ISSUE THREAD

**Issue by fergusding** [johnno1962/InjectionIII#137]
Hello @johnno1962 ,
  As the question's title, My project has a main project and many sub projects and they are in the peer directory, but what directory I should to select to support the sub projects' changes can be injected. When I select main project directory, there is nothing happen; and when I select one sub project directory, the error is 'Could not locate containing project or it's logs.  On macOS you need to turn off the App Sandbox. Have you customised the DerivedData path?'

**Comment by johnno1962** [comment]
InjectionIII only works if he main project is in the root of the Source tree. Does that answer your question?

**Comment by fergusding** [comment]
Thanks for your reply. The problem is that the main project is in a folder of the root of the Source tree. Just like the attachment. Is there a way to solve it?
![image](https://user-images.githubusercontent.com/9957817/56798737-f98a4300-6849-11e9-9730-1484a6af6f3a.png)

**Comment by johnno1962** [comment]
If you select the Main directory you may be able to inject files under that directory (but not those in the Sub directory)

**Comment by fergusding** [comment]
Yeah, I understand. There is no way to inject files under the Sub directory except to change my project structure. Thanks.
