### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aiyang** [johnno1962/InjectionIII#138]
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `(cd "/Users/apple1/Desktop/InventoryNew" &&     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/apple1/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/apple1/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Index/DataStore -iquote /Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/Inventory-generated-files.hmap -I/Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/Inventory-own-target-headers.hmap -I/Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/Inventory-all-target-headers.hmap -iquote /Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/Inventory-project-headers.hmap -I/Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Products/Debug-iphonesimulator/include -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/AFNetworking -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/CYLTabBarController -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/IQKeyboardManager -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/LBXScan -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/MBProgressHUD -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/MJExtension -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/MJRefresh -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/Masonry -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/ReactiveObjC -I/Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/SDWebImage -I/Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/DerivedSources-normal/x86_64 -I/Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/DerivedSources/x86_64 -I/Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/DerivedSources -F/Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Products/Debug-iphonesimulator -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/AFNetworking -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/CYLTabBarController -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/IQKeyboardManager -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/LBXScan -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/MBProgressHUD -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/MJExtension -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/MJRefresh -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/Masonry -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/ReactiveObjC -isystem /Users/apple1/Desktop/InventoryNew/Pods/Headers/Public/SDWebImage -include /Users/apple1/Desktop/InventoryNew/Inventory/PrefixHeader.pch -MMD -MT dependencies -MF /Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/Objects-normal/x86_64/InventoryListViewController.d --serialize-diagnostics /Users/apple1/Library/Developer/Xcode/DerivedData/Inventory-bathkstwojgifsfnzyjcfnibtdza/Build/Intermediates.noindex/Inventory.build/Debug-iphonesimulator/Inventory.build/Objects-normal/x86_64/InventoryListViewController.dia -c /Users/apple1/Desktop/InventoryNew/Inventory/InventoryHome(盘点单首页)/Controller/InventoryList(盘点单列表)/InventoryListViewController.m  -o /Users/apple1/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.o >/Users/apple1/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.log 2>&1)'
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “eval101.log” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/apple1/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.log, NSUnderlyingError=0x600001cb4a50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /Users/christofferwinterkvist/Documents/Code/InjectionIII/InjectionBundle/SwiftEval.swift, line 314
2019-04-26 17:20:55.324717+0800 Inventory[16063:1435073] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “eval101.log” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/apple1/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.log, NSUnderlyingError=0x600001cb4a50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /Users/christofferwinterkvist/Documents/Code/InjectionIII/InjectionBundle/SwiftEval.swift, line 314

COMMAND + S  crash

**Comment by johnno1962** [comment]
Looks like you have a space or ' in the path to your project. I'm afraid this isn't supported.

**Comment by aiyang** [comment]
@johnno1962  
Thank you very much for your reply! But After - (void)injected{} execution, another crash occurred.
💉 Injection connected, watching /Users/apple1/Desktop/InventoryNew/**
💉 *** Compiling /Users/apple1/Desktop/InventoryNew/Inventory/InventoryHome/Controller/InventoryList/InventoryListViewController.m ***
💉 Loading .dylib ...
objc[1856]: Class InventoryListViewController is implemented in both /Users/apple1/Library/Developer/CoreSimulator/Devices/D8F6B6DE-53A3-47CA-9142-40F2F530CF98/data/Containers/Bundle/Application/6553F720-F5B5-4EAA-903B-1C5C7CC50859/Inventory.app/Inventory (0x100c27a88) and /Users/apple1/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib (0x126e0c888). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ^
objc[1856]: Attempt to use unknown class 0x6000033e5a80.
