### ISSUE TITLE
UIView with programmatic layout

### ISSUE THREAD

**Issue by mhillebrand** [johnno1962/InjectionIII#139]
I'd like to use Injection with my UIView subclasses that contain programmatic layout. That is, I've created Auto Layout constraints using Swift code within UIViews...not within UIViewControllers. Injection doesn't seem to help in this scenario, or is there something I'm missing?

Thanks!

**Comment by mhillebrand** [comment]
I created a workaround, but I'm not sure I like it very much. It requires each UIView subclass to override the addConstraints() method, and what I've done with subview constraints feels awkward:

`@objc extension UIView {
    #if DEBUG
    @objc func injected() {
        removeAllSubviewConstraints()
        addConstraints()
    }
    #endif

    func addConstraints() {}

    func removeAllSubviewConstraints() {
        subviews.forEach { $0.removeAllConstraints() }
    }

    func removeAllConstraints() {
        var superview = self.superview

        while superview != nil {
            for constraint in superview!.constraints {
                if constraint.firstItem as? UIView == self || constraint.secondItem as? UIView == self {
                    constraint.isActive = false
                }
            }

            superview = superview?.superview
        }

        constraints.forEach { $0.isActive = false }
    }
}`

**Comment by mhillebrand** [comment]
Bah. This is no good. I can't see programmatic updates to UIViews that are NOT related to layout constraints. There must be something I'm missing here. If the views are being removed in the view controller, then why don't I see updates made in the UIView subclasses?

**Comment by Polisas** [comment]
Did you fix it ? Or got a workaround ?

**Comment by mhillebrand1** [comment]
Yeah, I mentioned my workaround above:

>  I guess I could just stop using anonymous closures to configure my subview properties and do all of that within a method that gets called both on init and on injection.

Here's an example:

`import TinyConstraints

class InjectableView: UIView {
    private let subview1 = UIView()
    private let subview2 = UIView()

    init() {
        super.init(frame: CGRect.zero)
        configure()
        addSubviews()
        addConstraints()
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func configure() {
        subview1.backgroundColor = .green
        subview2.backgroundColor = .yellow
    }

    private func addSubviews() {
        addSubview(subview1)
        addSubview(subview2)
    }

    override func addConstraints() {
        subview1.edgesToSuperview(excluding: .bottom)
        subview1.height(300)

        subview2.edgesToSuperview(excluding: .top)
        subview2.topToBottom(of: subview1)
    }
}`
