### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HappyDaydayUp** [johnno1962/InjectionIII#142]
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.)

💉 *** Could not locate compile command for
/Users/dongdongding/Desktop/eCar/项目/xiaoka/XiaoKa/XiaoKa/Class/Third/InBlue/Manage/Vehicle/Main/Controller/ExVehicleViewController+Animation.h
Xcode  最新版本好

**Comment by johnno1962** [comment]
Hi, sorry but you can’t have non-ASCII characters in the path to your project with injection - particularly with Objective-C projects.

**Comment by HappyDaydayUp** [comment]
> Hi, sorry but you can’t have non-ASCII characters in the path to your project with injection - particularly with Objective-C projects.

Thanks I understand.  I will try .
