### ISSUE TITLE
Storyboard hot reload not working with InjectionIII 1.5.2 on Xcode 10.2

### ISSUE THREAD

**Issue by chiquan91** [johnno1962/InjectionIII#143]
Hi bros,
I recently use InjectionIII and it's awesome, i can save many time of software development. I'm using version 1.5.2/1.5.1 with Xcode 10.2/10.2.1, simulator 12.2/12.1. The hot reloading is working good with .m or .swift files, but .storyboard files. Firstly i think it's because of my half objc half swift project, but when i create a fresh new Single View project, build and connect successfully with InjectionIII, then i change color of the main view in storyboard, or change text of an existing label, then save the storyboard file, nothing happen in simulator, only the message "💉 *** Copied /InjecSample/Base.lproj/Main.storyboard ***" in console, even if i pop to previous viewcontroller, then push again.
Thank you for your help and very hard working.

**Comment by johnno1962** [comment]
Hi, you are using version [1.5.2](https://github.com/johnno1962/InjectionIII/releases/tag/1.5.2) right? The other thing that may be going wrong is you don’t save the storyboard but build the project to inject.

**Comment by chiquan91** [comment]
I had saved the storyboard, both by Ctrl+S or File->Save, and don't re-build the project, nothing happen in simulator.

**Comment by chiquan91** [comment]
And can you please make a demo video for .storyboard and .xib injection, i can't find any in the internet, thanks.

**Comment by johnno1962** [comment]
Don’t sabe the storyboard. This won’t work. Just build your project.

**Comment by MohamedRed** [comment]
Hi @chiquan91 , did you get it to work ? Because I face the same problem.
I do a change in the storyboard, then rebuild the project without saving, but nothing is updated. 
I only get this log  💉 *** Copied /InjecSample/Base.lproj/Main.storyboard ***
I am using Xcode 10.1 and InjectionIII 1.6.
Is there anything I need to do in the injected function ?
