### ISSUE TITLE
New files added from AppCode aren't picked up

### ISSUE THREAD

**Issue by grav** [johnno1962/InjectionIII#147]
To reproduce:
  1. add `Foobar.swift` in AppCode
  2. run in AppCode
  3. change `Foobar.swift` and observe error:
```
💉 *** Could not locate compile command for /path/to/Foobar.swift
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.) ***
```

**Resolution:** run in Xcode after adding file (editing isn't necessary). Afterwards, running in AppCode and editing will work.

I guess it has something to do with `DerivedData` being out of sync?

**Comment by johnno1962** [comment]
You’ll need to rebuild in Xcode after adding to the to update the Xcode logs which Injection uses.
