### ISSUE TITLE
Injection can not work with project in path of iCloud directory in Mac 

### ISSUE THREAD

**Issue by KevinKingCN** [johnno1962/InjectionIII#149]
When I put my project into the iCloud folder, it can't use injection to make hot-reload, and here is the alert info: 
💉 *** Could not locate compile command for /Users/user/Library/Mobile Documents/com~apple~CloudDocs/1_Kaifa/0_Shopping/0_SourceCode/shopping_ios_app/Shopping/ViewControllers/Home/KFHomeViewController.swift
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.) ***
 
Then I tried to copy the project to another folder like Desk, or Document, it turns to that Injection's hot-reload works very well with the project and simulator. Is symbol "~" in iCloud path name that leading to that problem?

**Comment by johnno1962** [comment]
This is more like because you have non-ascii characters (or space) in your file path.
