### ISSUE TITLE
It seems stop working with Xcode 9.3

### ISSUE THREAD

**Issue by ooopscc** [johnno1962/InjectionIII#15]
When using Xcode 9.2, it worked. But, I update Xcode yesterday, and InjectionIII seems not working. Icon on the menu bar not change color, and 'Start Injection' has no effect.

**Comment by johnno1962** [comment]
This is due to slight changes in the Swift stdlib. I’ve uploaded a new version which will only work with Xcode 9.3 if you want to give it a try.

**Comment by ooopscc** [comment]
Thanks, I found the 9.3version Injection.app from your blog. But it seems modified from Injection9 not the new Swift InjectionIII, I can not follow the new README to make it work. Would you please update a separate InjectionIII for Xcode 9 version?


```
Can't locate InjectUnitTests.pm in @INC (you may need to install the InjectUnitTests module) (@INC contains: /Applications/Injection.app/Contents/Resources /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Applications/Injection.app/Contents/Resources/injectSource.pl line 17. BEGIN failed--compilation aborted at /Applications/Injection.app/Contents/Resources/injectSource.pl line 17. *** Bundle build failed ***  
```

**Comment by johnno1962** [comment]
Thanks for letting me know about the missing file and I’ve updated the binary under the 9.3 link. There is a new version of InjectionIII for 9.3 under the existing InjectionIII link at the bottom.

**Comment by johnno1962** [comment]
Sorry, that wan’t my intention.. you should find the version updated works now.

**Comment by ooopscc** [comment]
So sorry for bothering, but I still can not find where the `a new version of InjectionIII for 9.3 under the existing InjectionIII link at the bottom.` is. Could you please paste that link here if convenient ?

**Comment by johnno1962** [comment]
There is only one link and it is for 9.3

**Comment by phynet** [comment]
Yes, forgot to add it to the comment, I just did this in my app (as the example) that's why I was wondering what could be "wrong". 😢

**Comment by johnno1962** [comment]
Is the injected method being called - add a print statement? Is there a live instance of MyProject.ViewController?

**Comment by zenangst** [comment]
Hey @phynet, hope you are feeling better, just wanted to check in if you've had time to revisit this issue.

**Comment by rlam3** [comment]
does this work with xcode 10?

**Comment by rlam3** [comment]
@zenangst Thanks!

**Comment by zenangst** [comment]
Closing this issue now.
