### ISSUE TITLE
Symbol not found: OBJC_CLASS

### ISSUE THREAD

**Issue by rsardek** [johnno1962/InjectionIII#155]
I couldn't resolve my issue by looking into other threads.

Injection connects correctly, and when I hit command-save, the console fires:
💉 Loading .dylib ...
💉 *** dlopen() error: dlopen(/Users/me/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval106.dylib, 2): Symbol not found: _OBJC_CLASS_$_....
  Referenced from: /Users/me/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval106.dylib
  Expected in: flat namespace
 in /Users/me/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval106.dylib ***

On a side note:
I have some static libraries integrated in the project.
Injection: v1.5.1
Xcode: v10.2.1 (named as Xcode.app in Applications directory)

**Comment by johnno1962** [comment]
Hi, This can be because the classes have been given the attribute “hidden” in the library (e.g. some google libs)

**Comment by rsardek** [comment]
Yes, this completely makes sense.
If, in my app delegate, I omit any references to these classes, injection works out fine.
Is there something I can try to make it work?

Many thanks :)

**Comment by johnno1962** [comment]
Unfortunately no. Once marked hidden. The symbol cannot be referenced in a dynamic load.

**Comment by ldwardx** [comment]
I have encountered the same problem, but I don't understand what "class attribute hidden" means, my project is completely objc, no swift.
