### ISSUE TITLE
Support for AppCode

### ISSUE THREAD

**Issue by mgamer** [johnno1962/InjectionIII#16]
This is an excellent project, highly helpful in rapid development.

Is it a must to use XCode to run InjectionIII or is there a way to do make it work only with AppCode and build/run the app from it?

**Comment by johnno1962** [comment]
You can use AppCode with InjectionIII as it uses a file watcher. You need to have the project Open in Xcode though so it can find the build logs.

**Comment by zenangst** [comment]
Closing this issues due to the lack of activity but feel free to re-open it if the purposed solution turned out to be faulty.
