### ISSUE TITLE
 Xcode10.2.1   💉 *** Re-compilation failed 

### ISSUE THREAD

**Issue by ylrs** [johnno1962/InjectionIII#163]
💉 *** Re-compilation failed (/Users/zhulongfei/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
/Users/zhulongfei/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh: line 1: -o: command not found
 ***
version: 1.6
![image](https://user-images.githubusercontent.com/3962127/61291684-c54b7080-a801-11e9-8a30-333296232a13.png)

**Comment by johnno1962** [comment]
Check the file /Users/zhulongfei/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh

**Comment by ylrs** [comment]
command.sh
(cd "/Users/zhulongfei/Documents/HotProject/InjectionTest" &&   -o /Users/zhulongfei/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.o >/Users/zhulongfei/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.log 2>&1)

eval102.log:
/Users/zhulongfei/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh: line 1: -o: command not found

**Comment by johnno1962** [comment]
That really shouldn’t happen. I don’t know what would cause that.

**Comment by ylrs** [comment]
![image](https://user-images.githubusercontent.com/3962127/61447100-e5566d80-a982-11e9-809a-fc5326fa8782.png)
I know the reason.
can you help me?

**Comment by johnno1962** [comment]
Interesting, You’ll have to clone the project and build it if you need injection on a background thread.

**Comment by ylrs** [comment]
Because the main thread compiles, the APP will get stuck

**Comment by johnno1962** [comment]
It could compile on the background and inject on main I suppose. I don’t think we’re going to change this.

**Comment by ylrs** [comment]
But now the compilation and inject  is on the main thread

**Comment by zenangst** [comment]
I don’t see the issue with the complication being done on the main thread, perhaps I’m missing something. What would be the main advantage about using a different queue for compilation.m? Yes the app would stop to respond for a short period of time, but I don’t really see that as an issue.

**Comment by ylrs** [comment]
My  company's project will be on 6s,Relatively large project

**Comment by zenangst** [comment]
But dispatching into another thread won’t make it faster, it would just make a tinsy bit more complex to ensure that the last results that you see are the relevant one. Play with the idea that you save/inject multiple times during a period of time, it will be harder to ensure that the relevant changes reflect the last change as the process is no longer synchronized. I might be overthinking the complications but another queue won’t speed things.

**Comment by ylrs** [comment]
You're right.but  I'm not trying to save time.I Don't want the app would stop to respond
