### ISSUE TITLE
Error loading 

### ISSUE THREAD

**Issue by a100201** [johnno1962/InjectionIII#164]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Symbol not found: _$s19ArrayLiteralElements013ExpressibleByaB0PTl
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection

**Comment by johnno1962** [comment]
Hi, What version of Xcode is this?

**Comment by markyecn** [comment]
I also meet this issue, my xcode version is 10.2.1
the same error message

**Comment by XuFeng-Li** [comment]
Me too, my Xcode Version is 12.4.
When I execute Command + S, an error is reported:

💉 Injection connected 👍
💉 Watching /Users/lucky1204/Documents/Learn/TestInjectionDemo/**
💉 *** Error reading /var/folders/2p/0wdcktrs7478q5bgdmp7_9bc0000gn/T/com.johnholdsworth.InjectionIII/eval101.sh, scanCommand: /var/folders/2p/0wdcktrs7478q5bgdmp7_9bc0000gn/T/com.johnholdsworth.InjectionIII/command.sh ***

**Comment by johnno1962** [comment]
Hi, this may be because you are using a project in ~/Documents which has special permissions. Can you move the project?

**Comment by XuFeng-Li** [comment]
@johnno1962 
I just create a new project, configure the project according to the documentation, then modify the background color of the view, and report an error after saving

**Comment by johnno1962** [comment]
Have you moved the project out of ~/Documents? What version of InjectionIII is this? App Store or a release?

**Comment by XuFeng-Li** [comment]
I have not moved the location of the project, my InjectionIII is the latest version downloaded from the AppStore

**Comment by johnno1962** [comment]
I think the problem may be using a project in ~/Documents. Can you try moving it?

**Comment by XuFeng-Li** [comment]
Thans. I know the problem. The project I created is stored in my mobile hard drive.But i don't understand why this happens

**Comment by XuFeng-Li** [comment]
Thanks. I know the problem. The project I created is stored in my mobile hard drive. But i don't understand why this happens

**Comment by johnno1962** [comment]
How do you mean "mobile hard drive"?

**Comment by XuFeng-Li** [comment]
external HDD,😢.

**Comment by XuFeng-Li** [comment]
And thank you for your help, my Injection is already working normally.😁

**Comment by johnno1962** [comment]
Cool 👍

**Comment by hanxuhanxu** [comment]
hi, my project has the same question:
Error reading /var/folders/nk/1vv69vkd2kjgdrkjnb3y96n00000gp/T/com.johnholdsworth.InjectionIII/eval101.sh, scanCommand: /var/folders/nk/1vv69vkd2kjgdrkjnb3y96n00000gp/T/com.johnholdsworth.InjectionIII/command.sh
the position is /Users/***/Downloads, please help!

**Comment by Jackie-Lee-Mr** [comment]
> hi, my project has the same question: Error reading /var/folders/nk/1vv69vkd2kjgdrkjnb3y96n00000gp/T/com.johnholdsworth.InjectionIII/eval101.sh, scanCommand: /var/folders/nk/1vv69vkd2kjgdrkjnb3y96n00000gp/T/com.johnholdsworth.InjectionIII/command.sh the position is /Users/***/Downloads, please help!

can you solved it ?

**Comment by Master-gg-02** [comment]
> And thank you for your help, my Injection is already working normally.😁

请问下怎么解决的？
