### ISSUE TITLE
Xcode11 is not supported

### ISSUE THREAD

**Issue by josercc** [johnno1962/InjectionIII#166]
Loading Bundle in Xcode11 can be loaded, but the InjectionIII does not work

**Comment by johnno1962** [comment]
Hi, I’ve been using Injection with Xcode 11 and it works. How is it not working?

**Comment by josercc** [comment]
@johnno1962 I will try again

**Comment by josercc** [comment]
@johnno1962 
```Swift
2019-08-01 16:47:39.513632+0800 SwiftTableViewGroupApp[55630:2883313] [ApplicationLifecycle] UIWindows were created prior to initial application activation. This may result in incorrect visual appearance.
💉 Injection connected, watching /System/Volumes/Data/Users/zhangxing/Documents/GITHUB/SwiftTableViewGroup/SwiftTableViewGroupApp/**
2019-08-01 16:47:39.932283+0800 SwiftTableViewGroupApp[55630:2883313]  INFO: Reveal Server started (Protocol Version 49).
💉 *** Could not locate compile command for /Users/zhangxing/Documents/GITHUB/SwiftTableViewGroup/SwiftTableViewGroupApp/SwiftTableViewGroupApp/ViewController.swift
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.) ***
```

**Comment by johnno1962** [comment]
That’s more information to go on. Looks like it might be an issue related to canonical paths (/System/Volumes/Data/Users/zhangxing v.s. /Users/zhangxing) Not sure what the solution would be. We haven’t had an issue with this before.

**Comment by josercc** [comment]
Not sure if it is 10.15 changed the path

**Comment by johnno1962** [comment]
Interesting. I’ll see if I can test on Catalina

**Comment by josercc** [comment]
![image](https://user-images.githubusercontent.com/4713847/62281848-1190e480-b481-11e9-83f1-2084e87d7393.png)
Estimated that the engineering structure does not support

**Comment by johnno1962** [comment]
How do you mean? I’ve not tested injection with a Swift Package myself.

**Comment by josercc** [comment]
I try to use CocoaPods integration.

**Comment by josercc** [comment]
![image](https://user-images.githubusercontent.com/4713847/62284030-6df60300-b485-11e9-970d-58cbb9e9a262.png)
InjectionIII open project this path always fail

**Comment by johnno1962** [comment]
Ah, that’s something different. You can’t have any non-ascii characters in the path to the project. Sorry about this. This is a known limitation.

**Comment by josercc** [comment]
![image](https://user-images.githubusercontent.com/4713847/62284875-15c00080-b487-11e9-8468-a96f6ce77f1b.png)
But the Chinese that can exist in the above is the system that will automatically convert to the corresponding English.

**Comment by johnno1962** [comment]
I have no explanation for that. This is something new with Catalina we’ll have to look out for.

**Comment by josercc** [comment]
Thanks

**Comment by johnno1962** [comment]
Thanks for the report. Just checking, you’re using Xcode 11 with Catalina (macOS 10.15) with the version of InjectionIII from the App Store right?

**Comment by josercc** [comment]
YES
