### ISSUE TITLE
Recompile Fail For Special Character

### ISSUE THREAD

**Issue by starFelix** [johnno1962/InjectionIII#17]
There is a directory named `ab&de` in my project. It works well in xcode. But when I try to use injection for some files which import this special file, It will throw an error said `clang: error: no input files` or `de Common Not Found`。
I don't know why It works well in xcode, but not in injection.

**Comment by johnno1962** [comment]
I’m sorry but that’s not supported. I’ve tried to fix that in the past but for some reason it is difficult.
