### ISSUE TITLE
not work for Xcode10.3

### ISSUE THREAD

**Issue by heyehao2008** [johnno1962/InjectionIII#170]
It's work well when use Xcode 10.2. but can not connected with Xcdoe10.3. Any for helps?

**Comment by zenangst** [comment]
Hey @heyehao2008, which version of InjectionIII are you currently using?

**Comment by limingLiuBaBa** [comment]
Same question , my current xcode version is  Version 10.3 (10G8).

**Comment by johnno1962** [comment]
Are you using Xcode 10.3 at the default location /Applications/Xcode.app?

**Comment by heyehao2008** [comment]
sorry, It's my fault. I forgot it must use simulator. It's work well with Xcode10.3
