### ISSUE TITLE
I found that it doesn't work on Xib file changes

### ISSUE THREAD

**Issue by zhenguanqing** [johnno1962/InjectionIII#171]
Changes in.m files can be refreshed normally, but changes in Xib files cannot be refreshed. Why? My Xcode version is 10.3

**Comment by zenangst** [comment]
@zhenguanqing did you build the project after making changes to your Xib file? Xibs are not updated when save but rather when you build a new version of it.

**Comment by zhenguanqing** [comment]
Do you mean I need command + R to rerun the project? That would have been InjectionIII and it wouldn't have worked, would it? I am a developer from China. My English is not very good. I may not express myself clearly

**Comment by zenangst** [comment]
@zhenguanqing naw, what I mean is to build it while it is still running ⌘B.
Keep in mind that injecting Xibs/Storyboard is highly experimental.

**Comment by zenangst** [comment]
@zhenguanqing did you get it working?

**Comment by zhenguanqing** [comment]
> @zhenguanqing did you get it working?
no, I tried to do a command + B rebuild after I modified the Xib file but the emulator still didn't show my changes

**Comment by zenangst** [comment]
@zhenguanqing interesting, anything that you can share about you implementation? Do you get any log extracts when you do build a modified Xib file?
