### ISSUE TITLE
System framework header not found.

### ISSUE THREAD

**Issue by ldwardx** [johnno1962/InjectionIII#172]
Error msg:fatal error: 'Webkit/Webkit.h' file not found.
My project uses cocopods, the error appears in the header file of the pod library.

**Comment by zenangst** [comment]
Never seen this before, have you @johnno1962 ?
Mind sharing more details about your current project?

**Comment by johnno1962** [comment]
Probably to do with case sensitivity. Should it be #import <WebKit/WebKit.h>?

**Comment by ldwardx** [comment]
Really not using angle brackets when import system library headers. I want to determine if this is the root cause.
I found that there are many such import with system library headers. My project has nearly 200 pod libraries maintained by many teams. It is not easy to contact each team to modify these imports.
Is there any other way to solve the problem?

**Comment by johnno1962** [comment]
It’s not the angle brackets, it’s the case (a vs A) of the letteres in the include. Injection’s compiles are case sensitive.

**Comment by ldwardx** [comment]
You are right, thank you.
