### ISSUE TITLE
How to debug the client code in the InjectionBundle target.

### ISSUE THREAD

**Issue by ldwardx** [johnno1962/InjectionIII#173]
As the title, I want to debug the client code to locate some compilation problems.

**Comment by johnno1962** [comment]
Hi, You would need to build InjectionIII from this repo and install it in /applications. It’s not too difficult a build but at the moment you would need Xcode 10.1 or a symlink from XApplications/Xcode101.app to your Xcode.app.

**Comment by ldwardx** [comment]
I have debugged the client code with the following steps:
1. clone the repo
2. target->InjectionIII->Build Phase->Run Script, change compile option from release to debug
3. Build InjectionIII target
4. Load the bundle under the tmp folder to your application delegate's `applicationDidFinishLaunching:`
```
[[NSBundle bundleWithPath:@"/private/tmp/Injection/Debug-iphonesimulator/iOSInjection.bundle"] load];
```
5. Drag the InjectionIII project into your own project

Done.
