### ISSUE TITLE
Support sub projects?

### ISSUE THREAD

**Issue by ldwardx** [johnno1962/InjectionIII#174]
Larger projects are split into many sub projects that are maintained by different teams, and then integrated into the main project as a static library.
Most sub projects are stand-alone repos, and the code is not included in the main project folder.

Is it possible to add a sub project menu? When the sub project is manually selected, the file watcher observes the sub project folder, and the derived data search still uses the main project name.

**Comment by johnno1962** [comment]
Hi, Injection needs two pieces of information to work, the path to the file changed and the path to the project/workspace to find it’s derived data. At the moment injection derives the later from the former and separating them would be difficult as others injection would have no idea how to find the project file and hence the commands to recompile the project. Can you think of a way we could reorganise this thai wouldn’t be difficult for users to understand? The only I can think of is a second menu item that adds directories to the watch list but keeps the project directory the same.

**Comment by ldwardx** [comment]
Yes, I have the same idea as you. I have supported the subproject and it works fine.
I added a `Open Subproject` menu, when specified, the file watcher will observe the subproject instead of the main project, add modify the `projectFile` logic in the `determineEnvironment` method.

This may not be the best way. In addition to adding the concept of subproject, I am thinking about the dimensions of the file watcher, and maybe it can be better.

**Comment by johnno1962** [comment]
Very interesting @ldwardx. It would be great to be able to support more general arrangements of projects as it comes up reasonably often as an issue. The model of Select project/workspace then add directories to watch (which would be reset every time you select a project) seems understandable and given the app communicates the project file to the simulator client it should be possible to keep injection working. Please file a PR when you think you’re ready and we can look at including the feature. I’m not sure about the menu item being"add subproject" but I can’t think of a better name (perhaps "watch directory”). Thanks for looking at this for us!

**Comment by zenangst** [comment]
I support this idea!

**Comment by johnno1962** [comment]
Hi @ldwardx, are you using injection with subproject now? What changes did you have to make? We're about to prepare another release and it would be great to include this.

**Comment by johnno1962** [comment]
@ldwardx, I've prepared an implementation to Watch additional directories https://github.com/johnno1962/InjectionIII/pull/184 if you want to compare it to your version.

**Comment by ldwardx** [comment]
@johnno1962 Sorry to reply now, I just finished a long holiday.
One small difference is that my implementation allows multiple subprojects to be selected at once. The rest is similar.

**Comment by johnno1962** [comment]
Doh, maybe the next release. Thanks for bringing this up 1.7 should be available soon.

**Comment by zenangst** [comment]
Great news, 1.7 is available in the Mac App Store :)

**Comment by johnno1962** [comment]
Thanks again @zenangst, @ldwardx, we're working on the next release https://github.com/johnno1962/InjectionIII/pull/1 if you want to review/update.
