### ISSUE TITLE
Follow symbolic links

### ISSUE THREAD

**Issue by grav** [johnno1962/InjectionIII#175]
If I replace a file with a symbolic link (eg with `ln -s /somewhere/AppDelegate.swift MySource/AppDelegate.swift`), Injection does not pick up any changes to the file that the link points to.

**Comment by johnno1962** [comment]
Hi, as InjectionIII uses a FSEventStream this would be difficult to support unless you can think of a way to do it.

**Comment by zenangst** [comment]
I wonder if sandboxing could potentially break such a feature if the file is located in a directory where InjectionIII does not have the correct access.

**Comment by grav** [comment]
@johnno1962 I'm not familiar at all with that API, but the [docs](https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html) discuss the difference between using `stat` and `lstat` wrt symbolic links.

The current behaviour is not a killer for me, and considering that you believe it's difficult to implement, and what @zenangst mentions wrt sandboxing, I'll close this topic for now.

**Comment by zenangst** [comment]
Don't get me wrong, I'd love for it to be able to do this!
My workaround right now is to have folders that are invisible to git, and that's where I include non-project source code.
