### ISSUE TITLE
Why not support device? Is there any possibility?

### ISSUE THREAD

**Issue by ldwardx** [johnno1962/InjectionIII#176]
Are there any technical limitations that only support the simulator?
Is there any other way to support the device? For example, using private API in debug mode? Move the client's work as much as possible to the server? etc. 
I don't know enough about it, just discuss the possibilities.

**Comment by johnno1962** [comment]
Hi, Its not been possible to inject on a device since iOS 10 due to sandboxing. There is no place where you can dyload that is writable by an app.
