### ISSUE TITLE
Support for Device debugging

### ISSUE THREAD

**Issue by moshiwu** [johnno1962/InjectionIII#18]
Can InjectionIII support (or planing) for debug with device but not simulator?

**Comment by johnno1962** [comment]
No longer possible since iOS 10 I’m afraid

**Comment by johnno1962** [comment]
It's longer be possible to load native code outside the app bundle which is not writable.

**Comment by garsdle** [comment]
Bummer, I guess the simulator will have to do

**Comment by moshiwu** [comment]
Still thanks for your work!
