### ISSUE TITLE
Re-compilation failed 

### ISSUE THREAD

**Issue by wzpziyi1** [johnno1962/InjectionIII#188]
Injection connected, watching /Users/XXX/xxx-ios/**
💉 *** Re-compilation failed (/Users/XXX/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)

Xcode Version 11.1 (11A1027)

It was ok until I got the upgrade.

**Comment by johnno1962** [comment]
Odd, I’m assuming you’re having a problem with non-ascii characters. Nothing critical has changed in the interim. Can you be sure it was OK with Xcode 11 before the upgrade? Have you upgraded to Catalina?

**Comment by johnno1962** [comment]
Can you try with the saved version of Injection 1.6 from https://github.com/johnno1962/InjectionIII/releases/tag/1.6

**Comment by wzpziyi1** [comment]
> Odd, I’m assuming you’re having a problem with non-ascii characters. Nothing critical has changed in the interim. Can you be sure it was OK with Xcode 11 before the upgrade? Have you upgraded to Catalina?

I'm sure it was ok before Xcode11. Catalina has not been updated.

**Comment by wzpziyi1** [comment]
> Odd, I’m assuming you’re having a problem with non-ascii characters. Nothing critical has changed in the interim. Can you be sure it was OK with Xcode 11 before the upgrade? Have you upgraded to Catalina?

I have adapted for the project, deleted some conflicting files and confused files. It was ok in Xcode10, and it was ok to upgrade to Xcode11 beta, until I upgraded to the latest Version (Xcode Version 11.1 (11A1027)).

**Comment by wzpziyi1** [comment]
> Can you try with the saved version of Injection 1.6 from https://github.com/johnno1962/InjectionIII/releases/tag/1.6




> Can you try with the saved version of Injection 1.6 from https://github.com/johnno1962/InjectionIII/releases/tag/1.6

Still the re-compilation failed.

**Comment by wzpziyi1** [comment]
> Can you try with the saved version of Injection 1.6 from https://github.com/johnno1962/InjectionIII/releases/tag/1.6

Still the re-compilation failed.
I found the problem because someone else added "inttypes.h" file. Thanks

**Comment by johnno1962** [comment]
Cool. Happy you’ve worked it out.
