### ISSUE TITLE
change path for injection to support beta

### ISSUE THREAD

**Issue by pives** [johnno1962/InjectionIII#189]
Is there a way to change the path to support Xcode Beta? or just a different application directory for Xcode? it currently looks for files when injecting in /Applications/Xcode.app. I just want a way to change it to /Applications/foo/Xcode.app

**Comment by johnno1962** [comment]
Hi, InjectionIII's bundle that has an “rpath” hardcoded at linking that requires Xcode to be at a path /Applications/Xcode.app. You can use a symbolic link from this path to anywhere you like.
