### ISSUE TITLE
Xcode 10 - Problem loading bundle

### ISSUE THREAD

**Issue by zenangst** [johnno1962/InjectionIII#19]
Hey John,

Justed wanted to report a small tidbit that I found when testing Xcode 10.
It seems like the application has issues with loading the bundle when it is located in `/Applications`.
If I build `InjectionIII` from source and point to the bundle located in derived data, injection works just like before.

Just a small heads up :)

**Comment by johnno1962** [comment]
Hi Chris, That’s right, this is a Swift ABI issue. InjectionBundle needs to be rebuilt for Xcode 10.

**Comment by zenangst** [comment]
Yeah, you are right. My bad, this is a non-issue I think. Closing :)

**Comment by johnno1962** [comment]
Not your bad at all. The good news is that injection works with Swift 4.2. I’ll be releasing a new version in a due course.

**Comment by johnno1962** [comment]
I’ve made a new compiled version of available at http://johnholdsworth.com/injection.html. This does work on Mojave though.

**Comment by zenangst** [comment]
Fantastic! Cheers @johnno1962

**Comment by zenangst** [comment]
Also as a side-note, InjectionIII is super snappy with the new build-system.

**Comment by johnno1962** [comment]
Really? Good to hear. I suspect that’s just ongoing improvements to compiler speed.

**Comment by zenangst** [comment]
Working on a small demo for Vaccine for people to try it out while tinkering with that demo I tried switching between build systems and you can see a slight difference with the new one (even for smaller projects).

**Comment by johnno1962** [comment]
I wonder what that is. It must be using a different compile command which is faster. Injection doesn’t use the build system it just greps out the logs for the compile command. I’ve uploaded another version for Xcode 10 if you want to download containing a Swift 4.2 fix to inject classes not derived from NSObject.

**Comment by zenangst** [comment]
Oh, that sounds pretty stellar. I'll give it a go later this evening!

**Comment by zenangst** [comment]
@johnno1962 is this the fix for injecting classes that don't inherit from `NSObject`? - https://github.com/johnno1962/InjectionIII/commit/69bea254a696f8fdbe50d2c1b02e899a2cc6e88f#diff-18639e3a0b290faf6a8d18ab284aec54R392

** Trying to slowly learn the inner-workings of InjectionIII in the hopes of being able to contribute

**Comment by johnno1962** [comment]
Thats it. They changed the mangling with Swift 4.2. Thanks for getting me round to this. It’s been on the list for a while.

**Comment by zenangst** [comment]
Is it Swift 4.2 specific or would it work for older versions? Maybe it wasn't an issue with <4.2 ?

**Comment by johnno1962** [comment]
Unfortunately until Swift symbols settle down (related to ABI) it’s not possible to produce a version that supports multiple swift versions when you’re loading a pre-compiled bundle. The alternative would be to package it as a cocoapod.
