### ISSUE TITLE
recompile fail with local framework header missing

### ISSUE THREAD

**Issue by miku1958** [johnno1962/InjectionIII#192]
InjectionIII always recompile swift file fail when search c header to bridge header once I using:
#import <UMPUsh/UMessage.h> rather than #import "UMessage.h"

💉 *** Re-compilation failed (/Users/mi/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
/Users/mi/Desktop/xxx/Resources/bridging-Header.h:23:9: error: 'UMPUsh/UMessage.h' file not found
#import <UMPUsh/UMessage.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/mi/Desktop/xxx/Resources/bridging-Header.h'
 ***

It there any solution?

**Comment by johnno1962** [comment]
Look at adding to your header search path in build settings.

**Comment by KBvsMJ** [comment]
@miku1958  The problem you encountered has been solved? Is there a solution?
