### ISSUE TITLE
  Expected in: flat namespace ... _OBJC_CLASS_$_BaseTabBarController .

### ISSUE THREAD

**Issue by orzxu1988** [johnno1962/InjectionIII#193]
I couldn't resolve my issue by looking into other threads.

Injection connects correctly, 

💉 Injection connected 👍
💉 Watching /****/code/trunk/**

and when I hit command-save, the console fires:

💉 *** Compiling /******/AppDelegate.m ***
💉 Loading .dylib ...
💉 *** dlopen() error: dlopen(/Users/martin.ren/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.dylib, 2): Symbol not found: _OBJC_CLASS_$_BaseTabBarController
  Referenced from: /Users/martin.ren/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.dylib
  Expected in: flat namespace
 in /Users/martin.ren/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.dylib ***

Injection: v1.7
Xcode: v11.0 (named as Xcode.app in Applications directory)

The programming language: Objective-C.
Any file saved will report an error like this.

**Comment by johnno1962** [comment]
Hi, is BaseTabBarController a class from a third party library? sometimes these are not visible to injection as they have a “hidden” attribute set by the provider (e.g. google analytics)

**Comment by bytegh** [comment]
I think I got the same error when I using Xcode11

https://github.com/johnno1962/InjectionIII/issues/199
