### ISSUE TITLE
Successful injection but no changes on simulator (Xcode 11.2.1, macOS Catalina 10.15.1)

### ISSUE THREAD

**Issue by tmprk** [johnno1962/InjectionIII#196]
I downloaded InjectionIII from the mac app store and included
```swift
#if DEBUG
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()
#endif
```
in my AppDelegate file. The injection bundle is loaded properly when I run the project and includes the injections when I press `cmd + s` but the view doesn't change. I've seen related issues but most were on Xcode 10. [It seems to be working fine on Xcode 11](https://github.com/johnno1962/InjectionIII/issues/166#issuecomment-517180222) so I'm not sure why it isn't working on the latest release. Any ideas why?
```swift
💉 Loaded .dylib - Ignore any duplicate class warning ^
💉 Injected 'ViewController'
```

**Comment by johnno1962** [comment]
Are you calling viewDidLoad from an \@objc injected() method?

**Comment by tmprk** [comment]
Ahh, that did it. Didn't know we were supposed to call `@objc func injected()`
