### ISSUE TITLE
Not work on Swift Package Manager

### ISSUE THREAD

**Issue by yycking** [johnno1962/InjectionIII#197]
InjectionIII cannot `file watcher` on project that create by Swift Package Manager.
Work around is to create xcodeproj by `swift package generate-xcodeproj`.

Is it be possible to use package.swift without xcodeproj?

**Comment by johnno1962** [comment]
Interesting, we didn't think of that! It would require new release to take this into account. I'll think about it. Any chance you could post a simple example project?

**Comment by yycking** [comment]
I had create a sample
https://github.com/yycking/injectSPM

**Comment by johnno1962** [comment]
Hi @yycking, we've made a small change to injection and a new release candidate that accepts Package.swift as a project is up if you want to give it a try.

**Comment by yycking** [comment]
Hi @johnno1962 ,

I am not sure if it was caused by Sandbox
> 💉 *** Could not locate containing project or it's logs.
> For a macOS app you need to turn off the App Sandbox.
> Have you customised the DerivedData path? ***

But, it will fix after `generate-xcodeproj`

**Comment by johnno1962** [comment]
Hi, looks like the file watcher is working but you need an xcodeproj after all for the logs to be generated.
