### ISSUE TITLE
Amazing tool! But one small bug, getting "Could not locate storyboard compile"

### ISSUE THREAD

**Issue by ryanneuroflow** [johnno1962/InjectionIII#198]
Xcode: 11.3
iOS Simulator: 13.3
Derived data: Default
Version: 1.8 (also tried with 1.7, updated to 1.8 to see if it fixed this issue)
Code reloading: Working wonderfully!

When I change a storyboard and save, I get an error in the console:
`💉 *** Could not locate storyboard compile ***`

I understand storyboard/xib support is experimental, but oh my god would it be wonderful to have fully functional. I tried doing a cmd-b like I saw suggested in another post, but no such luck.. it actually prints the exact same error as soon as I hit cmd-b on the unsaved storyboard.

Let me know if there's anything I can do to help - logs to pull or something. 
This tool is incredible though and you are a saint for creating it!

**Comment by johnno1962** [comment]
Hi, Loading storyboards is different from loading code. You don’t save the storyboard, you build the project instead which saves the storyboard and compiles it.

**Comment by ryanneuroflow** [comment]
> I tried doing a cmd-b like I saw suggested in another post, but no such luck.. it actually prints the exact same error as soon as I hit cmd-b on the unsaved storyboard.

Isn't that what I'm doing? Sorry if I'm misunderstanding

**Comment by johnno1962** [comment]
I wonder if this is a problem with Xcode 11.3, downloading now...

**Comment by johnno1962** [comment]
I've just tried Xcode 11.3 and it seems to work fine. Unless you can come up with a small project that replicates the problem I can’t say much more. This is practically an unsupportable feature.

**Comment by ryanneuroflow** [comment]
Ok thanks for looking into it - I'll take some time towards the end of the day today and try to recreate with a sample project. If you don't hear from me by the end of the day feel free to close this.
