### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by Sully73** [johnno1962/InjectionIII#2]
Hi,

I have tried loading the bundle directly and using the "start injection".  When trying to load the Bundle in didFinishLaunchingWithOptions, i get 

```
2017-11-28 14:01:53.283088-0400 CN-iOS[9053:630912] Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/libswiftXCTest.dylib
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found
```
I know for certain the bundle is in that location, so any idea what may be causing that?

**Comment by johnno1962** [comment]
Hi, A couple of things to check.. Is this the binary version you’re using? Is your Xcode.app at the standard path /Applications? Have you tried building from source? I’m keen to work out what’s going on here. If you’d like to TeamView can you send your details to injection at johnholdsworth dot com

**Comment by johnno1962** [comment]
HI, sorry this was my fault. I uploaded a broken version of the binary yesterday built with an Apple toolchain. It should be ok now.

**Comment by Sully73** [comment]
That fixed it. Thank you!

**Comment by MarkVillacampa** [comment]
I'm experiencing this issue again with "Version 1.0 (789)".

Running `otool -L /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection `  shows the bundle tries to load `@rpath/libswiftXCTest.dylib`.
