### ISSUE TITLE
crash on I've been injected: *nil description*

### ISSUE THREAD

**Issue by Just013** [johnno1962/InjectionIII#200]
i used storyboard, and a tableViewController. when i command + s , the project will crash,and log: "I've been injected: *nil description*"
what is wrong ?

**Comment by johnno1962** [comment]
Hi, I’m not sure about the specific error you’re seeing but for storyboard injection you must build the project to inject i.e. don’t just save the file but use cmd-b not cmd-s.

**Comment by Just013** [comment]
i find this problem:
1.after command + s ,  this project will be crash 90%, the 10% is normal.
2.x-code will auto save, this causes repeat drawing.
3.i can take a video for you to emersion this problem. please give me your Email... thanks

**Comment by johnno1962** [comment]
Hi, Thanks for tracking this down. If you could possibly produce an example project that show the problem rather than a video that would be a big help.
