### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by 616115891** [johnno1962/InjectionIII#202]
<img width="528" alt="截屏2020-02-12下午12 23 25" src="https://user-images.githubusercontent.com/14053894/74302737-7adba380-4d92-11ea-9c0c-37359dcaa40f.png">

**Comment by johnno1962** [comment]
Hi, This is probably because of a case-sensitivity issue in your project i.e. the file is in directory InjectionTest rather than injectionTest in your project. Try re-adding it to your project.

**Comment by 616115891** [comment]
> Hi, This is probably because of a case-sensitivity issue in your project i.e. the file is in directory InjectionTest rather than injectionTest in your project. Try re-adding it to your project.

same question
<img width="446" alt="截屏2020-02-12下午2 40 10" src="https://user-images.githubusercontent.com/14053894/74309383-94d2b180-4da5-11ea-9bda-65c544782686.png">

**Comment by 616115891** [comment]
> Hi, This is probably because of a case-sensitivity issue in your project i.e. the file is in directory InjectionTest rather than injectionTest in your project. Try re-adding it to your project.

Catalina 10.15.3

**Comment by 616115891** [comment]
Xcode 11.3.1

**Comment by johnno1962** [comment]
All I am saying is that compilation in Injection is case-sensitive so you have to be a bit careful.

**Comment by 616115891** [comment]
> All I am saying is that compilation in Injection is case-sensitive so you have to be a bit careful.

Still not work,can you describe in detail?

**Comment by 616115891** [comment]
> All I am saying is that compilation in Injection is case-sensitive so you have to be a bit careful.

I have a new project and still have this problem

**Comment by johnno1962** [comment]
Hmmm, try running the script it mentions to see if it is another problem. Also try moving the project to you home directory rather than desktop. I can’t understand the “Operation no permitted” error.

**Comment by 616115891** [comment]
> Hmmm, try running the script it mentions to see if it is another problem. Also try moving the project to you home directory rather than desktop. I can’t understand the “Operation no permitted” error.

Thanks!

**Comment by gatherheart** [comment]
It's late, but if I answer here, it's because of the project location issue.
The client project's location should be on allowed location.
For example, simulator cannot access "~/Download" location, and prints Operation no permitted” error.
