### ISSUE TITLE
The file system injection uses is case sensitive.

### ISSUE THREAD

**Issue by Nil-Wang** [johnno1962/InjectionIII#208]
`💉 *** File /Users/caesar/Desktop/suibian/suibian/ViewController.swift is not readable. This could be because
the file is in a secure area of the file system or because the
case of the letters in the file name does not match that in the
Xcode project. The file system injection uses is case sensitive. ***`

**Comment by Nil-Wang** [comment]
I'm just create a demo, but it's not work...

**Comment by johnno1962** [comment]
Hi, is this Catalina? If so, for some reason you can’t inject projects in ~/Desktop

**Comment by Nil-Wang** [comment]
> Hi, is this Catalina? If so, for some reason you can’t inject projects in ~/Desktop

Oh well，thank you
