### ISSUE TITLE
build failure   file not found     xcode 11.3  macOS 10.14.6

### ISSUE THREAD

**Issue by liuaaaddxiaoer** [johnno1962/InjectionIII#211]
💉 *** Re-compilation failed (/Users/xxx/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
fatal error: malformed or corrupted AST file: 'could not find file '/Users/xxxxx.h' referenced by AST file '/Users/xxx-fivrjpkkiqxrcnfjcokxubntgejp/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/1365542912086092492/xxx-Prefix.pch.gch''
note: after modifying system headers, please delete the module cache at '/Users/xxx/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/YDUAI77BEDN5'
1 error generated.
 ***

If  set  Precompile Prefix Header  = No   only show  file not found

**Comment by johnno1962** [comment]
Hi, Have you tried modifying you head search path, or, deleting the ModuleCache mentioned?

**Comment by songxing10000** [comment]
Say where you can't find pch, just put the copy of pch where

**Comment by liuaaaddxiaoer** [comment]
用项目路径地址是吗

**Comment by LionWY** [comment]
> 用项目路径地址是吗

你解决了吗？跟你同样的问题

**Comment by imbahong** [comment]
> Hi, Have you tried modifying your header search path, or, deleting the ModuleCache mentioned?

Hi, author，I resove this problem

**Comment by imbahong** [comment]
> Hi, Have you tried modifying your header search path, or, deleting the ModuleCache mentioned?

Hi, author,i resoved this problem about three steps:
1. remove $(SRCROOT) in prefix Header
![1601738364646](https://user-images.githubusercontent.com/19756873/94995143-e64add80-05ce-11eb-90e7-2b0688c5ca17.jpg)
2.command + k,  clean project   
3.remove all files in /Library/Developer/Xcode/DerivedData folder
4.simulater,  choose Device -> Erase all contens and settings
5.Reset Computer and reopen Xcode

I hope I can help someone~@johnno1962

**Comment by johnno1962** [comment]
Thanks for writing this up 👍

**Comment by mistdon** [comment]
> > Hi, Have you tried modifying your header search path, or, deleting the ModuleCache mentioned?
> 
> Hi, author,i resoved this problem about three steps:
> 
> 1. remove $(SRCROOT) in prefix Header
>    ![1601738364646](https://user-images.githubusercontent.com/19756873/94995143-e64add80-05ce-11eb-90e7-2b0688c5ca17.jpg)
>    2.command + k,  clean project
>    3.remove all files in /Library/Developer/Xcode/DerivedData folder
>    4.simulater,  choose Device -> Erase all contens and settings
>    5.Reset Computer and reopen Xcode
> 
> I hope I can help someone~@johnno1962

Not work for me

**Comment by x122536638** [comment]
如果xx.h报错  就把pch导入xx.h注释掉即可

**Comment by x122536638** [comment]
如果xx.h报错 就把pch文件里     import  "txx.h" 这一行注释掉即可

**Comment by jumpingfrog0** [comment]
> > Hi, Have you tried modifying your header search path, or, deleting the ModuleCache mentioned?
> 
> Hi, author,i resoved this problem about three steps:
> 
> 1. remove $(SRCROOT) in prefix Header
>    ![1601738364646](https://user-images.githubusercontent.com/19756873/94995143-e64add80-05ce-11eb-90e7-2b0688c5ca17.jpg)
>    2.command + k,  clean project
>    3.remove all files in /Library/Developer/Xcode/DerivedData folder
>    4.simulater,  choose Device -> Erase all contens and settings
>    5.Reset Computer and reopen Xcode
> 
> I hope I can help someone~@johnno1962
Not work for me too.
