### ISSUE TITLE
cant find ClasSymbols

### ISSUE THREAD

**Issue by natewang** [johnno1962/InjectionIII#212]
`
shell(command: """
            \(xcodeDev)/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm \(tmpfile).o | grep -E ' S  _OBJC_CLASS_\\$_| _(_T0|\\$S|\\$s).*CN$' | awk '{print $3}' >\(tmpfile).classes
`
Cant find the class, my output like this. 
Class start with U, not S
![image](https://user-images.githubusercontent.com/5310851/77304378-5084ea80-6d2f-11ea-918d-4a72014a1721.png)

**Comment by natewang** [comment]
@johnno1962

**Comment by johnno1962** [comment]
Hi, `U` means undefined, i.e a reference to a class in the object file you are injecting so this shouldn’t be a problem. What version of Xcode is this?

**Comment by natewang** [comment]
> Hi, `U` means undefined, i.e a reference to a class in the object file you are injecting so this shouldn’t be a problem. What version of Xcode is this?

11.3 (11C29). 
yes,this is not a problem, but this project class always start with U，D. the other project is good, i dont know why?  @johnno1962

**Comment by natewang** [comment]
@johnno1962  can i delete the S ？ so i can get the right class

**Comment by johnno1962** [comment]
I wouldn’t recommend that. It’s used to determine which classes a _defined_ in the object file.

**Comment by natewang** [comment]
thanks a lot, i will close this issue.
