### ISSUE TITLE
Build EvalApp into Injector app, bring up a REPL console similar to lldb but nicer

### ISSUE THREAD

**Issue by web3d0** [johnno1962/InjectionIII#213]
lldb is somewhat annoying to use for probing around due to needing "po" at the front of every line. Since EvalApp already exists, build it into InjectorIII and make it into a nice command line REPL.

(how do I mark this as a feature request, not a bug?)

**Comment by johnno1962** [comment]
Hi, in fact the “EvalApp” code is already built into InjectionIII though it is well hidden. You access it through the “Run Xprobe” menu item which gives you a list links for the objects in the application found by  “the sweep”. Click on one of the object links and you can run code against it by pressing the “Eval code against this instance” button which brings up an editor. It is likely you will be the first person in the world to use this feature and your millage will vary but on a good day with the tide behind you it works fairly well.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1786033/77892343-c67adb80-7272-11ea-8167-5585fbda5483.png">

**Comment by web3d0** [comment]
If I'm the first person in the world to use this, the rest of the world is way behind! Been looking for this since Smalltalk days. Programmed in Nu then moved to Javascript. I think it's true, Basic does ruin the mind, but only because it shows you what should be possible. Now here it is!
