### ISSUE TITLE
Enable InjectionIII to run on iPad and iPhone, not just the simulator

### ISSUE THREAD

**Issue by web3d0** [johnno1962/InjectionIII#214]
Since InjectionIII communicates over a socket, why couldn't the injection code run on the iPad/iPhone as well? Instead of Bundle(path:"/Applications...."), the bundle could be included into the project and then built for the iPad to run natively?

I work on AR applications, so I'm not able to use the Simulator for making a world map and then probing through it. So I need to be able to hot reload on the real device... (FEATURE REQUEST: not a bug)

**Comment by johnno1962** [comment]
Hi stephen, Injection used to work this way but changes to the sandbox on real devices now prevent this. You can now  longer dyload from a directory that is writable.

**Comment by web3d0** [comment]
Can you dyload a hard-linked file in a non-writeable directory? Often the update is a copy which breaks the hard-link, but you could overwrite the data and preserve the link. Or did Apple already handle all that kind of file access lawyering and just block it all off?

**Comment by johnno1962** [comment]
I’ve not tried that specifically but Apple went out of their way to stop ad-hoc updates to app code on the device. A hard link is an interesting idea though.

**Comment by web3d0** [comment]
Another thought, could use lldb custom breakpoints to inject code? This is running on the iOS device: https://developer.apple.com/videos/play/wwdc2018/412/?time=502

**Comment by johnno1962** [comment]
Back in the plugin days you used to be be able to invoke injection by injecting a lldb command. The problem is you can’t update the .dylib with new code on a real device and have it loadable since iOS 10.

**Comment by web3d0** [comment]
Maybe give up on the recompile and load new .dylib, and implement InjectionIV by diffing the lines of code and auto-inserting custom breakpoints to skip lines and to run lines?

**Comment by johnno1962** [comment]
We’d need to go back to being a plugin again which is no longer possible. Keep the ideas coming, there has to be a better way. Many people miss the days when it worked on a phone.

**Comment by web3d0** [comment]
Run a Swift REPL on the iPad side?

Recompile then directly overwrite memory?

Bridge the iPad sensors to the Simulator, so I can wave the camera around for AR and it's all on the Simulator?
