### ISSUE TITLE
could not find file 

### ISSUE THREAD

**Issue by LongLIGit** [johnno1962/InjectionIII#215]
💉 *** Re-compilation failed (/Users/lilongchangingedu.com/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
fatal error: malformed or corrupted AST file: 'could not find file '/Users/lilongchangingedu.com/QQingStudent/student/Models/StudentInfoHelper.h' referenced by AST file '/Users/lilongchangingedu.com/Library/Developer/Xcode/DerivedData/QQing-bbwooyimassnosauipkehqrvowkt/Build/Intermediates.noindex/PrecompiledHeaders/QQing-Prefix-ambuvchcmrvsfvanaworgabldvak/QQing-Prefix.pch.pch''
note: after modifying system headers, please delete the module cache at '/Users/lilongchangingedu.com/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3FJNMFI76WGNC'
1 error generated.

**Comment by johnno1962** [comment]
Hi, You may need to alter the "header search path" of your project.

**Comment by LionWY** [comment]
> Hi, You may need to alter the "header search path" of your project.

add the link path "StudentInfoHelper.h"?

**Comment by johnno1962** [comment]
What is the error you are getting? Sounds like you just need to add a directory to your header search path in build settings.

**Comment by LionWY** [comment]
> What is the error you are getting? Sounds like you just need to add a directory to your header search path in build settings.

I fix the bug, But now  I have another problem, here the error info
`💉 *** Re-compilation failed (/var/folders/xx/m_c6ngsd1qd_9hwwtf2hjqssqpj9ht/T/com.johnholdsworth.InjectionIII//command.sh)
error: PCH was compiled with module cache path '/Users/lion_liu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1TJ4M88Y6JDIA', but the path is currently '/Users/lion_liu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/161X17CHAUI22'
error: definition of macro 'EnableDebugMode' differs between the precompiled header ('@"1"') and the command line ('@1')
2 errors generated.
 ***`
Then  I try close the Precompile prefix header,
the other error info
`💉 *** Re-compilation failed (/var/folders/xx/m_c6ngsd1qd_9hwwtf2hjqssqpj9ht/T/com.johnholdsworth.InjectionIII//command.sh)
In file included from <built-in>:1:
/Users/lion_liu/Desktop/Git/xxx/Classes/xxx.pch:45:9: fatal error: 'xxxx.h' file not found
#import "xxxx.h"
        ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
 ***`

**Comment by LionWY** [comment]
almost crazy

**Comment by johnno1962** [comment]
xxxx.h is your file? That would be the header search path again. The other error I’ve seen before. Is EnableDebugMode yours?

**Comment by LionWY** [comment]
xxx.h is just the file I create, not in the framework or .a, still need the header search path? I'm not sure,
EnableDebugMode is mine, I can try delete it.

**Comment by LionWY** [comment]
> xxxx.h is your file? That would be the header search path again. The other error I’ve seen before. Is EnableDebugMode yours?

`The other error I’ve seen before.` is there a resolved method ?

**Comment by johnno1962** [comment]
Sorry I haven’t seen it before. I you can remove it that may help.
