### ISSUE TITLE
Hello when I failed to save, there are the following reasons, any good Suggestions and methods

### ISSUE THREAD

**Issue by zuqiu123** [johnno1962/InjectionIII#220]
When I modify the code to save an error, could  you help me occasionally
```swift
         ^
xxxxxx/AZConfiguration+HealthSettings.h:8:2: note: in module 'AmazfitWatchService' imported from /xxxx/Model/Configuration/AZConfiguration+HealthSettings.h:8:
#import <AmazfitWatchService/HMServiceAPI+AmazfitConfiguration.h>
 ^
xxxx/Pods/HMNetwork/Carthage/Build/iOS/Static/AmazfitWatchService.framework/Headers/HMServiceAPI+AmazfitThirdPartyAuthorize.h:39:12: warning: duplicate definition of category 'ThirdPartyAuthorize' on interface 'HMServiceAPI'

<unknown>:0: error: failed to import bridging headerxxxxx/SupportingFiles/MiFit-Bridging-Header.h'
```

**Comment by johnno1962** [comment]
Hi, you'll probably need to set the header search path for your project then it should inject.

**Comment by zuqiu123** [comment]
Hello my idol, I found that the a library can not be used directly, relying on another b library, but there is a b library in the project, this is to modify the file, suggesting that the a library cannot find the class in the b library, this pair is injected Does it have an impact, it is still unsuccessful, and it is a headache

**Comment by johnno1962** [comment]
What error message are you seeing?
