### ISSUE TITLE
Does it support Objective-C?

### ISSUE THREAD

**Issue by xiaohange** [johnno1962/InjectionIII#23]
Does it support Objective-C ? If you support Objective-C, how to access it? Thanks!

**Comment by johnno1962** [comment]
I should just  work

**Comment by xiaohange** [comment]
@johnno1962 Thanks!

**Comment by andermoran** [comment]
It doesn't "just work" for me. I have tried saving my project and doing the hotkey but nothing happens. Could you write a couple steps as to what we're supposed to do? I'm using Xcode 10 on Mojave
