### ISSUE TITLE
Problem reloading nib

### ISSUE THREAD

**Issue by nerdycat** [johnno1962/InjectionIII#233]
Good day Johnno. For some reason, I'm using individual XIB files to construct UI. When I make changes to an XIB file and rebuild the project, I very often getting this error message:

*** Assertion failure in -[UINib initWithNibName:directory:bundle:], /Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3920.31.100/UINib.m:97
Problem reloading nib: Invalid parameter not satisfying: (name != nil) && ([name length] > 0)

By the way, I'm using the latest version of InjectionIII (2.0.0) downloaded form AppStore.

**Comment by johnno1962** [comment]
Hi, I haven’t tested nib injection as opposed to storyboard for some time. Are bulling the project instead of just saving the nib. Are you saying this is an intermittent problem (which would be strange)?

**Comment by nerdycat** [comment]
I haven't found a specific way to reproduce this issue yet. It seems like this could happen after altering any XIB file (not very often this time, weird). When the error message occurred, any subsequent changes to an XIB file will produce the same result unless restart the App. 
Yes, I'm build the project instead of just saving the nib.
