### ISSUE TITLE
no suitable image found

### ISSUE THREAD

**Issue by TomLongJoy** [johnno1962/InjectionIII#234]
when I command + S . the log shows this 
💉 Injection connected 👍
💉 Watching /Users/xxxxxxx/Desktop/GitHub/SVProgressHUD/Demo/**
💉 *** Compiling /Users/xxxxxxx/Desktop/GitHub/SVProgressHUD/Demo/Classes/ViewController.m ***
💉 Loading .dylib ...
💉 *** dlopen() error: dlopen(/Users/xxxxxxx/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib, 2): no suitable image found.  Did find:
	/Users/xxxxxxx/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib: mach-o, but not built for iOS simulator ***

**Comment by johnno1962** [comment]
Hi, that’s a problem I wouldn’t expect. Have you tried cleaning the project, rebuilding and try again?

**Comment by DSPerson** [comment]
> Hi, that’s a problem I wouldn’t expect. Have you tried cleaning the project, rebuilding and try again?

Yes. i clean my project . but it not work.
this is my thread track
```
Error loading /Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle/Contents/MacOS/macOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle/Contents/MacOS/macOSInjection, 265): no suitable image found.  Did find:
	/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle/Contents/MacOS/macOSInjection: code signature in (/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle/Contents/MacOS/macOSInjection) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
```

**Comment by johnno1962** [comment]
What version of macOS/Xcode  is this?

**Comment by DSPerson** [comment]
> What version of macOS/Xcode is this?

Thanks reply；
Xcode is 11.3.1 
OSX: 10.15

**Comment by johnno1962** [comment]
I see you’re using macOS injection which is less common so we may not have seen this before. Have you tried building InjectionIII from the repo?

**Comment by DSPerson** [comment]
> 我看到您使用的是不常见的macOS注入，因此我们以前可能没有看到过。您是否尝试过从仓库中构建InjectionIII？

not before; I try it now；

**Comment by DSPerson** [comment]
谢谢！ I build source code. It works;

**Comment by johnno1962** [comment]
Interesting. This seems to be something new with Catalina. Thanks for the report. Not sure there’s much I can do about it.

**Comment by DSPerson** [comment]
> Interesting. This seems to be something new with Catalina. Thanks for the report. Not sure there’s much I can do about it.

Thanks 。 Great

**Comment by johnno1962** [comment]
The solution to this seems to be to select “Disable Library Validation” under hardened runtime in "Signing and Capabilities".
