### ISSUE TITLE
Can u support xcode 12 beta （；

### ISSUE THREAD

**Issue by JaterLee** [johnno1962/InjectionIII#237]

**Comment by johnno1962** [comment]
Hi, Xcode 12 beta should be fine. What version of macOS are you using? macOS 11 Big Sur is not supported as yet.

**Comment by johnno1962** [comment]
If you are using Big Sur, please use this release https://github.com/johnno1962/InjectionIII/releases/tag/2.1BS1

**Comment by JaterLee** [comment]
> If you are using Big Sur, please use this release https://github.com/johnno1962/InjectionIII/releases/tag/2.1BS1

thank you very much!

**Comment by johnno1962** [comment]
Hi, there is a new Beta available which will allow you to inject any member function not just non-final ones on classes. You should just just need to add "-Xlinker -interposable” to your project's "other linker flags” for it to work.
