### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by yingpaihuai** [johnno1962/InjectionIII#24]
Some ***.m can Re-compilation succ
but some ***.m (***.m means some of my class)

Log below:
*** Re-compilation failed
xxxxxxxxxx （lots of ***.h Compiling path ）
 fatal error: '***.h' file not found
#import "***.h"
        ^~~~~~~~~~~~~

But when i rebuild all project 
xcode can build succ and run succ.

version and language:
Xcode 9.3 object-c

**Comment by johnno1962** [comment]
Normally this is to do with case insensitivity. In injection “File.h" is not equal to "file.h"

**Comment by blastmann** [comment]
It seems that the Header Search Paths doesn't expand to the right path like below:

Header Search Paths configure like this: `$(SRCROOT)/../../../../AAA/**`

The command.sh will expand it like this: `-I../../../../AAA/ -I../../../../AAA/bbb`, `$(SRCROOT)` is missing.
