### ISSUE TITLE
Error: no such module 'Module Name' - Using local SPM dependencies

### ISSUE THREAD

**Issue by mendesbarreto** [johnno1962/InjectionIII#244]
Hello guys,

I start to us InjectionIII on my project, but every time I hit CMD + S , this error message is displayed:

```
💉 *** Re-compilation failed (/var/folders/lp/_b_sv9h55g555b7n0zc312nc0000gn/T/com.johnholdsworth.InjectionIII//command.sh)
/Users/douglasmendes/Git/socialmom-ios-legacy/socialmom/Feature/Content/Data/Gateway/LocalMediaInformationGateway.swift:7:8: error: no such module 'SocialMomCore'
import SocialMomCore
```

SocialMomCore is a module from SPM lib that I have created, it seems like Injection could not find the module.. This module is linked by the frameworks tab on Xcode like that:
![Screen Shot 2020-07-23 at 3 31 20 PM](https://user-images.githubusercontent.com/2684784/88330555-919b0480-ccf9-11ea-829d-b91ec2cd7133.png)

I already included de dependency folder to InjectionIII but the result is the same.

**Comment by johnno1962** [comment]
Interesting, that shouldn’t happen. Have you looked at the script file the log mentions to see what it is doing:
/var/folders/lp/_b_sv9h55g555b7n0zc312nc0000gn/T/com.johnholdsworth.InjectionIII//command.sh
