### ISSUE TITLE
Opens the injection 💉 swift often cannot print log

### ISSUE THREAD

**Issue by zuqiu123** [johnno1962/InjectionIII#248]
![image](https://user-images.githubusercontent.com/15611129/89011000-393fb480-d342-11ea-93ac-ea8eb09b71a2.png)

**Comment by johnno1962** [comment]
I’m not sure what you are saying is the problem but I know people have had issues trying to inject code in the `Desktop` folder.

**Comment by zuqiu123** [comment]
1. It means that the contents of variables cannot be printed out when debugging is disconnected.

2.I know people have had issues trying to inject code in the Desktop folder.
How to fix him, where to move him

**Comment by johnno1962** [comment]
It doesn’t seem like using the Desktop folder is your problem, you could try moving the project to your home folder. With respect to printing variables it could be anything and LLDB is never very reliable. Are you saying this only happens when you inject code?

**Comment by zuqiu123** [comment]
```
Yes, it only happens when injection is used, when I start injection, run the project, and then fill in the code `command + S` save, after breakpoint, unable to print the information, close the injection, reruns the project, LLDB printing is fine
```

**Comment by johnno1962** [comment]
I’ll take a look but I’m not sure there is much I can do. To be honest I’m surprised breakpoints are working given the injected code is loaded from a different object file and lives in a different part of memory. LLDB was not written with Injection mind.

**Comment by johnno1962** [comment]
I’ve been able tore plicate this and tried a few things but I not been able to find a solution. Would you know if this is new to the last version of InjectionIII (2.2.0)? If you’re looking to inspect `self` have you tried the `Run Xprobe` menu item?

**Comment by zuqiu123** [comment]
```
1.Hi idol, this not only self does not print out, but Po fails after all variables are switched off. I don't know why.

2.I updated the latest version of the App Store

3.What's this' Run Xprobe '? I've never Run this
```

**Comment by johnno1962** [comment]
`Run Xprobe` is on the Menu that appears when you click on the Injection icon on the menu bar. It’s lists the objects in your app and you can inspect them.
