### ISSUE TITLE
Can't find ordinal for imported symbol for architecture x86_64

### ISSUE THREAD

**Issue by wuchuanyu** [johnno1962/InjectionIII#249]
Injection works fine without "-Xlinker -interposable".
But after adding "-Xlinker -interposable" to project's "Other Linker Flags", there's a link error:  "Can't find ordinal for imported symbol for architecture x86_64".

**Comment by johnno1962** [comment]
Hi, that's a new error. Can you tell me some more about your project? Does it mix Swift and Object-ve-C?
Did you set up the flag like this:
![](https://user-images.githubusercontent.com/1786033/87988527-c41de500-cae0-11ea-97e3-5aaa5d09b503.png)

**Comment by wuchuanyu** [comment]
Thanks for your reply. 
I use Injection in two projects, one mixes Swift and Objective-C, the other just use Objective-C. The issue occurs in both projects. My Xcode version is 11.6 (11E708). I set up the flag like this:
![image](https://user-images.githubusercontent.com/1055323/89292363-d7a77f00-d68e-11ea-82cd-87f081c3d503.png)
![image](https://user-images.githubusercontent.com/1055323/89292298-bc3c7400-d68e-11ea-94a3-ebe93ad00956.png)
![image](https://user-images.githubusercontent.com/1055323/89292504-0887b400-d68f-11ea-87f6-4c31f9e0adff.png)

**Comment by johnno1962** [comment]
Are you able to post your podfile here?

**Comment by wuchuanyu** [comment]
It turns out that this issue only occurs when:
1. Set both "-ObjC" and "-Xlinker -interposable"  to project's "Other Linker Flags".
I considered there is something to do with this line in Podfile before:
`use_frameworks! :linkage => :static`
It's just because my project inherited "-ObjC" from pod project, as I set "$(inherited)" to project's "Other Linker Flags".
2. I also integrated another third-party framework downloaded from http://anychat.oss-cn-hangzhou.aliyuncs.com/AnyChatCoreSDK_iOS_V8.1.zip

**Comment by johnno1962** [comment]
Great, very glad you managed to find the answer to this problem.
```
     -ObjC       Loads all members of static archive libraries that implement an Objective-C class or category.
```
I’m not sure why this causes a problem but for pure Objective-C projects you won’t need the `-Xlinker -interposable` flag.

**Comment by johnno1962** [comment]
Let’s keep this open in case anybody else runs across it.

**Comment by johnno1962** [comment]
Let’s keep this open in case anybody else runs across it.

**Comment by bmcciscoding** [comment]
> Great, very glad you managed to find the answer to this problem.
> 
> ```
>      -ObjC       Loads all members of static archive libraries that implement an Objective-C class or category.
> ```
> 
> I’m not sure why this causes a problem but for pure Objective-C projects you won’t need the `-Xlinker -interposable` flag.

my project has the same problem but I have to set '-Objc' flags. so what I should set to fix the problem?

**Comment by johnno1962** [comment]
Are you wanting to inject Swift?

**Comment by bmcciscoding** [comment]
> Are you wanting to inject Swift? If so, I currently don’t know the answer. Are you sure you need the -ObjC flag on framework or bundle where you need to inject Swift.

Thanks for you replay!😄
my proejct mixs Swift and Objc.So I decide to remove "-Xlinker -interposable" flags and Injection works fine.

**Comment by Nuke-** [comment]
Hi @johnno1962, when using -undefined -Xlinker dynamic_lookup it fixed the issue mentioned here for me but it gives warnings in the project.
`ld: warning: -undefined dynamic_lookup is deprecated on iOS Simulator`
Is this maybe not needed for simulator or is there a way to make that warnings go away?
As we have a strict no warning policy in our project, but I would like the project to be InjectionIII compatible/ready.

Given that this is related to this issue I decided not to open a new ticket for this.
If however this should be reported as a new ticket please tell me and I'll create one.

**Comment by johnno1962** [comment]
Hi @Nuke, not much I can do about that warning alas. You could argue it is a linker warning not a code warning and hence less indicative of a potential problem.
