### ISSUE TITLE
Crash Issue on big sur or only big sur?

### ISSUE THREAD

**Issue by okeyeat** [johnno1962/InjectionIII#258]
1. I initialized injectionIII and iOS simulator
2. Change background color of viewcontroller
3. cmd + s, save and send order injectionIII
4. Got below error
`Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “eval101.sh” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/folders/6k/tgvpjlv91sq0s8hy_zmlwk700000gn/T/com.johnholdsworth.InjectionIII/eval101.sh, NSUnderlyingError=0x60000170d9e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /Users/christofferwinterkvist/InjectionIII/InjectionBundle/SwiftEval.swift, line 571`

Please let me know how to prevent or fix this issue to use InjectionIII

**Comment by johnno1962** [comment]
Hi, what version of injection are you using? For Big Sur you need to use this version: https://github.com/johnno1962/InjectionIII/releases/tag/2.2.0. The App Store version won’t work though it would normally give a more helpful error.

**Comment by okeyeat** [comment]
Of course. I used above version but It doesn't work. 
Is this app needs some permissions?

**Comment by johnno1962** [comment]
I don’t think its possible you are using the Big Sur version looking at who built it. It seems to be the App Store version. The Big Sur version has the Sandbox turned off.

**Comment by borrrrring** [comment]
I having same problem with 
`Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “eval101.sh” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/folders/95/72vm5s252x5fz7t254ts75vw0000gp/T/eval101.sh, NSUnderlyingError=0x600000e600f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /Users/johnholdsworth/InjectionIII/InjectionBundle/SwiftEval.swift, line 579`

 I had install InjectionIII from AppStore and replace it to [newest Github Release version](https://github.com/johnno1962/InjectionIII/releases/tag/2.2.1) , but it doesn't help me anything at all

**Comment by borrrrring** [comment]
> I having same problem with
> `Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “eval101.sh” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/folders/95/72vm5s252x5fz7t254ts75vw0000gp/T/eval101.sh, NSUnderlyingError=0x600000e600f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /Users/johnholdsworth/InjectionIII/InjectionBundle/SwiftEval.swift, line 579`
> 
>  I had install InjectionIII from AppStore and replace it to [newest Github Release version](https://github.com/johnno1962/InjectionIII/releases/tag/2.2.1) , but it doesn't help me anything at all

I changed to Xcode 12 beta then it's all right now

**Comment by johnno1962** [comment]
What version of Xcode were you using when it was failing; It’s very strange that the Xcode version would affect it. What version of macOS is this?

**Comment by borrrrring** [comment]
> What version of Xcode were you using when it was failing; It’s very strange that the Xcode version would affect it. What version of macOS is this?

Xcode: Version 11.7 (11E801a)
MacOS: Version 11.0 Beta (20A5364e)

I feel confused as same

**Comment by minjin-violet** [comment]
good!

**Comment by johnno1962** [comment]
Sounds like this is an issue with Xcode 11.7. I’ll download it and see if I can replicate but if Xcode 12 is fine that’s good news.

**Comment by johnno1962** [comment]
I’ve made a test with Xcode 11.7 and basic injection functionality seems to be working. My intuition at this stage is this could be a character set issue with the build logs injection uses that was introduced in Xcode 11.7 but fixed in Xcode 12.

**Comment by mushanlianshi** [comment]
I have the same problem when i use Big Sur system. before I update Big Sur system, It works。 Xcode 11.3.1

**Comment by johnno1962** [comment]
Sounds like there is an issue using injection on Big Sur with old versions of Xcode. Are you using the latest release from https://github.com/johnno1962/InjectionIII/releases?

**Comment by johnno1962** [comment]
I've pushed a new release which prints more debugging information when this error occurs. Can one of you give it a try?
https://github.com/johnno1962/InjectionIII/releases/tag/2.5.1
