### ISSUE TITLE
xcode.activeWorkspaceDocument is nil in branch "MAS-version"

### ISSUE THREAD

**Issue by zlit** [johnno1962/InjectionIII#26]
```
       //InjectionServer.runInBackground
        XcodeApplication *xcode = (XcodeApplication *)[SBApplication
                           applicationWithBundleIdentifier:XcodeBundleID];
        XcodeWorkspaceDocument *workspace = [xcode activeWorkspaceDocument];
        //workspace is nil
        projectFile = workspace.file.path;
```

but in branch "master" is not nil and work fine. why?

**Comment by johnno1962** [comment]
MAS-branch has the app sandbox switched on for the App Store.

**Comment by zlit** [comment]
thanks for your answer.and i found a bug in master branch.

see this commit:
https://github.com/zlit/InjectionIII/commit/cfbb13db5df51e267240c544d33001b3aa404a52

I not sure,can i pull request to master branch, It looks like it is not polite.
you said MAS-version branch is experiment,it looks like not very stable.
so which branch can let me pull my first request~

At last, I not very good in English,i'm sorry for that.

**Comment by johnno1962** [comment]
Hi, Thanks for this. I’ve created a new branch “auto-select-project” from master you can PR this to.

**Comment by johnno1962** [comment]
Perhaps you could make it fall-back to the activeWorkspaceDocument.file.path if it doesn’t find a workspace with the binaries's name.
