### ISSUE TITLE
I don't know how to run it on macOS.

### ISSUE THREAD

**Issue by eto** [johnno1962/InjectionIII#261]
I would like to run InjectionIII on macOS. However, I tried, but it did not work.
The following, MacInjectionTest, is a source code.
https://github.com/eto/MacInjectionTest

The steps are as follows.
- Create macOS "Single View App" and "Storyboard" in Xcode.
- Add methods called injected() and show() to ViewController.swift.
- Add "Bundle" to applicationDidFinishLaunching in AppDelegate.swift.
- Added "-Xlinker -interposable" to Other Linker Flags.
- Checked "Disable Library Validation" in "Signing & Capabilities".
- Removing "App Sandbox" from "Signing & Capabilities".
- From InjectionIII, select "Open project" and open the project.

I did this, but it did not work. How can I make it work on macOS?

**Comment by johnno1962** [comment]
Hi, thanks for the example project. You were doing all this right things and the code was injecting but the problem was The "Sweep" could not find your object so injected() was not called. Add the following:
```
        NotificationCenter.default.addObserver(self, selector: Selector("injected"), name: NSNotification.Name(rawValue: "INJECTION_BUNDLE_NOTIFICATION"), object: nil)
```
