### ISSUE TITLE
Class does not implement methodSignatureForSelector:

### ISSUE THREAD

**Issue by dwirandyh** [johnno1962/InjectionIII#263]
Hello, guys, I feel so bad, but i cannot solve this issue, I got an error 

2020-08-26 13:25:50.680062+0700 GameDB[21672:880151] *** NSForwarding: warning: object 0x108074200 of class 'GameDB.TestViewController' does not implement methodSignatureForSelector: -- did you forget to declare the superclass of 'GameDB.TestViewController'?

here is my TestViewController class

```
class TestViewController: BaseViewController<HomeViewModel> {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        self.setupView()
    }

    override func setupView(){
        self.view.backgroundColor = .blue
    }

    @objc func injected() {
        setupView()
    }

}
```
Note: I use Swinject for dependency injection to inject this class

may you help me please? if you need full of source code you can visit this [link](https://github.com/dwirandyh/ios-dicoding-submission-pemula)

**Comment by johnno1962** [comment]
Hi, thanks for the example project. I'm seeing injection but not a class TestViewController. Can you tell me how I can replicate this please?

**Comment by dwirandyh** [comment]
oh @johnno1962 sorry my bad
here is the the viewcontroller 
https://github.com/dwirandyh/ios-dicoding-submission-pemula/blob/master/GameDB/GameDB/TestViewController.swift

**Comment by johnno1962** [comment]
Yes,but what do I do with it?

**Comment by dwirandyh** [comment]
oh i see, after i change the generic to non generic it works, thank you @johnno1962
