### ISSUE TITLE
How to make it work with UIView subclasses ?

### ISSUE THREAD

**Issue by X901** [johnno1962/InjectionIII#264]
Hi, 

I tried it with ViewControllers, it works without any issue
I depended on this extention 

```
extension UIViewController {
    #if DEBUG

  @objc func injected() {
  
    for subview in self.view.subviews {
        subview.removeFromSuperview()
    }
    if let sublayers = self.view.layer.sublayers {
        for sublayer in sublayers {
            sublayer.removeFromSuperlayer()
        }
    }

    viewDidLoad()
    viewWillAppear(true)
    viewDidAppear(true)
  }
    #endif

}
```

but with UIView subclass won't work

for example

 I have UIButton as subclass

```
class GFButton: UIButton {

    override init(frame: CGRect) {
        super.init(frame:frame)
        configure()
    }
        
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    init(backgroundColor: UIColor, title: String) {
        super.init(frame: .zero)
        self.backgroundColor = backgroundColor
        self.setTitle(title, for: .normal)
        configure()
    }

    
    private func configure(){
        titleLabel?.textColor = .white
        titleLabel?.font = UIFont.preferredFont(forTextStyle: .headline)
        translatesAutoresizingMaskIntoConstraints = false     
    }

@objc func injected() {
configure()
    }
}
```

and this Viewcontroller 

```
class SearchVC: UIViewController {

    let callToActtonButton = GFButton(backgroundColor: .systemGreen, title: "Get Followers")
        
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .systemBackground
        configureCallToActionButton()
    }

    func configureCallToActionButton(){
        view.addSubview(callToActtonButton)
        
        NSLayoutConstraint.activate([
            callToActtonButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -50),
            callToActtonButton.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 50),
            callToActtonButton.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -50),
            callToActtonButton.heightAnchor.constraint(equalToConstant: 50)
        ])
    }

}


```

if I tried to change 
`GFButton(backgroundColor: .systemGreen, title: "Get Followers")
`
to
`GFButton(backgroundColor: .systemGreen, title: "Get Followers1223")`

it won't change

I don't know how to make it work with UIView subclasses

**Comment by johnno1962** [comment]
Hi, The first thing to do is add a print to check whether configure is being called. i.e. is the injected() method being called? This relies on a sweep of app objects from the App’s delegate and UIWindow objects which may not see your UIView object.

**Comment by X901** [comment]
> Hi, The first thing to do is add a print to check whether configure is being called. i.e. is the injected() method being called? This relies on a sweep of app objects from the App’s delegate and UIWindow objects which may not see your UIView object.

It being called 
<img width="1137" alt="Screen Shot 1442-01-20 at 3 24 58 PM" src="https://user-images.githubusercontent.com/16876982/92476346-7a4fa200-f1e7-11ea-8f59-0520e917012b.png">

**Comment by johnno1962** [comment]
Thanks for the test project, It helps a lot! This seems to be a UIKit issue. if you change the backgroundColor instead of the textColor in configure() you can see this is injecting. I can’t say why so this doesn’t seem to be a problem with injection itself.

**Comment by X901** [comment]
> Thanks for the test project, It helps a lot! This seems to be a UIKit issue. if you change the backgroundColor instead of the textColor in configure() you can see this is injecting. I can’t say why so this doesn’t seem to be a problem with injection itself.

This issue only happend with subclass

If I move the code from GFButton to ViewController
it will work

for example
change

`    let callToActtonButton = GFButton(backgroundColor: .systemGreen, title: "Get Followers")
`
to
`    let callToActtonButton = GFButton()
`

then change

  ```
 func configureCallToActionButton(){
        view.addSubview(callToActtonButton)        
        NSLayoutConstraint.activate([
            callToActtonButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -50),
            callToActtonButton.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 50),
            callToActtonButton.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -50),
            callToActtonButton.heightAnchor.constraint(equalToConstant: 50)
        ])
    }
```

to

```
   func configureCallToActionButton(){
        view.addSubview(callToActtonButton)
        
        callToActtonButton.backgroundColor = .systemGreen
        callToActtonButton.setTitle("Get Followers", for: .normal)
        
        NSLayoutConstraint.activate([
            callToActtonButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -50),
            callToActtonButton.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 50),
            callToActtonButton.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -50),
            callToActtonButton.heightAnchor.constraint(equalToConstant: 50)
        ])
    }
```
Then the injection will work ,I can change `callToActtonButton.backgroundColor` and `callToActtonButton.setTitle`
without any problem!

like on this new test [demo](https://a.cl.ly/L1uJErnB)

**Comment by johnno1962** [comment]
Aha, I think I’m with you now. This is a lifecycle thing. The SearchVC ViewController instance is not reinitialised so changing 
```
    let callToActtonButton = GFButton(backgroundColor: .systemGreen, title: "Get Followers")
```
to
```
     let callToActtonButton = (backgroundColor: .systemGreen, title: "Get Followers1223”)
```
…will have no effect when you inject it unless you create a new SearchVC instance. When you move  the code to configureCallToActionButton() it works because this is called when you inject from viewDidLoad() which is called by the extension you have on UIViewController so you can see the display change.

**Comment by X901** [comment]
Is there any workaround ?
or I must re-run the application when I make any change to instances ?

**Comment by johnno1962** [comment]
You must recreate objects (for example by encasing your SearchVC in a navigation controller) if you want to see instance variables take new values unless you set new values via an injected method().

**Comment by X901** [comment]
I did read your reply multiple times but still don't get it 
BTW SearchVC had navigation controller , but nothing change with button title and background

Could you give me example code

**Comment by johnno1962** [comment]
I don’t know what to say.. Injection re-binds new function implementations into your app but for these to take effect these new functions have to be called so you need to think about what is the execution path of your program. Making the change you mention above to the initialiser of an instance variable will not be called unless you create a new instance of that object. There is only so much injection can do.

**Comment by X901** [comment]
Thank you, I get the idea
