### ISSUE TITLE
no suitable image found

### ISSUE THREAD

**Issue by c344081** [johnno1962/InjectionIII#266]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/libswiftCore.dylib

Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection

Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftCore.dylib: mach-o, but not built for iOS simulator

Xcode 12.0 macOS 10.15.4

**Comment by johnno1962** [comment]
Hi, is this the Mac App Store version? If so can you try the version here please: https://github.com/johnno1962/InjectionIII/releases/tag/2.2.3

**Comment by c344081** [comment]
hi, I have tried the 2.2.3 version, I can still see the error

**Comment by johnno1962** [comment]
Have you used InjectionIII before? Was there an Xcode version that worked previously? (Could this be specific to Xcode 12?)

**Comment by c344081** [comment]
I used InjectionIII before, and it worked for Xcode 11

I found it worked for my simulator with ios 14, the error only occurred when I use simulator with iOS 12.0

**Comment by johnno1962** [comment]
Very interesting, odd even. Let me try a few things. I'll get back to you if I can replicate the problem and fix it.

**Comment by johnno1962** [comment]
I've been unable to replicate the problem with Xcode 12 GM but with iOS sim 12.0. Try restarting InjectionIII as it keeps a certain amount of information about how to build files cached.

**Comment by c344081** [comment]
after add a swift file to my project, I can use it with iOS sim 12.0 now

**Comment by johnno1962** [comment]
Very interesting, curious it should only be a problem cross iOS versions. I may add this to the README.
