### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by shaozhe-chen** [johnno1962/InjectionIII#268]
![image](https://user-images.githubusercontent.com/17985450/94357197-3c002100-00c9-11eb-9888-05177918d8e2.png)

**Comment by johnno1962** [comment]
Hi, but what is the error reported?

**Comment by shaozhe-chen** [comment]
It's only get the error reported, I can't get any more error.

when I save the code , the error print

**Comment by johnno1962** [comment]
Do you see the file name it mentions ending in `command.sh`? It contains the compile command that was used you can try running it to see the error using `bash …/comand.sh` or look at the contents of the file to see if there is a problem.
