### ISSUE TITLE
-Xlinker -interposable

### ISSUE THREAD

**Issue by TTggBest** [johnno1962/InjectionIII#269]
hi.
I download InjectionIII that in the App Store , when I run it, get the error: Injection connected 👍
💉 on remembered to add "- Xlinker - interposable" to the project 's "Other would Flags"?
Then I follow this solution here. I add "Any IOS Simulator SDK" to Debug in "Other Linker Flags", assign -Xlinker-interposable, and run it again. But, the error: Have you remembered to add "-Xlinker-interposable" to your project's "Other Linker Flags"?appear again. (Xcode 12.0.1, Simulator :11 Pro max-14.0,11 Pro Max-13.0,8 plus-12.4).
When I use "iphone  8-12.1",get the error: "Error loading/Applications/InjectionIII app/Contents/Resources/iOSInjection bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/libswiftCore.dylib
Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
Reason: no suitable image found.  Did find:
The/usr/lib/swift/libswiftCore dylib: Mach - o, but not built for the iOS simulator ".
According to the solutions from "Issuess", I have tried them all and they are not issues.Please help me with them. Thank you very much.
<img width="971" alt="111111111" src="https://user-images.githubusercontent.com/25764520/94389791-5c8cb180-0183-11eb-9d39-b5a571d60626.png">
<img width="889" alt="2222222222" src="https://user-images.githubusercontent.com/25764520/94389799-62829280-0183-11eb-8d6f-9cafe0d95a64.png">
<img width="545" alt="3333333333" src="https://user-images.githubusercontent.com/25764520/94389808-66aeb000-0183-11eb-8852-8e59ee03c5be.png">

**Comment by johnno1962** [comment]
Hi, a couple of things. "Have you remembered to add "-Xlinker-interposable" to your project's "Other Linker Flags” is intended to be a friendly reminder to add that flag to your project otherwise injection won’t work. It could be printed in error if you have a complex project or have not selected the right project directory when you start injection. The other error sounds like you don’t have a versions of Xcode at the path /Applications/Xcode.app except that it is strange it should only give you that error with an iPhone 8. Probably the best thing to do is start simple with the project in http://johnholdsworth.com//GettnigStarted.zip to see injection working and then work your way up to your actual project. Another thing to try could be to add a single dummy Swift file to your project to see if it removes the error about libraries not loaded. I’ll perform some more testing of Objective-C projects this end and see if I can replicate your problem.

**Comment by TTggBest** [comment]
hi, johnno1962 .
I've added "-Xlinker-interposable" to "Other Linker Flags "as I sent the pictures. And chose the right project. InjectionIII cannot be used whether my project is complex or simple. The weirdest thing for me is that my friend doesn't have to add "-Xlinker-interposable" and can always use it, but I can never use it. I wonder if it has anything to do with my system, or my Xcode environment. 
What makes me sad is that My friend and I were working on the same project together. We both had the same Settings, "Build Settings" and downloaded "InjectionIII" from the App Store. As a result, I can't use it, but he can. I hope you can help me solve this problem.
Thank you very much.
(macOS 10.15.7 xcode 12.0.1)

**Comment by johnno1962** [comment]
Don't worry about the "-Xlinker-interposable" thing if your project is Objective-C. Sounds like there is a difference between your machines. Are you using Xcode at a different path. Did you check /Applications/Xcode.app exists? Try with GettingStarted.zip to make sure your machine is set up correctly.

**Comment by TTggBest** [comment]
My project is OC and the path of "/Applications/Xcode.app" is correct.
<img width="464" alt="12344445" src="https://user-images.githubusercontent.com/25764520/94413761-1ac53080-01ae-11eb-9737-a3810eb76206.png">
When I command + S, it appears
"💉 * * * the Compiling/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/ViewController/EquityShareVC m * * *
💉 * * * Re - compilation failed (/ var/folders/ty/s9f81hrx1mv6zn3d8bm671580000gn/T/com. Johnholdsworth. InjectionIII / / command. The sh)
error: error reading '/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/xxxxx/ViewController/EquityShareVC.m'
1 error generated.
* * *"。
So I guess it didn't inject success

**Comment by johnno1962** [comment]
OK, you're further along. Chances are this is to do with upper v.s lower case in the file name. Can you try the newer version from here: https://github.com/johnno1962/InjectionIII/releases/tag/2.3.0 please.

**Comment by TTggBest** [comment]
Thank you very much. Now it's working perfectly. It's great!
