### ISSUE TITLE
Could not locate compile command 

### ISSUE THREAD

**Issue by senlan** [johnno1962/InjectionIII#27]
*** Could not locate compile command for /Users/chengda/Documents/chenshengbao_swift_new_version/chenshengbao5.0beifen/Tea/ViewController.swift Injection doesn’t work when using whole module optimisation. If you have switched xcode versions, please cmd-shift-k to clean then rebuild the project so there is a complete build history logged and try again. /Users/chengda/Library/Developer/Xcode/DerivedData/Tea-davwimzuyhcukoecqbmyfdslmugk/Logs/Build/E1A3683C-B1E2-40DA-8BF4-84F5BACFFD92.xcactivitylog /Users/chengda/Library/Developer/Xcode/DerivedData/Tea-davwimzuyhcukoecqbmyfdslmugk/Logs/Build/../Debug/E453E80E-3EC2-496B-B74B-ADD3B0B0A62B.xcactivitylog /Users/chengda/Library/Developer/Xcode/DerivedData/Tea-davwimzuyhcukoecqbmyfdslmugk/Logs/Build/9D0A471F-7157-43CA-810C-6C12E0B74E9D.xcactivitylog /Users/chengda/Library/Developer/Xcode/DerivedData/Tea-davwimzuyhcukoecqbmyfdslmugk/Logs/Build/99C26A6F-647D-4E89-9993-7D8F9E9D15C4.xcactivitylog ***   at /Applications/Injection.app/Contents/Resources/common.pm line 61. 	main::error(‘Could not locate compile command for /Users/chengda/Documents…’) called at /Applications/Injection.app/Contents/Resources/injectSource.pl line 292 *** Bundle build failed ***

**Comment by johnno1962** [comment]
Have you tried the AppStore version “InjectionIII”?

**Comment by senlan** [comment]
Yes, but isn't working

**Comment by senlan** [comment]
*** Compiling /Users/chengda/Downloads/InjectionIII-master/SwiftEval/MasterViewController.swift ***

real	0m0.526s
user	0m0.436s
sys	0m0.071s
ld: warning: -undefined dynamic_lookup is deprecated on iOS
2018-06-21 15:03:29.055174+0800 SwiftEval[4739:661979] TIC TCP Conn Failed [9:0x60400016c180]: 1:61 Err(61)
2018-06-21 15:03:29.055549+0800 SwiftEval[4739:661979] Task <9531BD97-121D-498C-BC54-114282F7F445>.<0> HTTP load failed (error code: -1004 [1:61])
2018-06-21 15:03:29.055723+0800 SwiftEval[4739:658065] NSURLConnection finished with error - code -1004
*** Codesign failed. Is 'signer' daemon running? ***

**Comment by johnno1962** [comment]
That doesn’t look like the latest version from the App Store somehow and the error is a very strange one. Looks like your injection is confused and trying to inject itself. Do you have more than one project open?

**Comment by senlan** [comment]
*** Could not locate compile command for /Users/chengda/Desktop/beifen/chenshengbaobeifen/Tea/ViewController.swift
Try a clean build. There are also restrictions on characters allowed in paths. ***

I updated Xcode（Version 9.4.1），but it has this problem

**Comment by johnno1962** [comment]
Are you using whole module optimisation?

**Comment by senlan** [comment]
Yes, I got it, Thanks！
