### ISSUE TITLE
Is there any way to make REPL work properly? 

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [johnno1962/InjectionIII#271]
Hi, 
Recently i starded using Injection III on big project in Xcode 12, i just love it.

The only downside i can see is that it doesn't work really well with console, is there any way to get it work with REPL? 

```
(lldb) po delegate
error: <EXPR>:3:3: error: 'mutating' isn't valid on methods in classes or class-bound protocols
  mutating func $__lldb_wrapped_expr_55(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
  ^~~~~~~~~
  

warning: <EXPR>:12:9: warning: initialization of variable '$__lldb_error_result' was never used; consider replacing with assignment to '_' or removing it
    var $__lldb_error_result = __lldb_tmp_error
    ~~~~^~~~~~~~~~~~~~~~~~~~
    _
```

As for running context - each time injection is run, i'm just restarting app using internal mechanisms, so setting new navigation from scratch in app delegate.

**Comment by johnno1962** [comment]
Hi, yes this is LLDB coping poorly with the dynamically loaded code when it has been injected. I looked to see if there was something that could be done but in the end filed a bug https://bugs.swift.org/browse/SR-13499.
