### ISSUE TITLE
I don't know if the injection was successful when I used the plug-in

### ISSUE THREAD

**Issue by zuqiu123** [johnno1962/InjectionIII#272]
Idol, how are you, when I was in the use of plug-in met confusion is I don't know whether my code into success, especially when developing code for a test, I don't know whether this code has effect, I `command + s` to save, and then view the results found that there is no any response, thought he was going to write the code has a problem, and then I` command + R`to run again, found that the result is right, sometimes really brought me trouble, do you have what good method

Today I had a problem. I changed the background color of the View 
![image](https://user-images.githubusercontent.com/15611129/96833574-436ddc80-1473-11eb-9eb0-e851e592795e.png)

and found that `command+ S` did not respond, but the console already showed the replaced code
![image](https://user-images.githubusercontent.com/15611129/96833529-318c3980-1473-11eb-961d-317b478b30d5.png)

After I added this injection method, `Command + S` succeeded, which made me sometimes wonder whether the code modification was successful or not. Is there any good method? Two questions altogether

Thank you very much

**Comment by johnno1962** [comment]
Hi, You need an @objc func injected() method to make sure your changes take effect after injection. Just injecting to change to the viewDidLoad function is not enough if the view is not reloaded. This is a common error. I recommend putting in print() statements so you can see if the new version of the method is actually called and that it has been patched.

**Comment by zuqiu123** [comment]
Hi,Must I write it this way
```swift
@objc func injected() {
 viewDidLoad()
}
```
 or just have this function, you don't have to write anything in there
```swift
@objc func injected() {
}
```


If I must use `injected` functions that need to be altered to enter into force, then the agents and some methods with parameters would not know how to deal with this,How do you handle this situation

**Comment by johnno1962** [comment]
You’ll need to do something in your injected() function. The example ViewControllers have a method configureView() separate from viewDidLoad() to update the view which you call call from your injected() method. viewDidLoad() is not called unless the view has just loaded - it is not called by Injection.
