### ISSUE TITLE
File missing in the filelist.text

### ISSUE THREAD

**Issue by xyreryp** [johnno1962/InjectionIII#274]
Hi team,

I am running InjectionIII on 
```
Catalina 10.15.7 (19H2)
Xcode 11.5
Simulator iPhone 11 Pro Max 13.5
```

I am getting this error when I `cmd+s` on the file
```
 ***
💉 Mapped: FirebaseListener.swift
💉 ... to: Firebaselistener.swift
💉 *** Compiling FirebaseListener.swift ***
💉 *** Re-compilation failed (/var/folders/7d/573kd2qn5x52yssd18phrfbh3khd43/T/com.johnholdsworth.InjectionIII//command.sh)
<unknown>:0: error: primary file 'Firebaselistener.swift' was not found in file list '/var/folders/7d/573kd2qn5x52yssd18phrfbh3khd43/T/com.johnholdsworth.InjectionIII//filelist.txt'
 ***
```

I am curious where I could find the filelist.txt and the root cause of it. Is there any way that I could add the file in the filelist.txt?

Thanks

**Comment by johnno1962** [comment]
HI, Looks like this is a problem with upper vs. lower case. Check to make sure the file on the disk has exactly the same name as the file as you can see it in the project i.e. Firebase>L<istener.swift, vs. Firebase>l<istener.swift

**Comment by xyreryp** [comment]
Thank you! @johnno1962 It was fixed by renaming the file.
