### ISSUE TITLE
How can i resolve this problem？ My Xcode version is 12.2Beta and iOS14

### ISSUE THREAD

**Issue by DongWei02** [johnno1962/InjectionIII#276]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found

**Comment by johnno1962** [comment]
Which version of InjectionII is this? What is the version number? Is it the App Store version 2.2.0 or one of  the more recent releases from https://github.com/johnno1962/InjectionIII/releases

**Comment by DongWei02** [comment]
Thanks for asking. I'll try.
Did i must place The Xcode but not Xcode_beta.

**Comment by johnno1962** [comment]
You can make a symbolic link. There needs to be something at /Applications/Xcode.app

**Comment by DongWei02** [comment]
Thanks~
It works, i remove Xcode12-beta, then use Xcode11.
