### ISSUE TITLE
Doesn't work with Xcode v. 12.0.1

### ISSUE THREAD

**Issue by deda9** [johnno1962/InjectionIII#278]
I've tried it but it did stuck forever and didn't update the view, any insights?

Here's what I had:
<img width="1112" alt="Screenshot 2020-11-09 at 15 40 17" src="https://user-images.githubusercontent.com/6483622/98555242-fe82dc00-22a1-11eb-9594-3cdc41618450.png">

**Comment by johnno1962** [comment]
Hi, can you take a look at this ticket to make sure you've made all the necessary steps for SwiftUI https://github.com/johnno1962/InjectionIII/issues/275#issuecomment-719980357

**Comment by deda9** [comment]
Thank you @johnno1962  for your fast reply, but unfortunately I did all those steps and didnt work too!

**Comment by johnno1962** [comment]
Hmmm, what isn’t working? You are seeing injection but the view doesn’t update? Have you remembered "-Xlinker -interposable” for “Other Linker Flags”? This is SwiftUI using the MovieSwift app right?

**Comment by deda9** [comment]
@johnno1962 Thank you so much for following up this issue ♥️

Here's all the steps which I made

1- I created `@ObservedObject var iO = injectionObserver` (I'm not sure if its right or not)

```Swift
public struct MoviesView<ViewModel>: View where ViewModel: MoviesViewModelProtocol {
    
    @ObservedObject var viewModel: ViewModel

    public init(viewModel: ViewModel) {
        self.viewModel = viewModel
    }
    
    public var body: some View {
        HStack {
Text("Test View").eraseToAnyView()
        }
    }
    
    #if DEBUG
    @ObservedObject var iO = injectionObserver
    #endif
}
```

2- I added `"-Xlinker -interposable”` for “Other Linker Flags”

<img width="1202" alt="Screenshot 2020-11-09 at 22 23 15" src="https://user-images.githubusercontent.com/6483622/98598067-33ab2080-22da-11eb-8215-a7a867235ca2.png">


3- I added the code somewhere as you mentioned in `README`.

```Swift
#if DEBUG
private var loadInjection = {
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()
}()

import Combine

let injectionObserver = InjectionObserver()

class InjectionObserver: ObservableObject {
    @Published var injectionNumber = 0
    var cancellable: AnyCancellable? = nil
    let publisher = PassthroughSubject<Void, Never>()
    init() {
        cancellable = NotificationCenter.default.publisher(for:
            Notification.Name("INJECTION_BUNDLE_NOTIFICATION"))
            .sink { [weak self] change in
            self?.injectionNumber += 1
            self?.publisher.send()
        }
    }
}

extension View {
    func eraseToAnyView() -> some View {
        _ = loadInjection
        return AnyView(self)
    }
    func onInjection(bumpState: @escaping () -> ()) -> some View {
        return self
            .onReceive(injectionObserver.publisher, perform: bumpState)
            .eraseToAnyView()
    }
}
#else
extension View {
    func eraseToAnyView() -> some View { return self }
    func onInjection(bumpState: @escaping () -> ()) -> some View {
        return self
    }
}
#endif
```


but the view **didnt refresh** even it logged on the console 


<img width="1112" alt="Screenshot 2020-11-09 at 15 40 17" src="https://user-images.githubusercontent.com/6483622/98555242-fe82dc00-22a1-11eb-9594-3cdc41618450.png">

**Comment by johnno1962** [comment]
Thanks for your persistence and sorry you're having these problems. I'm at loss to explain why it isn't working for you. I've created a simple example using generics as you do and tested with the Mac App Store version of the App and it works.
[zwiftui.zip](https://github.com/johnno1962/InjectionIII/files/5515060/zwiftui.zip)

If you still can't get the specific code you are working on to work, I can TeamView if that's ok with you to get to the bottom of what's going on.

**Comment by deda9** [comment]
@johnno1962 Thank you so much for providing me the sample, it works well. I admit that's a magic! to refresh the view in no time 😍 

The problem was setting the other linker flags **like this:**

![image](https://user-images.githubusercontent.com/6483622/98683677-9e556e00-2365-11eb-9c9a-eea3c8118e43.png)



**Not like this:**

![image](https://user-images.githubusercontent.com/6483622/98683623-8bdb3480-2365-11eb-83c2-69ebbd5b6ff9.png)

**Comment by deda9** [comment]
@johnno1962  I'll close the issue as long as it works now and I will mention this solution on the other issue which you sent ftUI #275  , in case anyone faced the same issue again.

**Comment by johnno1962** [comment]
Glad you sorted this out. I've made a minor change to the project README.md so someone else doesn't get caught.

**Comment by CompuGenius** [comment]
> 
> 
> @johnno1962 Thank you so much for providing me the sample, it works well. I admit that's a magic! to refresh the view in no time 😍
> 
> The problem was setting the other linker flags **like this:**
> 
> ![image](https://user-images.githubusercontent.com/6483622/98683677-9e556e00-2365-11eb-9c9a-eea3c8118e43.png)
> 
> **Not like this:**
> 
> ![image](https://user-images.githubusercontent.com/6483622/98683623-8bdb3480-2365-11eb-83c2-69ebbd5b6ff9.png)

OMG, thanks so much for specifying! I went down a rabbit hole and finally found this, and i'm glad I finally did! I was following AppCode's instructions, which have you enter them as one line,
