### ISSUE TITLE
Could not load class symbol list

### ISSUE THREAD

**Issue by AshmoreT2** [johnno1962/InjectionIII#280]
Hello,

I'm trying to get InjectionIII to work for the first time on Big Sur with XCode 11.3. 

I have everything set up and it appears to be working, but when I save nothing happens and I get the following in the console. Am I missing something? I have an injected function that reloads all the views. Thanks.

```
💉 Compiling /Users/xxxxx/Developer/iOS/dfd-ios/dfd-ios/Scenes/Find Care/Controllers/FindCareSearchTableViewController.swift
💉 Loading .dylib ...
objc[77787]: Class _TtC7dfd_ios33FindCareSearchTableViewController is implemented in both /Users/xxxxx/Library/Developer/CoreSimulator/Devices/0A10FFC9-1321-4D95-A7D8-6A55510A538E/data/Containers/Bundle/Application/BF5D6030-2253-433C-BA48-4B649CED6D3B/dfd-ios.app/dfd-ios (0x1068bd8c8) and /var/folders/n5/nhp221wn23s30kvw5s73xcd80000gn/T/eval101.dylib (0x11379f770). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ^
💉 *** Could not load class symbol list ***

**Comment by johnno1962** [comment]
Hi, that's an error I wouldn't have expected to see but it's given an excuse to sort out some I've been meaning to replace for a while. Can you try with the new release https://github.com/johnno1962/InjectionIII/releases/tag/2.4.4.
