### ISSUE TITLE
InjectionIII doesn't support injecting iOS application without Simulator

### ISSUE THREAD

**Issue by unchartedworks** [johnno1962/InjectionIII#284]
M1 Mac supports iOS applications. I means we can debug iOS application without iOS simulator.
I tried to use InjectionIII for an iOS application on macOS without iOS simulator, I got an error.

Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 0x0109): could not use '/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection' because it was not built for platform iOS

Is it possible to add a new iOSInjection bundle for iOS application without simulator?

**Comment by johnno1962** [comment]
Hi, interesting. I’ve tried a few things but can’t see /Applications/InjectionIII.app from inside the application to load the bundle. Is there an entitlement I need to access the Mac’s file system? I’ve been able to build another bundle for iphoneos “miOSInjection.bundle but have a code signing error os it looks like it might not be straightforward.

You can clone the project if you like and try some things if you want. The changes I made to make the new bundle where:
diff --git a/InjectionBundle/InjectionClient.mm b/InjectionBundle/InjectionClient.mm
index 43ffd9c..57ffea3 100644
--- a/InjectionBundle/InjectionClient.mm
+++ b/InjectionBundle/InjectionClient.mm
@@ -20,6 +20,8 @@
 #import "tvOSInjection-Swift.h"
 #elif __has_include("iOSInjection10-Swift.h")
 #import "iOSInjection10-Swift.h"
+#elif __has_include("miOSInjection-Swift.h")
+#import "miOSInjection-Swift.h"
 #else
 #import "iOSInjection-Swift.h"
 #endif
diff --git a/InjectionIII/Info.plist b/InjectionIII/Info.plist
index b275776..6ad32d5 100644
--- a/InjectionIII/Info.plist
+++ b/InjectionIII/Info.plist
@@ -19,7 +19,7 @@
 	<key>CFBundleShortVersionString</key>
 	<string>$(MARKETING_VERSION)</string>
 	<key>CFBundleVersion</key>
-	<string>5177</string>
+	<string>5252</string>
 	<key>LSApplicationCategoryType</key>
 	<string>public.app-category.developer-tools</string>
 	<key>LSMinimumSystemVersion</key>
diff --git a/InjectionIII/build_bundles.sh b/InjectionIII/build_bundles.sh
index 9a7cb6b..5749dd9 100755
--- a/InjectionIII/build_bundles.sh
+++ b/InjectionIII/build_bundles.sh
@@ -25,11 +25,12 @@ function build_bundle () {
         exit 1
     fi
     "$DEVELOPER_BIN_DIR"/xcodebuild SYMROOT=$SYMROOT ARCHS="$ARCHS" -sdk $SDK -config $CONFIGURATION -target SwiftTrace &&
-    "$DEVELOPER_BIN_DIR"/xcodebuild SYMROOT=$SYMROOT ARCHS="$ARCHS" PRODUCT_NAME="${FAMILY}Injection" LD_RUNPATH_SEARCH_PATHS="$SWIFT_DYLIBS_PATH $XCTEST_FRAMEWORK_PATH @loader_path/Frameworks" -sdk $SDK -config $CONFIGURATION -target InjectionBundle &&
-    "$DEVELOPER_BIN_DIR"/xcodebuild SYMROOT=$SYMROOT ARCHS="$ARCHS" -sdk $SDK -config $CONFIGURATION -target SwiftUISupport
+    "$DEVELOPER_BIN_DIR"/xcodebuild SYMROOT=$SYMROOT ARCHS="$ARCHS" PRODUCT_NAME="${FAMILY}Injection" LD_RUNPATH_SEARCH_PATHS="$SWIFT_DYLIBS_PATH $XCTEST_FRAMEWORK_PATH @loader_path/Frameworks" -sdk $SDK -config $CONFIGURATION -target InjectionBundle #&&
+#    "$DEVELOPER_BIN_DIR"/xcodebuild SYMROOT=$SYMROOT ARCHS="$ARCHS" -sdk $SDK -config $CONFIGURATION -target SwiftUISupport
 }
 
 #build_bundle macOS MacOSX macosx &&
+build_bundle miOS iPhoneOS iphoneos &&
 build_bundle iOS iPhoneSimulator iphonesimulator &&
 build_bundle tvOS AppleTVSimulator appletvsimulator &&
 
@@ -41,6 +42,7 @@ rsync -au $SYMROOT/$CONFIGURATION/macOSSwiftUISupport.bundle $SYMROOT/$CONFIGURA
 rsync -au $SYMROOT/$CONFIGURATION/SwiftTrace.framework/{Headers,Modules,Versions} "$CODESIGNING_FOLDER_PATH/Contents/Resources/macOSInjection.bundle/Contents/Frameworks/SwiftTrace.framework" &&
 rsync -au $SYMROOT/$CONFIGURATION-iphonesimulator/SwiftTrace.framework/{Headers,Modules} "$CODESIGNING_FOLDER_PATH/Contents/Resources/iOSInjection.bundle/Frameworks/SwiftTrace.framework" &&
 rsync -au $SYMROOT/$CONFIGURATION-appletvsimulator/SwiftTrace.framework/{Headers,Modules} "$CODESIGNING_FOLDER_PATH/Contents/Resources/tvOSInjection.bundle/Frameworks/SwiftTrace.framework" &&
+rsync -au $SYMROOT/$CONFIGURATION-iphoneos/SwiftTrace.framework/{Headers,Modules} "$CODESIGNING_FOLDER_PATH/Contents/Resources/miOSInjection.bundle/Frameworks/SwiftTrace.framework" &&
 # This seems to be a bug producing .swiftinterface files.
-perl -pi.bak -e 's/SwiftTrace.(Swift(Trace|Meta)|dyld_interpose_tuple)/$1/g' $CODESIGNING_FOLDER_PATH/Contents/Resources/{macOSInjection.bundle/Contents,{i,tv}OSInjection.bundle}/Frameworks/SwiftTrace.framework/Modules/*/*.swiftinterface &&
+perl -pi.bak -e 's/SwiftTrace.(Swift(Trace|Meta)|dyld_interpose_tuple)/$1/g' $CODESIGNING_FOLDER_PATH/Contents/Resources/{macOSInjection.bundle/Contents,{i,mi,tv}OSInjection.bundle}/Frameworks/SwiftTrace.framework/Modules/*/*.swiftinterface &&
 find $CODESIGNING_FOLDER_PATH/Contents/Resources/*.bundle -name '*.bak' -delete

**Comment by unchartedworks** [comment]
Hi,
Thanks! I have applied your patch and tried to load the new bundle. I got a new error.

.bundle/miOSInjection, 0x0109): code signature in (/Applications/InjectionIII.app/Contents/Resources/miOSInjection.bundle/miOSInjection) not valid for use in process: Trying to load an unsigned library

There is no option which I can disable library validation for Mac Catalyst.

**Comment by johnno1962** [comment]
Bad luck, seems like you're nearly there but without being able to turn off library validation you won't be able to load the dynamically compiled classes or even the injection bundle unless they are signed with exact the same certificate. There was a user default to control to certificate used for the class .dylib [(currently commented out)](https://github.com/johnno1962/InjectionIII/blob/master/InjectionIII/InjectionServer.swift#L218). Let me know if you find a solution.

**Comment by unchartedworks** [comment]
I changed the entitlement of my iOS project to disable library validation. 
```
<key>com.apple.security.cs.disable-library-validation</key>
     <true/>
```
It is not working.

**Comment by johnno1962** [comment]
I guess that must be by design. Any chance you could post a small example project I can take a look at?

**Comment by unchartedworks** [comment]
<img width="1064" alt="Screenshot 2020-12-15 at 12 11 28" src="https://user-images.githubusercontent.com/4646838/102207776-dacd3a00-3ece-11eb-849d-c31f0534e2d4.png">

I think you are right. That must be by design. There is nothing special about the project. If you create an iOS project, you build it for Mac Catalyst. As you can see in the screenshot.  When you build it for Mac Catalyst, you can not enable hardened run time and disable library validation.

**Comment by johnno1962** [comment]
Even if you can’t disable library validation there is still a reasonable chance by changing the InjectionIII project to code sign the iOSInjection.bundle with the identity your target project uses (or do it manually after the build or as part of your target project build) and reinstate the ability for injection to use the same identity to sign it’s recompiled classes dylib through a user default that I mentioned above. You can get the string identifying the code signing identity from the build logs of your target project. Normally its as simple as something like:
```
export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
/usr/bin/codesign --force --sign 4C50F8659CFB22F9B956D19EA61FC68…. etc.
```
From the build log of your project though an entitlement file may complicate matters.

**Comment by unchartedworks** [comment]
It seems that I had a misunderstanding. I thought I had signed the bundle using the same code signing identity. It is good to know I should do it manually instead.

**Comment by johnno1962** [comment]
The iOSInjectionBundle is signed by the identity of the InjectionIII project whereas it needs to be signed by that of your target project if we're ever to load it when library validation is on. The identities are likely be different.

**Comment by unchartedworks** [comment]
I have some good news. I signed the bundle using the same code signing identity. It works. It can load the bundle.

After I made some changes, InjectionIII compiled the changed file successfully. 
Then I got a new issue.
It seems that there is a bug in InjectionIII, InjectionIII compiled the changed file for incorrect architecture.
```
ld: building for macOS, but linking in object file built for iOS, file '/var/folders/ty/65cvx7f570g53y5xb0xsbz_80000gn/T/eval101.o' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I guess you can use the code below to handle it.
```
#if os(macOS)
   // Put CPU-independent macOS code here.
   #if arch(arm64)
      // Put 64-bit arm64 Mac code here.
   #elseif arch(x86_64)
      // Put 64-bit x86_64 Mac code here.
   #endif
#elseif targetEnvironment(macCatalyst)
   // Put Mac Catalyst-specific code here.
#elseif os(iOS)
   // Put iOS-specific code here.
#endif
```

https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

**Comment by johnno1962** [comment]
Great progress! If your looking for where to patch the linking for this new case check here:
https://github.com/johnno1962/InjectionIII/blob/master/InjectionBundle/SwiftEval.swift#L406

**Comment by johnno1962** [comment]
Actually its a bit complicated as that code will run in the InjectionIII app. You would need to add something like the following:
```
        } else if compileCommand.contains("iPhoneOS.platform") {
            osSpecific = "-isysroot \(xcodeDev)/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=9.0 -L\(toolchain)/usr/lib/swift/iphoneos -undefined dynamic_lookup"// -Xlinker -bundle_loader -Xlinker \"\(Bundle.main.executablePath!)\""
```

**Comment by johnno1962** [comment]
I've made the changes you should need available on master: https://github.com/johnno1962/InjectionIII/commit/78e809f1135ca19c1aab9da48f142a1405ae3f32

**Comment by unchartedworks** [comment]
Thank you very much!
I have pulled the latest changes.
I can load the bundle. I get a dlopen error after compiling a Swift file successfully.

```
💉 Loading .dylib ...
💉 *** dlopen() error: dlopen(/var/folders/ty/65cvx7f570g53y5xb0xsbz_80000gn/T/eval101.dylib, 0x0002): file system sandbox blocked open("/var/folders/ty/65cvx7f570g53y5xb0xsbz_80000gn/T/eval101.dylib", O_RDONLY) ***

```
Do you know how to disable sandbox? I haven't found a solution to it.

**Comment by johnno1962** [comment]
Hmmmm. Getting tricky. There may be limitations on where you can dyload from and we need write access to that directory.
You could try the following patch which moves the temporary files including the dylib into the app bundle:
```
diff --git a/InjectionBundle/InjectionClient.mm b/InjectionBundle/InjectionClient.mm
index 05eaae1..5e166ce 100644
--- a/InjectionBundle/InjectionClient.mm
+++ b/InjectionBundle/InjectionClient.mm
@@ -160,12 +160,8 @@ + (void)load {
 
 - (void)runInBackground {
     SwiftEval *builder = [SwiftInjectionEval sharedInstance];
-    NSString *tmpDir = [self readString];
-    BOOL notPlugin = ![@"/tmp" isEqualToString:tmpDir];
-    builder.tmpDir = tmpDir;
 
-    if (notPlugin)
-        [self writeInt:INJECTION_SALT];
+    [self writeInt:INJECTION_SALT];
     [self writeString:INJECTION_KEY];
 
     NSString *frameworksPath = [NSBundle mainBundle].privateFrameworksPath;
@@ -174,6 +170,10 @@ - (void)runInBackground {
     [self writeString:builder.arch];
     [self writeString:[NSBundle mainBundle].executablePath];
 
+    NSString *tmpDir = [self readString];
+    BOOL notPlugin = ![@"/tmp" isEqualToString:tmpDir];
+    builder.tmpDir = tmpDir;
+
     int codesignStatusPipe[2];
     pipe(codesignStatusPipe);
     SimpleSocket *reader = [[SimpleSocket alloc] initSocket:codesignStatusPipe[0]];
diff --git a/InjectionBundle/SwiftEval.swift b/InjectionBundle/SwiftEval.swift
index b431af8..1c2a5ba 100644
--- a/InjectionBundle/SwiftEval.swift
+++ b/InjectionBundle/SwiftEval.swift
@@ -384,7 +384,7 @@ public class SwiftEval: NSObject {
         _ = evalError("💉 Compiling \(sourceFile)")
 
         guard shell(command: """
-                (cd "\(projectDir.escaping("$"))" && \(compileCommand) -o \(tmpfile).o >\(logfile) 2>&1)
+                (cd "\(projectDir.escaping("$"))" && \(compileCommand) -o \"\(tmpfile).o\" >\"\(logfile)\" 2>&1)
                 """) else {
             compileByClass.removeValue(forKey: classNameOrFile)
             throw evalError("Re-compilation failed (see: \(tmpDir)/command.sh)\n\(try! String(contentsOfFile: logfile))")
@@ -415,7 +415,7 @@ public class SwiftEval: NSObject {
         }
 
         guard shell(command: """
-            \(xcodeDev)/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch "\(arch)" -bundle \(osSpecific) -dead_strip -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fprofile-instr-generate \(tmpfile).o -L "\(frameworks)" -F "\(frameworks)" -rpath "\(frameworks)" -o \(tmpfile).dylib >>\(logfile) 2>&1
+            \(xcodeDev)/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch "\(arch)" -bundle \(osSpecific) -dead_strip -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fprofile-instr-generate \"\(tmpfile).o\" -L "\(frameworks)" -F "\(frameworks)" -rpath "\(frameworks)" -o \"\(tmpfile).dylib\" >>\"\(logfile)\" 2>&1
             """) else {
             throw evalError("Link failed, check \(tmpDir)/command.sh\n\(try! String(contentsOfFile: logfile))")
         }
diff --git a/InjectionIII/Info.plist b/InjectionIII/Info.plist
index ab77657..0c4b327 100644
--- a/InjectionIII/Info.plist
+++ b/InjectionIII/Info.plist
@@ -19,7 +19,7 @@
 	<key>CFBundleShortVersionString</key>
 	<string>$(MARKETING_VERSION)</string>
 	<key>CFBundleVersion</key>
-	<string>5532</string>
+	<string>5542</string>
 	<key>LSApplicationCategoryType</key>
 	<string>public.app-category.developer-tools</string>
 	<key>LSMinimumSystemVersion</key>
diff --git a/InjectionIII/InjectionServer.swift b/InjectionIII/InjectionServer.swift
index 7fafc4a..a3080c3 100644
--- a/InjectionIII/InjectionServer.swift
+++ b/InjectionIII/InjectionServer.swift
@@ -41,9 +41,6 @@ public class InjectionServer: SimpleSocket {
     }
 
     @objc override public func runInBackground() {
-        let tmpDir = NSTemporaryDirectory()
-        write(tmpDir)
-
         var candiateProjectFile = appDelegate.selectedProject
 
         if candiateProjectFile == nil {
@@ -65,7 +62,6 @@ public class InjectionServer: SimpleSocket {
         }
 
         builder = SwiftEval()
-        builder.tmpDir = tmpDir
         defer { builder = nil }
 
         // client spcific data for building
@@ -77,6 +73,10 @@ public class InjectionServer: SimpleSocket {
             builder.arch = arch
         } else { return }
 
+        builder.tmpDir = URL(fileURLWithPath: builder.frameworks)
+            .deletingLastPathComponent().path
+        write(builder.tmpDir)
+
         // log errors to client
         builder.evalError = {
             (message: String) in
@@ -220,7 +220,7 @@ public class InjectionServer: SimpleSocket {
                     NSLog("Signing with identity: \(identity!)")
                 }
                 let signedOK = SignerService
-                    .codesignDylib(tmpDir+"/eval"+readString()!,
+                    .codesignDylib(builder.tmpDir+"/eval"+readString()!,
                                    identity: identity)
                 sendCommand(.signed, with: signedOK ? "1": "0")
                 break
```

**Comment by johnno1962** [comment]
Ok, so it's good news and bad news. I was able to get injection running for iOS on M1 mac with the changes in the new  [ios-on-mac](https://github.com/johnno1962/InjectionIII/tree/ios-on-mac) branch of the repo and controlling code sign using a user default as I mentioned (I couldn't see the Injection app to load the bundle as it was a symbolic link to my build area in DerivedData, D'oh.) The bad news is that ["interposing"](http://johnholdsworth.com/dyld_dynamic_interpose.html) does not work in this configuration so you can only inject the old way which is limited to non-final methods of classes and not struct so no SwiftUI injection. So, if possible it may be best sticking to the simulator if you want to use injection.

**Comment by unchartedworks** [comment]
Yes, I use SwiftUI injection, so It's a deal-breaker for now. I will stick to the simulator to be able to use injection. Thanks for everything!

**Comment by johnno1962** [comment]
@unchartedworks I've been able to get this working in the end using https://github.com/facebook/fishhook for arm64. Can you pull the changes on the iOS-on-mac branch an give it a try? Thanks for bringing this up. It prompted a bit of a rethink.

**Comment by johnno1962** [comment]
I've made a new release available from this branch if you want to use that and updated the README with what should be the build phase of your project for iOS on mac. Let me know if you have any problems.

**Comment by unchartedworks** [comment]
I am so sorry for my late reply. 
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/4646838/103138964-c6135200-46d7-11eb-9e22-d99ed269ac36.png">
It seems that there is a missing bundle. I am using the latest master branch.

**Comment by unchartedworks** [comment]
Hello again! I added the missing bundle by modifying the build script.
I have a new issue. I have no way to turn off App Sandbox.
```
💉 *** Could not locate containing project or it's logs.
For a macOS app you need to turn off the App Sandbox.
Have you customised the DerivedData path? ***
```

**Comment by johnno1962** [comment]
Hi, master is now synched to the App Store version which has to have the Sandbox enabled for the InjectionIII app itself. For your use case this needs to be turned off and the line you found in the build_bundles.sh script uncommented. The last binary release in the repo should also work for iOS on M1.

**Comment by unchartedworks** [comment]
I have disabled Sandbox in InjectionIII app and added the script to my project.
```
# Type a script or drag a script file from your workspace to insert its path.
export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
INJECTION_APP_RESOURCES=/Applications/InjectionIII.app/Contents/Resources
/usr/bin/codesign --force --sign $EXPANDED_CODE_SIGN_IDENTITY  $INJECTION_APP_RESOURCES/maciOSInjection.bundle/maciOSInjection
/usr/bin/codesign --force --sign $EXPANDED_CODE_SIGN_IDENTITY  $INJECTION_APP_RESOURCES/maciOSSwiftUISupport.bundle/maciOSSwiftUISupport
/usr/bin/codesign --force --sign $EXPANDED_CODE_SIGN_IDENTITY $INJECTION_APP_RESOURCES/maciOSInjection.bundle/Frameworks/SwiftTrace.framework/SwiftTrace
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" $EXPANDED_CODE_SIGN_IDENTITY

```

 I got a new error. 

```
💉 Loading .dylib ...
💉 *** dlopen() error: dlopen(/Users/liang/Library/Containers/
D0B3F02E-DFEB-4A33-8CB1-69103476A4EE/Data/tmp/eval103.dylib, 0x0002): 
code signature invalid (errno=1) sliceOffset=0x00000000, 
codeBlobOffset=0x00012940, codeBlobSize=0x00004BF0 for 
'/Users/liang/Library/Containers/D0B3F02E-DFEB-4A33-8CB1-69103476A4EE/Data/
tmp/eval103.dylib' ***

```

**Comment by johnno1962** [comment]
Seems like the default to set the code signing identity for the project isn't being picked up by the InjectionIII application. This can happen when you switch between Sandboxed and un-Sandboxed as the app ends up with two defaults .plist files. Use the following command to see the two plist files and you could try deleting them to get back to where you started.
```
find ~/Library -name com.johnholdsworth.InjectionIII.plist
````

**Comment by unchartedworks** [comment]
It works like a charm! Thank you very much indeed!
