### ISSUE TITLE
dlopen() error

### ISSUE THREAD

**Issue by longjun-9** [johnno1962/InjectionIII#285]
*** dlopen() error: dlopen(/var/folders/_3/clmkshc10s74wv83tnd1ds2c0000gp/T/eval102.dylib, 2): Symbol not found: _$s16HelloTalk_Binary12AuthPlatformOMn
  Referenced from: /var/folders/_3/clmkshc10s74wv83tnd1ds2c0000gp/T/eval102.dylib
  Expected in: flat namespace
 in /var/folders/_3/clmkshc10s74wv83tnd1ds2c0000gp/T/eval102.dylib ***

I have added "-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup" to "Other linker Flags", and built the unhide project, and added shell code to "Run Script".

But when I saved changes, it didn't work, with error shown above.

The following is unhide buid log.
"unhide: Missing symtab or dylib cmd float.o: 0x0 & 0x0"

Looking forward to your reply, thank you~

**Comment by johnno1962** [comment]
Hi, without seeing your project its difficult to say what the problem might be here. It doesn't look like something that needs you to use unhide. Experiment with access control, make classes structs public perhaps.

**Comment by longjun-9** [comment]
By comparing the build settings of the demo project and the current project one by one, I finally found that what affects the injection settings is "Enable Testability", which should be set to YES in debug mode.

**Comment by johnno1962** [comment]
Thanks for getting to the bottom of this for me. We’ve not seen this problem before. I’ll leave it open in case it trips someone else up.

**Comment by zuqiu123** [comment]
`Enable Testability ` Where to set up

**Comment by johnno1962** [comment]
Hi it's Build Settings: Enable Testability
