### ISSUE TITLE
Shows "..._loadViewFromNibNamed:bundle:unrecognized selector sent to instance..." when reload xib

### ISSUE THREAD

**Issue by smartrejames** [johnno1962/InjectionIII#288]
Hi there, I'm using xib to build ViewController interface, after save changes and build,  log as:

```
💉 *** Copied ....
_loadViewFromNibNamed:bundle:]: unrecognized selector sent to instance 0x7ffc9be0e750
Problem reloading nib:... _loadViewFromNibNamed:bundle:]: unrecognized selector sent to instance ...
...
```

InjectionIII is 2.2.0 and downloaded from App Store,
Xcode: 12.3
Simulator: iOS 14.3
OS: Catalina 10.15.7

**Comment by johnno1962** [comment]
HI, this is a change in iOS 14 and there is a fix. Can your download one of the newer releases and give it a try: https://github.com/johnno1962/InjectionIII/releases

**Comment by smartrejames** [comment]
@johnno1962 It works on 2.5.0 , thank you very much  👍
