### ISSUE TITLE
Could not locate compile command

### ISSUE THREAD

**Issue by himeshmyk** [johnno1962/InjectionIII#289]
Hello, I know this issue has had multiple reportings, and I've checked all of them but still am not able to get it to work.
For clarification, injection is working with a [sample app](https://drive.google.com/file/d/1Y0Zv3YAA7cB6SLSu2Q95Q01uuVJMQUNA/view?usp=sharing) that I created, but not with other apps that I am working on, like this [PhotoTagger app](https://drive.google.com/file/d/1MDHvYkf9A2RuuRvXYlIDnTUPNzk18bDT/view?usp=sharing); its giving this error when saving file:

```
Could not locate compile command for /Users/xxxxx/Desktop/PhotoTagger/PhotoTagger/ViewController.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator paths are case sensitive.
Try a build clean then rebuild to make logs available.
```

I've checked that I'm using Incremental, not Whole Module, Optimization for both projects, and have tried cleaning and rebuilding multiple times too. Also, project file names seem okay to me too.

I'm on macOS BigSur version 11.1 (20C69), XCode version 12.2 (12B45b), and as the Readme suggested I've installed [version 2.5.0 of the app from github](https://github.com/johnno1962/InjectionIII/releases/tag/2.5.0).

Initially I was thinking that Injection doesnt work with xcworkspace, but after I added a pod to my sample app it was working there too.

**Comment by johnno1962** [comment]
Hi, I think might be because you have the project in your Desktop folder which has special restrictions. People have had problems with this in the past. Can you move the project to your home directory and try again?

**Comment by johnno1962** [comment]
OK, so this is officially a very strange problem. Thanks for the PhotoTracker project, I’ve tried it in the Desktop folder on Mojave, Catalina and Big Sur without any issues so it could be the path to your homee directory and yet you say you have another project working. Not sure what to suggest. Have you tried previous versions of InjectionIII such as 2.4.5?

**Comment by himeshmyk** [comment]
@johnno1962:
1. I've tried, and am facing similar issues, with projects in my home directories too.
2. No, this is the first time I've come across InjectionIII, I'll try once by installing v2.4.5 and by building from source, and let you know of the results.
Just FYI, even for the project working with Injection, I dont get the project directory selection prompt on opening the project, I have to always manually add directory from the Injection icon. Not sure if this helps.

**Comment by johnno1962** [comment]
You must select a project directory which selects the project file, use add directory only if you need to.

**Comment by 372945980** [comment]
Hello! Facing the same problems here.  Also tried to move project to Desktop folder but turned out useless.
Have you figured out some solutions?

**Comment by johnno1962** [comment]
Hi, Have you tried the "GettingStarted.zip" project? Once you have that working, you can work your way up from there. This sort of problem is generally because there is a non-ascii character in your path or something like ()${} characters etc.

**Comment by zuqiu123** [comment]
Where is GettingStarted.zip

**Comment by johnno1962** [comment]
https://johnholdsworth.com/GettingStarted.zip
