### ISSUE TITLE
Loaded .dylib - Ignore any duplicate class warning ^

### ISSUE THREAD

**Issue by howoften** [johnno1962/InjectionIII#290]
2020-12-25 11:57:12.427927+0800 National[4253:130394] <iOSInjection.SwiftEval: 0x6000021708f0>.deinit()
💉 Injection connected 👍
💉 Watching /Users/someone/Desktop/National/**
💉 Compiling /Users/someone/Desktop/National/National/ViewController.m
💉 Loading .dylib ...
objc[4253]: Class ViewController is implemented in both /Users/someone/Library/Developer/CoreSimulator/Devices/F1A39D2C-9EC7-46B3-8E79-15494B4700F0/data/Containers/Bundle/Application/32CAED62-BA01-465C-9E58-B86F26A2FBFC/National.app/National (0x100acc188) and /Users/someone/Library/Developer/CoreSimulator/Devices/F1A39D2C-9EC7-46B3-8E79-15494B4700F0/data/Containers/Data/Application/A715C406-C8F2-4429-B687-22BE2EF75F01/tmp/eval101.dylib (0x10844b120). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ^
💉 Injected 'ViewController'

macOS Big Sur 11.0
xcode 12.2
injectionIII 2.5.0

**Comment by johnno1962** [comment]
Hi, you really can ignore that message. It comes from the system telling you another version of the class has loaded and there is no way I know to remove it.

**Comment by howoften** [comment]
I will not make an issue, if it's just a log.
it doesn't work when i change view's color to red in -[ViewController viewDidLoad], and the running device is iPhone simulator 12 pro max(iOS14.2)

**Comment by johnno1962** [comment]
But did the view reload? Injection only takes effect when viewDidLoad is called.

**Comment by howoften** [comment]
thanks for reply!
after i open the same page  again, it does work.
