### ISSUE TITLE
dlopen() error:  xcode 12.2 beat3

### ISSUE THREAD

**Issue by zuqiu123** [johnno1962/InjectionIII#291]
The injection failed.
```
💉 *** dlopen() error: dlopen(/var/folders/z9/_rmmqs6n121bd4gnbp1swhl40000gp/T/com.johnholdsworth.InjectionIII/eval102.dylib, 2): Symbol not found: _$s7PDFEDit13ZDPDFDocumentC4from8filePath8passwordACSgSS_SSSgtKFZfA0_
  Referenced from: /var/folders/z9/_rmmqs6n121bd4gnbp1swhl40000gp/T/com.johnholdsworth.InjectionIII/eval102.dylib
  Expected in: flat namespace
 in /var/folders/z9/_rmmqs6n121bd4gnbp1swhl40000gp/T/com.johnholdsworth.InjectionIII/eval102.dylib ***
```
i am download and build the unhide project 
`https://github.com/johnno1962/unhide`

`Build phases` add `Run Script`
![image](https://user-images.githubusercontent.com/15611129/103186220-a90a9900-48fa-11eb-9896-e470e54b1b72.png)

`Command + R` Run the project, then add a print(1) to the project and execute 'Command + S'

The error remains

**Comment by johnno1962** [comment]
Have you built the project before injecting? Unfortunately unhide patches the object files after the project is linked so you may have the unpatched version of the object file in your program which will may give this error.

**Comment by zuqiu123** [comment]
After I configure the 'command +R' shortcut to compile and run the program

After the project was running, I added the code 
```swift
print(1)
``` 
in one place to see if the injection was successful,
 I did not add `@objc func injected()` This code is not sure if it is affected by this sentence

**Comment by zuqiu123** [comment]
I used the  official version of xcode and this problem also occurred
```swift
💉 Loading .dylib ...
💉 Loading .dylib has failed, This may be because Swift code being injected refers to a function with a default argument. Consult the section in the README at https://github.com/johnno1962/InjectionIII about using "unhide".
💉 *** dlopen() error: dlopen(/var/folders/z9/_rmmqs6n121bd4gnbp1swhl40000gp/T/com.johnholdsworth.InjectionIII/eval101.dylib, 2): Symbol not found: _$s7PDFEDit13ZDPDFDocumentC4from8filePath8passwordACSgSS_SSSgtKFZfA0_
  Referenced from: /var/folders/z9/_rmmqs6n121bd4gnbp1swhl40000gp/T/com.johnholdsworth.InjectionIII/eval101.dylib
  Expected in: flat namespace
 in /var/folders/z9/_rmmqs6n121bd4gnbp1swhl40000gp/T/com.johnholdsworth.InjectionIII/eval101.dylib ***

```

**Comment by johnno1962** [comment]
An undefined symbol ending in A0_ (or anything ANNN_) means you are trying to inject code with a call to a function with a default argument and need to use unhide (which requires you to have built the project twice before it works when you next inject). The alternative is to specify the default argument in the code you are injecting.

**Comment by zuqiu123** [comment]
sorry ,My English is not very good, I don’t understand too much, I just added these two sentences, and then I saved it and reported an error. You mean I commad+r twice in a row, right?
![image](https://user-images.githubusercontent.com/15611129/103231200-3937f500-4972-11eb-9939-62e1de7306b9.png)

**Comment by johnno1962** [comment]
The problem is we are talking about two problems at the same time.

If you get the undefined symbol you need to use unhide and cmd-R twice or don't use default argument.

If you don't get undefined symbol it is injecting and you should see print(1) coming out as you change it if the code is called. Perhaps you should start with a simpler project to get used to Injection.

**Comment by zuqiu123** [comment]
Hello, I would like to ask where is the latest introduction, the link in this link looks quite old now

https://github.com/johnno1962/injectionforxcode

**Comment by johnno1962** [comment]
The link you give is for a very old version. The project home page is here: https://github.com/johnno1962/InjectionIII (where you have raised this issue.)
