### ISSUE TITLE
Menu bar icon doesn't match other macOS icons

### ISSUE THREAD

**Issue by shpuntov** [johnno1962/InjectionIII#294]
Hi there! It would be nice to have menu bar icon updated:

1. Add @2x version so it looks better on retina displays
1. Add support for macOS Light/Dark modes
1. Add an ability to switch to monochrome version (vs current color one)
1. Make sure that the icon uses color shades similar to the standard macOS icons, so it looks more natively.

<img width="701" alt="menu-bar-icon" src="https://user-images.githubusercontent.com/1327944/106143340-145eb980-618c-11eb-9301-8971acb6ff41.png">

I'm almost sure that 2 and 4 are covered automatically once you setup menu bar icon with the most recent way recommended by Apple. 1 and 3 needs new source for the icon. How about this: 💉 — it's available in high resolution, and could be used as a base for all 4 states.

**Comment by johnno1962** [comment]
That wouldn't be a priority for me personally but I would look at a PR. I'd prefer to use the existing Icon which is available high res as my github avatar.
