### ISSUE TITLE
App closes without error when using @State

### ISSUE THREAD

**Issue by rauldeheer** [johnno1962/InjectionIII#295]
If I make a brand new project with SwiftUI and configure InjectionIII everything works fine, but when I use something simple as:

```swift
@State var amountOfClicks = 0;
```

The app won't startup anymore. If I leave the app open and add the above code the app keeps working. There is no exception thrown the app just closes silently. 

Is this a known issue?

**Comment by rauldeheer** [comment]
I've just asked someone else to test it on his system and it works on his end. Am I doing something wrong?

**Comment by johnno1962** [comment]
Hi, not had a report like this before. Same version of Xcode/InjectionIII as your colleague?

**Comment by johnno1962** [comment]
I think, I know what’s might be happening here. You cannot inject changes to memory layout (new properties etc.) Your app is probably failing to start as this previous injection is being re-applied causing it to crash. Do a build clean and restart your app.

**Comment by rauldeheer** [comment]
Hi thanks for responding this fast first of all.

Cleaning the build folder seemed to have helped out and fixed the problem. My colleague never had this problem but one other colleague messaged me yesterday night telling me the same issue was happening with him.

Thanks and cheers! 👍
