### ISSUE TITLE
Can't recompile

### ISSUE THREAD

**Issue by UOCecalero** [johnno1962/InjectionIII#297]
When I save any changes in SwiftUI (XCode 11) it throws me the following error:

*** 💉 Compiling /Users/esfds/Documents/MyOwnProjects/Scoreboard/ScoreBoard/ScoreBoard/ScoreBoard/Player/List/PlayerList.swift ***
💉 *** Re-compilation failed (see: /var/folders/h2/ms1p92x928711qnttxrj19140000gn/T/com.johnholdsworth.InjectionIII//command.sh)
<unknown>:0: error: error opening input file '/Users/esfds/Documents/MyOwnProjects/Scoreboard/ScoreBoard/ScoreBoard/ScoreBoard/Player/Model/PlayerModel.swift' (Operation not permitted)
 ***

**Comment by johnno1962** [comment]
I'd imagine that is some kind of permission issue. Can you try moving your project out of the 'Documents' folder?
