### ISSUE TITLE
Could not locate compile command for

### ISSUE THREAD

**Issue by NashAnd** [johnno1962/InjectionIII#299]
It sames does not work for directories containing Chinese
such as 
*** Could not locate compile command for /Users/byx/byxmaster/App/MyAccount/Fund(基金)/证件/Controller/MFUpLoadIDCardInfoController.m.

**Comment by johnno1962** [comment]
Hi, The problem is probably the () characters.

**Comment by NashAnd** [comment]
the problem has been solved,thank you
