### ISSUE TITLE
Fatal error: 'try!' expression unexpectedly raised an error

### ISSUE THREAD

**Issue by zhuxiaod** [johnno1962/InjectionIII#300]
### **Hello, since I know your program, I greatly improve the efficiency of my code, I love your program so much. But due to a recent project change, I may have changed some of the configuration.

The first time I was prompted by the Command+ S console:**
💉 Injection connected 👍
💉 ⚠️ Have you remembered to add "-Xlinker -interposable" to your project's "Other Linker Flags"? ⚠️
💉 Watching /Users/mac/Desktop/CompanyProject/student-ios/**
2021-03-01 15:44:07.427428+0800 NewTalkEnglishStudentProject[19713:353118] item:<UITabBarItem: 0x7fd3b322ebd0> title='约课' image=<UIImage:0x600003f7db90 anonymous {22, 22}> selected
💉 *** 💉 Compiling /Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Schedule/ViewController/TESSpokenLanguageTestViewController.m ***
/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/command.sh: line 1: syntax error near unexpected token `('
/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/command.sh: line 1: `(cd "/Users/mac/Desktop/CompanyProject/student-ios" &&     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios9.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/mac/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/mac/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wquoted-include-in-framework-header -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Index/DataStore -iquote /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-generated-files.hmap -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-own-target-headers.hmap -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-all-target-headers.hmap -iquote /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-project-headers.hmap -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Products/Debug-iphonesimulator/include -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/AFNetworking -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/BRPickerView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FBRetainCycleDetector -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FDFullscreenPopGesture -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FLAnimatedImage -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FSCalendar -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/IQKeyboardManager -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/JPush -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/JXCategoryView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/JXPagingView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/LYEmptyView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/MJExtension -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/MJRefresh -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/MLeaksFinder -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/Masonry -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/QBImagePickerController -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SDCycleScrollView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SDWebImage -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SGPagingView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SVProgressHUD -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/TABAnimated -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/TZImagePickerController -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/Toast -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/YYKit -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/YYStarView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC.framework/Headers -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/DerivedSources-normal/x86_64 -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/DerivedSources/x86_64 -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/DerivedSources -F/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Products/Debug-iphonesimulator -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/AgoraRtcEngine_iOS -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/BRTC -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/BaijiaYun/frameworks -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/Bugly -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/CL_ShanYanSDK/framework -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/UMCCommonLog/UMCommonLog -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/UMCommon/UMCommon_7.2.5 -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/UMDevice/UMDevice_1.1.0 -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/Vloud -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/YYKit/Vendor -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib/TencentOpenApi(Lite)_3 -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib/TencentOpenApi -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/TencentOpenApi(Lite)_3 -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib/xdy -include /Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/NewTalkEnglishStudentProject.pch -MMD -MT dependencies -MF /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/Objects-normal/x86_64/TESSpokenLanguageTestViewController.d --serialize-diagnostics /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/Objects-normal/x86_64/TESSpokenLanguageTestViewController.dia -c /Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Schedule/ViewController/TESSpokenLanguageTestViewController.m  -o "/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/eval101.o" >"/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/eval101.log" 2>&1)'
💉 *** Re-compilation failed (see: /var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/command.sh
/Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.m:16:17: warning: method definition for 'getTeacherChatUrlWithId:name:' not found [-Wincomplete-implementation]
@implementation ETPWebViewController
                ^
In file included from /Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.m:1:
In file included from /Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/EnglishTeacherPlatform.pch:24:
/Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.h:46:1: note: method 'getTeacherChatUrlWithId:name:' declared here
+(NSString *)getTeacherChatUrlWithId:(NSString *)teacherId name:(NSString *)teacherName;
^
/Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.m:16:17: warning: method definition for 'getMsgCenterUrl' not found [-Wincomplete-implementation]
@implementation ETPWebViewController
                ^
In file included from /Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.m:1:
In file included from /Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/EnglishTeacherPlatform.pch:24:
/Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.h:49:1: note: method 'getMsgCenterUrl' declared here
+(NSString *)getMsgCenterUrl;
^
/Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.m:16:17: warning: method definition for 'getCSUrl' not found [-Wincomplete-implementation]
@implementation ETPWebViewController
                ^
In file included from /Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.m:1:
In file included from /Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/EnglishTeacherPlatform.pch:24:
/Users/mac/Desktop/CompanyProject/EnglishTeacherPlatform/EnglishTeacherPlatform/Class/Profile/ViewController/ETPWebViewController.h:52:1: note: method 'getCSUrl' declared here
+(NSString *)getCSUrl;
^
3 warnings generated.
ld: warning: directory not found for option '-L/Users/mac/Library/Developer/CoreSimulator/Devices/E3A71977-648B-4F25-9F8E-B90B30A8DD41/data/Containers/Bundle/Application/99B04812-2D0F-417A-9E81-8C0AE9899BF8/Talk915Teacher.app/Frameworks'
ld: warning: directory not found for option '-F/Users/mac/Library/Developer/CoreSimulator/Devices/E3A71977-648B-4F25-9F8E-B90B30A8DD41/data/Containers/Bundle/Application/99B04812-2D0F-417A-9E81-8C0AE9899BF8/Talk915Teacher.app/Frameworks'
ld: warning: -undefined dynamic_lookup is deprecated on iOS Simulator
 ***

**### My App didn't compile any changes, so I pressed it again：**
💉 *** 💉 Compiling /Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Schedule/ViewController/TESSpokenLanguageTestViewController.m ***
/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/command.sh: line 1: syntax error near unexpected token `('
/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/command.sh: line 1: `(cd "/Users/mac/Desktop/CompanyProject/student-ios" &&     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios9.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/mac/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/mac/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wquoted-include-in-framework-header -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Index/DataStore -iquote /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-generated-files.hmap -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-own-target-headers.hmap -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-all-target-headers.hmap -iquote /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/NewTalkEnglishStudentProject-project-headers.hmap -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Products/Debug-iphonesimulator/include -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/AFNetworking -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/BRPickerView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FBRetainCycleDetector -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FDFullscreenPopGesture -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FLAnimatedImage -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/FSCalendar -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/IQKeyboardManager -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/JPush -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/JXCategoryView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/JXPagingView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/LYEmptyView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/MJExtension -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/MJRefresh -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/MLeaksFinder -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/Masonry -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/QBImagePickerController -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SDCycleScrollView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SDWebImage -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SGPagingView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/SVProgressHUD -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/TABAnimated -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/TZImagePickerController -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/Toast -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/YYKit -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/Headers/Public/YYStarView -I/Users/mac/Desktop/CompanyProject/student-ios/Pods/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC.framework/Headers -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/DerivedSources-normal/x86_64 -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/DerivedSources/x86_64 -I/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/DerivedSources -F/Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Products/Debug-iphonesimulator -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/AgoraRtcEngine_iOS -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/BRTC -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/BaijiaYun/frameworks -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/Bugly -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/CL_ShanYanSDK/framework -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/UMCCommonLog/UMCommonLog -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/UMCommon/UMCommon_7.2.5 -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/UMDevice/UMDevice_1.1.0 -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/Vloud -F/Users/mac/Desktop/CompanyProject/student-ios/Pods/YYKit/Vendor -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib/TencentOpenApi(Lite)_3 -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib/TencentOpenApi -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/TencentOpenApi(Lite)_3 -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib -F/Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Other/ThirdLib/xdy -include /Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/NewTalkEnglishStudentProject.pch -MMD -MT dependencies -MF /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/Objects-normal/x86_64/TESSpokenLanguageTestViewController.d --serialize-diagnostics /Users/mac/Library/Developer/Xcode/DerivedData/NewTalkEnglishStudentProject-ewelrzxquarvvpdzdqibmjadepwu/Build/Intermediates.noindex/NewTalkEnglishStudentProject.build/Debug-iphonesimulator/NewTalkEnglishStudentProject.build/Objects-normal/x86_64/TESSpokenLanguageTestViewController.dia -c /Users/mac/Desktop/CompanyProject/student-ios/NewTalkEnglishStudentProject/Classes/Schedule/ViewController/TESSpokenLanguageTestViewController.m  -o "/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/eval102.o" >"/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/eval102.log" 2>&1)'
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "未能打开文件“eval102.log”，因为它不存在。" UserInfo={NSFilePath=/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/eval102.log, NSUnderlyingError=0x6000003bf2a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file iOSInjection/SwiftEval.swift, line 394
2021-03-01 15:48:47.362576+0800 NewTalkEnglishStudentProject[19713:353118] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "未能打开文件“eval102.log”，因为它不存在。" UserInfo={NSFilePath=/var/folders/hy/xwhmvj6x2319s069jgw7d5ph0000gn/T/com.johnholdsworth.InjectionIII/eval102.log, NSUnderlyingError=0x6000003bf2a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file iOSInjection/SwiftEval.swift, line 394

I tried to change a project to run and it was normal. But this project doesn't work properly. I know what might be causing the conflict, but I just can't figure it out. If possible, I hope you can help me.

**Comment by johnno1962** [comment]
Hi, this is probably because you are using the Desktop folder which has special permissions. Can you move the project to another directory?

**Comment by zhuxiaod** [comment]
Thanks for your reply, I transfer the project path, or the same mistake, I noticed a point, eval101 failed to open the file. The log, as a beginner, I would like to know what this file is not created, my other project is to generate the log file, and I may not be very good English, can communicate with you very happy.

**Comment by johnno1962** [comment]
Can you try it without the () in the project path? That may be the problem.

**Comment by zhuxiaod** [comment]
This is crazy. I reload the framework path and show that the compilation was successful, so I can see my work again without having to compile. I'm curious, how do you locate where, which makes me think it's incredible. Thank you for helping me, Hope everything goes your way!

**Comment by johnno1962** [comment]
It's always the () that causes problems! I've already removed the try! from the code base so this shouldn't happen in a future version of InjectionIII. Thanks for taking the time to raise an issue.
