### ISSUE TITLE
dlopen() error:   Loading .dylib has failed, This may be because Swift code being injected refers to a function with a default argument

### ISSUE THREAD

**Issue by KBvsMJ** [johnno1962/InjectionIII#303]
I operate like this：

<img width="947" alt="1" src="https://user-images.githubusercontent.com/8489350/110907313-2bc2c200-8348-11eb-9f3a-405eb9b77f3b.png">

But the result is output like this

![image](https://user-images.githubusercontent.com/8489350/110906954-af2fe380-8347-11eb-8b70-478c8980123a.png)

**Comment by johnno1962** [comment]
Hi, Try building and running the program again (without doing a clean) and it should work. This is because default arguments needs to be patched by unhide. They only work the second time a project is built.

**Comment by KBvsMJ** [comment]
@johnno1962  I tried several times without success，Can you provide a demo reference setting！

**Comment by johnno1962** [comment]
This is definitely a default argument problem (see the A0_ at the end). Have included the unhide script in the target that contains the function with the default argument?

**Comment by KBvsMJ** [comment]
@johnno1962 sorry!  What does it mean ？ (see the A0_ at the end)

**Comment by johnno1962** [comment]
At the end of the missing symbol name, but never mind.. Any chance you'd like to switch to the new version of injection https://github.com/johnno1962/HotReloading which has "unhide" integrated internally. You add this repo as a "Swift Package", remove the bundle loading code in your AppDelegate.swift and replace the Unhide build phase with:
```
if [ -d $SYMROOT/../../SourcePackages ]; then
    $SYMROOT/../../SourcePackages/checkouts/HotReloading/start_daemon.sh
elif [ -d "$SYMROOT"/../../../../../SourcePackages ]; then
    "$SYMROOT"/../../../../../SourcePackages/checkouts/HotReloading/fix_previews.sh
fi
```

**Comment by KBvsMJ** [comment]
@johnno1962 This is my demo, can you please troubleshoot it? Why can't it be used normally.
[SwiftInjectionlllDemo.zip](https://github.com/johnno1962/InjectionIII/files/6140031/SwiftInjectionlllDemo.zip)

**Comment by johnno1962** [comment]
Thanks for the example. I've tried it and can inject all classes fine. Which file are you trying to inject that gives the problem?

**Comment by KBvsMJ** [comment]
@johnno1962  tks! Later, I re-downloadedand [ injectionlll ](https://github.com/johnno1962/InjectionIII/releases/download/2.6.1/InjectionIII.app.zip) it can be used normally!

**Comment by johnno1962** [comment]
Which version where you using? The app store one?

**Comment by KBvsMJ** [comment]
> Which version were you using? The app store one?

Yes, downloaded from appstore

**Comment by jinliyuelong** [comment]
i have the same  problem，how can i sovle it

**Comment by johnno1962** [comment]
Hi, can you tell me the exact error message please. This issue with default arguments is much rarer since Xcode 13.
