### ISSUE TITLE
 error: failed to import bridging header

### ISSUE THREAD

**Issue by KBvsMJ** [johnno1962/InjectionIII#304]
Dynamic modification of view-related attributes cannot achieve corresponding effects. However, recompilation indicates that the bridge file cannot be passed normally.

![image](https://user-images.githubusercontent.com/8489350/111244271-86586880-863d-11eb-892a-241468427e43.png)

**Comment by johnno1962** [comment]
You may need to modify your project's "Header Search Path".

**Comment by KBvsMJ** [comment]
> You may need to modify your project's "Header Search Path".
However, it is normal before dynamic modification

**Comment by johnno1962** [comment]
When your code is recompiled. It may not be in the same working directory so you may need to specify $SRCDIR/something.

**Comment by Jason8Zhang** [comment]
<img width="1143" alt="截屏2021-03-16 下午6 16 39" src="https://user-images.githubusercontent.com/10389173/111294014-da3a7000-8684-11eb-8ed8-ebd090507c33.png">
<img width="747" alt="企业微信截图_180fd18d-a740-4645-8637-10763d1dc33f" src="https://user-images.githubusercontent.com/10389173/111294027-ddcdf700-8684-11eb-9476-f65c90afa97d.png">
It seems not ok😅

**Comment by Jason8Zhang** [comment]
<img width="1143" alt="截屏2021-03-16 下午6 16 39" src="https://user-images.githubusercontent.com/10389173/111294269-1a015780-8685-11eb-8fb6-d6db858c3e34.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/10389173/111294252-153ca380-8685-11eb-8cd0-dc178ec8c881.png">

It seems not work😅

**Comment by johnno1962** [comment]
No, you don't change the bridging header path but change the "Header Search Path" to include where the missing file is.

**Comment by KBvsMJ** [comment]
@Jason8Zhang  Your problem is solved?

**Comment by johnno1962** [comment]
The problem is not the path to the bridging header but the path to the <RMLocationKit/RMLocationComponent.h> it imports.

**Comment by KBvsMJ** [comment]
> Header Search Path

These libraries are managed with cocoapods

**Comment by johnno1962** [comment]
Aha, you need to modify your "Header Search Path" build property to include something like "$(SRCROOT)/Pods/RMLocation" if it is not already there in the target you are trying to inject.

**Comment by KBvsMJ** [comment]
> Aha, you need to modify your "Header Search Path" build property to include something like "$(SRCROOT)/Pods/RMLocation" if it is not already there in the target you are trying to inject.

Refer to your suggested settings, but still failed
![image](https://user-images.githubusercontent.com/8489350/111464399-b138de80-875b-11eb-9c03-de3beab90afe.png)
![image](https://user-images.githubusercontent.com/8489350/111464519-d2013400-875b-11eb-8a67-22d5eb9e0d7e.png)

**Comment by johnno1962** [comment]
I could TeamView if you like. Please send contact details though to github @ johnholdsworth.com if you're interested.

**Comment by KBvsMJ** [comment]
> I could TeamView if you like. Please send contact details though to github @ johnholdsworth.com if you're interested.

Sorry, this is a company commercial project and cannot be disclosed. Can you provide a case demo? I can refer to your demo to operate.

**Comment by KBvsMJ** [comment]
@Jason8Zhang   The problem you encountered has been solved? Is there a solution?

**Comment by Jason8Zhang** [comment]
> @Jason8Zhang The problem you encountered has been solved? Is there a solution?

Not yet!

**Comment by KBvsMJ** [comment]
@johnno1962  Does this plug-in only support pure oc projects, and does not support mixed oc and swift projects?

**Comment by johnno1962** [comment]
@KBvsMJ, If you want to use injection for Objective-C on a project that uses Cocoapods, you need to invest some time extending the "Header Search Path" to include headers you bridging header is trying to include. This is a reasonably straightforward thing to fix but once you are setup you shouldn't have any problem. Try looking at and running the script file it mentions to see what the problem is. Without access to your project there isn't much more I can do. Good Luck!

**Comment by KBvsMJ** [comment]
@johnno1962 Do you mean to set the Header Search Path here to set the path of the bridge file?

**Comment by johnno1962** [comment]
No, the files it includes.

**Comment by KBvsMJ** [comment]
@johnno1962   I found that injectionlll is not very good for mixed **oc** and **swift** projects. So far, I have found that injection can be used normally in **pure oc** or **pure swift** projects.

**Comment by johnno1962** [comment]
Certainly Swift + OC + CocoaPods is a complicated combination but I'm sure it's possible once you've spend some time sorting out the "Header Search Path"

**Comment by advancc** [comment]
I'm having the same problem, it seems that injection is not parsing the <> headers correctly.

**Comment by johnno1962** [comment]
I'd like see what the problem is here. Can you TeamView? If you're interested send details to github at johnholdsworth.com.

**Comment by johnno1962** [comment]
Please see the comment https://github.com/johnno1962/HotReloading/issues/11#issuecomment-817757302, perhaps you should try one of the injection releases from here: https://github.com/johnno1962/InjectionIII/releases/tag/2.6.6
