### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by 372945980** [johnno1962/InjectionIII#306]
I cloned the project and build the app, then setting with the instruction but without adding "-Xlinker -interposable".

Injection seems success but error occurred as following:
`InjectionIII connected.`
`Re-compilation failed (see: /var/folders/l0/qcgnw5v10fv6cd47_lvf21jc0000gp/T/com.johnholdsworth.InjectionIII/command.sh)`

`/Users/liaohuanyu/Library/Developer/Xcode/DerivedData/xxx-hgsjqhaxbqkqvyankzfohnhsqgoz/Build/Products/Debug-iphonesimulator/xxx.framework/Headers/xxxSDK.h:88:9: fatal` `error: 'xxxSDk/xxx.h' file not found.`

Please help me solve it, thanks!

**Comment by johnno1962** [comment]
Hi, you need to look at your "Header Search Paths". Ass something like "$(SRCROOT)/<YourFramework>". Injection doesn't know the directory your framework was compiled in.
