### ISSUE TITLE
Your project file seems to be in the Desktop or Documents folder and may prevent InjectionIII working as it has special permissions.

### ISSUE THREAD

**Issue by aiewing** [johnno1962/InjectionIII#309]
Your project file seems to be in the Desktop or Documents folder and may prevent InjectionIII working as it has special permissions.

**Comment by johnno1962** [comment]
Hi, are you using a project in your Desktop folder. If so it may not work correctly. Move it to another folder if possible.

**Comment by cdoky** [comment]
```shell
💉 Watching files under /Users/cc/Documents/WorkSpace
💉 💉 ⚠️ Your project file seems to be in the Desktop or Documents folder and may prevent InjectionIII working as it has special permissions.
```

What permissions are required? How do I authorize?

**Comment by johnno1962** [comment]
Hi,, I'm afraid I don't know the answer to that question. It sometimes seems to work and sometimes not. Is it possible to move your project to say ~/Developer?
