### ISSUE TITLE
Can you provide the source code of SimpleSocket?

### ISSUE THREAD

**Issue by KBvsMJ** [johnno1962/InjectionIII#310]
Can you provide the source code of **SimpleSocket**?  I didn't find it in your open source project

**Comment by johnno1962** [comment]
Sure, its here: https://github.com/johnno1962/HotReloading/blob/main/Sources/HotReloadingGuts/SimpleSocket.mm

**Comment by KBvsMJ** [comment]
> Sure, its here: https://github.com/johnno1962/HotReloading/blob/main/Sources/HotReloadingGuts/SimpleSocket.mm

thank you very much! It turned out to be another branch library source code
