### ISSUE TITLE
It shows no change

### ISSUE THREAD

**Issue by almoradev** [johnno1962/InjectionIII#311]
With Xcode 12.4 and in the simulator it shows me that injection has been executed but does not show me any change:

💉 *** Compiling /multipledirectory/ViewController.swift ***
💉 Loading .dylib ...
objc[64656]: Class _TtC15project21ViewController is implemented in both /Users/askhdflak/Library/Developer/CoreSimulator/Devices/BB3FD1DE-818A-4595-ADD4-F7F1780B3D5D/data/Containers/Bundle/Application/7AB15218-0571-46F7-86A3-A376B6E3A8F0/akjdslhf Pre-Debug.app/lkjadshfa Pre-Debug (0x108104148) and /var/folders/tf/9d08kz8d4rj7p_vnx0zh1fzc0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib (0x10f1e1a20). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ^
💉 Injected class 'Balkjdhfl.ViewController'

The icon of injectionIII is in red, when save it converted in green and after in red again

What am I doing wrong so that the change is not show?

p.d.: I have edited the project names

**Comment by johnno1962** [comment]
By read do you mean orange? That is the normal colour of the icon. Are you re-presenting the View Controller? Do you have an @objc injected() method that call viewDidLoad or configureView? Injecting changes the code but it needs to be called.

**Comment by almoradev** [comment]
This is the problem. Fix it. Thanks a lot for your quick response.
