### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Patrik-svobodik** [johnno1962/InjectionIII#317]
Hey! I'm trying to use InjectionIII/HotReload in my app. It loads just fine but I get a connection error. 
`2021-05-05 12:00:48.996009+0200 Tabataa[8953:2122796] Could not connect: Connection refused
🔥 ⚠️ HotReloading loaded but could not connect. Is injectiond running? ⚠️
🔥 Have you added the following "Run Script" build phase to your project to start injectiond?
if [ -d $SYMROOT/../../SourcePackages ]; then
    $SYMROOT/../../SourcePackages/checkouts/HotReloading/start_daemon.sh
elif [ -d "$SYMROOT"/../../../../../SourcePackages ]; then
    "$SYMROOT"/../../../../../SourcePackages/checkouts/HotReloading/fix_previews.sh
fi
2021-05-05 12:01:36.230675+0200 Tabataa[8953:2122394] dnssd_clientstub read_all(11) DEFUNCT
2021-05-05 12:04:52.126077+0200 Tabataa[8953:2122394] dnssd_clientstub read_all(11) DEFUNCT
`

Also happens with the provided SwiftUI example. Xcode 12.5 (freshly downloaded), macOS 14.4 beta, iOS 14.6 beta

**Comment by johnno1962** [comment]
Have you added the "Run Script" build phase to your project? HotReloading needs a daemon to connect to,

**Comment by Patrik-svobodik** [comment]
Yes, I did (and the example project already had it there but I replaced it with the one from the README because the paths were incorrect)

I see the menubar icon and it says the server is running (or at least it has the tick there and I tried to click start server)

**Comment by Patrik-svobodik** [comment]
Weirdly enough it seems to work in the simulator after a clean build, I'll try on a real device again

**Comment by johnno1962** [comment]
Are you trying to run it on a real device? HotReloading only works in the simulator.

**Comment by Patrik-svobodik** [comment]
Oh, I didn't know that, I didn't see it mentioned anywhere so I assumed it should just work, don't have much experience with swizzling/swapping implementations. Closing this issue, thank you for your time!

**Comment by johnno1962** [comment]
It's mentioned in the first sentence of the README.

**Comment by Patrik-svobodik** [comment]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/25883885/117128907-4fc9df00-ad9e-11eb-983b-d8914724e6df.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/25883885/117129002-6c661700-ad9e-11eb-9045-9f1996cc6105.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/25883885/117129057-81db4100-ad9e-11eb-9da5-3ea3909c6822.png">

I don't see it anywhere but I may have just misread. Please correct me if I'm wrong

**Comment by Patrik-svobodik** [comment]
Wait I see it now, I'm really sorry for wasting your time

**Comment by johnno1962** [comment]
Never mind. It's a common question. It used to work for real devices but the sandbox on iOS 10 put paid to that. I'll update the README for HotReloading.
