### ISSUE TITLE
Build Fails After Adding -Xlinker -interposable

### ISSUE THREAD

**Issue by VidaHasan** [johnno1962/InjectionIII#319]
When adding xlinker interposable, the build fails for my project. 
Here's my setup

![Screen Shot 2021-05-05 at 11 53 18 AM](https://user-images.githubusercontent.com/18647135/117179187-7dac2500-ad98-11eb-90a5-b45f1c741a32.png)

Build Errors:
![Screen Shot 2021-05-05 at 11 51 50 AM](https://user-images.githubusercontent.com/18647135/117179317-9e747a80-ad98-11eb-8841-0e95d683d042.png)

I doubt this is an issue specific to injection, but thought maybe there is some value in adding discussion on this issue and possible workarounds. 

The errors are 'Undefined symbol: _OBJC_CLASS_$_$GMSPlacesClient whichis likely from Google places framework. 

docs here: https://developers.google.com/maps/documentation/places/ios-sdk/overview

System info: 
xcode 12.4
MacOS Big Sur (11.3)
Injection app downloaded via mac app link in repo (not app store)

**Comment by johnno1962** [comment]
Try adding -Xlinker -undefined -Xlinker dynamic_lookup as well.

**Comment by VidaHasan** [comment]
Hey @johnno1962 , thank you for the quick reply. 

I ended up getting it working after adding that flag & adding the app to my applications directory. 

great stuff, thanks for the help!
