### ISSUE TITLE
PCH was compiled with module cache path……

### ISSUE THREAD

**Issue by 5kccp** [johnno1962/InjectionIII#320]
Hi, InjectionIII is great job, it saves me a lot of time, recently i found an issue. I have a workspace with multiple projects, when i alter a file which in one of projects that turn on precompile prefix header it will occurs error below，looking forward to your reply.
![image](https://user-images.githubusercontent.com/2157448/119139146-42d30e00-ba75-11eb-8d12-767e0143e599.png)

![image](https://user-images.githubusercontent.com/2157448/119137403-5aa99280-ba73-11eb-99bc-cd27675d5d02.png)

**Comment by johnno1962** [comment]
Hi & thanks! I wonder if this might be to do with the directory of the project being "Yoga" in the Xcode project but "yoga" on the file system. Can you try renaming the folder?

**Comment by 5kccp** [comment]
> Hi & thanks! I wonder if this might be to do with the directory of the project being "Yoga" in the Xcode project but "yoga" on the file system. Can you try renaming the folder?

Yes， it does was another problem. I have rename it and it helps and then the pch file problem comes.It works fine when turn off.May yoga does has some problem ,I will test it later, thank you.

**Comment by HighmoreJx** [comment]
the same problem.
