### ISSUE TITLE
SwiftUI the project did not inject success

### ISSUE THREAD

**Issue by zuqiu123** [johnno1962/InjectionIII#328]
I did the following
1.i open the injectIII and Selected a project project
![image](https://user-images.githubusercontent.com/15611129/122156988-a72e9500-ce9c-11eb-9d55-37316ca585cc.png)
![image](https://user-images.githubusercontent.com/15611129/122157052-c3323680-ce9c-11eb-81bd-b2b6c646d512.png)
2. Creates a file with the following code
```swift
import SwiftUI

#if DEBUG
private var loadInjection: () = {
    #if os(macOS)
    let bundleName = "macOSInjection.bundle"
    #elseif os(tvOS)
    let bundleName = "tvOSInjection.bundle"
    #elseif targetEnvironment(simulator)
    let bundleName = "iOSInjection.bundle"
    #else
    let bundleName = "maciOSInjection.bundle"
    #endif
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/"+bundleName)!.load()
}()

import Combine

public let injectionObserver = InjectionObserver()

public class InjectionObserver: ObservableObject {
    @Published var injectionNumber = 0
    var cancellable: AnyCancellable? = nil
    let publisher = PassthroughSubject<Void, Never>()
    init() {
        cancellable = NotificationCenter.default.publisher(for:
            Notification.Name("INJECTION_BUNDLE_NOTIFICATION"))
            .sink { [weak self] change in
            self?.injectionNumber += 1
            self?.publisher.send()
        }
    }
}

extension View {
    public func ijeraseToAnyView() -> some View {
        _ = loadInjection
        return AnyView(self)
    }
    public func onInjection(bumpState: @escaping () -> ()) -> some View {
        return self
            .onReceive(injectionObserver.publisher, perform: bumpState)
            .ijeraseToAnyView()
    }
}
#else
extension View {
    public func eraseToAnyView() -> some View { return self }
    public func onInjection(bumpState: @escaping () -> ()) -> some View {
        return self
    }
}
```
3. Add identifier `-Xlinker -interposable` or `-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup` both doesn't work

![image](https://user-images.githubusercontent.com/15611129/122157188-fe346a00-ce9c-11eb-83fd-873a3637541a.png)
4. Start the program and find that the app does not show successful connect1
![image](https://user-images.githubusercontent.com/15611129/122157315-39369d80-ce9d-11eb-8873-4cb51ede02f9.png)
![image](https://user-images.githubusercontent.com/15611129/122157365-4a7faa00-ce9d-11eb-8b2d-2286ded82c18.png)

please help me

**Comment by johnno1962** [comment]
Hi, Is this in the simulator? InjectionII can not work on a real device.

**Comment by zuqiu123** [comment]
Hi, my most respected idol, I forgot to reply to you. I will fix it later, but I forgot the details. I used the simulator, I verified your framework again, it is normal and usable, very impressive ~ Thank you
