### ISSUE TITLE
"Prepare Project" pastes an `eraseToAnyView()` method without `_ = loadInjection`

### ISSUE THREAD

**Issue by Orgmir** [johnno1962/InjectionIII#329]
I am on Big Sur 11.4, using XCode Version 12.5 (12E262). I have just installed version 2.8.3 and used "Prepare Project" to set up a SwiftUI project for injection.

All good, but injection wasn't actually injecting working when I saved a file. I managed to trace the issue to the code pasted onto the App.swift file, its missing a `_ = loadInjection`:

```swift
extension SwiftUI.View {
    public func eraseToAnyView() -> some SwiftUI.View {
        return AnyView(self)
    }
....
}
```
After I've added the `_ = loadInjection` so it matches whats on the README, it all works fine.

The code in the main branch [seems to be ok](https://github.com/johnno1962/InjectionIII/blob/fa950ae81c0db3804743328217e7718175a84c66/InjectionIII/Experimental.swift#L358), so not sure how this could be happening...

Was this fixed in a previous commit and is pending an update? Is the pasting action removing that line because it thinks it does nothing?

If I can help in anyway to figure this out, let me know! Working with SwiftUI is so much easier this way ;)

**Comment by johnno1962** [comment]
Hi, you did well to track this down. I removed the automatic load of injectionIII a few months ago when I was creating the [HotReloading](https://github.com/johnno1962/HotReloading) version of InjectionIII but I've re-instated it now. The code you found was a red herring from the original project that should have been deleted in the move but I've deleted it now.
