### ISSUE TITLE
dlopen() error

### ISSUE THREAD

**Issue by DouDouYup** [johnno1962/InjectionIII#330]
I have tried every solution mentioned in related Issues. it's still not working.

`dlopen() error: dlopen(/Users/z/Library/Developer/CoreSimulator/Devices/32702559-118E-4CBF-9E0E-73A55D795EB7/data/Containers/Data/Application/2516A9FD-6DCB-42B4-AE4D-441FDC07374A/tmp/eval101.dylib, 2): Symbol not found: _$s10MosProject10RPAManagerC12backToRootVCyyFZ
  Referenced from: /Users/z/Library/Developer/CoreSimulator/Devices/32702559-118E-4CBF-9E0E-73A55D795EB7/data/Containers/Data/Application/2516A9FD-6DCB-42B4-AE4D-441FDC07374A/tmp/eval101.dylib
  Expected in: flat namespace`

**Comment by johnno1962** [comment]
Hi, can you try the following in terminal:
```
nm /Users/z/Library/Developer/CoreSimulator/Devices/32702559-118E-4CBF-9E0E-73A55D795EB7/data/Containers/Data/Application/2516A9FD-6DCB-42B4-AE4D-441FDC07374A/tmp/eval101.dylib | grep s10MosProject10RPAManagerC12backToRootVCyyFZ
```

**Comment by DouDouYup** [comment]
> Hi, can you tell me the output go the following in terminal:
> 
> ```
> nm /Users/z/Library/Developer/CoreSimulator/Devices/32702559-118E-4CBF-9E0E-73A55D795EB7/data/Containers/Data/Application/2516A9FD-6DCB-42B4-AE4D-441FDC07374A/tmp/eval101.dylib | grep s10MosProject10RPAManagerC12backToRootVCyyFZ
> ```

thanks for your replay, output as follows:
`U _$s10MosProject10RPAManagerC12backToRootVCyyFZ`

**Comment by johnno1962** [comment]
Sorry, my bad there, can you do the same for your app binary where the symbol should be defined?
```
nm /path/to/app/binary.app/binary | grep s10MosProject10RPAManagerC12backToRootVCyyFZ
```

**Comment by DouDouYup** [comment]
> Sorry, my bad there, can you do the same for your app binary where the symbol should be defined?
> 
> ```
> nm /path/to/app/binary.app/binary | grep s10MosProject10RPAManagerC12backToRootVCyyFZ
> ```

`0000000101d49400 t _$s10MosProject10RPAManagerC12backToRootVCyyFZ`

**Comment by johnno1962** [comment]
Thanks, this is  "hidden" symbol as it is lower cased. I've added tis to to the list of symbols types to "unhide". Are you able to build yourself a new version of InjectionIII and copy/symlink it into /Applications?
```
git clone https://github.com/johnno1962/InjectionIII --recurse-submodules -b new-hidden
```

**Comment by DouDouYup** [comment]
> Thanks, this is "hidden" symbol as it is lower cased. I've added tis to to the list of symbols types to "unhide". Are you able to build yourself a new version of InjectionIII and copy/symlink it into /Applications?
> 
> ```
> git clone https://github.com/johnno1962/InjectionIII --recurse-submodules -b new-hidden
> ```

1. I have successfully built this version. 
2. Export a copy of the archived app.
3. Copy InjectionIII.app into /Applications. 
4. It's still not working  and the same error occurred.

I'm sorry. Am I missing something important?

**Comment by johnno1962** [comment]
ok, you may need to build/run your app again to have the unhide take effect. Have you tried a second time. This is because unhide patches the object files.

**Comment by DouDouYup** [comment]
> looks ok, you may just need to build/run your app again to have the unhide take effect. Have you tried a second time? This is because unhide patches the object files which need to be relinkedI've tried it many times. 

> looks ok, you may just need to build/run your app again to have the unhide take effect. Have you tried a second time? This is because unhide patches the object files which need to be relinked.

I've tried many times.

**Comment by johnno1962** [comment]
Strange, that should have done the trick. Would I be able to TeamView to see what the problem is?

**Comment by DouDouYup** [comment]
> Strange, that should have done the trick. Would I be able to TeamView to see what the problem is?



> Strange, that should have done the trick. Would I be able to TeamView to see what the problem is?

Sorry. Teamview is not allowed for this commercial project, thank u for your patience.  If I find a solution, I will keep Posting.

**Comment by johnno1962** [comment]
Thanks, I'll see if I can replicate and resolve it this end. Which version of Xcode is this?

**Comment by DouDouYup** [comment]
> Thanks, I'll see if I can replicate and resolve it this end. Which version of Xcode is this?



> Thanks, I'll see if I can replicate and resolve it this end. Which version of Xcode is this?

Mixed Objective-C and swift  project that uses Cocopods.  
Xcode Version 12.4 (12D4e). 
MacOS Catalina 10.15.7.
Thanks.

**Comment by johnno1962** [comment]
I've been unable to replicate this problem this end. Can you share the signature of the function RPAManager.backToRootVC() ? In the end, I've released a new version of InjectionIII with what I thought would be the fix https://github.com/johnno1962/InjectionIII/releases/tag/2.8.5. Perhaps you could give that a try?

**Comment by Xchn** [comment]
i meet the same problem...

**Comment by Xchn** [comment]
i meet the same problem... 
my project has many sub module. it can not work. is that the reason?

**Comment by johnno1962** [comment]
Does the symbol name it mentions after "not found" end in "FZ"?

**Comment by Xchn** [comment]
My question is “Symbol not found: _OBJC_CLASS_$_SomeClass”

**Comment by johnno1962** [comment]
This is a slightly different problem where the symbol it is trying to link to has been "hidden" by the library developer. It comes up when you refer to some classes in libraries like GoogleAnalytics in the file you're injecting. These symbols you can link against but not dynamic load against.

**Comment by Xchn** [comment]
How can solve this problem?🙏

**Comment by johnno1962** [comment]
You won't be able to inject source files that refer to these hidden classes directly i.e. reference their class object symbol through class methods.

**Comment by Xchn** [comment]
This Framework is not me create. And in my project it used in many files. I can not change it. Anyway thank you for you reply.🙏🙏🙏

**Comment by johnno1962** [comment]
Create a local #define for SomeClass that refers to a function you created in a file you don't need to inject that returns [SomeClass class]; (#undef it in that file before the function.)

**Comment by Xchn** [comment]
I have a try. Thank you
