### ISSUE TITLE
Permission Warning

### ISSUE THREAD

**Issue by vijaytabhandari93** [johnno1962/InjectionIII#334]
Your project file seems to be in the Desktop or Documents folder and may prevent InjectionIII working as it has special permissions

Tried to move the project to Applications folder as well. How to set the correct permissions?

**Comment by johnno1962** [comment]
Hi, That's more a warning as people have had problems using those directories. If you're not having problems don't worry.

**Comment by vijaytabhandari93** [comment]
It seems to be not working for my project which has multiple modules created as development pods and it has more dependencies as well. Should this have any impact on the execution of InjectionIII?

**Comment by johnno1962** [comment]
Are you getting an error?, did you set the -Xlinker -interposable "Other Linker Flag"?

**Comment by vijaytabhandari93** [comment]
Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument. Rebuilding and re-running your project (without a build clean) can resolve this. I am getting this error whenever trying to modify any line in the code.

**Comment by johnno1962** [comment]
Perhaps you could tell me the error message?

**Comment by xiaohanyu** [comment]
hey @johnno1962,

Can you clarify more about this?

```
Hi, That's more a warning as people have had problems using those directories. 
```

What kind of issues you get from people? 

Thanks!

**Comment by johnno1962** [comment]
I put that message in as people where having problems when they dowloaded a project to ~/Downloads and tried to inject it. It could be noise as sometimes it does work and seems to change with the version of the OS. IIRC the error was being unable to read the source file when it went to recompile it and could depend on whether you're using the App Store version or one downloaded from GitHub.  Since you seem to be taking an interest in Injection have you read: https://github.com/johnno1962/InjectionIII/blob/main/ROADMAP.md ?

**Comment by xiaohanyu** [comment]
Hey @johnno1962:

> IIRC the error was being unable to read the source file when it went to recompile it and could depend on whether you're using the App Store version or one downloaded from GitHub.

Thanks for clarifying on this.

> Since you seem to be taking an interest in Injection have you read: https://github.com/johnno1962/InjectionIII/blob/main/ROADMAP.md ?

I read it before and today I read it again, but still didn't have time to dig in each file one by one. I kind of know the basic flow of how injecting works but you know, "The devil is in the details". Anyway, will try to dig in as much if time allows.
