### ISSUE TITLE
apple store version works. but 2.9.1  release doesn't work

### ISSUE THREAD

**Issue by HighmoreJx** [johnno1962/InjectionIII#337]
on my own work project. it reports under apple store injection.
```
malformed or corrupted AST file: 'could not find file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/
iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIkit.h' 
referenced by AST file '/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/xxxxxxxx-atuioiyywryfdgfnbytzkbzmcvvs/Build/Intermediates.noindex/PrecompiledHeaders/
SharedPrecompiledHeaders/4037933282539056576/xxxxxx-Prefix.pch.gch''
```
so I download injection from GitHub using latest version 2.9.1
the error is gone. but still not work.

I write a simple demo.
```
@implementation BViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    self.view.backgroundColor = [UIColor greenColor];
}
```
it works fine under apple store version. but on 2.9.1, it doesn't work.

-----
I tried 2.8.6. it works on both demo and my own project.

**Comment by johnno1962** [comment]
Hi, strange problem. Any chance you could send me the TestInject project?

**Comment by HighmoreJx** [comment]
[TestInject.zip](https://github.com/johnno1962/InjectionIII/files/6917213/TestInject.zip)

**Comment by johnno1962** [comment]
Thanks so much for this bug report and the test project. Some code to support Xcode 13 caused Objective-C injection to regress in a very obscure way. There is a new release 2.9.2 which you should find works fine now.

**Comment by HighmoreJx** [comment]
thanks

**Comment by songxing10000** [comment]
the same to me , download 2.9.2 is ok
