### ISSUE TITLE
codesign failed

### ISSUE THREAD

**Issue by m260154117** [johnno1962/InjectionIII#339]
codesign[2622:74766] [logging-persist] cannot open file at line 44595 of [02c344acea]
 codesign[2622:74766] [logging-persist] os_unix.c:44595: (0) open(/var/db/DetachedSignatures) - Undefined error: 0
codesign failed,can't work

**Comment by m260154117** [comment]
InjectionIII version is 2.9.2, InjectionIII from GitHub releases, xcode 12.5.1, OS Big Sur 11.4, I tried print "sudo touch /var/db/DetachedSignatures" ,like this, It worked

**Comment by johnno1962** [comment]
Interesting, I've seen the error before but it went away. Happy you've found a workaround, I'll leave this open so other people can pick it up.
