### ISSUE TITLE
Changes made in development pod not recognized by file watcher and not injected

### ISSUE THREAD

**Issue by rene-dohan** [johnno1962/InjectionIII#34]
Obviously because development pod has path outside of project, still its part of project source that is changing a lot, how to set file watcher to watch more folders ? Any workaround ?

**Comment by johnno1962** [comment]
You could watch a shared super-directory/your home directory?

**Comment by CoderAFI** [comment]
@rene-dohan hope [Vaccine](https://github.com/zenangst/Vaccine) can help you.

**Comment by zenangst** [comment]
What I usually do when working with pods and injection is to clone the pod into the directory of the project root.

I have `_pods` in my global `.gitignore`. Then I simply do `git clone ...` into that directory, change my Podfile to temporarily point to that folder.

```ruby
pod 'PodName', path: '_pods/PodName'
```

Hope that helps

**Comment by rene-dohan** [comment]
Thanks, looks easy, i also had to comment out script in podfile that was turning on wholemodule optimization, because somehow now popped out warning about it. It looks like i did put it there for some reason but didnt write comment so we will see... 
.......
I removed it, did pod update, but still similar errors:

*** Could not locate compile command for /Users/rene/Documents/Development/Motorkari/Motorkari/renetik-ios/CS-IOS/Classes/Core/Categories/UIKit/UIView+CSAutoResizing.m
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.) ***
*** Compiling /Users/rene/Documents/Development/Motorkari/Motorkari/Motorkari/Controller/Adverts/AdvertCell.m ***
*** Re-compilation failed (/Users/rene/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
/Users/rene/Documents/Development/Motorkari/Motorkari/Motorkari/Controller/Adverts/AdvertCell.m:39:49: error: property 'test' not found on object of type 'UILabel *'; did you mean 'text'?
            .fixedLeft.fixedRight.flexibleWidth.test;


I will try and clean and build and pod instal or whatever and we will see but it don't looks working now.

**Comment by rene-dohan** [comment]
Ok it works.

**Comment by ylrs** [comment]
@rene-dohan @zenangst  我也这样做了，但是报错：
All paths are also case sensitive is another thing to check.) ***
💉 *** Could not locate compile command for /Users/zhulongfei/Documents/Pintu/InjjectionDemo-OC/Pods/Headers/Private/Pintu/PintuView.h
(Injection does not work with Whole Module Optimization.
There are also restrictions on characters allowed in paths.
All paths are also case sensitive is another thing to check.) ***

你是怎么解决的？

**Comment by wzpziyi1** [comment]
@rene-dohan How to solve？Are you using zenangst's solution?

**Comment by erduoniba** [comment]
@ylrs 就是将你的pod 的代码，迁移到主工程的目录下，比如之前是这样的文件结构：
-HDBaseProject
--Pods.xcodeproj
--Example
---Podfile
---HDBaseProject.xcworkspace
---HDBaseProject.xcodeproj
--HDBaseProject
---PodCodeSources
--HDBaseProject.podspec

需要改成：
-HDBaseProject
--Pods.xcodeproj
--Example
---Podfile
---HDBaseProject.xcworkspace
---HDBaseProject.xcodeproj
---HDBaseProject.podspec
---HDBaseProject
----PodCodeSources

同时将Podfile由之前的：
pod 'HDBaseProject', :path => "../"
改成：
pod 'HDBaseProject', :path => "HDBaseProject/"

然后pod install即可
