### ISSUE TITLE
Error reading

### ISSUE THREAD

**Issue by hanxuhanxu** [johnno1962/InjectionIII#343]
hi, my project has this question:
Error reading /var/folders/nk/1vv69vkd2kjgdrkjnb3y96n00000gp/T/com.johnholdsworth.InjectionIII/eval101.sh, scanCommand: /var/folders/nk/1vv69vkd2kjgdrkjnb3y96n00000gp/T/com.johnholdsworth.InjectionIII/command.sh
the position is /Users/***/Downloads, please help!

**Comment by johnno1962** [comment]
Hi, which version of InjectionIII is this? Can you move your project out of Downloads folder which has special permissions.

**Comment by hanxuhanxu** [comment]
> Hi, which version of InjectionIII is this? Can you move your project out of Downloads folder which has special permissions.

2.8.0 from APPStore，can I open the permissions Manually？It looks like all folders have special permissions.

**Comment by johnno1962** [comment]
Try o ne of the GitHub releases which are not sandboxed: https://github.com/johnno1962/InjectionIII/releases

**Comment by hanxuhanxu** [comment]
> Try o ne of the GitHub releases which are not sandboxed: https://github.com/johnno1962/InjectionIII/releases

No more error messages，but It does not work，I use two method,  send notification and rewrite injected, but nothing happen.

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [self setupComponents];
    [self trackerForEnterViewController];
    

    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(hotReloadingUI)
                                                 name:@"INJECTION_BUNDLE_NOTIFICATION"
                                               object:nil];
}

- (void)hotReloadingUI {
    self.view.backgroundColor = [UIColor blueColor];
}

**Comment by hanxuhanxu** [comment]
💉 Compiling /Users/bytedance/injection/campai/campai-ios/DevelopmentPods/CPAProfile/CPAProfile/Classes/ProfileEdit/Controller/CPAProfileEditViewController.m
💉 Loading .dylib ...
objc[47994]: Class CPAProfileEditViewController is implemented in both /Users/bytedance/Library/Developer/CoreSimulator/Devices/CE529231-0040-4E82-961C-BB0084FE0361/data/Containers/Bundle/Application/F5466A4C-F8A0-4040-AF70-EF6F60D91CA7/campai.app/campai (0x110156930) and /Users/bytedance/Library/Developer/CoreSimulator/Devices/CE529231-0040-4E82-961C-BB0084FE0361/data/Containers/Data/Application/C78E3696-2FD2-4B08-A741-929DF92676FC/tmp/eval108.dylib (0x11e945dc0). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ^
💉 Injected class 'CPAProfileEditViewController'

**Comment by johnno1962** [comment]
The notification may not arrive on the main thread. Can you try surrounding your hotReloadingUI code with 
```
dispatch_sync(dispatch_get_main_queue(), {
    self.view.backgroundColor = [UIColor blueColor];
});

**Comment by hanxuhanxu** [comment]
> The notification may not arrive on the main thread. Can you try surrounding your hotReloadingUI code with
> 
> ```
> dispatch_async(dispatch_get_main_queue(), ^{
>     self.view.backgroundColor = [UIColor blueColor];
> });
> ```

Hi, I can run successfully for the first time, but when I change the color again, It does not work anymore. I change the color to red and yellow, It always show blue.
