### ISSUE TITLE
Symbols Hidden by Default

### ISSUE THREAD

**Issue by Xchn** [johnno1962/InjectionIII#344]
Hi. In my project. There have many Frameworks. And some Framework have set "Symbols Hidden by Default" to YES. But i do not have the source code to build a new Framework with "Symbols Hidden by Default" is NO. How can i to solve this problem? Pls🙏

**Comment by johnno1962** [comment]
Hi, thanks for picking this up. Have you had a chance to look at it yet? If you sent something through I didn't get it. I've [laid the groundwork](https://twitter.com/MarxinHell/status/1432086980058361863) for an "unhiding frameworks" implementation but without test data I can't work on it which I'd like to as you are not the only person has encountered this.

**Comment by Xchn** [comment]
Hi. I try to build a demo. But now i can't repeat this error. May my origin project has some setting or other framework's setting. I try it again later.

**Comment by johnno1962** [comment]
OK, cheers. Let me know if you work it out.

**Comment by Xchn** [comment]
OK. Cheers. But i think it not to repeat it. I think my origin project is to big to repeat it in a demo. Last Friday i build a empty project to repeat it. But it failed.

**Comment by johnno1962** [comment]
Interesting, I can TeamView to take a look if you send me the details.

**Comment by Xchn** [comment]
TeamView may be forbided by company. When i repeat it, i send to you. Thank you!

**Comment by johnno1962** [comment]
Thanks! But don't spend too much time on it. It would nice to get this fixed but it is possible that once a framework is linked it is not as easy to unhide a symbol as it is for object files. It would be very interesting however to know the project setting which is causing your problem.

**Comment by Xchn** [comment]
I will. Thank you.
