### ISSUE TITLE
Is it possible to extend this tool to support hot reloading of dart code in a hybrid iOS App?

### ISSUE THREAD

**Issue by buptwsg** [johnno1962/InjectionIII#346]
Hi @johnno1962 ,
    Thank you for making such a great tool! I have used this tool with my daily app development, and it saves me a huge amount of time.
    My app is a hybrid app, built with objective c and Flutter. I want to know if it is possible to extend this tool to support hot reloading of dart code during hybrid development.

   thanks!

**Comment by johnno1962** [comment]
HI, I know absolutely nothing about dart so I can't give you an answer but it might be both difficult and useful. Is there any chance you could prove a small example project combining dart and object-c and I can evaluate if there is anything I can do.
