### ISSUE TITLE
Could not locate containing project or it's logs.

### ISSUE THREAD

**Issue by placrosse** [johnno1962/InjectionIII#35]
The subject error occurs, using the sample GettingStarted.zip app
* tested on Xcode v9.4.1
* Xcode Preferences Locations has:
  => Derived Data: Relative  build/DerivedData
       -> click Advanced under Derived Data:
            Custom  Relative to Workspace
                    Products:  build/Build/Products
                    Intermediates:  build/Build/Intermediates.noindex
                    Index Datastore:  build/Index/DataStore

In other words, all of the build products are put underneath a "build" directory in the root of the project.  This was done to allow command line builds, and xcode builds, to share the same build output dir, thereby allowing you to interact with both.  It also allows easy full cleans of both, and .gitignore of the build dir in the root of the project.

This change appears to be causing Injection to fail, though, due to the message provided in the subject line.

How may I keep the relative build directory, and still use Injection?

**Comment by johnno1962** [comment]
I’m afraid the current version of injection doesn’t support finding logs at a custom location.

**Comment by johnno1962** [comment]
I’ve pushed a mod which may support your DerivedData path to the MAS-Version branch if you want to roll your own and give it a try.

**Comment by lazylady** [comment]
I got stuck on the same error today and solved it by removing the xcworkspaces files also located in the project directory.  Does xcworkspace have precedence over xcodeproj? Could it be a better idea to choose the project file instead of project directory?

**Comment by johnno1962** [comment]
Injection relies on knowing the open workspace document in order to be able to find the logs. This is usually the .xcworkspace file so I don’t think we can change this.

**Comment by narendrabade** [comment]
How to solve this issue?
"*** Could not locate containing project or it's logs.
Have you customised the DerivedData path? ***"

**Comment by LionWY** [comment]
same problem , how to solve
