### ISSUE TITLE
每次注入函数时，主视图中的子视图是否会被移除？

### ISSUE THREAD

**Issue by LingliZ** [johnno1962/InjectionIII#352]
“Every time the injected function runs, we’re going to remove all the subviews in the main view of the UIViewController. This should clear the screen in most cases.”
您好，我从文档中看到这样一段话，但是当我对如下代码进行热重载时，发现每次注入函数之前子视图并没有被删除，请问是什么原因呢？

Hello, I read this in the documentation, but when I heat reload the following code, I find that the subview is not deleted before each injection function, what is the reason?

`- (void)viewDidLoad {
    [super viewDidLoad];
    UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 100, 100, 100)];
    view.backgroundColor = UIColor.blueColor;
    [self.view addSubview:view];
    
}

- (void)hotReloadingUI {
#if DEBUG
    NSLog(@"I've been injected: %@", self);
    [self viewDidLoad];
#endif
}
`

**Comment by johnno1962** [comment]
You need to use removeFromSuperview to remove all existing subviews or they accumulate?
