### ISSUE TITLE
When I tried to compile injectionlll project by myself and copy the iOSInjection.bundle product to the simulator sandbox, I encountered an error，I cannot generate "command.sh" shell script

### ISSUE THREAD

**Issue by Liulinzhe17** [johnno1962/InjectionIII#353]
I want to compile the project to learn the implementation principle of hot reload，I encountered an error when i try hot reload，I cannot generate "command.sh" shell script

Here are some things I did
1. clone this project
2. build  target of Injectionlll
3. copy products of iOSInjection.bundle in Injection.app to my App's sandbox in Simulator
4. load bundle `    NSString *path = [NSBundle.mainBundle pathForResource:@"iOSInjection" ofType:@"bundle"];
    NSLog(@"injection load: %d", [[NSBundle bundleWithPath:path] load]);`
5. run my demo project, i can see some success log `💉 InjectionIII connected /Users/xx/Projects/HotReloadDemo/Example/HotReloadDemo.xcworkspace
💉 Watching files under /Users/xx/Projects/HotReloadDemo/Example`
6. But when I hot reload, my demo project will print error log `💉 ⚠️ Error reading /var/folders/rj/_70lf7094zv2cjb14cvvrcz40000gp/T/com.johnholdsworth.InjectionIIIl/eval101.sh, scanCommand: /var/folders/rj/_70lf7094zv2cjb14cvvrcz40000gp/T/com.johnholdsworth.InjectionIIIl/command.sh`

Did i do something wrong

**Comment by johnno1962** [comment]
Hi, I'm afraid I can't support you on that as the code is rather delicate. There is a reason why we do a binary release!

**Comment by Liulinzhe17** [comment]
A sad day😢
