### ISSUE TITLE
Do you support class methods?

### ISSUE THREAD

**Issue by LingliZ** [johnno1962/InjectionIII#356]
`class TCBlankAlertDemoVC: UIViewController {
    class func changeUI() -> UILabel {
        let label = UILabel()
        label.text = "我是"
        label.backgroundColor = UIColor.red
        return label
    }
}
`

`class TCAlertDemoListVC: EPBaseVC {
    override func viewDidLoad() {
        super.viewDidLoad()
        let label = TCBlankAlertDemoVC.changeUI()
        label.frame = CGRect(x: 200, y: 400, width: 100, height: 30)
        view.addSubview(label)
    }
}
`
When I change the color of the label, there is no change. Do you support class methods?

**Comment by LingliZ** [comment]
yes, I have tried using OC language and there is no problem，only in swift that might not work as the class method is being called from the newly injected,Sample code has been uploaded as an attachment.

Thank you for your reply.

At 2021-10-29 20:21:43, "John Holdsworth" ***@***.***> wrote:

Hi, I can see why that might not work as the class method is being called from the newly injected instance method. Have you tried using Self.changeUI() or type(of: self).changeUI()? Give me some time to look at this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LingliZ** [comment]
yes, I have tried using OC language and there is no problem，only in swift that might not work as the class method is being called from the newly injected,sample code has been sent to you via email
Thank you for your reply.

**Comment by johnno1962** [comment]
Thanks, I didn't receive your test project however. Did you send it to github at johnholdsworth.com?

**Comment by LingliZ** [comment]
I just posted the code to Github,The address is as follows:   [https://github.com/angrykub/TestInjectionIIISwift](https://github.com/angrykub/TestInjectionIIISwift).

**Comment by johnno1962** [comment]
Hi, I've made the unanticipated changes necessary to support class/static methods available in the HotReloading project https://github.com/johnno1962/HotReloading, commit ac95d4308baf439dcf6da9bf460d73925d551807 if you are able to give it a try. If not, I'll roll a new GitHub release you can pick up in a couple of days.

**Comment by johnno1962** [comment]
I have released this if you want to download a new version of the InjectionIII app.
https://github.com/johnno1962/InjectionIII/releases/tag/3.1.5

**Comment by LingliZ** [comment]
Thank you very much for your efforts,I tried the new version,no more questions.

**Comment by johnno1962** [comment]
Great! 👍
