### ISSUE TITLE
dlopen error and loading dylib has failed

### ISSUE THREAD

**Issue by gpake** [johnno1962/InjectionIII#357]
Hi @johnno1962,
### Original Issue
I'm still facing the same issue https://github.com/johnno1962/InjectionIII/issues/330 with the latest version of the app (https://github.com/johnno1962/InjectionIII/releases/tag/3.1.5).
### Then what I tried:
1. Using the least version of InjectionIII
2. Restart/Rebuild the project
But no effect.
After I clean the whole project, I got another error
```
💉 Compiling /path/to/a/ViewController.swift
💉 ⚠️ Re-compilation failed (see: ~/Library/Developer/CoreSimulator/Devices/0B651512-DB78-45A8-A8BE-9C0E47D143D3/data/Containers/Data/Application/080DBC45-BF3E-40DE-9D1C-1B008DFCB652/tmp/command.sh)
<unknown>:0: error: cannot open file '~/Library/Developer/CoreSimulator/Devices/0B651512-DB78-45A8-A8BE-9C0E47D143D3/data/Containers/Data/Application/08444319-0E14-4394-A190-70E761095740/tmp//filelist.txt' (No such file or directory)
```

### Next Day:
Re-clean/Delete the DerivedData and rebuild still not work.

Tried to reset the simulator
then building

Got 2 kinds of issues and 1 success:
0. Building the Objective-C file works
1. Could not locate compile command; Building the swift files in one framework
2. dlopen() error; Building the swift file in the main project, rerun the project not work
Update: 2.1 For some file, but other swift files work, interesting)
Update: 2.2 After restarting the Mac, rebuilding, issue 2.1 disappeared.

Issue 1:
As the background, all the files are in the same observing root directory.
```
💉 ⚠️ Could not locate compile command for /path/to/the/ViewController.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator paths are case sensitive.
Try a build clean then rebuild to make logs available or
consult: "~/Library/Developer/CoreSimulator/Devices/0B651512-DB78-45A8-A8BE-9C0E47D143D3/data/Containers/Data/Application/43740B7A-9CC6-4444-9D47-E3FEEB5AFBAA/tmp/command.sh".
```

Issue 2:
```
💉 Compiling ~/path/to/the/swift/file/in/main/project/AppDelegateExtension.swift
💉 Loading .dylib ...
💉 ⚠️ Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument. Rebuilding and re-running your project (without a build clean) can resolve this.
💉 ⚠️ dlopen() error: dlopen(~/Library/Developer/CoreSimulator/Devices/0B651512-DB78-45A8-A8BE-9C0E47D143D3/data/Containers/Data/Application/3A92A9B8-44AB-47A4-814E-AE01619B7897/tmp/eval102.dylib, 2): Symbol not found: _$sSo13UIApplicationC4GrabE17topViewControllerySo06UIViewE0CSgAGFZfA_
  Referenced from: ~/Library/Developer/CoreSimulator/Devices/0B651512-DB78-45A8-A8BE-9C0E47D143D3/data/Containers/Data/Application/3A92A9B8-44AB-47A4-814E-AE01619B7897/tmp/eval102.dylib
  Expected in: flat namespace
 in ~/Library/Developer/CoreSimulator/Devices/0B651512-DB78-45A8-A8BE-9C0E47D143D3/data/Containers/Data/Application/3A92A9B8-44AB-47A4-814E-AE01619B7897/tmp/eval102.dylib
 ```

btw: Teamview is not supported, but Zoom may work if you want to take a look at the environment.

**Comment by johnno1962** [comment]
Hi, Zoom might be the best option if that's possible. Send the details to github at johnholdsworth.com

**Comment by gpake** [comment]
email sent, thanks

**Comment by gpake** [comment]
The root cause here is we are using the cocoapods to wrap our codes into frameworks, this setting caused the Injection app not able to find the building logs so that it can't re-compile the source code I want to reload.
I'm still investigating where are the full compile logs, will update once I got it.

**Comment by johnno1962** [comment]
Aha, not familiar with where Bazel puts it logs but I'd like to know as many large projects use it. I'll do some research then perhaps we can zoom again and look into supporting this.

**Comment by johnno1962** [comment]
Had a quick look and it doesn't look likely I'll be supporting bezel. Links & example broken. Example project in Objective-C...

**Comment by gpake** [comment]
Update: 
Hi @johnno1962 
This is solved, thank you for spending so much time.
Root cause: Our team made a separated Xcode build config file for the whole workspace that enabled the **Whole Module Optimization**.
It is the hint on the first line 🤣
Disable the WMO will work as expected, super cool!

💉 ⚠️ Could not locate compile command for /path/to/the/ViewController.swift.
This could be due to one of the following:
1. **Injection does not work with Whole Module Optimization**.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator paths are case-sensitive.
Try a build clean then rebuild to make logs available or
consult: ".../tmp/command.sh".

**Comment by johnno1962** [comment]
🤦‍♂️!

**Comment by gpake** [comment]
maybe we can add a check on the WMO config, but may not that necessary 🤦‍♂️

**Comment by johnno1962** [comment]
I've looked at that but it is not simple particularly if people are using a config. If I think of an easy way I'll do it. Now you are an injection expert, any ideas on this one https://github.com/johnno1962/InjectionIII/issues/358 (in Chinese)
