### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by LWisCL** [johnno1962/InjectionIII#358]
![image](https://user-images.githubusercontent.com/37854320/141227001-edee8edf-24b5-4e25-bd84-e46279cefde2.png)

自从出现这个问题之后  卸载了N多次都还是一直出现这个问题 头大。。。

**Comment by johnno1962** [comment]
Have a look at and try running the `command.sh` file it mentions.

**Comment by gpake** [comment]
@LWisCL 看看command.sh 是什么内容，run 一下这个 sh 看看有什么提示？有没有出现过左右括号
重新 build，清空 derivedData 有变化么？
记得检查文档中提到的各种配置都符合要求
如果可以，最好用英文回复。
