### ISSUE TITLE
Re-compilation failed if PREPROCESSOR_DEFINITIONS has a  "

### ISSUE THREAD

**Issue by qmkCamel** [johnno1962/InjectionIII#359]
I have a PREPROCESSOR_DEFINITIONS like this  PODNAME=@"XXPodName" in xcconfig, and need to use it in code.

The Xcode compile command is like this 
```
-DPODNAME\=@\"XXPodName\"
```

But the re-compile command is like this, then the re-compile would failed.
```
-DPODNAME\=@"XXPodName"
```

So, is it possible to support this case ?

Thanks~

**Comment by johnno1962** [comment]
Hi, I'm afraid this is a know limitation of InjectionIII. If you want to build your own version of InjectionII removing/commenting out line 699 in the file SwiftEval.swift you should be able to disable this "feature".

**Comment by qmkCamel** [comment]
> Hi, I'm afraid this is a know limitation of InjectionIII. If you want to build your own version of InjectionII removing/commenting out line 699 in the file InjectionIII/HotReloading/Sources/HotReloading/SwiftEval.swift you should be able to disable this "feature".
> 
> ```
> git clone https://github.com/johnno1962/InjectionIII --recurse-submodules
> ```

I try to avoid this problem,  but found the following comment. 
Need to use new build system,  so,  will it work properly if I disable the "feature".
```
// remove excess escaping in new build system
.replacingOccurrences(of: #"\\([\"'\\])"#, with: "$1", options: [.regularExpression])
```

**Comment by johnno1962** [comment]
It may longer be the case that that line is required even using the new build system. That line was added some years ago.

**Comment by qmkCamel** [comment]
If I need support the macro ` -DPODNAME\=@\"XXPodName\" ` with  the new build system, the only way is keep the line `.replacingOccurrences(of: #"\\([\"'\\])"#, with: "$1", options: [.regularExpression])` and make a workaround for the macro ?
Is there any chance to handle this case officially in the future ?
And I am a little confused about is it a correct way to handle this case.

Thanks

**Comment by johnno1962** [comment]
Have you tried building in the InjectionIII project with that line commented out? Does it work for you then? This is one of those very old possibly legacy lines of code that can only be taken out of the official release after a lot of testing.

**Comment by qmkCamel** [comment]
Not yet. I will try it. Thanks

**Comment by qmkCamel** [comment]
It worked. Helps me a lot. Thanks~

**Comment by johnno1962** [comment]
👍

**Comment by johnno1962** [comment]
You'll be happy to hear I've removed this code from the main branch as it no longer seems to be required: https://github.com/johnno1962/InjectionIII/releases/tag/4.1.6
