### ISSUE TITLE
Cannot find executable

### ISSUE THREAD

**Issue by isishere** [johnno1962/InjectionIII#360]
Hello!
I did download InjectionIII from Mac App Store, then connected to the AppCode (added code to ContentView.swift and MyApp.swift, chose project path in InjectionIII app). Something went wrong and I got this output in the run menu:
" 2021-11-16 Surf[] Cannot find executable for CFBundle 0x7f94b01051d0 </Applications/InjectionIII.app/Contents/Resources> (not loaded) "

Could you please help me?

**Comment by johnno1962** [comment]
Seems like the bundle load failed. It should be something like this:
```
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()
```
If this is a Mac App it will need to be macOSInjectionBundle and you will need to turn the sandbox off.
