### ISSUE TITLE
crash when add new method

### ISSUE THREAD

**Issue by donggelaile** [johnno1962/InjectionIII#363]
before :
- (void)viewDidLoad {
    [super viewDidLoad];
}

after : 
- (void)viewDidLoad {
    [super viewDidLoad];
    [self testMethod];
}

- (void)testMethod {
    NSLog(@"testMethod");
}

i found when i add a new method, then i call it, will get  unrecognized selector sent to instance xxxxx exception
It is ok when just edit existed method, but can not add new method. is this a bug or a feature ?
thanks

**Comment by johnno1962** [comment]
Hi adding or changing the order of methods in non-final classes  is not supported as it results in a re-ordering of the class' vtable and call invocations are dispatched to the wrong implementation. If you make your class final this shouldn't happen.

**Comment by donggelaile** [comment]
ok, thanks
