### ISSUE TITLE
Linking failed

### ISSUE THREAD

**Issue by barron9** [johnno1962/InjectionIII#365]
Compiling /Users/admin/ViewController.swift
💉 ⚠️ Linking failed (see: /Users/admin/Library/Developer/CoreSimulator/Devices/DFFB9F73-7DE6-4630-BD68-3A504A276A5C/data/Containers/Data/Application/E01E6295-A788-4D9A-B0FE-89E480DF97DD/tmp/command.sh)
/Users/admin/Library/Developer/CoreSimulator/Devices/DFFB9F73-7DE6-4630-BD68-3A504A276A5C/data/Containers/Data/Application/E01E6295-A788-4D9A-B0FE-89E480DF97DD/tmp/command.sh: line 1: /Users/admin/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang: No such file or directory

**Comment by johnno1962** [comment]
Hi, Injection requires you use/have an Xcode at the standard path /Applications/Xcode.app. Using one from the Downloads directory might be causing the problem as it has particular permissions.

**Comment by barron9** [comment]
hi, thank you, xcode and injectionIII is in the app folder actually.

**Comment by johnno1962** [comment]
Hva you implemented and @objc injected() method to redraw?
