### ISSUE TITLE
Support for workspace-relative custom DerivedData paths

### ISSUE THREAD

**Issue by spnkr** [johnno1962/InjectionIII#368]
Can InjectionIII work when I customize my DerivedData path?

I have it set to a workspace-relative location, but I get this error:

```
Have you customized your DerivedData path?
```

**Comment by johnno1962** [comment]
Hi Will, Standard relative DerivedData paths (as opposed to completely custom ones which InjectionIII can't support) used to work but in fact there was a bug :( I've rolled a new release candidate for you: https://github.com/johnno1962/InjectionIII/releases/tag/3.2.2RC2

**Comment by johnno1962** [comment]
I've re-worked this code and released https://github.com/johnno1962/InjectionIII/releases/tag/3.2.2RC6 to hopefully fix relative DerivedData once and for all without breaking anything else this time. Let me know if it doesn't work for you.
