### ISSUE TITLE
crash when I add a new element

### ISSUE THREAD

**Issue by DigitEdge** [johnno1962/InjectionIII#369]
<img width="1074" alt="iShot2022-01-18 17 35 58" src="https://user-images.githubusercontent.com/18003805/149910727-bd5222d1-09fa-4d38-9838-b70474e1cfed.png">

**Comment by johnno1962** [comment]
Hi, How do you mean new element? Do you mean a new instance variable? I'm afraid that's not supported.

**Comment by DigitEdge** [comment]
> 

Ok. I tried it, the local variable is ok
