### ISSUE TITLE
Simulator stuck InjectionIII

### ISSUE THREAD

**Issue by duytrann** [johnno1962/InjectionIII#37]
When trying to adjust constraints or adding new UI elements in storyboard the simulator gets stuck.

Any ideas what might cause this or the solution to it?

**Comment by zenangst** [comment]
@duytrann I ran into similar issues when trying to inject `xib`-files. I haven't really found a good way to properly fix the issue, you can see this issue for more context: https://github.com/johnno1962/InjectionIII/issues/43

Or rather, the way I fixed it is to stick with writing my views in code (for the time being).
I know that's not really a comfort but it is what I got right now :/

**Comment by zenangst** [comment]
Hello again, I've been focusing on storyboard and nib injection recently and that feature still needs a bit more work to be top notch (or at least as far as we can take it). The recent changes that have been done to this specific part of InjectionIII can be found here #76. It improves how view controllers are resolved and should make injecting storyboard more reliable.

What I noticed when working with it is that injecting code is way faster than storyboard and right now I don't really know how to speed up that process.

But when it gets stuck, do you get any additional log messages in your application that might give a hint to what might be going wrong here? Any logs that would narrow down the search would be helpful!

Thanks!

**Comment by zenangst** [comment]
@duytrann hey mate, wanted to follow up on this issue, have you tried the latest version of InjectionIII to see if that doesn't fix the issue that you are seeing?
