### ISSUE TITLE
⚠️ Error reading /var/folders/jc/.....

### ISSUE THREAD

**Issue by SandyLoo** [johnno1962/InjectionIII#372]
when i click "command + s" to save the changes,  i get a error message as following ? 

💉 ⚠️ Error reading /var/folders/jc/f7p46mhx2tg4md7xmsbh03dw8f51y8/T/com.johnholdsworth.InjectionIII/eval101.sh, scanCommand: /var/folders/jc/f7p46mhx2tg4md7xmsbh03dw8f51y8/T/com.johnholdsworth.InjectionIII/command.sh

**Comment by johnno1962** [comment]
Hi, this is probably to do with unsupported characters in path to the file being injected. Try running `$ bash the/path/to/the/command.sh` it mentions to see the error.

**Comment by SandyLoo** [comment]
> Hi, this is probably to do with unsupported characters in path to the file being injected. Try running `$ bash the/path/to/the/command.sh` it mentions to see the error.

I moved the project to another path , and re-watch the new path, after i save changes, got the resonse : 💉 ⚠️ Codesign failed. If you are using macOS 11 (Big Sur), Please download a new release from https://github.com/johnno1962/InjectionIII/releases.


The software is the newest version which i download from app store, and mac version is  12.1

**Comment by johnno1962** [comment]
Unusual, we need to capture the error from code signing to see what's going on: Can you run the InjectionIII app from the command line to see the error:
```
$ /Applications/InjectionIII.app/Contents/MacOS/InjectionIII
```

**Comment by chandrapol** [comment]
I have this same problem 

```
💉 ⚠️ Error reading /var/folders/_1/97p229zj2r94py8s8tp21h280000gn/T/com.johnholdsworth.InjectionIII/eval103.sh,
scanCommand: /var/folders/_1/97p229zj2r94py8s8tp21h280000gn/T/com.johnholdsworth.InjectionIII/command.sh
```

Running the `$bash <SCRIPT>` does not give any output.

```
$ echo $?
1
```

**Comment by johnno1962** [comment]
Hi, This is probably sue to non-ASCII character in a path somewhere. Are you sure you're using the most recent release of the InjectionIII app, download [from here](https://github.com/johnno1962/InjectionIII/releases)? The error message mentions a `command.sh` script. If you view this script you can see where it redirects errors into a file. Can you look at that file and tell me what it says please.
