### ISSUE TITLE
error opening input file

### ISSUE THREAD

**Issue by CodeForYang** [johnno1962/InjectionIII#373]
when i modyfile TGTestCell.swift , then command + s, the log --->

💉 Compiling /Users/yangpei/Documents/FindCustomer/tungeeindustry/TGUserCenterKit/TGUserCenterKit/Classes/Test/TGTestCell.swift
💉 ⚠️ Re-compilation failed (see: /Users/yangpei/Library/Developer/CoreSimulator/Devices/238E7A48-A2BC-4233-8DCE-1A178EA6C6B7/data/Containers/Data/Application/47892317-89BB-4BBB-9973-84BF9B04EECA/tmp/command.sh)
<unknown>:0: error: error opening input file '/Users/yangpei/Documents/FindCustomer/tungeeindustry/TGUserCenterKit/TGUserCenterKit/Classes/Mine（我的）/View/dynamic/名片访客/TGMineCardVisitorsCell.swift191CompileSwift normal x86_64 /Users/yangpei/Documents/FindCustomer/tungeeindustry/TGUserCenterKit/TGUserCenterKit/Classes/Mine（我的）/View/dynamic/名片访客/TGMineCardVisitorsCell.swiftc47c0b77ecdec341^340eb979ecdec341^-276/Users/yangpei/Documents/FindCustomer/tungeeindustry/TGUserCenterKit/TGUserCenterKit/Classes/Mine（我的）/View/article/TGMyArticleView.swift:137:20:' (No such file or directory)
<unknown>:0: error: error opening input file 'warning:' (No such file or directory)
<unknown>:0: error: error opening input file 'variable' (No such file or directory)
<unknown>:0: error: error opening input file 'self' (No such file or directory)
<unknown>:0: error: error opening input file 'was' (No such file or directory)
<unknown>:0: error: error opening input file 'written' (No such file or directory)
<unknown>:0: error: error opening input file 'to,' (No such file or directory)
<unknown>:0: error: error opening input file 'but' (No such file or directory)
<unknown>:0: error: error opening input file 'never' (No such file or directory)
<unknown>:0: error: error opening input file 'read
' (No such file or directory)

**Comment by johnno1962** [comment]
Hi, this is most likely because you have `()` characters in the path to the project. I've been unable to support this.
