### ISSUE TITLE
error: couldn't IRGen expression - virtual filesystem overlay file not found `/Users/johnholdsworth/.../SwiftTrace.build/all-product-headers.yaml`

### ISSUE THREAD

**Issue by spnkr** [johnno1962/InjectionIII#374]
Sometimes I get this error, with release [4.1.2](https://github.com/johnno1962/InjectionIII/releases/tag/4.1.2):

`error: virtual filesystem overlay file '/Users/johnholdsworth/Library/Developer/Xcode/DerivedData/InjectionIII-gyrknukcgontnjbwfbsardzhrixu/Build/Intermediates.noindex/ArchiveIntermediates/InjectionIII/BuildProductsPath/InjectionIII.build/Release-iphonesimulator/SwiftTrace.build/all-product-headers.yaml' not found`

`error: couldn't IRGen expression. Please check the above error messages for possible root causes.`

Do you know what's happening?

M1 Mac, Xcode in rosetta mode, latest Mac OS and Xcode version.

**Comment by johnno1962** [comment]
Xcode strangeness I'd venture. When you say sometimes, does it go away if you inject the file again/restart the app/try a different file. This was never a problem until this specific version? I've published https://github.com/johnno1962/InjectionIII/releases/tag/4.1.1 which was to be the version before this. Can you try it out and if that fails I'll roll another release using Xcode 12.5.

**Comment by johnno1962** [comment]
Could this be to do with LLDB/debugging? Releases Ince 3.2.2 have include .dSYM files in the hope that people encountering crashes inside the injection bundle could clone the project to /tmp where I build it and debug. It's possible these files aren't made to transport across machines and contain hardcoded paths (https://steipete.com/posts/couldnt-irgen-expression/) which may be causing this problem. Could you try removing all .dSYM files in the app package and bundles and see if you sill get this error?

**Comment by spnkr** [comment]
awesome @johnno1962 it's working in the newest release 🥳
