### ISSUE TITLE
InjectionIII connected but no effect when command + S

### ISSUE THREAD

**Issue by quietStefan** [johnno1962/InjectionIII#375]
the xcode log :
💉 InjectionIII connected /Users/apple/Downloads/Test/test.xcworkspace
💉 Watching files under /Users/apple/Downloads/Test/test.xcworkspace

the injected method:
- (void)injected
{
    //自定义修改...
    //重新加载view
    self.view.backgroundColor = [UIColor redColor];
    [self viewDidLoad];
}

but when Command + S, the view backgroundColor wont change. and have no other log,

**Comment by johnno1962** [comment]
Hi, Can you try moving the project out of your Downloads folder? This has special permissions.

**Comment by quietStefan** [comment]
Thanks for you  reply.

When i move the project to the Desktop,the,the log will warning me "💉 💉 ⚠️ Your project file seems to be in the Desktop or Documents folder and may prevent InjectionIII working as it has special permissions."

But the Downloads floder wnot,So ,how can i know which floder has special permissions?

**Comment by quietStefan** [comment]
Or are there have some CMD can disable the permission?

**Comment by quietStefan** [comment]
Amazing! it works!!!!! In Desktop Or Downloads.

**Comment by chagtraife** [comment]
@quietStefan I am facing the same issue as you. How did you fix it?
