### ISSUE TITLE
Class XXXX is implemented in both And doesn't  work

### ISSUE THREAD

**Issue by quietStefan** [johnno1962/InjectionIII#378]
The no work log like this:
objc[40639]: Class SWDSLocationServiceImpl is implemented in both /Users/apple/Library/Developer/CoreSimulator/Devices/7F3BEC6D-148D-4D5D-8C73-A5411F37C777/data/Containers/Bundle/Application/0896C75F-8F50-4014-B01F-45160AD606BE/XXX.app/XXX (0x11518a7f0) and /Users/apple/Library/Developer/CoreSimulator/Devices/7F3BEC6D-148D-4D5D-8C73-A5411F37C777/data/Containers/Data/Application/CFE40DF2-C8DB-4900-858F-410D40AC9D4F/tmp/eval102.dylib (0x14ab820f8). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ⬆️
💉 Patched class 'SWDSLocationServiceImpl' (0,142)
2022-02-28 16:57:39.737919+0800 XXX[40639:4072987] start loc!

But the other ViewClass Or ViewControllerClass which in the same project can work,i am so confused.

This is successful log:
2022-02-28 17:17:27.767812+0800 CallWatch[40639:4072987] stop loc!
💉 Compiling /Users/apple/Desktop/Trunk/XXX/XXX/XXX/Modules/CallWatchLocation/CallWatchLocation/LocationViewController.m
2022-02-28 17:17:39.752714+0800 CallWatch[40639:4072987] start loc!

The InjectionIII is the newest version,

<img width="271" alt="image" src="https://user-images.githubusercontent.com/12831937/155956390-21129190-80cb-4252-a5db-00a823dfb892.png">

The Xcode Version:Version 13.2.1 (13C100)

Thanks for your attention and hope your answer.

**Comment by johnno1962** [comment]
I'm confused too! You can always ignore the message about the class being duplicated. Unfortunately there isn't anything I can do about it as it comes from deep in the Objective-C runtime. You're saying SWDSLocationServiceImpl isn't injecting?

**Comment by quietStefan** [comment]
Thanks for your answer;
Yes，the code which inject into SWDSLocationServiceImpl Class was not working;
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/12831937/156088093-25a01a7f-d043-44a8-88b1-2890b6ba0f06.png">

**Comment by quietStefan** [comment]
When i added the NOTIFICATION,it can not work either;
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/12831937/156090191-e8ccc471-fa76-48eb-b83b-88c85ac13bdb.png">
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/12831937/156090225-08110ad3-06dd-4a20-9f1f-fd799532eeb4.png">

**Comment by quietStefan** [comment]
Thanks for your answer;
I try to use NOTIFICATION And i can work.
Thanks.
