### ISSUE TITLE
Can it be used in iOS 12 or lower?

### ISSUE THREAD

**Issue by kcharliek** [johnno1962/InjectionIII#381]
Hello. The minimum supported version of my service is iOS 12. 
But Injection3 uses 'Combine', so I can't compile it.
Can it be used in iOS 12 or lower?

**Comment by johnno1962** [comment]
Hi, You should be able to use injection on iOS 12 or lower but I haven't tested it lately. It only uses Combine for the SwiftUI code snippet.
