### ISSUE TITLE
EXC_BAD_ACCESS when using Generic struct with SwiftUI

### ISSUE THREAD

**Issue by exevil** [johnno1962/InjectionIII#383]
Hello, 

First of all, thanks for the great product. 👍 Here's the bug I found: When my SwiftUI view involves generic type of PreferenceKey I'm constantly getting the following crash without any stack trace:  
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/1979535/162268244-d733d812-6654-42a7-b36b-bff85016a780.png">
```
#0	0x000000018f98f30c in swift_getAssociatedTypeWitnessSlowImpl(swift::MetadataRequest, swift::TargetWitnessTable<swift::InProcess>*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolRequirement<swift::InProcess> const*, swift::TargetProtocolRequirement<swift::InProcess> const*) ()
```

Here's a quick sample project that reproduces the issue on the latest Xcode 13.3.0 running on Monerey 12.3: [InjectionBug.zip](https://github.com/johnno1962/InjectionIII/files/8445445/InjectionBug.zip)
(I'm using @krzysztofzablocki's recent wrapper [Inject](https://github.com/krzysztofzablocki/Inject))

Is there something I missed during the configuration or there's something else? I already tried `INJECTION_OF_GENERICS` with no luck.

Thanks in advance.

**Comment by johnno1962** [comment]
Hi, Thanks for the test project which helped a lot tracking down where the problem was. I've made a new release "4.2.1" you could try that seems to resolve this https://github.com/johnno1962/InjectionIII/releases/tag/4.2.1

**Comment by exevil** [comment]
Hi John, thanks a lot for the quick response and solution. I just tested it in my main project and the latest version seems to resolve the issue.

Thanks you! 👏
