### ISSUE TITLE
Assertion failed: (currentSyncQueue != self && "inDatabase: was called reentrantly on the same queue, which would lead to a deadlock"), function -[FMDatabaseQueue inDatabase:], file FMDatabaseQueue.m, line 185.

### ISSUE THREAD

**Issue by dongpeng66** [johnno1962/InjectionIII#384]
非常感谢您们提供这个好的一个工具！
我在集成过程中遇到了以下问题：
我的项目中有FMDB这个库，当我集成InjectionIII到项目中，我更改UI热重载以后，我的项目卡死了。报错信息如下：
Thank you so much for this great tool!
I encountered the following issues during the integration process:
I have the FMDB library in my project. When I integrated InjectionIII into the project, after I changed the UI hot reload, my project was stuck. The error message is as follows:

Assertion failed: (currentSyncQueue != self && "inDatabase: was called reentrantly on the same queue, which would lead to a deadlock"), function -[FMDatabaseQueue inDatabase:], file FMDatabaseQueue.m, line 185.

当我把FMDB从我项目中移除以后，热重载正常了。
After I removed FMDB from my project, hot reload worked fine.

**Comment by johnno1962** [comment]
Hi, Thanks for the Thanks! I'm afraid InjectionIII can't support all that code imported into your app may do, particularly Objective-C. Could this a singleton (static top-level var) getting re-initialised on injection? Sorry but I can't offer much else in the way of information than this.
