### ISSUE TITLE
"Enable TDD" tutorial

### ISSUE THREAD

**Issue by wojciech-kulik** [johnno1962/InjectionIII#387]
Hi,

I'm trying to find some information about "Enable TDD" option and I don't see anything. I tried to investigate the code and from what I understood it should run XCTest with a similar name to the injected file. However, I enabled this option, modified sample file and tests haven't been launched.

I also tried legacy [InjectionTDD](https://github.com/polac24/InjectionTDD), and it works, but it has some problems caused by a lack of updates, I guess.

Can you provide some information on how to work with unit tests using InjectionIII? Thanks in advance.

**Comment by johnno1962** [comment]
@zenangst, do you know if this is still coded in?

**Comment by johnno1962** [comment]
Did I break it? https://github.com/johnno1962/HotReloading/blob/main/Sources/HotReloading/InjectionClient.swift#L157

**Comment by spnkr** [comment]
Is Enable TDD supposed to "immediately run your related unit tests, every time you save a file with ⌘+S"?

**Comment by johnno1962** [comment]
Apparently.

**Comment by johnno1962** [comment]
OK, I've looked at this a found a small problem with the Swift port. I'm looking at another issue but expect a new release later tonight.

**Comment by johnno1962** [comment]
New release available, https://github.com/johnno1962/InjectionIII/releases/tag/4.2.4 which restores "Enable TDD" which I broke during the port to Swift. If you feel it works OK, I'll promote it from pre-release to an actual release.

**Comment by wojciech-kulik** [comment]
It looks like it finds the test file, but it can't run it:
```
💉 Loading .dylib ...
💉 ⚠️ Could not locate compile command for /Users/wkulik/repositories/MyProject-iOS/MyProjectTests/States/CartState/CartStateTests.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
Try a build clean then rebuild to make logs available or
```

Any idea what I am doing wrong?

**Comment by johnno1962** [comment]
Have you run the tests at some point in the past? It needs to be in the project logs somewhere.

**Comment by wojciech-kulik** [comment]
Ok, I tried running tests first. Now I get a new error:
```
💉 Compiling /Users/wkulik/repositories/MyProject-iOS/MyProjectTests/States/CartState/CartStateTests.swift
💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/Users/wkulik/Library/Developer/CoreSimulator/Devices/CC5A3560-D389-4CA2-AF7A-229486035EB9/data/Containers/Data/Application/8DE0C082-B195-487A-85EC-B11B7A9F13A3/tmp/eval102.dylib, 0x0002): symbol not found in flat namespace '_$s8MyProjectTests10LoggerMockC13MyProjectLoggerTool0B8ProtocolAAWP'
💉 ⚠️ Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument. Rebuilding and re-running your project (without a build clean) can resolve this.
```

**Comment by wojciech-kulik** [comment]
I'm not sure if I understand. The host application for tests can't depend on frameworks, correct? We have a modular application with multiple frameworks.

**Comment by johnno1962** [comment]
TDD uses the functionality of injection that "injects" the test class by dynamically loading it and then runs it. If the test class references a symbol that is not part of the main application which is assumed to be a valid "host application" this is not possible. There are plenty of limitations to this feature like not being able to inject UI tests which is why it isn't emphasised in the documentation.

**Comment by wojciech-kulik** [comment]
Ok, thank you for the explanation :)

**Comment by johnno1962** [comment]
You're very brave, dusting off all these hidden nooks and crannies for me.

**Comment by AleMaMi** [comment]
Hello. I have tried the Enable TDD as well and with the same issue(s). Unfortunately, the "symbol" which is not part of application, is XCTAssert... function(s) (just comment assertions makes the injection work). As I know, XCTest.framework cannot be part of the application. Thus there is perhaps no way, how to use TDD feature - or I have no idea. Could you help?
And what relation exactly should be between tested object name and test name? For example SimpleOperationImpl file/class and SimpleOperationImplTest does not work - after Impl change I see injection of it, but no test run.
I am really curious about this TDD feature, I would like to use it, if there is a way how to make it work.

**Comment by johnno1962** [comment]
Hi, It's strange you're getting undefined symbols for XCTAsssert* and yet your XCTestCase subclass is able to load. InjectionIII lazily loads the XCTest framework into your application which should make this work. Can you uncomment your XCTestAssert*'s and show me the error please? Is this a macCatalyst application by any chance? Do you have an Xcode.app at the usual location in /Applications?

**Comment by AleMaMi** [comment]
You are right, the reason is not framework, my bad, I am sorry :-(
 
```
dlopen() error: dlopen(/var/folders/8q/__6hh2716sg59qjp026lhylw0000gq/T/com.johnholdsworth.InjectionIII/eval112.dylib, 0x0002): symbol not found in flat namespace '_$s6XCTest14XCTAssertEqual___4file4lineyxyKXK_xyKXKSSyXKs12StaticStringVSutSQRzlF'
💉 ⚠️ Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument. Rebuilding and re-running your project (without a build clean) can resolve this.
```

It is iOS app. Whole environment:
MacStudio with M1 Max
macOS Monterey 12.3.1
XCode 13.3.1
AppCode 2022.1

Target: iOS 15.4
Simulator iPhone 12 Max Pro, 15.4

Xcode is in usual path
```
xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

Rebuild and re-run does not help.

**Comment by johnno1962** [comment]
So this is in AppCode? That shouldn't make a difference though. Have you tried the TDD inside Xcode?

**Comment by AleMaMi** [comment]
Yes, it is in AppCode. But in Xcode it is the same. I have tried to tune project (because AppCode can run tests without link to project, Xcode needs proper set test target), but no change :-( May be I do something incorrectly or I have missed some necessary setup ...

Sequence (in Xcode):
1. Run tests
2. Run application
3. Change test source => injection error
4. Re-build app
5. Re-run app
6. Change test source => same injection error

I have created very simple project from Xcode template, modified directly by InjectionIII, and tried with this one (attached) and it is the same as for my other project. Injection works fine, e.g. for SwiftUI view. But if I change test (true/false), it produces error.


[InjectionExperiment.zip](https://github.com/johnno1962/InjectionIII/files/8608307/InjectionExperiment.zip)

**Comment by johnno1962** [comment]
I was grasping at straws there. I've built a new pre-release that loads the Swift XCTest dylib that seems to work with your example project: https://github.com/johnno1962/InjectionIII/releases/tag/4.2.6. Let me know if this fixes it.

**Comment by AleMaMi** [comment]
Yes! This one works. But version from AppStore doesn't (4.2.5).

**Comment by johnno1962** [comment]
Great!  I'll release 4.2.6 as it was such a small change and we'll update the App Store version in due course. Strange I hadn't noticed this before now - all the Swift specific XCTAssert* variations were not available. 

Thanks for taking the time to report this and preparing the example project.

**Comment by AleMaMi** [comment]
This is incredible and fantastic work! Thanks a lot for such tool!

Can I have other question? It is related to TDD ... how to properly name unit/unit test to trigger TDD feature? Because even the test is run now for its change, it is not run if tested unit is changed. See attached modified project.

If I change the MyUnit, it is properly injected and UI is changed. If I change MyUnitTest, it is properly injected and test is run. But test is not run if MyUnit is changed. Steps:

1. Enable TDD
2. Build project
3. Run unit tests
4. Run app
5. Change MyUnitTest + save
=> test is run
6. Change MyUnit + save
=> UI updated
=> test is NOT run

I guess I have wrong naming ... 

[InjectionExperiment.zip](https://github.com/johnno1962/InjectionIII/files/8608410/InjectionExperiment.zip)

**Comment by johnno1962** [comment]
I think the problem there is MyUnitTest.swift needed to be named MyUnitTests.swift. I've force pushed a new release 4.2.6 (build 6998) that only checks for the presence of "Test" in the file name instead of "Tests.".

**Comment by AleMaMi** [comment]
OK, I see, renaming to MyUnitTests works and the latest build works as well. Thanks a lot for your help!

Is there any way how to allow using special test frameworks with this feature? I usually use Quick framework for writing tests - of course, it is not loaded into application and it uses different test naming - and Nimble framework for matchers. I see it is tricky to inject tests into live app and this is just a question.

**Comment by johnno1962** [comment]
I guess you could try with a Debug config "Other Linker Flags" to link with these frameworks?

**Comment by johnno1962** [comment]
However, I remember there was a problem with Quick being written to only allow you to run a test once which I has a "workaround" for which is currently commented out. Let me know if it doesn't work and I may look at reinstating it.
```
//                if ( [newClass isSubclassOfClass:objc_getClass("QuickSpec")] )
//                [[objc_getClass("_TtC5Quick5World") sharedWorld]
//                setCurrentExampleMetadata:nil];
```

**Comment by AleMaMi** [comment]
Thanks for tips. I will need more time to experiment with this, because Quick requires XCTest and this one cannot be added to App target. And I have very little experience with such low-level configuration of project.

**Comment by johnno1962** [comment]
Take all the time you need. It could be as simple as adding "Quick.framework" to "Other Linker Flags". If there was any way you could update your test project to include a Quick and Nimble test I can look at it for you.

**Comment by AleMaMi** [comment]
Here is updated previous project - added SPM dependency for Quick and Nimble and added test(s) based on Quick and Nimble. 
[InjectionExperiment.zip](https://github.com/johnno1962/InjectionIII/files/8612976/InjectionExperiment.zip)

**Comment by johnno1962** [comment]
Thanks very much for the test project. It isn't pretty what I've had to do but I think I can support Quick Spec injection in a new version of the 4.2.6 pre-release. No need to change your project and you should be able to inject specs provided the filename contains "Spec." (which is is the flag used to dynamically load what is required by Quick). There are bound to be some rough corners to round off but let me know how this version is looking.

**Comment by AleMaMi** [comment]
Are you kidding me? This is incredible! It seems it works. There are some "warnings" in some cases, but it definitely works. I can provide some testing, if you want, it will be very small price for such amazing work. I am going to prepare some scenarios and I will send you the results ASAP. Is it OK to continue posting to this closed issue?

**Comment by johnno1962** [comment]
Yeah, I'm pretty please how it turned out :) In effect it injects all of Quick each time you run a test which makes sure it gets reset so you can re-run tests, inject the thing you're testing etc. Sorry about all the warnings about duplicate classes which there isn't much I can do about but at least the last thing you see is generally the test result. If you don't come back with any problems I'll merge the branch, rebuild and promote the release candidate to the main release. Thanks for bringing this up, I think this will be a very popular feature!

**Comment by wojciech-kulik** [comment]
If it is going so well then maybe there is some way to make it work for a modular application that has code divided into frameworks :D? After all, everything is within the same project.

**Comment by johnno1962** [comment]
It's not working for modular applications? Have you added -Xlinker -interposable to your frameworks as well?

**Comment by wojciech-kulik** [comment]
I'm not sure if it is because of modularity but I get every time errors like this:
```
💉 Interposed 7 function references.
💉 Injected type #1 'MyProject.MyProjectAvailability'
💉 Injected type #2 'MyProject.MyProjectProvider'
💉 ⚠️ Could not locate compile command for /Users/wkulik/repositories/MyProject-iOS/MyProjectTests/Providers/MyProjectProviderTests.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
Try a build clean then rebuild to make logs available or
consult: ...
```

I just edit files from the main app target.

**Comment by johnno1962** [comment]
But have you run that test at some point in the past? How to compile the source needs to be in the build logs.

**Comment by wojciech-kulik** [comment]
Oops, I forgot this time because I cleaned the project... but after running tests I get different errors like this one: https://github.com/johnno1962/InjectionIII/issues/387#issuecomment-1106583597

It looks like it has some problems with mocks? We are using sourcery to generate mocks.

**Comment by wojciech-kulik** [comment]
Interesting! Maybe we could move them to the main project and wrap them with `#if`. I will check this out. Thank you for some guidance.

**Comment by johnno1962** [comment]
@AleMaMi, if you're doing more testing I've merged everything and updated the 4.2.6 release candidate (build 7005) ready for release tomorrow. Let me know if you find anything that doesn't work. Cheers.

**Comment by AleMaMi** [comment]
It looks fine to me. I have just noticed this one: very first change of test subject (MyUnit) after run triggers tests, but with "previous" version of the unit. Following save and all next changes works fine. Steps (with last version of test project):

0. MyUnit does not pass tests to see test failure
1. Run app
2. Change MyUnit to produce failure with different value
3. Save
=> it runs tests, tests fail but messages show original failure without change
4. Save again
=> it runs tests, tests fail now with proper failure

Since second save the tests works correctly. I hope it helps.

**Comment by johnno1962** [comment]
WOW, that's what I call a good catch! Perusing it led to a super subtle bug where a file referring to something that has has been interposed but doesn't itself contain interposing fails to apply the other file's interpose; I digress. I've uploaded a new build 7006 which should resolve this problem by removing a line of code for an "optimisation".

**Comment by AleMaMi** [comment]
Respect! Thanks a lot for your help. This tool is incredible. Honestly, great job.

**Comment by AleMaMi** [comment]
It seems Cocoapods differently handle libraries/frameworks. Please, see attached project - it is like the previous one, but dependency is handled by Cocoapods. Just for your info, I do not want to bother you. I am going to try to add as linker option, but you are much more experienced. (Just to explain: I use SPM and Cocoapods on different projects)

[InjectionExperimentCocoapods.zip](https://github.com/johnno1962/InjectionIII/files/8643011/InjectionExperimentCocoapods.zip)

**Comment by johnno1962** [comment]
I'm sorry but I have very little interest in supporting CocoaPods which I do not have installed. You might have more success supporting Quick yourself as I originally suggested by adding "-framework Quick -framework Nimble" to other linker flags for a CocoaPods project but that will likely leave the problem of tests only being able to run once.

**Comment by AleMaMi** [comment]
Fair enough. To be honest, my long term goal is to replace Cocoapods by SPM, thus I am happy with it as it is. Thanks a lot for your support.
