### ISSUE TITLE
Error opening input file 

### ISSUE THREAD

**Issue by waltcow** [johnno1962/InjectionIII#39]
Hi, I am using `InjectionIII` app store version

The `GettingStart` project work fine in my xcode

but when I use in my project, something seems wrong

the file and directory is exist

```sh
*** Compiling /Users/waltcow/Swift/Inner/Classes/Modules/Tweet/ViewController/TweetDetailsViewController.swift ***
*** Re-compilation failed (/Users/waltcow/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
<unknown>:0: error: error opening input file '/Users/waltcow/Swift/Inner/Classes/Modules/Settings/ViewController/UserNameEditViewController.swift' (No such file or directory)
 ***

```

**Comment by johnno1962** [comment]
Normally this is because the letter case (A vs. a) doesn’t match in the path somewhere.

**Comment by waltcow** [comment]
Can you give me a little more hints 😅, how can I find out which path is unmatched ?

**Comment by waltcow** [comment]
After I rename `UserNameEditViewController.swift` file to another name,
Problem solved. it's so weird 😭
