### ISSUE TITLE
Cannot run on mac Catalyst

### ISSUE THREAD

**Issue by darioroa** [johnno1962/InjectionIII#390]
Adding the project to a Catalyst project after checking "Disable Library Validation" does not work. 
I have tried with the `macOSInjection.bundle` and `maciOSInjection.bundle`. The former allows the initial `💉 InjectionIII connected` message, but when updating a file produces this error: 

```
ld: building for macOS, but linking in object file built for Mac Catalyst, file '/var/folders/1p/nyb_m6b154g_fhd38h9qvldm0000gn/T/com.johnholdsworth.InjectionIII/eval101.o' for architecture arm64
```

**Comment by johnno1962** [comment]
Hi, those were good guesses. any chance you could post a simple example project so I could research how to differentiate between the two and try to add support for this case. It may be quite simple.

**Comment by darioroa** [comment]
Absolutely! Here is a sample project: 
[Link to project](https://github.com/darioroa/Catalyst-Inject-Sample)

**Comment by darioroa** [comment]
A few more insights: 
I assume the way to solve this mostly depends on building the bundle for catalyst. 

I have tried the following in `build_bundles`:

```sh
"$DEVELOPER_BIN_DIR"/xcodebuild SYMROOT=$SYMROOT ARCHS="$ARCHS"  -config $CONFIGURATION -target InjectionBundle PRODUCT_NAME="macCatalystInjection" -destination 'platform=macOS,variant=Mac Catalyst'  &&
rsync -au $SYMROOT/$CONFIGURATION/macCatalystInjection.bundle "$CODESIGNING_FOLDER_PATH/Contents/Resources" &&
```

But the behavior seems to be the same as the aforementioned `macOSInjection.bundle`.

**Comment by johnno1962** [comment]
Thanks very much for the example project. I managed find a way to get it going with a relatively minor change. Download the new release https://github.com/johnno1962/InjectionIII/releases/tag/4.2.4 and if you use the macOSInjection.bundle and it should work now for Catalyst.

**Comment by darioroa** [comment]
Works as expected, thank you!

**Comment by johnno1962** [comment]
Hey Dario, Very impressed with your tweet, in fact amazed InjectionIII was up to it. You mention I your post Inject is loading the wrong injection bundle for Catalyst apps which I don't know the way to detect in Swift code. Can you suggest how the following code should be modified?
```Swift
private var loadInjectionImplementation: Void = {
#if os(macOS)
    let bundleName = "macOSInjection.bundle"
#elseif os(tvOS)
    let bundleName = "tvOSInjection.bundle"
#elseif targetEnvironment(simulator)
    let bundleName = "iOSInjection.bundle"
#else
    let bundleName = "maciOSInjection.bundle"
#endif // OS and environment conditions
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/" + bundleName)?.load()
}()

**Comment by darioroa** [comment]
> Hey Dario, Very impressed with your tweet, in fact amazed InjectionIII was up to it. You mention I your post Inject is loading the wrong injection bundle for Catalyst apps which I don't know the way to detect in Swift code. Can you suggest how the following code should be modified?
 
I always use `targetEnvironment(macCatalyst)` for this. The following should work:

```swift
private var loadInjectionImplementation: Void = {
#if os(macOS)
    let bundleName = "macOSInjection.bundle"
#elseif os(tvOS)
    let bundleName = "tvOSInjection.bundle"
#elseif targetEnvironment(simulator)
    let bundleName = "iOSInjection.bundle"
#elseif targetEnvironment(macCatalyst)
    let bundleName = "macOSInjection.bundle"
#else
    let bundleName = "maciOSInjection.bundle"
#endif // OS and environment conditions
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/" + bundleName)?.load()
}()
```

**Comment by johnno1962** [comment]
Thanks Dario, I've raised a PR to use your fix in the Inject repo.

**Comment by johnno1962** [comment]
Hey, just following up on the problems you had running "iPad apps on the Mac". Something has changed since I looked at this (https://github.com/johnno1962/InjectionIII/issues/284) and it is no longer possible to load the maciOSInjection.bundle directly due to sandboxing. 

You can get around this by using the DYLD_INSERT_LIBRARIES environment variable with the path to the bundle executable /Applications/InjectionIII.app/Contents/Resources/maciOSInjection.bundle/maciOSInjection. You still need the build phase to resign the bundle and write a default to control the signing identity for the injection (See the issue for a twist on this if you've ever used the App Store version of InjectionIII.)
