### ISSUE TITLE
SImulator is not updating 

### ISSUE THREAD

**Issue by Maaz-Surti** [johnno1962/InjectionIII#392]
The code is being injected but the simulator is not updating. I have seen a similar question asked here but I don't know what calling @objc func injected() means. There is no such function when I try to autocomplete. Do I have to create one? If yes, then how ? 

These are the logs: 
💉 Loaded .dylib - Ignore any duplicate class warning ⬆️
💉 Patched class 'Netflix.DownloadsViewController' (0,3)
💉 Interposed 1 function references.

**Comment by johnno1962** [comment]
Hi, Its difficult to say without more information. Are you sure the new version of the code is being executed? This is what you use the `injected()` method for - to reload/reconfigure the view controller with the new code. It needs to be of the form:
```Swift
@objc func injected() {
    print("I've been injected!")
    self.reconfigure()
}
