### ISSUE TITLE
`No such file or directory` for file that's been removed

### ISSUE THREAD

**Issue by everlof** [johnno1962/InjectionIII#393]
I'm running the latest version of `InjectionIII` (according to update check).

I inject using: 
```
#if DEBUG
if UserDefaults.standard.bool(forKey: "LiveReload") {
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()
}
#endif
``` 

It's been working out great. However, now I rebased my branch and I get: 

```
💉 ⚠️ Re-compilation failed (see: /Users/..../Developer/CoreSimulator/Devices/4D65F726-460C-4C93-B56C-084EC06B9E18/data/Containers/Data/Application/920CD13C-4F83-4937-B915-2ABD5BE5BFD1/tmp/command.sh)
<unknown>:0: error: error opening input file '/Users/.../SomeSwitch.swift' (No such file or directory)
```

When I rebased, I got a change that removed `SomeSwitch.swift` and I can't find any references to `SomeSwitch.swift`anywhere.

If I open `/Users/david/Library/Developer/CoreSimulator/Devices/4D65F726-460C-4C93-B56C-084EC06B9E18/data/Containers/Data/Application/920CD13C-4F83-4937-B915-2ABD5BE5BFD1/tmp/command.sh` and then open the `filelist.txt` that's part of that I get like 1022 files. But in my project I have 1024 files. So it feels like Injection's file-list is out of sync with the Xcode-project I'm building?

**Comment by johnno1962** [comment]
Hi, Sounds like it might be time to do a "Project/Clean Build Folder", rebuild then try again. Let me know if this doesn't fix it.

**Comment by everlof** [comment]
Hi, thanks for the swift response! Unfortunately that didn't solve it for me, still the same issue, what else might I try?

**Comment by everlof** [comment]
Okay, now it suddenly started working again, perhaps the clean did it, but just needed some time 🤷‍♂️

Thank you anyway for a great product!

**Comment by everlof** [comment]
Spoke too soon. Everything started up fine, just the re-compilation that failed, which I hadn't triggered yet (sorry).

**Comment by johnno1962** [comment]
So you're up and running now?

**Comment by everlof** [comment]
> So you're up and running now?

No, I just though I was, but still has the same issue. Gonna try to nuke the whole DerivedData manually!

**Comment by everlof** [comment]
Yeah, still get the exact same error after nuking he "DerivedData" folder with `rm -rf DerivedData`. I wonder if I've set it up wrong somehow? Or what it might be? I've verified that the file isn't part of "Compile Sources" build-phase.

**Comment by everlof** [comment]
It's just the strangest thing. It's still not working. First I tried `rm /tmp/eval_builds.plist` but didn't solve it. Next I tried reboot, but still the same error.

**Comment by everlof** [comment]
But `/tmp/eval_builds.plist` isn't recreated yet, could that give a hint?

After removing it and rebooting: `cat: /tmp/eval_builds.plist: No such file or directory`

**Comment by johnno1962** [comment]
/tmp is cleared when you reboot so that was the other way of clearing it out. It gets created when you inject something and is a fallback for when the logs get cleared out but Xcode. Still no luck then? It sounds like quite a complex project. Any chance you could mail though the logs saved from the build tab to github at johnholdsworth.com?

**Comment by everlof** [comment]
Yeah, still no luck, unfortunately. I will verify with my project that it's okay to share the logs, and if so, email them.

**Comment by johnno1962** [comment]
Thanks. Is the error still the same? Referring to a file that is no longer in the project? All I can suggest is quit Xcode, nuke project DerivedData, reboot, nuke project DerivedData,  restart InjectionIII, restart Xcode in that order. Are you sure you have the right project directory/file selected?

**Comment by everlof** [comment]
Yes, the error is still the same. Just tried the steps, still the same.

Where can I see what folder is selected? The output in the console points to the correct folder and `xcodeproj`:

```
💉 InjectionIII connected /Users/.../.../A..ch.xcodeproj
💉 Watching files under /Users/.../.../
```

What does the color of the status-bar icon convey?

**Comment by everlof** [comment]
Okay! I actually solved it now!

I have this setting below, and I just kept erasing "DerivedData" relative to the project folder in the project I'm working on. But realised perhaps ~/Library/Developer/Xcode/DerivedData need to be cleaned as well? And yes erasing `~/Library/Developer/Xcode/DerivedData` solved it. I think I pretty recently switched from `Default` to `Relative` and some artefact from `~/Library/Developer/Xcode/DerivedData` was still messing with the build. 

<img width="679" alt="Screenshot 2022-05-04 at 22 13 07" src="https://user-images.githubusercontent.com/1321434/166818162-0f6be432-8952-4baa-b748-2976e56687e4.png">

**Comment by johnno1962** [comment]
Hallelujah! In theory it should choose either relative or the main DerivedData on the basis of which has the most recently modified logs so something is not quite right there but if you're up and running again that's great! The icon colours are: Blue - disconnected, Orange collected but idle, Green compiling/injecting, Yellow - an error.

**Comment by everlof** [comment]
Btw, this just happen to me again, but solved it the same way as last time, rm the previous location of DerivedData

**Comment by johnno1962** [comment]
Interesting, it shouldn't be using both. Are you still using device injection. If not, quit the app and start using "standalone" injection where this shouldn't be a problem.

**Comment by everlof** [comment]
I recently had problems launching Xcode, due to a kotlin plugin, and to
debug that I erased the Xcode's plist with settings. That got me back to
the "Default" location again, and then I relatively fast changed it into
"Relative", but there was still dontent in the
~/Library/Developer/Xcode/DerivedData
and that was the problem!

I used simulator injection here

Den fre 15 sep. 2023 kl 13:00 skrev John Holdsworth <
***@***.***>:

**Comment by johnno1962** [comment]
I'll see if I can replicate this tomorrow but I remember testing this at the time. Why is it important to you to be able to use a relative DerivedData path? It is scarcely supported.

**Comment by everlof** [comment]
How do you mean it’s scarcely supporter?

I like it because it’s just easier to nuke derived data without any problems then. Just ‘rm -ref DerivedData’ from the terminal in the repo I have a fresh slate!

**Comment by johnno1962** [comment]
Well in theory it's debugged and supported and I've just tested it but you seem to have found a way for it not to work. I can TeamView if you like?

**Comment by everlof** [comment]
Alright. Thanks for the offer, but it’s working right now, after I removed the old location of deriveddata. If it is of any interest I can see if I can reproduce it. But I agree that the setting isn’t widely used so maybe it’s fine having it as it is?

**Comment by johnno1962** [comment]
If you not injecting to a device I recommend quitting the app using "standalone" injection as you shouldn't encounter this problem.

**Comment by johnno1962** [comment]
I've pushed a new build of the 4.7.4 release candidate that should resolve this for you. A legacy fallback for the DerivedData path became an override with a change a year ago. Let me know if this resolves the problem you've been seeing.

**Comment by gonchar** [comment]
I just had the same issue.

`🔥 Compiling $PATH_TO_SWIFT_FILE_I_JUST_SAVED$.swift
🔥 ⚠️ Re-compilation failed (see: /var/folders/j1/gf6bz7c52rq7np1h92q7whc40000gn/T/command.sh)
<unknown>:0: error: error opening input file '/Users/gonchar/Documents/work/$PATH_TO_SWIFT_FILE_I_REMOVED_SOME_TIME_AGO$.swift' (No such file or directory)
<unknown>:0: error: error opening input file '/Users/gonchar/Documents/work/$PATH_TO_SWIFT_FILE_I_REMOVED_SOME_TIME_AGO$.swift' (No such file or directory)`


@johnno1962 maybe if you make it that way that you just don't compile files that are not present? when file rename/remove happens it is quite painful to clear derived data because SPM need some time resolve again, and requires Xcode reboot

**Comment by johnno1962** [comment]
InjectionIII uses a cache which should clear out when you reboot or `rm /tmp/*builds.plist`. You shouldn't need to remove derived data, a "Clear Build Folder" should remove previous build logs which is where there shadow files are going from.
