### ISSUE TITLE
Dose InjectionIII App support on-device for now?

### ISSUE THREAD

**Issue by tinymind** [johnno1962/InjectionIII#395]
Hi, thanks for the great projects.
I'm a little confuse, since I saw this PR([On device injection](https://github.com/johnno1962/InjectionIII/pull/371)) and this commit([Remove on-device injection from main app for now](https://github.com/johnno1962/InjectionIII/commit/ee774ff4db803316bc9409b126dc32e2d7338744)).

So, dose InjectionIII App support on-device for now? Or just the HotReloading Swift Package supports on-device injection?
I did try the released InjectionIII App on device, but it did not work.

I want to use InjectionIII App because Swift Package can't config for debug mode only.

Thanks for your time.

**Comment by johnno1962** [comment]
Hi, the InjectionIII app could easily support on device injection but I decided against it as it would need to open a network port to do so which may confuse people. What the final configuration will be depends on what surprises Xcode 14 has in store for the project and how I'll have to respond tactically. For now on-device injection is only supported using the HotReloading project and running a daemon version of the app from a "Build Phase".

**Comment by tinymind** [comment]
Got it, thanks and looking forward to your update.
