### ISSUE TITLE
Adjust the "Header Search Paths" in your project's Build Settings

### ISSUE THREAD

**Issue by mafiaIOS** [johnno1962/InjectionIII#397]
💉 Compiling xxxxxxxx.swift
💉 ⚠️ Re-compilation failed (see: /var/folders/zf/25qh27sj4lq8wl74svnwx1n40000gn/T/com.johnholdsworth.InjectionIII/command.sh)
xxxx/xxx-Bridging-Header.h:18:9: error: 'AlicloudHTTPDNS/AlicloudHttpDNS.h' file not found
#import <AlicloudHTTPDNS/AlicloudHttpDNS.h>
        ^
<unknown>:0: error: failed to import bridging header '/xxxxxxxx/xxxx-Bridging-Header.h'
💉 ⚠️ Adjust the "Header Search Paths" in your project's Build Settings

The bridge file has already imported this”#import <AlicloudHTTPDNS/AlicloudHttpDNS.h>“， what means does this "Adjust the "Header Search Paths" in your project's Build Settings" ?? somebody could help me ?

**Comment by johnno1962** [comment]
Hi, This is because injection does not necessarily compile in the same working directory. Find where AlicloudHTTPDNS/AlicloudHttpDNS.h is and add that directory to the "Header Search Paths"

**Comment by mafiaIOS** [comment]
I delete the import AlicloudHTTPDNS/AlicloudHttpDNS.h  in the bridge file , then fixed the error.
