### ISSUE TITLE
SwiftUI: Fatal error: No ObservableObject of type * found

### ISSUE THREAD

**Issue by exevil** [johnno1962/InjectionIII#398]
Hi again, John!

I probably found another bug, didn't find any solution in the resolved issues though. For some reason, it seems that Environment Objects are missing when injection in SwiftUI contexts takes place:

![CleanShot 2022-05-17 at 18 01 44@2x](https://user-images.githubusercontent.com/1979535/168870081-9b059584-642b-447c-81fb-0263058a2421.jpg)
> Thread 1: Fatal error: No ObservableObject of type StateManager found. A View.environmentObject(_:) for StateManager may be missing as an ancestor of this view.

Here's a super simple example project that reproduces the issue constantly for me: [InjectionBug.zip](https://github.com/johnno1962/InjectionIII/files/8710275/InjectionBug.zip)

Can't stop thanking you for your help and the great app.

Cheers!

**Comment by johnno1962** [comment]
Hi, thanks for your example project. I was able to get it injecting by moving the @ObservedObject into the InnerView. Seems like causing the outer ContentView to re-render is a no-no when there is an environmentObject(). I may look at it some more but this is taking me out of my SwiftUI "comfort zone".

**Comment by exevil** [comment]
You're absolutely right, separating files did help.

Thanks a lot, John.
