### ISSUE TITLE
Xcode9.4.1,swift4.1, there is no effect

### ISSUE THREAD

**Issue by huayingxiong** [johnno1962/InjectionIII#40]
Hello, I added the following code in the project
AppDelegate.swift
        #if DEBUG
        Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()
        #endif
ViewController.swift
      func injected() {
        viewDidLoad()
    }
Execute "CTRL" +"=" without any response. But I have no problem in the OC project. Could you give me some advice?

**Comment by johnno1962** [comment]
"CTRL" +”=“, was the old version of injection. With the App Store version you need only save the file if you have selected the correct project directory.

**Comment by zenangst** [comment]
Great news @huayingxiong, we have restored the injecting with ctrl+= functionality. It is currently on the `master` branch and not available in the Mac App Store yet but we are working on a version that we should be shipping very soon.

**Comment by zenangst** [comment]
@huayingxiong did you manage to get it working?

I see from your example that your `injected` method is missing `@objc`.
It needs to visible in Objective-C runtime for injection to pick up the class.
