### ISSUE TITLE
Inner classes can be added but new properties cannot be added

### ISSUE THREAD

**Issue by MyronX** [johnno1962/InjectionIII#402]
Using InjectionIII for the first time

When I add a property it crashes after re-running the app, but adding an inner class works fine.
Wondering if this is a special design?
Or is there some reason why I can't add new properties?

**Comment by johnno1962** [comment]
HI, It's strange your app should crash after re-running it after adding a property. You certainly can't add a property across an injection though as the memory model for the type changes. Inner classes are effectively a new type that doesn't affect the memory model of the outer type so that's fine.

**Comment by MyronX** [comment]
Thanks a lot, but I still have a question. method_list is a readable and writable space, why can't it be added to method_list after adding methods?
When I add a new code I do ctrl+s.
Then reinitialize InjectionViewController, using `[self addfunc]` will cause the app to crash, but `[[[InjectionViewController alloc] init] addfunc]` is executable. Is this as expected?
like this
Before
```
@implementation InjectionViewController

- (void)testFunc {
    // do something

}
```

After
```
@implementation InjectionViewController

- (void)testFunc {
    // do something
    
    [self addFunc]; // If do this, the app will crash
    
    [[[InjectionViewController alloc] init] addFunc]; // if do this, printf the log and no carsh
    
}



- (void)addFunc {
    NSLog(@"add a new func");
}
```

**Comment by johnno1962** [comment]
You're exploring the outer reaches of what is possible there. The way InjectionIII is coded it's not possible to add a method to an instance of an existing Objective-C class on the fly. The reason why it works if you create a new instance is that it uses the injected version of the class that already has the new method. In general adding new methods over the course of an injection is not supported.

**Comment by MyronX** [comment]
#363 When I saw this issue, I thought that OC could not support such a feature, but now it seems that the dynamic addition method is feasible

**Comment by johnno1962** [comment]
It is technically feasible in terms of the runtime, it's just the current implementation of swizzling in InjectionIII doesn't support it. I'll look at seeing if there is a way to remove a sanity check which is stopping it working.

**Comment by johnno1962** [comment]
OK, I've rolled a new pre-release https://github.com/johnno1962/InjectionIII/releases/tag/4.3.0 if you want to see if it supports adding methods for Objective-C which by rights really should work. Can you try it out for me please?
