### ISSUE TITLE
Can I change Xcode Path ?

### ISSUE THREAD

**Issue by X901** [johnno1962/InjectionIII#403]
Hi

I have multiple Xcode versions
I want to use it with different name
like **Xcode_13.1**
Is it possible to change the path of Xcode ?
BTW I cannot change the Xcode name!

**Comment by johnno1962** [comment]
Hi, a symbolic link works fine. It gives you a warning but the Xcode path may not be important.

**Comment by X901** [comment]
I tried I got this error

Also I tried HotReloading , but I got same error

`Linking failed : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang: No such file or directory`

**Comment by johnno1962** [comment]
OK, you'll be needing a symbolic link then. I'll look into whether this can be avoided.

**Comment by X901** [comment]
Thank you it working
