### ISSUE TITLE
Can I use it with subproject

### ISSUE THREAD

**Issue by haoboxuxu** [johnno1962/InjectionIII#404]
I 'Open project' to shell project and subproject, I 'Add Directory' to location of subproject, the injection did't work. Not giving me any error, the icon turned green but did't not turn back to orange after I pressed cmd+s (it do wokrs on my demo project without any subproject)

**Comment by johnno1962** [comment]
Hi, It's easier if you don't use 'Add Directory' any more as you can select the root directory containing all sources or even you home directory and then the project file if it is under that directory. I don't know why injection is hanging but this would be the first thing to try.
