### ISSUE TITLE
Mind me to contribute this to homebrew as a cask?

### ISSUE THREAD

**Issue by xiaohanyu** [johnno1962/InjectionIII#405]
Hey @johnno1962,

As the title, would you mind me to contribute this project to homebrew as a cask?

If you don't mind I can propose a PR to homebrew to make InjectionIII available from homebrew, for better distribution.

Thank you!

**Comment by johnno1962** [comment]
What would you see are the problems with the existing distribution methods: AppStore or downloading the zip from GitHub? How would they be solved by a homebrew cast? My first reaction would be to ask you not to create another mean people have to get InjectionIII that I have to support if it isn't absolutely necessary.

**Comment by xiaohanyu** [comment]
Hi,

App Store distribution is good enough just one click. 

While downloading the zip from Github is a bit longer but acceptable. 

I would say that yes it isn't absolutely necessary to always ask people to get InjectionIII from App Store or github releases. However, by making it available via homebrew, it would more easier to onboard people, just one line of command: `brew install injectioniii`.

As homebrew community rule said, the PR would be [rejected](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md?plain=1#L122) if "the author has [specifically asked us not to include it](https://github.com/Homebrew/homebrew-cask/pull/5342)."

So I would like ask for your thoughts first.

**Comment by johnno1962** [comment]
Homebrew would be building from source though right? I really only want to support binary releases apart from the HotReloading variation. It's a tricky build. I am worried if we create a cask it will be difficult for me to update.

**Comment by xiaohanyu** [comment]
Hey,

> Homebrew would be building from source though right? 

No this is not exactly what we had to provide for homebrew. 

Actually homebrew support special packages called cask, where you can just put a download link there and it can install '.app' format packages via `brew install xxx`.

Here is a sample cask app: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lookin.rb, so basically we can follow the same way to onboard injectioniii to homebrew cask and maintaining cost for would be pretty low as we just need to update version numbers periodically.

Hope it helps to clarify on this.

**Comment by johnno1962** [comment]
But the cask would be to download a specific GitHub release version and could fall out of sync with the most recent version I released unless I ask you to update it? I'd rather not introduce these extra variables and complexity and things I have to think about. Some people have a preference for a command line install but I don't see downloading a zip file as a barrier to adoption. Thanks again for the idea, but please don't do this.

**Comment by xiaohanyu** [comment]
Roger that, OK then, understand and appreciate.
