### ISSUE TITLE
💉 ⚠️ Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument or perhaps an XCTest that depends on code not normally linked into your application. Rebuilding and re-running your project (without a build clean) can resolve this.

### ISSUE THREAD

**Issue by jinliyuelong** [johnno1962/InjectionIII#407]
My project is a swift project and the following error occurs frequently

💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/Users/xxx/Library/Developer/CoreSimulator/Devices/880C43E1-83CE-4DDA-983D-09ADA468C884/data/Containers/Data/Application/2BCA73F6-F9DF-42C1-AD31-EB86F2D2CBBD/tmp/eval103.dylib, 0x0002): symbol not found in flat namespace '_$s18xxxxx11xxxxxn'
💉 ⚠️ Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument or perhaps an XCTest that depends on code not normally linked into your application. Rebuilding and re-running your project (without a build clean) can resolve this.

one build has two targets,namespace '_$s18xxxxx11xxxxxn' shows the other one

**Comment by johnno1962** [comment]
Hi, not quite enough information there. Are you able to tell me the actual symbol name or email it to me at github at johnholdsworth.com? This only occurs when you inject a particular file? Can you email me that file?

**Comment by jinliyuelong** [comment]
Sometimes when I restart Xcode, there is no problem again, so strange！ symboe name has been sent to you

**Comment by johnno1962** [comment]
InjectionIII does what is called an "unhide" when you get this error which is why this error goes away until you next edit the file containing the type associated with this symbol. Is this enough for you to be able to keep working?
