### ISSUE TITLE
It can be used at first, but it can't be used later.please help！

### ISSUE THREAD

**Issue by Charles2016** [johnno1962/InjectionIII#408]
It can be used at first, but it can't be used later.As soon as the project is saved, an error is reported, and the reason can't be found.

💉 InjectionIII connected /Users/charles2022/Documents/GitHub/NewProject-master/NewProject.xcworkspace
💉 Watching files under /Users/charles2022/Documents/GitHub/NewProject-master

💉 ⚠️ Error reading /var/folders/5t/jt0_210j3kxftxbn6sfnjgpr0000gn/T/com.johnholdsworth.InjectionIII/eval101.sh, scanCommand: /var/folders/5t/jt0_210j3kxftxbn6sfnjgpr0000gn/T/com.johnholdsworth.InjectionIII/command.sh

command.sh：
# search through build logs, most recent first
cd "/Users/charles2022/Library/Developer/Xcode/DerivedData/NewProject-gsiklciboqzyjphepbccrbuqcykt/Logs/Build" &&
for log in `ls -t *.xcactivitylog`; do
    #echo "Scanning $log"
    /usr/bin/env perl "/var/folders/5t/jt0_210j3kxftxbn6sfnjgpr0000gn/T/com.johnholdsworth.InjectionIII/eval105.pl" "$log" >"/var/folders/5t/jt0_210j3kxftxbn6sfnjgpr0000gn/T/com.johnholdsworth.InjectionIII/eval105.sh" 2>"/var/folders/5t/jt0_210j3kxftxbn6sfnjgpr0000gn/T/com.johnholdsworth.InjectionIII/eval105.err" && exit 0
done
exit 1;

eval101.pl:
use JSON::PP;
use English;
use strict;

# line separator in Xcode logs
$INPUT_RECORD_SEPARATOR = "\r";

# format is gzip
open GUNZIP, "/usr/bin/gunzip <\"$ARGV[0]\" 2>/dev/null |" or die;

# grep the log until there is a match
my ($realPath, $command);
while (defined (my $line = <GUNZIP>)) {
    if ($line =~ /^\s*cd /) {
        $realPath = $line;
    }
    elsif ($line =~ m@ -(?:primary-file|c(?<! -frontend -c)) (?:\\?\"(\Q/Users/charles2022/Documents/GitHub/NewProject-master/NewProject/Views/Home/Controllers/HomeVC.m\E)\\?\"|(\Q/Users/charles2022/Documents/GitHub/NewProject-master/NewProject/Views/Home/Controllers/HomeVC.m\E)) @oi and $line =~ " x86_64") {
        # found compile command
        # may need to extract file list
        if ($line =~ / -filelist /) {
            while (defined (my $line2 = <GUNZIP>)) {
                if (my($filemap) = $line2 =~ / -output-file-map ([^ \\]+(?:\\.[^ \\]+)*) / ) {
                    $filemap =~ s/\\//g;
                    my $file_handle = IO::File->new( "< $filemap" )
                        or die "Could not open filemap '$filemap'";
                    my $json_text = join'', $file_handle->getlines();
                    my $json_map = decode_json( $json_text, { utf8  => 1 } );
                    my $filelist = '/var/folders/5t/jt0_210j3kxftxbn6sfnjgpr0000gn/T/com.johnholdsworth.InjectionIII//filelist.txt';
                    my $swift_sources = join "\n", keys %$json_map;
                    my $listfile = IO::File->new( "> $filelist" )
                        or die "Could not open list file '$filelist'";
                    binmode $listfile, ':utf8';
                    $listfile->print( $swift_sources );
                    $listfile->close();
                    $line =~ s/( -filelist )([^ \\]*(?:\\.[^ \\]*)*)( )/$1$filelist$3/;
                    last;
                }
            }
        }
        if ($realPath and (undef, $realPath) = $realPath =~ /cd (\"?)(.*?)\1\r/) {
#           print "cd \"$realPath\" && ";
        }
        # find last
        $command = $line
        #exit 0;
    }
}

if ($command) {
    print $command;
    exit 0;
}
# class/file not found
exit 1;

**Comment by johnno1962** [comment]
Hi, can you move your project out of the Documents folder. This can cause problems.

**Comment by Charles2016** [comment]
> Hi, can you move your project out of the Documents folder. This can cause problems.

I tried, but it didn't work. I don't think this is a permission problem, but I don't know what the problem is just based on the wrong log!

**Comment by Charles2016** [comment]
I sent the project to my colleague for operation. There was no problem on his side, and I reported an error on my side. Before, hot updates were available on my side. I don't know what has been changed recently. It doesn't work on my computer. I deleted the app and reinstalled it. It's very strange. Can you see the problem from the wrong log?

**Comment by Charles2016** [comment]
> Hi, can you move your project out of the Documents folder. This can cause problems.

by the way，my project url is https://github.com/Charles2016/InjectionIIIDemo。

**Comment by johnno1962** [comment]
If it is working for your colleague as you say it seems to be looking at the wrong derived data directory for logs. Can you run the command.sh file it mentions and let me know if it gives an error?

**Comment by Charles2016** [comment]
I can't run command.sh，it seems just print the error log. the content of <command.sh and eval101.pl>  at the first question i write.

**Comment by johnno1962** [comment]
Have you tried:
```
$ bash /var/folders/5t/jt0_210j3kxftxbn6sfnjgpr0000gn/T/com.johnholdsworth.InjectionIII/command.sh ?

**Comment by Charles2016** [comment]
I run the command.sh，it tips me to download the new release，download it and solve the problem！thank you for your help！
💉 Compiling /Users/charles2022/Documents/GitHub/InjectionIIIDemo/InjectionIIIDemo/ViewController.m
💉 ⚠️ Codesign failed. If you are using macOS 11 (Big Sur), Please download a new release from https://github.com/johnno1962/InjectionIII/releases

**Comment by johnno1962** [comment]
👍
