### ISSUE TITLE
No such module 'SwiftUIX'

### ISSUE THREAD

**Issue by lockieluke** [johnno1962/InjectionIII#411]
InjectionIII might not be compatible with SwiftUIX

![image](https://user-images.githubusercontent.com/25424409/180643292-13ff3961-4d8b-4559-88cc-875c4ecfaa8a.png)

**Comment by johnno1962** [comment]
Hi, But have you added https://github.com/SwiftUIX/SwiftUIX as a package?

**Comment by lockieluke** [comment]
It works on the first run but as soon as I make changes to the code in hot reload mode, it breaks and prints the error

**Comment by johnno1962** [comment]
Strange, that shouldn't happen and seems to work for me after a quick test. Has SwiftUIX been added to that target? Any chance you could prepare a small example project demonstrating the problem?

**Comment by lockieluke** [comment]
i have added to the linked frameworks section in project settings already

**Comment by johnno1962** [comment]
Not sure I can say much more without knowing how your project is set up. You are getting the error above when you try to inject? How have you added SwiftUIX to the project - as a Swift Package?
