### ISSUE TITLE
ccache: error: Could not determine home directory from $HOME or getpwuid(3)

### ISSUE THREAD

**Issue by c344081** [johnno1962/InjectionIII#413]
I get this error while using when using ccache. After removing the ccache config, InjectionIII works fine

**Comment by johnno1962** [comment]
Hi, when do you get this error? When it is recompiling to inject? Can you tell me the compilation command?

**Comment by c344081** [comment]
1.I get this error when recompiling to inject

```
💉 ⚠️ Re-compilation failed (see: /var/folders/5y/pxxpcxh12zqgb2gjgkjnmj2h0000gn/T/com.johnholdsworth.InjectionIII/command.sh)
ccache: error: Could not determine home directory from $HOME or getpwuid(3)
```

2. it's the app store version

3. the ccache config
```
#!/bin/sh
export PATH=$PATH:/usr/local/bin:/opt/homebrew/bin
if type -p ccache >/dev/null 2>&1; then
  export CCACHE_CPP2=true
  export CCACHE_DEPEND=true
  export CCACHE_DIRECT=true
  export CCACHE_SLOPPINESS=file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches,modules
  #export CCACHE_DEBUG=true
  #export CCACHE_DEBUGDIR=$PWD/ccache_debug_dir
  exec ccache /usr/bin/clang "$@"
else
  exec clang "$@"
fi
```

**Comment by c344081** [comment]
command
[command.sh.zip](https://github.com/johnno1962/InjectionIII/files/9207069/command.sh.zip)

a demo project
[injectiiontest.zip](https://github.com/johnno1962/InjectionIII/files/9207084/injectiiontest.zip)

**Comment by johnno1962** [comment]
ok, thanks for the info, that makes sense. Can you try one of the GitHub releases: https://github.com/johnno1962/InjectionIII/releases/tag/4.3.1 ? If that works I can make sure $HOME is set in the App Store version.

**Comment by c344081** [comment]
I can use it with ccache now 😄，4.3.1

**Comment by johnno1962** [comment]
Great! Best to stick with that version until we get a new App Store release out.

**Comment by johnno1962** [comment]
As an alternative have you tried exporting HOME=/Users/... in your cache config?
