### ISSUE TITLE
Could not bind service socket: Address already in use

### ISSUE THREAD

**Issue by ugomarinelli** [johnno1962/InjectionIII#414]
Hello, 

I am trying to setup Injection for our project, but running into this: 

_Could not bind service socket: Address already in use_

<img width="263" alt="image" src="https://user-images.githubusercontent.com/4938517/186932056-ece33bea-29a9-46bf-9a53-ba8d0eef387a.png">

I saw there was already one issue related to it, but it did not help ... 
I am using the company device, and I think this might cause the issue, so I was wondering if there is any workaround on this.
 
Also I wanted to know, if it was mandatory to make use of the InjectionIII app, or if it was possible just to use SPM to integrate it in our project. 

Thank you !

**Comment by johnno1962** [comment]
This would normally only happen if you were running the InjectionIII app twice or the InjectionIII app at the same time as the now obsolete "start_aemon.sh" script. To find out who is using the port you can use "lsof | grep 8898".

**Comment by ugomarinelli** [comment]
I tried to kill the process living on the 8898 port, but few seconds later, it comes back .. 
Is there any way i can change the port of InjectionIII ? 
Thanks !

**Comment by johnno1962** [comment]
Unfortunately no but this has never been a problem before now. Can you tell me the output of "lsof | grep 8898"?

**Comment by ugomarinelli** [comment]
this is when I `lsof | grep 8898` 

<img width="1693" alt="image" src="https://user-images.githubusercontent.com/4938517/188111686-648e7a86-ce44-438a-8f0b-57bf1e8658b6.png">

And this when I do: `sudo lsof -i :8898`

<img width="656" alt="image" src="https://user-images.githubusercontent.com/4938517/188110167-10c18657-9780-46c2-8509-800696db713d.png">

**Comment by johnno1962** [comment]
Hmm, seems like you have a java service running that has taken port 8898. One alternative you have would be to switch to the [HotReloading](https://github.com/johnno1962/HotReloading) project which doesn't use sockets. You don't run the InjectionIII app but add it as a Swift Package.
