### ISSUE TITLE
Could not locate compile command

### ISSUE THREAD

**Issue by shinichy** [johnno1962/InjectionIII#417]
Hi, I'm trying to run InjectionIII, but I can't make it work in my iOS UIKit project. I keep getting `Could not locate compile command` error. I tried cleaning and rebuilding, but it didn't work. I checked that Whole Module Optimization is turned off. It would be great if I could borrow someone's help. Thanks.

```
💉 ⚠️ Could not locate compile command for /Users/shinichikatayama/ghq/github.com/ExploramedNC7/willow-ios-gen2s/Willow/Willow/Help/HelpViewController.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
5. The source file is an XCTest that has not been run yet.
Try a build clean then rebuild to make logs available or
consult: "/Users/shinichikatayama/Library/Developer/CoreSimulator/Devices/91EAB1A4-F45C-43FC-A0CB-5537FCC81750/data/Containers/Data/Application/CD21982E-3F34-4ED6-BDFD-CAA4F33A300F/tmp/command.sh".
```

The content of the command.sh.
```
❯ cat /Users/shinichikatayama/Library/Developer/CoreSimulator/Devices/91EAB1A4-F45C-43FC-A0CB-5537FCC81750/data/Containers/Data/Application/CD21982E-3F34-4ED6-BDFD-CAA4F33A300F/tmp/command.sh
# search through build logs, most recent first
cd "/Users/shinichikatayama/Library/Developer/Xcode/DerivedData/Willow-fejpcchmllftwnfisuhvzbtspwue/Logs/Build" &&
for log in `ls -t *.xcactivitylog`; do
    #echo "Scanning $log"
    /usr/bin/env perl "/Users/shinichikatayama/Library/Developer/CoreSimulator/Devices/91EAB1A4-F45C-43FC-A0CB-5537FCC81750/data/Containers/Data/Application/CD21982E-3F34-4ED6-BDFD-CAA4F33A300F/tmp/eval101.pl" "$log"     >"/Users/shinichikatayama/Library/Developer/CoreSimulator/Devices/91EAB1A4-F45C-43FC-A0CB-5537FCC81750/data/Containers/Data/Application/CD21982E-3F34-4ED6-BDFD-CAA4F33A300F/tmp/eval101.sh" 2>"/Users/shinichikatayama/Library/Developer/CoreSimulator/Devices/91EAB1A4-F45C-43FC-A0CB-5537FCC81750/data/Containers/Data/Application/CD21982E-3F34-4ED6-BDFD-CAA4F33A300F/tmp/eval101.err" && exit 0
done
exit 1;%
```

When I run the command.sh, it fails with the following error.
```
❯ bash /Users/shinichikatayama/Library/Developer/CoreSimulator/Devices/91EAB1A4-F45C-43FC-A0CB-5537FCC81750/data/Containers/Data/Application/CD21982E-3F34-4ED6-BDFD-CAA4F33A300F/tmp/command.sh
ls: *.xcactivitylog: No such file or directory
```

There's no xcactivitylog file in the directory. Is this an issue?
```
❯ ls /Users/shinichikatayama/Library/Developer/Xcode/DerivedData/Willow-fejpcchmllftwnfisuhvzbtspwue/Logs/Build
LogStoreManifest.plist
```

My environment.
- M1 Macbook Pro
- OS: 12.6
- Xcode 14.0
- InjectionIII 4.4.0
- I try to run my app in a Simulator

I confirmed that the Getting Started project works. So I'll try to check what prevents me from using InjectionIII.

**Comment by johnno1962** [comment]
Thanks, your analysis is very helpful. This may be something new to Xcode 14 or changes to the build system. Are you able to tell me what the fle /Users/shinichikatayama/Library/Developer/Xcode/DerivedData/Willow-fejpcchmllftwnfisuhvzbtspwue/Logs/Build
LogStoreManifest.plist contains? There are no other files in that directory?

**Comment by shinichy** [comment]
Sure. The content is below. And that's the only file in the directory.

```
❯ cat /Users/shinichikatayama/Library/Developer/Xcode/DerivedData/Willow-fejpcchmllftwnfisuhvzbtspwue/Logs/Build/LogStoreManifest.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>logFormatVersion</key>
	<integer>10</integer>
	<key>logs</key>
	<dict/>
</dict>
</plist>
```

**Comment by johnno1962** [comment]
Interesting, that's not very useful at all about where the missing logs have gone! I notice, like the [other](https://github.com/johnno1962/HotReloading/issues/59#issuecomment-1235404418) [times](https://github.com/johnno1962/InjectionIII/issues/415) we've seen a similar problem you're running quite an old simulator OS. Is it possible to change the targeted iOS version to something more recent and see if that works? Otherwise I can take a look if you have, for example TeamView or hangouts.

**Comment by shinichy** [comment]
`find /Users/shinichikatayama/Library/Developer/Xcode/DerivedData/Willow-fejpcchmllftwnfisuhvzbtspwue -name '*.xcactivitylog' -print` doesn't output anything.

Surprisingly, it starts working well after I restart Xcode. I have no idea... Anyway, thanks for helping me! I'll reopen this issue when I hit this again.

**Comment by johnno1962** [comment]
Thanks for getting back, good that you're up and running. Newer versions of Xcode are more proactive about removing build logs and it seems you can get into a situation where your app runs but there are no build logs for Injection to use  to work out how to recompile the updated source file. You should be able to get out of this state by making a change to a file to force a build and re-run.

Thanks also for opening this issue. It promoted me to go back and finally work out what was the cause (simulator < iOS14 on M1 Mac) of the other two issues I mentioned. I tightened up the code and put in new warnings to provide a hint for users when things are failing and rolled a new 4.4.1 release.

**Comment by johnno1962** [comment]
Hi, when you say "this" issue. What exactly do you mean? The generic "Can't locate compile command..." error which can have many causes including having () characters in the path to the project or case sensitivity in file paths for example. You're saying the injection app has worked on this same project in the past but HotReloading not? The code is the same except HotReloading works from inside the simulator which introduces case sensitivity in the file system which is most likely the problem.

**Comment by cjwirth** [comment]
Right, "the issue" is the generic "Can't locate compile command..." error message with the multiple different options. 

I thought it was the same because:

> This could be due to one of the following:
> 1. Injection does not work with Whole Module Optimization.
We're not doing this

> 2. There are restrictions on characters allowed in paths.
As far as I can tell there shouldn't be any non-ascii characters in our paths

> 3. File paths in the simulator are case sensitive.
Seems like this is the one you are suspecting? Should everything be lowercase, or...? I'm not sure how filenames/paths would change case in the simulator to cause issues here. I know nothing of the process, so maybe this is the issue, but nothing seemed immediately obvious to me.

> 4. The modified source file is not in the current project.
Nope. 

> 5. The source file is an XCTest that has not been run yet.
Nope

> 6. Xcode has removed the build logs. Edit a file and re-run.
Seemingly not? The logs appear up there, as I've posted. 

So maybe you're right, maybe it is the case issue. I'm not sure what I need to change to fix it, though?

> You're saying the injection app has worked on this same project in the past but HotReloading not? The code is the same except HotReloading works from inside the simulator which introduces case sensitivity in the simulator file system which is most likely the problem.
Yes exactly, the Injection app has worked beautifully, and so I was hoping to get HotReloading working in the project so "it just works" for everyone else without manual setup.

Thanks for the insight that this probably points to a case sensitivity issue.

**Comment by johnno1962** [comment]
You can chase it down by running the command.sh from the command line using $ bash <script> and echo'ing $? which should be 0, Then, look at the Perl script it calls to see why it doesn't grep out a match from the build logs.

**Comment by cjwirth** [comment]
I'm not sure where the script is coming from, but it appears like it's searching the root dir for logs?
```
> bash /tmp/command.sh; echo $?
ls: *.xcactivitylog: No such file or directory
1

> cat /tmp/command.sh
# search through build logs, most recent first
cd "/" &&
for log in `ls -t *.xcactivitylog`; do
    #echo "Scanning $log"
    /usr/bin/env perl "/tmp/eval104.pl" "$log"     >"/tmp/eval104.sh" 2>"/tmp/eval104.err" && exit 0
done
exit 1;

**Comment by johnno1962** [comment]
Hmm, that really isn't going to help. Seems like HotReloading hasn't been able to find your logs at all. Currently (and it changed recently) it looks for the last changed file in your home directory that ends with .xcactivitylog and uses its directory. If you where using a custom derived data path outside your home directory for example this wouldn't work. Make sure your project has been built recently - edit a file, save it and rebuild.

**Comment by cjwirth** [comment]
Everything should be set up pretty standard -- Derived Data is `/Users/caesar/Library/Developer/Xcode/DerivedData/MyApp-czhykqicsjtfrjgwdilqryuwjfyq`, nothing fancy going on. 

> Currently (and it changed recently) it uses a FileWatcher to look for the last changed file in your home directory that ends with .xcactivitylog and uses its directory.

Seems weird to me that it's not able to detect these changes. I've definitely tried cleaning, rebuilding, and doing all that.

**Comment by johnno1962** [comment]
What version of iOS+macOS is this? Does it print "Using Logs ..." when you inject? The relevant code which you can debug when using HotReloading is here: https://github.com/johnno1962/HotReloading/blob/main/Sources/HotReloading/StandaloneInjection.swift

**Comment by johnno1962** [comment]
Actually, HotReloading shouldn't even need to use the file watcher to find the logs. It looks relative to the path to the SwiftTrace package sources.

**Comment by cjwirth** [comment]
Great, thanks. Yeah, maybe I'll check this out locally and see if I can figure anything out. 

macOS 12.6 (21G115)
Xcode Version 14.0 (14A309)
iOS 16.0

>  Does it print "Using Logs ..." when you inject? 

Yeah, kind of? But not really. Here are all the logs that come out:

```
🔥 HotReloading available for sources under ["/Users/caesar/Developer/MyApp", "/Users/caesar/Library/Developer/Xcode/DerivedData/MyApp-czhykqicsjtfrjgwdilqryuwjfyq/Logs/Build"]
```

It used to be `/Users/caesar`, but you mentioned it was looking for log files that change, so I set `INJECTION_DIRECTORIES` to contain these because 🤷 it was  shot in the dark.

Then, when I save a file, I get the output I've been seeing the whole time:

```
🔥 Using logs: .
ls: *.xcactivitylog: No such file or directory
🔥 ⚠️ Could not locate compile command for /Users/caesar/Developer/MyApp/Sources/Settings/Controllers/SettingsViewController.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
5. The source file is an XCTest that has not been run yet.
6. Xcode has removed the build logs. Edit a file and re-run.
Try a build clean then rebuild to make logs available or
consult: "/tmp/command.sh".
```

**Comment by johnno1962** [comment]
Your INJECTION_DIRECTORIES looks ok but I wasn't anticipating many people would use that now it should be all automatic if you're not using an external drive or something. Sounds like it knew the logs directory but the changes to allow app users to not have to run the app (the FileWatcher) may be overriding it to something invalid. Put a breakpoint on the line I mentioned above and see what the path it is coming up with is.

**Comment by cjwirth** [comment]
Both `builder.derivedLogs` and `FileWatcher.derivedLogs` are empty strings.... hmmmmmmm

**Comment by cjwirth** [comment]
OK so the line you sent me never actually gets hit. I printed out the files that it gets called for, and no xcactivitylog files ever make it in.

However, these lines seem strange? https://github.com/johnno1962/HotReloading/blob/main/Sources/HotReloading/StandaloneInjection.swift#L80-L83
`builder.derivedLogs` is the proper Logs directory in Derived Data
`FileWatcher.derivedLogs` is an empty string.

**Comment by johnno1962** [comment]
This is beginning to look like a stupid logic error. Give me a few minutes. I'll push a new branch.

**Comment by johnno1962** [comment]
Yes, this was just a bug when the "fallback" log directory search fails. Why it would be failing is another question. Can you try the "logic-error-fix" branch please?

**Comment by cjwirth** [comment]
Alright I think you were right. It works when I add in a conditional breakpoint to do this:

`expr FileWatcher.derivedLogs = builder.derivedLogs ?? ""`

if the `FileWatcher.derivedLogs` are empty.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/1579644/194613459-96a03394-814f-4629-b3fd-28f6306a3263.png">


> Why it would be failing is another question.

Wouldn't mind helping debug this! I do have some things to take care of though, so I'll be away for a bit.

> Can you try the "logic-error-fix" branch please?

Sure! At time of writing it doesn't look like it's pushed yet, but I can definitely do that.

**Comment by johnno1962** [comment]
Thanks, let me know how you get on. If you want to help track down why the "fallback" is failing, switch back to the failing main branch and increase this value https://github.com/johnno1962/HotReloading/blob/main/Sources/HotReloading/FileWatcher.swift#L37. The fallback works by processing file system events before the app starts by "backdating" the event id. If you have a very active file system this value might not be large enough. Thanks for taking the time to file this report and researching it!

**Comment by cjwirth** [comment]
Yes! This new branch is working 🎉

**Comment by cjwirth** [comment]
Sure, I'll look into this later in the day. Thanks for all the help getting this set up! It's been a huge productivity booster and I'm glad I'm closer to being able to share it with everyone :)

**Comment by johnno1962** [comment]
👍 👍
