### ISSUE TITLE
wrong watching file

### ISSUE THREAD

**Issue by tzxdtc** [johnno1962/InjectionIII#418]
Hi, Appreciate for your amazing tool.
I tried this in demo app and it worked well.
When I switch it to my project, the injection seems work fine but the watching file is still the demo one which is wrong. Maybe I can remove the cache or something. Did I do something wrong?
Thank you!

```
💉 InjectionIII connected /Users/zhixiang.tan/XXXX/IncomingMessageOverlayViewController.swift
💉 Watching files under the directory /Users/zhixiang.tan/InjectSwiftUIExample/DemoApp/DemoApp
```

**Comment by johnno1962** [comment]
Hi, when you change project, you need to select the root directory of the new one using the menubar menu: "Open Project". If you are using the newer 4.4.* versions of the app from [from github](https://github.com/johnno1962/InjectionIII/releases) you can stop running the InjectionIII app altogether and it should all be automatic.

**Comment by tzxdtc** [comment]
Thanks for your quickly response, it works!!!
But this time, After I save the file without change anything, the UI components disappeared. I Should find out what's wrong about it.

Anyway, thank you so much for your time! Appreciate!🙌🏻


https://user-images.githubusercontent.com/19767846/193437669-d6233c26-9c00-49cc-b75c-6d01df4415be.mov

**Comment by johnno1962** [comment]
👍
