### ISSUE TITLE
Content is not being updated after saving the file

### ISSUE THREAD

**Issue by joseortiz9** [johnno1962/InjectionIII#419]
I'm a little newbie with IOS development, I have been some weeks already trying to configure injectionIII with an existing project but without any success result :(
I wanted to solve it by myself but already tried everything that found.

Specs:
Computer MacBook Air M1, 2020
XCode Version 14.0.1
InjectionIII version 4.4.3

AppDelegate.swift
```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?
  
  func applicationDidFinishLaunching(_ application: UIApplication) {
    
#if os(macOS)
    let bundleName = "macOSInjection.bundle"
#elseif os(tvOS)
    let bundleName = "tvOSInjection.bundle"
#elseif targetEnvironment(simulator)
    let bundleName = "iOSInjection.bundle"
#else
    let bundleName = "maciOSInjection.bundle"
#endif
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/"+bundleName)!.load()
    
    let appearance = UINavigationBarAppearance()
    appearance.backgroundColor = UIColor(red: 1, green: 108.0/255, blue: 0, alpha: 1.0)
    UINavigationBar.appearance().scrollEdgeAppearance = appearance
    UINavigationBar.appearance().standardAppearance = appearance
  }
}
```
![Screenshot 2022-10-25 at 3 37 58 PM](https://user-images.githubusercontent.com/26872450/197774950-46975748-3bca-4da3-96ca-2fda1a19c1fd.png)

I have been changing the color of the NavigationBar, but the app in the simulator doesnt rerender the changes, I always have to recompile everything. I did all the steps that are listed in the readme and the logs of the app shows that InjectionIII is connected and that it injected successfully the code, but nothing changes. 

```
💉 InjectionIII connected /.../Starter-app/SnappyQuiz.xcodeproj
💉 Watching files under the directory /.../SnappyQuiz-iOS/Starter-app
💉 Compiling /.../SnappyQuiz-iOS/Starter-app/SnappyQuiz/AppDelegate.swift
💉 Loading .dylib ...
objc[5949]: Class _TtC10SnappyQuiz11AppDelegate is implemented in both /Users/user/Library/Developer/CoreSimulator/Devices/26D23239-938E-47C9-8A20-38D457C47611/data/Containers/Bundle/Application/E2204ACD-88A0-4FAA-9310-E3ED0AB8F53A/SnappyQuiz.app/SnappyQuiz (0x102490c70) and /Users/user/Library/Developer/CoreSimulator/Devices/26D23239-938E-47C9-8A20-38D457C47611/data/Containers/Data/Application/00BE39B9-4D33-4BFB-8B31-AC12D1561BD2/tmp/eval101.dylib (0x147020bd0). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ⬆️
💉 Injected type #1 'SnappyQuiz.AppDelegate'
```

Can you please help me out, maybe Im doing something wrong...

**Comment by joseortiz9** [comment]
So it should look like this?

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    func applicationDidFinishLaunching(_ application: UIApplication) {

        #if os(macOS)
        let bundleName = "macOSInjection.bundle"
        #elseif os(tvOS)
        let bundleName = "tvOSInjection.bundle"
        #elseif targetEnvironment(simulator)
        let bundleName = "iOSInjection.bundle"
        #else
        let bundleName = "maciOSInjection.bundle"
        #endif
        Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/" + bundleName)!.load()

        configureNavBar()
    }

    @objc func injected() {
        configureNavBar()
    }

    func configureNavBar() {
        let appearance = UINavigationBarAppearance()
        appearance.backgroundColor = UIColor(red: 1, green: 108.0 / 255, blue: 0, alpha: 1.0)
        UINavigationBar.appearance().scrollEdgeAppearance = appearance
        UINavigationBar.appearance().standardAppearance = appearance
    }
}
```

Does this means that for every ViewController that I want to watch I have to call its viewDidLoad() inside a injected() function?

**Comment by johnno1962** [comment]
You used to be able to make an extension on UIViewController itself with the `@objc func injected()` method you're thinking of but I'm not sure that still compiles.

**Comment by joseortiz9** [comment]
I did it as you asked and still having the same issue, 
```
💉 Loaded .dylib - Ignore any duplicate class warning ⬆️
💉 Interposed 4 function references.
💉 Injected type #1 'SnappyQuiz.AppDelegate'
💉 Starting sweep [SnappyQuiz.AppDelegate, SnappyQuiz.AppDelegate, SnappyQuiz.AppDelegate], []...
```
It seems to have no errors, but still nothing change in the simulator

**Comment by johnno1962** [comment]
Leave the UIViewController extension in your AppDelegate.swift and inject your ViewController. I'm not sure exactly what appearance is or whether it can accepts real time updates. Have you tried the https://johnholdsworth.com/GettingStarted.zip project? Always better to start with something that works and work your way up from there.

**Comment by joseortiz9** [comment]
Your project works as expected! thanks for helping and providing so quick response)) Im gonna try to replicate it in my project. Closing issue.
Thanks again!

**Comment by johnno1962** [comment]
👍
