### ISSUE TITLE
Rewrite docs

### ISSUE THREAD

**Issue by Kinark** [johnno1962/InjectionIII#422]
The docs simply doesn't explain anything. There's 2 "Stop Press" and a bunch of text that contradicts each other.

Should I install the app? Or just the package? Or both? Which option is better if there's any? Where do people in pure SwiftUI projects put the loaders? What should one do about the menu app with dozens of configurations? How to start the injection? Can we use it in physical devices?

You can't expect people to know what's in your mind, sorry.

Please, if you care about the community, erase that bunch of nonsense text and write it again.

**Comment by johnno1962** [comment]
Thank you for your thoughtful, considerate and appreciative message; I'll review the documentation. I try to keep it up to date but Injection continues to evolve. In terms of what you need to do to use to use injection all you need to do as of recently is load the injection bundle and save files i.e. follow the second "stop press" but I haven't had the courage to promote that widely as yet.

**Comment by johnno1962** [comment]
I've fleshed out the documentation a little and made it less noncommittal and the new standalone injection.

**Comment by Kinark** [comment]
It's still not understandable. Each paragraph has a different direction to take, you have to literally find your way out of that jungle you created. You need to rewrite that, but please, call someone who knows how to write a documentation to help you. I can't open a PR because I didn't understand.
