### ISSUE TITLE
change to property initial value not recognized

### ISSUE THREAD

**Issue by mvolkmann** [johnno1962/InjectionIII#425]
Here is an example where a code change is not recognized in hot reload:

```swift
import Inject
import SwiftUI

struct ContentView: View {
    @ObservedObject private var iO = Inject.observer
    private let name = "Bob"

    var body: some View {
        Text("Hello, \(name)!")
            .enableInjection()
    }
}
```

Steps to reproduce the issue:
1. Run the app in the Simulator.
2. In the code, change "Bob" to "Mary" and save.
3. Click on the Simulator.
4. Note that "Bob" is still displayed.
5. Change "Hello" to "Goodbye" and save.
6. Click on the Simulator.
7. Note that "Goodbye" is displayed, proving that everything was configured correctly.

Why doesn't changing the value of the `name` property get picked up?

**Comment by johnno1962** [comment]
Hi, this wouldn't work as the initialiser for `var name` is not called unless you re-create the struct. Only the body property is called again when you inject. For example, this will work as the struct is recreated by the parent view which reinitialises `name`:
```Swift
struct ContentView: View {
    @ObservedObject private var iO = Inject.observer

    var body: some View {
        BobView()
    }
}

struct BobView: View {
    @ObservedObject private var iO = Inject.observer
    private let name = "Bob"

    var body: some View {
        Text("Hello, \(name)!")
            .enableInjection()
    }
}

**Comment by mvolkmann** [comment]
Thanks for explaining that!
