### ISSUE TITLE
Cant hotload swift code in swift and objective-c project. 

### ISSUE THREAD

**Issue by showtestlog** [johnno1962/InjectionIII#427]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/12830799/205043844-ae91fc5b-4f1e-4b92-a705-1872d055d913.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/12830799/205043929-dc68a46e-b537-4a00-b304-8266b6ada530.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/12830799/205044009-d3c15230-009b-434b-b76a-bb17b115c8c3.png">

💉 ⚠️ Could not locate compile command for 
/Users/showcode/dev/halo/Halo/Submodules/Social/Message/MessageUIKit/Classes/Message/ViewController/GroupStickyTopViewController.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
  image show i have change it.
3. There are restrictions on characters allowed in paths.
the path is shown above.
5. File paths in the simulator are case-sensitive.

7. The modified source file is not in the current project.

it is in the halo dir.

9. The source file is an XCTest that has not been run yet.
no
11. Xcode has removed the build logs. Edit a file and re-run.
Try a build clean then rebuild to make logs available 

the log is 

# search through build logs, most recent first
cd "/Users/showcode/Library/Developer/Xcode/DerivedData/Halo-axrbsmsutrbaqgdmboixjsumxtfe/Logs/Build" &&
for log in `ls -t *.xcactivitylog`; do
    #echo "Scanning $log"
    /usr/bin/env perl "/Users/showcode/Library/Developer/CoreSimulator/Devices/3A85C7DC-094D-4BFF-B1DD-E371D4A7E5EF/data/Containers/Data/Application/77AF9F48-0FBC-4630-8134-768F38DE062A/tmp/eval104.pl" "$log"     >"/Users/showcode/Library/Developer/CoreSimulator/Devices/3A85C7DC-094D-4BFF-B1DD-E371D4A7E5EF/data/Containers/Data/Application/77AF9F48-0FBC-4630-8134-768F38DE062A/tmp/eval104.sh" 2>"/Users/showcode/Library/Developer/CoreSimulator/Devices/3A85C7DC-094D-4BFF-B1DD-E371D4A7E5EF/data/Containers/Data/Application/77AF9F48-0FBC-4630-8134-768F38DE062A/tmp/eval104.err" && exit 0
done
exit 1;

**Comment by showtestlog** [comment]
> Hi, can you tell me what version and version of Injection/Xcode/iOS this is? If it's the App Store release can you download and try one of the binary releases on this repo? It's likely to be an upper/lower casing issue or an issue with "special characters" such as (). Was this a Swift or Objective-C file? What is the full path to that file? Are you able to email the build log of your project and the eval104.pl file to github at johnholdsworth.com?



> Hi, can you tell me what version and version of Injection/Xcode/iOS this is? If it's the App Store release can you download and try one of the binary releases on this repo? It's likely to be an upper/lower casing issue or an issue with "special characters" such as (). Was this a Swift or Objective-C file? What is the full path to that file? Are you able to email the build log of your project and the eval104.pl file to github at johnholdsworth.com?

💉 Using logs: /Users/showcode/Library/Developer/Xcode/DerivedData/Halo-axrbsmsutrbaqgdmboixjsumxtfe/Logs/Build.
2022-12-01 20:17:31.907250+0800 discover[26619:248312] Cannot find executable for CFBundle 0x7ff789f57620 </System/Library/Frameworks/ExternalAccessory.framework> (not loaded)
💉 ⚠️ Could not locate compile command for /Users/showcode/dev/halo/Halo/Submodules/Social/Message/XYMessageUIKit/XYMessageUIKit/Classes/Message/ViewController/GroupStickyTopViewController.swift.
This could be due to one of the following:

Injection does not work with Whole Module Optimization.
There are restrictions on characters allowed in paths.
File paths in the simulator are case sensitive.
The modified source file is not in the current project.
The source file is an XCTest that has not been run yet.
Xcode has removed the build logs. Edit a file and re-run.
Try a build clean then rebuild to make logs available or
consult: "/Users/showcode/Library/Developer/CoreSimulator/Devices/3A85C7DC-094D-4BFF-B1DD-E371D4A7E5EF/data/Containers/Data/Application/E186BE01-236B-49D2-89E1-5C5B11E0036F/tmp/command.sh".
it tell me that Frameworks/ExternalAccessory.framework cant load Injection is new download from here not APP strore， xocde Version 14.1 14B47b the new one.

**Comment by showtestlog** [comment]
> /Users/showcode/dev/halo/Halo/Submodules/Social/Message/MessageUIKit/Classes/Message/ViewController/GroupStickyTopViewController.swift fullPath

**Comment by showtestlog** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/12830799/205054597-40aad898-9f06-4754-9c2a-a88a1ca5db52.png">
but the demo is ok.

**Comment by johnno1962** [comment]
Hi, it's difficult to know what the problem injecting that particular file is without being at your desk. Injection purposely delegates to scripts this phase of finding the command to recompile a command so it is possible to debug without access to the program source. At this point, perhaps you could try the following:
```
cd "/Users/showcode/Library/Developer/Xcode/DerivedData/Halo-axrbsmsutrbaqgdmboixjsumxtfe/Logs/Build" 
/usr/bin/env perl "/Users/showcode/Library/Developer/CoreSimulator/Devices/3A85C7DC-094D-4BFF-B1DD-E371D4A7E5EF/data/Containers/Data/Application/77AF9F48-0FBC-4630-8134-768F38DE062A/tmp/eval104.pl" *.xcactivitylog
```
and tell me what it says. If it prints a line it has found the compilation command otherwise there will be a non-zero exit code which you can print with `echo $?`. If there is no error and no line printed I'll need to see the perl code.

**Comment by showtestlog** [comment]
![image](https://user-images.githubusercontent.com/12830799/206734144-487f3858-9cfe-49aa-9276-d6c1550b95f5.png)

I have run the command and it show nothing 

@johnno1962

**Comment by showtestlog** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/12830799/206736383-bbb0531a-734e-4e07-bbd5-6fd111aa9d04.png">

and I added printf in it and it did not run this line.
Does It is because of x86_64?? I am using the M1 core.

**Comment by johnno1962** [comment]
What version of iOS is this? Try to running on iOS < 14 as they run as Intel.

**Comment by showtestlog** [comment]
The version is 16.0. and did you know any reason for the question? or what log or something can I do?

**Comment by johnno1962** [comment]
Can you send GitHub at johnholdsworth.com, one of the .xcactivity files in the directory the script mentions? i.e. can you send me one of the build logs?

**Comment by showtestlog** [comment]
OK, I have run the Process again. and here the full log and what i do.
![image](https://user-images.githubusercontent.com/12830799/206842319-2f8d8529-e271-4cf1-86b4-206523469a91.png)

This is the run "command.sh" content shown in Xcode debug. 
`# search through build logs, most recent first
cd "/Users/showcode/Library/Developer/Xcode/DerivedData/Halo-axrbsmsutrbaqgdmboixjsumxtfe/Logs/Build" &&
for log in `ls -t *.xcactivitylog`; do
    #echo "Scanning $log"
    /usr/bin/env perl "/Users/showcode/Library/Developer/CoreSimulator/Devices/3D359221-4E9E-4897-B087-B7D6F1B7B338/data/Containers/Data/Application/1B173350-AA42-4452-918A-F759CC1ED1E8/tmp/eval101.pl" "$log"     >"/Users/showcode/Library/Developer/CoreSimulator/Devices/3D359221-4E9E-4897-B087-B7D6F1B7B338/data/Containers/Data/Application/1B173350-AA42-4452-918A-F759CC1ED1E8/tmp/eval101.sh" 2>"/Users/showcode/Library/Developer/CoreSimulator/Devices/3D359221-4E9E-4897-B087-B7D6F1B7B338/data/Containers/Data/Application/1B173350-AA42-4452-918A-F759CC1ED1E8/tmp/eval101.err" && exit 0
done
exit 1;`

So I open 101.pl add more log. and run the command again then see eval101.err and sh file. 


`use JSON::PP;
use English;
use strict;

# line separator in Xcode logs
$INPUT_RECORD_SEPARATOR = "\r";

# format is gzip
open GUNZIP, "/usr/bin/gunzip <\"$ARGV[0]\" 2>/dev/null |" or die "gnozip";

printf "step1 \n";
# grep the log until there is a match
my ($realPath, $command);
printf "step2 \n";
while (defined (my $line = <GUNZIP>)) {
    if ($line =~ /^\s*cd /) {
        printf "step3 \n";
        $realPath = $line;
    }
    elsif ($line =~ m@ -(?:primary-file|c(?<!-frontend -c)) (?:\\?\"(\Q/Users/showcode/dev/halo/Halo/Submodules/Social/Message/XYMessageUIKit/XYMessageUIKit/Classes/MessageGroupChat/Square/GroupSquareViewController.swift\E)\\?\"|(\Q/Users/showcode/dev/halo/Halo/Submodules/Social/Message/XYMessageUIKit/XYMessageUIKit/Classes/MessageGroupChat/Square/GroupSquareViewController.swift\E)) @oi and $line =~ " x86_64") {
        # found compile command
        printf "step4 \n";
        # may need to extract file list
        if ($line =~ / -filelist /) {
            while (defined (my $line2 = <GUNZIP>)) {
                printf "step5 \n";
                if (my($filemap) = $line2 =~ / -output-file-map ([^ \\]+(?:\\.[^ \\]+)*) / ) {
                    printf "step6 \n";
                    $filemap =~ s/\\//g;
                    my $file_handle = IO::File->new( "< $filemap" )
                        or die "Could not open filemap '$filemap'";
                    my $json_text = join'', $file_handle->getlines();
                    my $json_map = decode_json( $json_text, { utf8  => 1 } );
                    my $filelist = '/Users/showcode/Library/Developer/CoreSimulator/Devices/3D359221-4E9E-4897-B087-B7D6F1B7B338/data/Containers/Data/Application/1B173350-AA42-4452-918A-F759CC1ED1E8/tmp//filelist.txt';
                    my $swift_sources = join "\n", keys %$json_map;
                    my $listfile = IO::File->new( "> $filelist" )
                        or die "Could not open list file '$filelist'";
                    binmode $listfile, ':utf8';
                    $listfile->print( $swift_sources );
                    $listfile->close();
                    $line =~ s/( -filelist )([^\s\\]*(?:\\.[^\s\\]*)*)( )/$1$filelist$3/;
                    printf "step7 \n";
                    last;
                    
                }
            }
        }
        if ($realPath and (undef, $realPath) = $realPath =~ /cd (\"?)(.*?)\1\r/) {
#           print "cd \"$realPath\" && ";
            printf "step8 \n";
        }
        # find last
        $command = $line
        #exit 0;
    }
    elsif (my ($bazel, $dir) = $line =~ /^Running "([^"]+)".* (?:patching output for workspace root|with project path) at ("[^"]+")/) {
        $command = "cd $dir && $bazel";
        last;
    }
}

printf "step9 \n";
if ($command) {
    print $command;
    exit 0;
}
# class/file not found
exit 1;
`
The result is 

![image](https://user-images.githubusercontent.com/12830799/206842523-3fc4aec4-dc32-48be-a49c-32839b57baec.png)

![image](https://user-images.githubusercontent.com/12830799/206842531-d5271fa8-cdb1-4658-9800-e277a25810fe.png)

![image](https://user-images.githubusercontent.com/12830799/206842555-3d7ef1ec-c567-4664-a7d6-bdd3dc37a579.png)

![image](https://user-images.githubusercontent.com/12830799/206842602-09d71723-d6fa-455a-85b1-3af11b88ed95.png)
![image](https://user-images.githubusercontent.com/12830799/206842610-89452207-63b8-4093-84fa-26baed65b4d0.png)

always  log step3 then the last is step9. so I wish this can show some info for you to help me. thank you @johnno1962

**Comment by showtestlog** [comment]
![image](https://user-images.githubusercontent.com/12830799/206843333-ff8e3772-c35f-4500-a07e-ee3ee88af056.png)
still 💉 ⚠️ Could not locate compile command for /Users/showcode/dev/halo/Halo/Submodules/Social/Message/XYMessageUIKit/XYMessageUIKit/Classes/MessageGroupChat/Square/GroupSquareViewController.swift.

**Comment by johnno1962** [comment]
You're doing the right things, if you send a log by email through to GitHub at johnholdsworth.com I can see if there is anything obvious.

**Comment by showtestlog** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/12830799/206847879-ad7c716a-a1f8-44f7-a592-7da4047b2d1a.png">
It was successful. Does the address I sent right?

**Comment by johnno1962** [comment]
I got it thanks, looking through it now.

**Comment by johnno1962** [comment]
I don't see how the file you are trying to inject, `GroupStickyTopViewController.swift` is compiled in the logs. Without this information injection can not do it's work and prints the message you're seeing. I'm seeing a lot of messages of the form `Build target PipeCore of project PipeCore with configuration Debug` in the logs with no information. Does CocoaPods no longer log how it is building it's projects? This used to work, I wonder if something has changed?

**Comment by johnno1962** [comment]
I see at least part of your project are using -whole-module-optimization which doesn't work with injection. Check your build settings under "Compilation Mode" (not "Optimisation Level")

**Comment by showtestlog** [comment]
![image](https://user-images.githubusercontent.com/12830799/206851006-c9dd73be-7ad6-42f1-b19b-358ea2f1e22a.png)
but its incremental

**Comment by johnno1962** [comment]
If you look in your log there are whole module optimised compilations going on. This seems to be a setting issue.

**Comment by showtestlog** [comment]
ok, I am checking and seeing what is wrong.

**Comment by showtestlog** [comment]
I have changed it and mailed you the build log. the issue is sill occurring. thank you  @johnno1962

**Comment by showtestlog** [comment]
Do you mean that all of the components must not have Whole module optimization？
I think so, I change all the targets in the source code compiler and have no optimization. and the swift hot reload is OK.
Thank you very mush again.

**Comment by johnno1962** [comment]
Great!
