### ISSUE TITLE
Swift injected failed

### ISSUE THREAD

**Issue by showtestlog** [johnno1962/InjectionIII#432]
Xcode version：14.2 (14C18)

![image](https://user-images.githubusercontent.com/12830799/211056471-944bf4f9-e231-4a30-aa1c-89e4503c66c1.png)

<img width="898" alt="image" src="https://user-images.githubusercontent.com/12830799/211056543-f9dfe22f-2668-429e-80dc-b596d99ceeb0.png">
<img width="219" alt="image" src="https://user-images.githubusercontent.com/12830799/211056570-46c3bf6c-10dd-4f47-83a1-420c2d75b4c4.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/12830799/211056597-ca945415-67eb-4a24-ac20-a60b34123e48.png">

<img width="169" alt="image" src="https://user-images.githubusercontent.com/12830799/211057177-dad37f90-3942-42ee-aeb4-dda004eaa4dd.png">

 **Inject Trace**

<img width="879" alt="image" src="https://user-images.githubusercontent.com/12830799/211061081-97e07161-122d-49b8-8165-178ebe5ed863.png">

I changed the view background color, but it did not affect it. The background color is still green

**Comment by johnno1962** [comment]
You need to use an `@objc fun injected()`
