### ISSUE TITLE
How can I use it on iOS device without install the  InjectionIII App ? 

### ISSUE THREAD

**Issue by qmkCamel** [johnno1962/InjectionIII#433]

**Comment by johnno1962** [comment]
Hi, You can't. Something needs to recompile the source file and prepare the dynamic library on your Mac where Xcode lives.

**Comment by qmkCamel** [comment]
Got it. Thanks.

**Comment by qmkCamel** [comment]
So, the easiest way to perform hot reload in device  is like below
1. download  the InjectionIII.app from github
2. add HotReloading as a package in demo project
3. add a build phase 

Am I right ?

**Comment by johnno1962** [comment]
Hi, not quite, you run the InjectionIII app after having set the default deviceUnlock to any (see the HotReloading README) and then you should be able to connect when you add the HotReloading project as.a package (the build phase is no longer required as the InjectionIII app opens a port once you set the default I mention). I have to say it is a little fiddly getting the connection depending on your network and even then device injection is experimental and nowhere as reliable as injection in the simulator.

**Comment by qmkCamel** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/5952752/212464476-9dd9621f-fbcd-44be-9d54-862aadb7057d.png">
The description of device injection from https://github.com/johnno1962/InjectionIII is out of date？

**Comment by johnno1962** [comment]
You're right, thanks for letting me know. I've updated the instructions there. The daemon hasn't been required since Xcode 14 though it should still work. Better to use the app instead.

**Comment by qmkCamel** [comment]
Found a problem.
I tried the HotReloading on device injection, but I cann't get a property in  a view controller with INJECTION_BUNDLE_NOTIFICATION. 
So I want to know why it cann't get the property?
```
@interface ViewController ()
@property (nonatomic, strong) NSString *content;
@property (nonatomic, strong) UILabel *contentLabel;
@end


@implementation ViewController
- (void)viewDidLoad {
    [super viewDidLoad];

    self.conten = @"content";

    self.contentLabel = [UILabel new];
    [self.view addSubview:self.contentLabel];

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(injectionReload) name:@"INJECTION_BUNDLE_NOTIFICATION" object:nil];
}

- (void)injectionReload {
   NSLog(@"self.content %@",self.content); // null 
   NSLog(@"self.contentLabel %@",self.contentLabel); // null 
   NSLog(@"self.view.subviews %@",self.view.subviews); // self.view.subviews (
    "<UILabel: 0x10b81fd80; frame = (100 100; 100 100); text = '123'; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x280276850>>",
)
}


```

**Comment by johnno1962** [comment]
Unfortunately, Objective-C is even less suited to device injection than Swift so you can expect some problems due to how the code is emitted and the limitations of how the new code is loaded. Exactly which line is crashing? It's possible I can suggest some workarounds; Sometimes you need to be inventive. One thing you might want to remove is the `[super viewDidLoad]`.

**Comment by johnno1962** [comment]
Ah, you mean these lines.. Let me take. look.
```
   NSLog(@"self.content %@",self.content); // null 
   NSLog(@"self.contentLabel %@",self.contentLabel); // null

**Comment by qmkCamel** [comment]
> Ah, you mean these lines.. Let me take. look. Any chance you have a small example project you can share?
> 
> ```
>    NSLog(@"self.content %@",self.content); // null 
>    NSLog(@"self.contentLabel %@",self.contentLabel); // null 
> ```



> Found a problem. I tried the HotReloading on device injection, but I cann't get a property in a view controller with INJECTION_BUNDLE_NOTIFICATION. So I want to know why it cann't get the property?
> 
> ```
> @interface ViewController ()
> @property (nonatomic, strong) NSString *content;
> @property (nonatomic, strong) UILabel *contentLabel;
> @end
> 
> 
> @implementation ViewController
> - (void)viewDidLoad {
>     [super viewDidLoad];
> 
>     self.conten = @"content";
> 
>     self.contentLabel = [UILabel new];
>     [self.view addSubview:self.contentLabel];
> 
>     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(injectionReload) name:@"INJECTION_BUNDLE_NOTIFICATION" object:nil];
> }
> 
> - (void)injectionReload {
>    NSLog(@"self.content %@",self.content); // null 
>    NSLog(@"self.contentLabel %@",self.contentLabel); // null 
>    NSLog(@"self.view.subviews %@",self.view.subviews); // self.view.subviews (
>     "<UILabel: 0x10b81fd80; frame = (100 100; 100 100); text = '123'; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x280276850>>",
> )
> }
> ```

This is all of the code. 
I didn't use the storyborad and xib.

**Comment by johnno1962** [comment]
Ok @qmkCamel, I've pushed a few minor changes to a new branch `objc-fixes` of the HotReloading project to inhibit the injection of property getters and setters which you can switch to in Xcode to resolve the problems you've seen. There is also a fix for messaging super which hasn't worked until now. You'll encounter other problems from time to time, particularly for Objective-C injection on a device which hasn't received a lot of attention. Let me know if any show-stoppers crop up and I can take a look at it.

**Comment by qmkCamel** [comment]
Hi, The same test code, found another problem, when access a ivar it is null.
`NSLog("_contentLabel %@",_contentLabel);`

**Comment by johnno1962** [comment]
Best not to refer to the instance variables directly but use the accessors given how the class metadata is not initialised entirely correctly on a device. Getting that fixed would likely be difficult though I'll take a look for you.

**Comment by johnno1962** [comment]
I've pushed another commit [f00dac80ed4fdc14dc1050691d44646a20a4e3fc](https://github.com/johnno1962/HotReloading/commit/f00dac80ed4fdc14dc1050691d44646a20a4e3fc) to the objc-fixes branch which should resolve the direct access to ivar problem. Thanks for trying these releases out for me.

**Comment by qmkCamel** [comment]
The newly added method and properties would invoke "unrecognized selector".
I read the code, found it only handle the old class's method. Maybe another unsupport  case?

**Comment by johnno1962** [comment]
Yes, that's very much an edge case. Adding new methods is something that only works for Objective-C and not on a device as it is difficult to know the new methods as the new version of the class is not initialised correctly and the runtime apis crash. I've been looking at another known problem where references to classes in Objective-C silently fail when the code has been injected as the pointer to the class is not initialised e.g. [UILabel new] returns nil. I've found a fix of sorts for this in a [new commit](https://github.com/johnno1962/HotReloading/pull/69/commits/96985bcb6adc3c3651db01da720ac61671efa9a9). This fix requires a change at the server end of injection however. If you want to try it out, rather than have me roll another version of the app can you switch to using a "build phase" to run a version of the injection app instead?
```
if [ -d $SYMROOT/../../SourcePackages ]; then
    $SYMROOT/../../SourcePackages/checkouts/HotReloading/start_daemon.sh
fi
```

**Comment by qmkCamel** [comment]
Thanks, I'll try it~
So, is there an Objective-C supported case list, WIP case list  and unsupported case list because of the language limitation?

**Comment by johnno1962** [comment]
I get working what I can as I/people discover problems but Objective-C is no longer the first priority. Device injection is more of a "would be nice" for most people but it is slowly becoming more and more usable. It will always be subject to random limitations unless I spend a lot of time replicating all of the things the dynamic linker does when it loads a dynamic library (for which the source is available but there is a lot of it). Someday perhaps, but most people use the simulator where I can be more confident of a better outcome.

**Comment by qmkCamel** [comment]
If not use the build phase ( just use the InjectionIII.app alone with HotReloading package), is there a server side log like `/tmp/hot_reloading.log`?

**Comment by johnno1962** [comment]
You can run the app from the command line to see what's going on `$ /Applications/InjectionIII.app/Contents/MacOS/InjectionIII &`

**Comment by johnno1962** [comment]
[New commit](https://github.com/johnno1962/HotReloading/pull/69/commits/c2e508b113874910d93d2a47394a286c1fd8af76) available which extends the fix for ivar offsets to Swift files which would have been the "proper" fix for a previous issue  https://github.com/johnno1962/HotReloading/issues/65. At the end of all this I may be able to re-enable injecting getters and setters.

**Comment by johnno1962** [comment]
I've merged the HotReloading branch I was working on, rolled a new version of the InjectionIII app and pre-released it with these various ivar & Objective-C fixes. 
https://github.com/johnno1962/InjectionIII/releases/tag/4.5.6
Thanks very much for raising this issue and testing out the various iterations. This is likely a big step forward for the viability of on-device injection! Any remaining problems you notice, please let me know.

**Comment by qmkCamel** [comment]
I tried the latest version. Found a little question, maybe the setter getter ignore in the swizzle function  locating in ObjcInjeciton.swift is not needed?
```
    public class func swizzle(oldClass: AnyClass, selector: Selector,
                              _ tmpfile: String) -> Int {
        var swizzled = 0
        let selectorName = sel_getName(selector)
        let setterOrGetter = strncmp(selectorName, "set", 3) == 0 ||
            class_getProperty(oldClass, selectorName) != nil
        if !setterOrGetter,
            let method = class_getInstanceMethod(oldClass, selector),
            let existing = unsafeBitCast(method_getImplementation(method),
                                         to: UnsafeMutableRawPointer?.self),
            let selsym = originalSym(for: existing) 
```

**Comment by johnno1962** [comment]
Ha! You're very right, I'm erring on the side of caution there. I've re-enabled getters/setters for Swift as they are required for SwiftUI injection (on device) which had been broken since November but previously worked quite well. If you want to take that code out on your clone and continue testing it should be fine; It's not a very elegant piece of code to leave in. If you don't turn up any problems I'll take this new code out the release the new build.

**Comment by johnno1962** [comment]
I've pushed removing the getter/setter inhibiting code to HotReloading, tag 4.9.3

**Comment by johnno1962** [comment]
I've released the app and haven't thought of anything else I could look at so I'll close this issue for now. Thanks again!

**Comment by qmkCamel** [comment]
So the method added or deleted in a class is not in the plan for now?

**Comment by johnno1962** [comment]
Hi, I tried some things on a new branch `objc-fixes2` as at the moment, class meta-data is not initialised correctly but couldn't get the runtime to stop crashing when you try to extract the method list so for now this will have to elude us. It's very much an edge case on an edge case on an edge case if you ask me. Technically, you can only inject changes to implementations, not the interface is the line I draw. If you want to take a look at it the sources for the Object-C runtime and the dynamic linker are available e.g. https://opensource.apple.com/source/objc4/objc4-818.2/

**Comment by johnno1962** [comment]
I gave up on initialising the class and came up with another solution on the `objc-fixes2` branch if you want to check it out.

**Comment by qmkCamel** [comment]
I tried using the HotReloading as a package with a build phase and without download the InjectionIII App, and it works.
So, after the device injection fallback to dlopen, maybe this way is the simplest way to hot reload ?

**Comment by johnno1962** [comment]
The build phase is just the app wrapped in a Swift Package. I added the preference to have the App opt into opening the HotReloading port as an early beta of Xcode 14 would hang when the build phase started a daemon. I'm undecided as to which is easier to explain to people - At the moment both work. Using the package in the simulator, you don't even need the App or the build phase as it runs as so-called "standalone" injection.

**Comment by qmkCamel** [comment]
Got it. Thanks for your detailed interpretation.
