### ISSUE TITLE
Re-compilation failed (see: /var/folders/8j/v_ncg3bj57n4f8nznshn8vph0000gn/T/com.johnholdsworth.InjectionIII/command.sh)

### ISSUE THREAD

**Issue by Jackie-Lee-Mr** [johnno1962/InjectionIII#434]
Re-compilation failed (see: /var/folders/8j/v_ncg3bj57n4f8nznshn8vph0000gn/T/com.johnholdsworth.InjectionIII/command.sh)

**Comment by johnno1962** [comment]
Hi, can you tell me any error message? Have you looked in the command.sh file?

**Comment by Jackie-Lee-Mr** [comment]
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/17540307/212859737-16378cf6-4991-4752-851f-08aff2d73083.png">

**Comment by johnno1962** [comment]
This is likely to be a problem with characters like () in the path to the project which is difficult to support. Can you try running the command.sh file on the command line (bash command.sh) and see if it prints out an error to the console or to the log file it re-directs output to?

**Comment by Jackie-Lee-Mr** [comment]
> bash command.sh

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/17540307/213075146-37ade068-2dd9-45dc-9b95-c91c8d61dc3d.png">

**Comment by Jackie-Lee-Mr** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/17540307/213077224-04f5961b-21ad-484b-b1ff-91cde4197f5b.png">
