### ISSUE TITLE
M1 errorload

### ISSUE THREAD

**Issue by DSPerson** [johnno1962/InjectionIII#437]
injectionlll version: latest
xcode: 14.2
m1 macos 

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/17868782/218022679-c3780e0c-866e-4631-9d8f-3b8e05ffd1a1.png">

error 
> Error loading /Applications/InjectionIII.app/Contents/Resources/maciOSInjection.bundle/maciOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/maciOSInjection.bundle/maciOSInjection, 0x0109): tried: '/Users/zuiyou/Library/Developer/Xcode/DerivedData/22222-cfqtyqhblbsaotfdysbtiyeytxkd/Build/Products/Debug-iphoneos/maciOSInjection' (no such file), '/usr/lib/system/introspection/maciOSInjection' (no such file), '/System/iOSSupport/Applications/InjectionIII.app/Contents/Resources/maciOSInjection.bundle/maciOSInjection' (no such file), '/Applications/InjectionIII.app/Contents/Resources/maciOSInjection.bundle/maciOSInjection' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0010F370, codeBlobSize=0x00008190 for '/Applications/InjectionIII.app/Contents/Resources/maciOSInjection.bundle/maciOSInjection')

**Comment by johnno1962** [comment]
Hi, maciOSInjection.bundle is only available in the GitHub binary releases. A few questions: Is this the App Store version or the app 4.5.2? Why are you trying to load maciOSInjection.bundle? What source is trying to load that? Did you use the "Prepare Project" menu item which I should update? Are you trying to use macCatalyst?

**Comment by johnno1962** [comment]
Seems like you're using macCatalyst. Find the source that is loading maciOSInjection and change it to:
```
                            guard objc_getClass("InjectionClient") == nil else {
                                return
                            }
                            #if os(macOS) || targetEnvironment(macCatalyst)
                            let bundleName = "macOSInjection.bundle"
                            #elseif os(tvOS)
                            let bundleName = "tvOSInjection.bundle"
                            #elseif targetEnvironment(simulator)
                            let bundleName = "iOSInjection.bundle"
                            #else
                            let bundleName = "maciOSInjection.bundle"
                            #endif
```
I'll update the app.

**Comment by DSPerson** [comment]
1. use Github binary release
2. Why are you trying to load maciOSInjection.bundle? my app dont't support ios simulator, so i use `my Mac Designed for iPhone`
3. I don't use macCatalyst, because some framework don't support macCatalyst
4. I used Prepare Project at menu
> I created a new project and select `my Mac Designed for iPhone`, same error use
```
                            guard objc_getClass("InjectionClient") == nil else {
                                return
                            }
                            #if os(macOS) || targetEnvironment(macCatalyst)
                            let bundleName = "macOSInjection.bundle"
                            #elseif os(tvOS)
                            let bundleName = "tvOSInjection.bundle"
                            #elseif targetEnvironment(simulator)
                            let bundleName = "iOSInjection.bundle"
                            #else
                            let bundleName = "maciOSInjection.bundle"
                            #endif
```
<img width="992" alt="image" src="https://user-images.githubusercontent.com/17868782/218360867-7281b1e4-a18a-4f3a-a3ab-9bfaea26ed1c.png">

**Comment by johnno1962** [comment]
Sorry, I misinterpreted the error message, this is a code signing problem specific to this configuration. To use injection iOS on Mac, you need to add the build phase below to resign the injection bundle and set a preference as it mentions in the project README.
```
export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
INJECTION_APP_RESOURCES=/Applications/InjectionIII.app/Contents/Resources
/usr/bin/codesign --force --sign $EXPANDED_CODE_SIGN_IDENTITY  $INJECTION_APP_RESOURCES/maciOSInjection.bundle/maciOSInjection
/usr/bin/codesign --force --sign $EXPANDED_CODE_SIGN_IDENTITY  $INJECTION_APP_RESOURCES/maciOSSwiftUISupport.bundle/maciOSSwiftUISupport
/usr/bin/codesign --force --sign $EXPANDED_CODE_SIGN_IDENTITY $INJECTION_APP_RESOURCES/maciOSInjection.bundle/Frameworks/SwiftTrace.framework/SwiftTrace
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" $EXPANDED_CODE_SIGN_IDENTITY
```
You may also need to type the following If you've used the App Store version of the app in the past:
```
rm ~/Library/Containers/com.johnholdsworth.InjectionIII/Data/Library/Preferences/com.johnholdsworth.InjectionIII.plist
