### ISSUE TITLE
Work with files outside of project directory

### ISSUE THREAD

**Issue by gpake** [johnno1962/InjectionIII#44]
### Problem
I have a main project, but some supplemental files are maintained in other directory.
* Root Project: `~/projects/theMainProject/mainProject.workspace`
* Sub Project: `~/projects/otherProject/someFiles.m`

so nothing happened while saving sub project files.

### What I've try:
Rebuild InejctionIII's filewatcher path, observer the `RootProject/../../`, that is `~/projects/`, and save the files.
* **[Works as usual]** Saving `appdelegate.m` in main project
    * file compiled
    * duplicate warning printed 
    * `-injected` called.
*  **[NOT totally Work]** Saving `someFiles.m` in other directory
    * file compiled
    * duplicate warning printed
    * `-injected` **NOT** called

but `someFiles.m` won't have the `-injection` method called, meanwhile save the `appdelegate.m` works fine.

I'm thinking if I should modify the `iOSInjection.Bundle`. But no idea, hope help.

**Comment by johnno1962** [comment]
If the duplicate warning message is printed and the class name is correct then injection has occurred. There are other reasons why -injected might not have been called as it uses a sweep which might not have included the instance you’re expected to see injected. Try using INJECTION_BUNDLE_NOTIDICATION instead.

**Comment by gpake** [comment]
Cool, `INJECTION_BUNDLE_NOTIFICATION` works as propose.
But insert `addObserver:` and trigger it off manually first is a little bit bother.

the reason why my class been swept is we are using KVO, though it uses `isa swizzling`, but the class not existed with the origin name, so the sweeper won't let the `NSKVONotifying_SomeFile` pass.

Maybe the sweeper should let `NSKVONotifying_OriginClassName` pass ?

**Comment by gpake** [comment]
I've found these sweeper codes, thanks.
here is the demo, check it out at `DetailViewController:35`, this is a copy of your `GettingStarted` project.
https://github.com/gpake/InjectionGettingStarted/blob/master/GettingStarted/DetailViewController.swift#L35

**Comment by johnno1962** [comment]
Here is the fix:
```
            let injectedClasses = oldClasses.filter {
                class_getInstanceMethod($0, #selector(SwiftInjected.injected)) != nil }

            func kvo_getClass(_ instance: Any?) -> AnyClass {
                var cls = object_getClass(instance)!
                if NSStringFromClass(cls).hasPrefix("NSKVONotifying_") {
                    cls = class_getSuperclass(cls)!
                }
                return cls
            }

            // implement -injected() method using sweep of objects in application
            if !injectedClasses.isEmpty {
                #if os(iOS) || os(tvOS)
                let app = UIApplication.shared
                #else
                let app = NSApplication.shared
                #endif
                let seeds: [Any] =  [app.delegate as Any] + app.windows
                SwiftSweeper(instanceTask: {
                    (instance: AnyObject) in
                    if injectedClasses.contains(where: { $0 == kvo_getClass(instance) }) {
                        let proto = unsafeBitCast(instance, to: SwiftInjected.self)
                        proto.injected?()
                    }
                }).sweepValue(seeds)
            }
```
I can update the Xcode 10 version for you if you like but sounds like you know what you’re doing. Thanks for reporting this.

**Comment by johnno1962** [comment]
I can’t see the double calling you mention. I’ve pushed the change to the github repo if you want to pick it up.

**Comment by gpake** [comment]
* first one call from: `iOSInjection`closure #1 (Swift.UnsafePointer<Swift.Optional<Swift.AnyObject>>) -> () in (extension in iOSInjection):__ObjC.NSObject.legacySwiftSweep() -> () + 208`
* second call from: `iOSInjection`iOSInjection.SwiftSweeper.sweepValue(Any) -> () + 2546`

**Comment by gpake** [comment]
* first call trace: https://gist.github.com/gpake/ebf64df9f3595033391ec45830cad4b3
* second call trace: https://gist.github.com/gpake/59b5d528f97c69d545c4a8b48e5fb308

**Comment by gpake** [comment]
Got it, this `GettingStarted` demo maintained 2 instance of `DetailViewController` when you enter the `DetailViewController`.
**There is NOT double calling bug.**
Thanks a lot

**Comment by johnno1962** [comment]
Cool. You had me worried there. I’ll be releasing a new version probably under a new name a little after Xcode 10 comes out.

**Comment by gpake** [comment]
Maybe InjectionIII s or InjectionX 🤣

**Comment by johnno1962** [comment]
I like the sound of InjectionX
