### ISSUE TITLE
[Feature Request] Selecting a project folder when workspace is not a direct decedent 

### ISSUE THREAD

**Issue by hilaza** [johnno1962/InjectionIII#440]
I have a project which has the following structure:

main folder
\>some source code folder
\>folder
\>>sub folder
\>>>workspace file + project file
\>>>another source code folder

My issue is that I would like to open the project from the main folder, since I have some source code directly under it, however when I try I get:

> Please select a directory with either a .xcworkspace or .xcodeproj file, below which, are the files you wish to inject.

Is there any way I could setup injection for these top level files without changing my project file hierarchy?

**Comment by johnno1962** [comment]
Hi, you should be able to. Use the "Open Project" menu item to select to project root containing all files you may want to inject. This sets up the "file watcher". If injection doesn't find a workspace file in that directory it will ask you to select it separately in another prompt.

**Comment by hilaza** [comment]
Thank you! Got it to work by using "Add Directory".
