### ISSUE TITLE
Code injection breaks when switching platforms

### ISSUE THREAD

**Issue by samwyndham** [johnno1962/InjectionIII#441]
Hi and thanks for the great software!

I have found that code injection breaks when switching platforms between `iOS` and `mac catalyst`.

# Steps to reproduce

1. Download [GettingStarted-edited.zip](https://github.com/johnno1962/InjectionIII/files/11042072/GettingStarted-edited.zip). This is the project downloaded from http://johnholdsworth.com/GettingStarted.zip and edited to have a Mac Catalyst target with correct entitlements.
2. Run a simulator build
3. Update the label text in `DetailViewController.swift` and save
4. Stop the build
5. Run a mac catalayst build
6. Update the label text in `DetailViewController.swift` and save

# Expected outcome

Code injection works after both step `3` and `6` above and the changes are reflected in the running build.

# Actual outcome

Code injection works after step `3`. However it fails after step `6`:

```
dlopen(/Users/Foo/Library/Developer/CoreSimulator/Devices/54434539-0A36-4C88-971E-DA55A0099E02/data/Containers/Data/Application/76A93123-6473-4C31-81F7-C8BE4D651C0A/tmp/eval101.dylib, 0x0002): tried: '/Users/Foo/Library/Developer/Xcode/DerivedData/GettingStarted-blibbyfieadznkgjnsnscilvcxxa/Build/Products/Debug-iphonesimulator/eval101.dylib' (no such file), '/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection/eval101.dylib' (no such file), '/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.5.simruntime/Contents/Resources/RuntimeRoot/Users/Foo/Library/Developer/CoreSimulator/Devices/54434539-0A36-4C88-971E-DA55A0099E02/data/Containers/Data/Application/76A93123-6473-4C31-81F7-C8BE4D651C0A/tmp/eval101.dylib' (no such file), '/Users/Foo/Library/Developer/CoreSimulator/Devices/54434539-0A36-4C88-971E-DA55A0099E02/data/Containers/Data/Application/76A93123-6473-4C31-81F7-C8BE4D651C0A/tmp/eval101.dylib' (mach-o file (/Users/Foo/Library/Developer/CoreSimulator/Devices/54434539-0A36-4C88-971E-DA55A0099E02/data/Containers/Data/Application/76A93123-6473-4C31-81F7-C8BE4D651C0A/tmp/eval101.dylib), but incompatible platform (have 'iOS-sim', need 'MacCatalyst'))
```

It seems that InjectIII is building the _patch_ for the wrong platform.

**Comment by johnno1962** [comment]
Hi, you need to switch from loading the the iOSInjection.bundle to loading the macOSInjection.bundle when switching platform. The code to do this automatically is going to be something like the following: https://github.com/johnno1962/HotSwiftUI/blob/main/Sources/HotSwiftUI/HotSwiftUI.swift#L35

**Comment by samwyndham** [comment]
Thank you for the quick response!

I'm running `4.6.2` from https://github.com/johnno1962/InjectionIII/releases/tag/4.6.2. I forgot to mention that I'm running it using the `Standalone Injection` instructions from the readme.

**Comment by johnno1962** [comment]
OK, that's the version with the changes. It must be caching between running the app. Are you able to switch to using the [HotReloading](https://github.com/johnno1962/HotReloading) project instead of loading the bundle from the app? I can push out a changed version with per-platform caching more quickly.

**Comment by johnno1962** [comment]
I've pushed a commit 8cfa5264681ade94872bbd45849c8c964f838984 which you can select as you add the Swift package with the potential fix. If it fixes the problem you're seeing I can tag it and build a new release of the app.

**Comment by johnno1962** [comment]
If you're uncomfortable using the HotReloading package, I've rolled a new release candidate with (hopefully) the fix the fix to the problem you're seeing https://github.com/johnno1962/InjectionIII/releases/tag/4.6.3.

**Comment by samwyndham** [comment]
Thanks @johnno1962 for the super fast update! I'll give that a try and let you know

**Comment by samwyndham** [comment]
I've now tried it on a couple of projects using the release candidate and it is working well. Thanks very much @johnno1962

**Comment by johnno1962** [comment]
Good news. Thanks for taking the time to raise this bug and testing out the new version. 4.6.2 contained a change to use the disk cache more to speed up the first injection by not re-searching the logs each time you restart the app. I guess it was inevitable this would affect something. Closing now. Thanks again!
