### ISSUE TITLE
Crashes when adding anything 

### ISSUE THREAD

**Issue by AdzeB** [johnno1962/InjectionIII#442]
The Project crashed when I had something new in my view, let's say padding(). It will crash

Thread 1: EXC_BAD_ACCESS (code=2, address=0x117630108)
/Users/laptop_name/Documents/Projects//IOS/App_Name/Client-Side/Home/TempHome.swift
💉 Loading .dylib ...
💉 Interposed 22 function references.
💉 Injected type #1 'APP_Name.TempHome'
💉 Injected type #2 'App_Name.TempHome_Previews'
(lldb)

**Comment by johnno1962** [comment]
Hi, are you erasing the type with a call to .eraseToAnyView() as described in the README?

**Comment by AdzeB** [comment]
I am currently using  this: https://github.com/krzysztofzablocki/Inject


do I still need to have eraseToAnyView()

**Comment by johnno1962** [comment]
You need to erase the type or injecting SwiftUI will only work for simple changes (changing font size etc.) but break for say, adding a user interface element which changes the underlying concrete type of the `some View`. In the Inject package the method to do this is called `.enableInjection()` which is equivalent.

**Comment by AdzeB** [comment]
I have it enabled for my content view and the specific view I am working on

**Comment by johnno1962** [comment]
You can't share the code or an example project showing the problem?

**Comment by AdzeB** [comment]
Here is the content view

```

struct ContentView: View {
    @EnvironmentObject var userViewModel: UserDetailsModel
     @State var isAuthenticated = AppManager.IsAuthenticated()

    // Inject
    @ObserveInjection var inject
    @ObservedObject private var iO = Inject.observer

    var body: some View {
        Group {
            if #available(iOS 16.0, *) {
                NavigationStack {
                    if self.isAuthenticated {
                          AnyView(
                                HomeView()
                            )
                    }
                    else {
                        AnyView(WelcomeView())
                    }
                }
            }
            else {
                // Fallback on earlier versions
                NavigationView {
                    if self.isAuthenticated {
                       AnyView(
                                HomeView()
                           )
                    }
                    else {
                        AnyView(WelcomeView())
                    }
                }
            }
        }
        .onReceive(AppManager.Authenticated) {
            self.isAuthenticated = $0
        }
        .enableInjection()
    }
}
```

**Comment by johnno1962** [comment]
Thanks. You only need `@ObserveInjection var inject` or `@ObservedObject private var iO = Inject.observer` though having both shouldn't cause a problem. What is happening at the moment? You're still getting the crash? When you try to add what causes the crash? Try removing the `.onReceive(AppManager.Authenticated) {
            self.isAuthenticated = $0
        }` though that shouldn't make. difference. Do you have a `.enableInjection()` inside HomeView if that's where you're adding the UI element? You need to add it at the end of every level you're injecting.

**Comment by AdzeB** [comment]
The amount of crashes has reduced, but it still occurs.

But I will add it to HomeView now.

**Comment by AdzeB** [comment]
Oh I also get this error sometimes.

💉 Compiling /Users/mac_name/Documents/Projects/IOS/Project_Name/Home/TempHome.swift
💉 ⚠️ Re-compilation failed (see: /Users/mac_name/Library/Developer/CoreSimulator/Devices/7B40C7FA-C3CA-4486-B856-AE91D99BDE25/data/Containers/Data/Application/39476319-D5BC-444B-B824-9870BC7F4E78/tmp/command.sh)

**Comment by AdzeB** [comment]
⚠️ Size of value type Project_Name.Profile has changed (160 != 144). You cannot inject changes to memory layout. This will likely just crash. ⚠️

**Comment by johnno1962** [comment]
Seems like you're trying to add properties to a view over an injection. This is not supported.

**Comment by AdzeB** [comment]
Ohh okay Thanks.
