### ISSUE TITLE
`dlopen` error on only some of objc files

### ISSUE THREAD

**Issue by Kingtous** [johnno1962/InjectionIII#444]
I've encounterd en `dlopen` error when trying to inject **ONLY PART** of the objc file:

```
⚠️ dlopen() error: dlopen(/Users//Library/Developer/CoreSimulator/Devices/0C041798-6919-4393-A5BA-F1B8AA54239D/data/Containers/Data/Application/B19A4B3A-C41C-488B-B3D7-9D7B67546523/tmp/eval106.dylib, 0x0002): symbol not found in flat namespace '_OBJC_CLASS_$_XXXXXXXXX'
💉 ⚠️ Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument or perhaps an XCTest that depends on code not normally linked into your application. Rebuilding and re-running your project (without a build clean) can resolve this.
```
Note that it will happen on only a part of objc files, which includes some normal objc class I write in the same project, I cannot find any difference with the other objc files. I confirm the symbol of `_OBJC_CLASS_$_XXXXXXXXX` is in the executable file via `nm ./executable_ios`, it shows:

```
0000000100ff0890 s _OBJC_CLASS_$_XXXXXXX
```

I also try to rebuild and re-running, but the error is still exists and the error msg is the same.

I've checked every of related dlopen error issue, but no luck:
#407 ...

I'm using InjectionIII.app 4.6.3 from github release, and use `NSBundle` to load the injection tool, using `bazel` to build the executable. `-Xlinker -interposable` is added to the project.

**Comment by Kingtous** [comment]
may also related: #344

**Comment by johnno1962** [comment]
Hi, this typically comes up when using a third party library (e.g. Goole Analytics) which has elected to give "hidden" visibility to a particular class or symbol. This makes it available to link with but not available to references in a dynamic library you are trying to load. In practice, it means you won't be able to inject any source that refers to these classes as there is not much that can be done about it when binaries are distributed that contain symbols you need with "hidden" visibility.

**Comment by Kingtous** [comment]
> Hi, this typically comes up when using a third party library (e.g. Goole Analytics) which has elected to give "hidden" visibility to a particular class or symbol. This makes it available to link with but not available to references in a dynamic library you are trying to load. In practice, it means you won't be able to inject any source that refers to these classes as there is not much that can be done about it when binaries are distributed that contain symbols you need with "hidden" visibility.

Thanks for the explanation. So if class A is referring a class B, which is invisible for other object files, the class A will also be invisible? So what I need to do is to make class B visible to resolve this problem?

**Comment by johnno1962** [comment]
It's not that class A becomes invisible. It's juts that it can't see class B when you try to dynamic load it which is part of injection. I'm afraid there is currently no solution to this problem.

**Comment by Kingtous** [comment]
> It's not that class A becomes invisible. It's juts that it can't see class B when you try to dynamic load it which is part of injection. I'm afraid there is currently no solution to this problem.

I agree with this point. All I am feeling strange is that the class A cannot be found when linking, which is written by myself, and it's in the same project. It just complains `_OBJC_CLASS_$_A` cannot be resolved.

**Comment by johnno1962** [comment]
_OBJC_CLASS_$_A is not the problem, it's the reference to _OBJC_CLASS_$_B inside the source for _OBJC_CLASS_$_A. If you really need to get this working you can replace messages to class objects i.e. [B something] (which create the symbol reference) with [objc_getClass("B") something];

**Comment by Kingtous** [comment]
> _OBJC_CLASS_$_A is not the problem, it's the reference to _OBJC_CLASS_$_B inside the source for _OBJC_CLASS_$_A. If you really need to get this working you can replace messages to class objects i.e. [B something] (which create the symbol reference) with [objc_getClass("B") something]; 

much appreciated! Thanks for the wonderful hot reload framework, which is a life saver tool for me.

**Comment by johnno1962** [comment]
Happy to hear it 👍

**Comment by Kingtous** [comment]
I'll found why dlopen encountered error in my objc projects. That is the `extern`.

I have 2 .mm files, let's say them A.mm and B.mm.

A.mm has a `id<NSObject> memberA`, and B.mm has an `extern` keyword to inform there is a `memberA` to its source. So when B.mm changes, the derived object file of `B.mm` has a linkage with this memeberA, and `SwiftEval` cannot resolve it.

**Comment by johnno1962** [comment]
HI, I'm not sure I understand your setup. Any chance of a small example project that shows the problem?

**Comment by Kingtous** [comment]
> HI, I'm not sure I understand your setup. Any chance of a small example project that shows the problem?

After investigating these days, I've found the key issue for reloading objc files. If my objc referenced a static method like `sharedInstance`, the problem shows.

<img width="520" alt="image" src="https://github.com/johnno1962/InjectionIII/assets/39793325/3cb878ab-f422-4eee-9ff2-bcc8db3c65d5">

The dlopen seems cannot resolve the singleton instance in ObjC.
