### ISSUE TITLE
Re-compilation failed (see: /var/folders/hf/f61grvh50_b57h3f4qr1zx980000gn/T/com.johnholdsworth.InjectionIII/command.sh)

### ISSUE THREAD

**Issue by agan23** [johnno1962/InjectionIII#447]
Re-compilation failed (see: /var/folders/hf/f61grvh50_b57h3f4qr1zx980000gn/T/com.johnholdsworth.InjectionIII/command.sh)

**Comment by johnno1962** [comment]
Hi, This means the re-compilation has failed for some reason (either invalid source or some other problem). You should have seen the erro inside the Xcode console. If not have a look at the command inside the file it mentions and try running it to see the error. It's just a shell script.
