### ISSUE TITLE
[Question] Does InjectionIII supports Bazel 6.1.x?

### ISSUE THREAD

**Issue by Kingtous** [johnno1962/InjectionIII#452]
Recently I upgraded bazel to 6.x in my project, And I've found the same complains as https://github.com/johnno1962/InjectionIII/issues/448 mentioned. It says:

```console
Could not locate compile command for
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
5. The source file is an XCTest that has not been run yet.
6. Xcode has removed the build logs. Edit a file and re-run.
Try a build clean then rebuild to make logs available or
consult: "/Users/xxx/Library/Developer/CoreSimulator/Devices/C9FBD644-3B3C-4223-A894-491E9205E223/data/Containers/Data/Application/9C926E27-345F-4906-87B5-824B76B90369/tmp/command.sh".
```

eval101.error and eval101.sh are both empty.

The project does not use Swift but PURE Objective-C.

I've tried the latest version of InjectionIII on Github, XCode 14.2, iOS Simulator.

Maybe Bazel 6.x.x is not supported by InjectionIII yet?

**Comment by johnno1962** [comment]
Hi, I haven't look at it at all to be honest. Any chance you could prepare a small example Bazel/Objective-C project.I could look at?

**Comment by Kingtous** [comment]
> 

Yes. 4.6.x - latest(4.7.x) of InjectionIII work on my project if I downgrade bazel to 5.0.0.

**Comment by johnno1962** [comment]
At this stage I have no idea what the problem could be and I'm surprised it ever worked with Objective-C TBH. If you could prepare the example project that would be a big help but Bazel support is not really core InjectionIII functionality. You may be the only person in the world using it!

**Comment by johnno1962** [comment]
It's all a question of what is logged by the Bazel build. If you want to look at this (I remember your PR when I broke Bazel builds a couple of months ago) Start by adding the HotReloading project to your target project and getting it working with Bazel 5, then upgrading to 6.0 and looking at what the scripts see when they try to extract the build command and start debugging. Perhaps you just have to add a verbose loging option somewhere.

**Comment by Kingtous** [comment]
> It's all a question of what is logged by the Bazel build. If you want to look at this (I remember your PR when I broke Bazel builds a couple of months ago) Start by adding the HotReloading project to your target project and getting it working with Bazel 5, then upgrading to 6.0 and looking at what the scripts see when they try to extract the build command and start debugging. Perhaps you just have to add a verbose loging option somewhere.

Yes, i've agree maybe a verbose is needed. Investigating.

**Comment by Kingtous** [comment]
> At this stage I have no idea what the problem could be and I'm surprised it ever worked with Objective-C TBH. If you could prepare the example project that would be a big help but Bazel support is not really core InjectionIII functionality. You may be the only person in the world using it!

Yes, It works with Objective-C too.
