### ISSUE TITLE
Codesign failed. If you are using macOS 11+, Please download a new release from 

### ISSUE THREAD

**Issue by ShengfengLee** [johnno1962/InjectionIII#455]
Hello, when I try to perform a hot update, the console prints the following error.：

Compiler failed to build request
💉 ⚠️ Codesign failed. If you are using macOS 11+, Please download a new release from https://github.com/johnno1962/InjectionIII/releases

Injection version： 4.7.2
Xcode version：Version 14.3.1 (14E300b)

**Comment by johnno1962** [comment]
You no longer need to run the /Applications/InjectionIII.app. If you quit it this problem shouldn't occur.
