### ISSUE TITLE
[Feature Request]: Supporting Bazel Build System with Hot Reloading

### ISSUE THREAD

**Issue by DominatorVbN** [johnno1962/InjectionIII#459]
Currently The Injection III uses last Xcode build log for the swapping and compiling the changed file but this does not work for bazel build system as the logs are not there.

**Comment by johnno1962** [comment]
Hi, Bazel support is very limited https://github.com/johnno1962/InjectionIII/issues/388 and seems like it is about to be made obsolete https://github.com/johnno1962/InjectionIII/issues/452 as Bazel updates. I've seen very little demand for it (three issues in as many years) and it is a difficult problem as without logs Injection cannot work. So TBH I'm unlikely to look at this further without something very concrete in the way of sponsorship.
