### ISSUE TITLE
App Store version do not do anything after selecting project folder

### ISSUE THREAD

**Issue by j531** [johnno1962/InjectionIII#46]
The steps I am taking:

- Install the app from the App Store.
- Open the app. The icon appeared in the status bar at the top. The icon is blue.
- Click it and then click 'Open Project'.
- Navigate to my project folder (containing the xcodeproj / xcworkspace files) and click 'Select Project Directory'.
- Nothing happens. I don't get an option to 'Start Injection' in the menu.  The icon stays blue. Ctrl + = doesn't do anything.

Notes: 

- My project folder has a space in it.
- I'm using the latest version of Xcode (Version 10.0 (10A255)).

Let me know if there's any other debug output that I can provide you with (nothing seems to be appearing in the Xcode console output or in console.app).

**Comment by popor** [comment]
xcode 9 work well.

**Comment by johnno1962** [comment]
Your problem is we need to get a new version out for Xcode 10 and with the AppSore version all you need to do is save the file and it will inject. Ctrl  + = is from the old version.

**Comment by zenangst** [comment]
@j531 @popor, we are currently working on shipping a new application to the App Store, in the meanwhile you can get the new application via direct download here: http://johnholdsworth.com/InjectionX.app.zip

**Comment by zenangst** [comment]
Small update, a new version has been submitted to the App Store. Minor spoiler alert, this new version will support both Xcode 9 and Xcode 10 but you'll have to point to the specific bundle for it to work. More information on this will be posted when the new version is approved.

**Comment by zenangst** [comment]
The README has been updated with instructions for Xcode 10 and older Xcode 9.x. I think we can safely close this issue now as the version referred to earlier is published on the App Store, cheers!
