### ISSUE TITLE
cannot open file while injecting

### ISSUE THREAD

**Issue by skrew** [johnno1962/InjectionIII#461]
Hi,

Using Xcode 15.0.1, latest version of InjectionIII, building for tvOS:

I've been getting this error a lot over the past few versions:

```
💉 Compiling /Users/xxx/Sources/xxx/xxx/Lists/ViewNetworkList.swift
💉 ⚠️ Re-compilation failed (see: /Users/xxx/Library/Developer/CoreSimulator/Devices/DDC81F77-3E6C-4D5E-B232-8C01DF8DB725/data/Containers/Data/Application/EAC4F3E2-3E39-4193-B617-86ECB19C5570/tmp/command.sh)
<unknown>:0: error: cannot open file '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-cvblaumrruyvbifmgnvwtimblmro/Build/Intermediates.noindex/xxx.build/Debug-appletvsimulator/xxx.build/Objects-normal/arm64/sources-4' (No such file or directory)
```

**Comment by johnno1962** [comment]
Hi, I suppose the question is whether this is specific to the new Xcode or there has been a regression in the InjectionIII app. Can you try an old version of the app from https://github.com/johnno1962/InjectionIII/releases to see if you can bisect it?

**Comment by skrew** [comment]
Testing with 4.6.5 from Jun 6, just got the same exactly same error. 
So it can be something with Xcode

**Comment by johnno1962** [comment]
Aha, probably the easiest thing to do is edit a file to add a syntax error and have the injection fail and email the command.sh it mentions to github at johnholdsworth.com so I can look at how that argument is being used and perhaps filter it out.

**Comment by skrew** [comment]
Mail sent. (it's not because a syntax error, it's simply fail on a valid source file :p)

**Comment by johnno1962** [comment]
Hi Eric, I've pushed a new release candidate https://github.com/johnno1962/InjectionIII/releases/tag/4.7.6RC1 with the two recent changes I mentioned via email reverted. Any chance you could give it a try a let me know if it fixes this problem?
