### ISSUE TITLE
[Question] Does Injection recompile the whole module?

### ISSUE THREAD

**Issue by WiesnerPeti** [johnno1962/InjectionIII#462]
While going through the fantastic Readme, I encountered a section explaining how "Injection uses the FSEventSteam api to watch for when a source file has been changed and scans the last Xcode build log for how to **recompile** it and links a dynamic library that can be loaded into your program." My question is, if my main application contains numerous Swift files (not organized in modules) and I want to incorporate this type of injection, will this process be as quick as performing an incremental build using the 'build and run' command in Xcode?

**Comment by johnno1962** [comment]
HI, It should be quicker as you won't need to re-link your application. The compile itself should be marginally faster too as injection arranges to compile only a single source at a time, where as your build normally batches them since Xcode 13.

**Comment by WiesnerPeti** [comment]
Thank you for the quick answer!
