### ISSUE TITLE
Inheritance seemingly not fully supported

### ISSUE THREAD

**Issue by chrisknapp98** [johnno1962/InjectionIII#465]
Hi, I just stumbled across this tool and think it's amazing!
However, it's not working flawlessly for me. This is more of a question instead of a bug report.

When trying to connect it to a more complex environment with dependencies from different pods, then the hot reload is only partially working for me, meaning that I save the file, see that it's compiling and succeeds, but I don't see any changes in Simulator. Only if I navigate back and re-navigate to the changed ViewController, then my changes are reflected in the UI (what still is quite an upgrade).

Here's a vague draft to describe my specific case

**External Pod:**
```swift
protocol ViewControllerBase { }

open class SomeViewControllerBase: UIViewController, ViewControllerBase { }
```

**My Pod:** 
```swift
class MyViewControllerBase: SomeViewControllerBase { }

class TestViewController: MyViewControllerBase {
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .systemGreen // not changed on file save 
    }
}
```

When I change `TestViewController` at runtime to inherit from UIViewController, then curiously the app doesn't crash and I get instant changes on file saves - the wanted behaviour. 
Additionally, I added the external pod, which is an `s.dependency` in my podspec, to my podfile, so that the implementation of `SomeViewControllerBase` is accessible. But that didn't change anything either.
Also when defining the described classes and protocols inside my pod, then I don't run into issues. So it seemingly is related to whether the initial class inheriting from `UIViewController` as part of my module.

Have you ever come across something like that and do you have a suggestion to fix the issue?

**Comment by johnno1962** [comment]
Hi, you seem to have a couple of issues mixed into one. Firstly, injection only updates function implementations but the new implementations are not re-called automatically. So, it cannot arrange for your ViewController to redraw and update the display on its own; You need to use one of the techniques described in the project README. That aside, inherited methods, particularly across modules is a tricky problem and you may have run across a limitation. Remember though, when injecting an inherited method remember to inject the superclass then inject the subclass again so it gets a change to update the subclass' vtable  if you want to see it work.

**Comment by chrisknapp98** [comment]
My issue is completely unrelated to calling any methods, I know that. I just wanted to make clear how this specific architecture looks like. 

I only expect a ViewControllers `viewDidLoad()` method to be re-executed because of the extension mentioned in the README
```swift
#if DEBUG
extension UIViewController {
    @objc func injected() {
        viewDidLoad()
    }
}
#endif
```
However, the `viewDidLoad()` is not executed when using those types from another module.

Unfortunately in my context adding a library to production code is not an option, so I am only able to load InjectionIII's bundle in `AppDelegate`, add the extension and the linker flags to the example project.

Have you got any further suggestion or am I maybe missing something?

**Comment by johnno1962** [comment]
Let's separate this into two problems. Are you saying the injected() method you add in your example project dependant on a pod containing the ViewControllers you're using isn't called? That would be unusual. Leave the sayHi() method to one side for a second.

**Comment by chrisknapp98** [comment]
yeah exactly. I updated the code to reduce confusion. There's no issue with calling any inherited methods whatsoever. 

My only problem is that I need to go back and push the ViewController again to see the changes

**Comment by johnno1962** [comment]
I can see how that might happen though I need to think about it some more. The problem won't be with the \@objc injected method but the dispatch of the viewDidLoad() through the vtable. Recapping, which "the" ViewController do you need to push again to see the changes? If you see the changes, how does this not meet your expectations?

**Comment by chrisknapp98** [comment]
I need to push the `TestViewController` again (the one I am working on). 
However, if at runtime I change `TestViewController` the following way, then my changes within `viewDidLoad()` update right-away. 
```swift
class TestViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .systemGreen // not changed on file save 
    }
}
```

**Comment by johnno1962** [comment]
So if TestViewController inherits UIViewController directly it works but if it inherits MyViewControllerBase it doesn't?

**Comment by chrisknapp98** [comment]
exactly!

**Comment by chrisknapp98** [comment]
Unfortunately I cannot share the code with you. But maybe I find some time in the coming days to reproduce this in a sample project set up with cocoapods.
But I think now you're understanding my problem.

**Comment by johnno1962** [comment]
Very strange, I may take a look tomorrow if I can think of something fixable. It would be very helpful to me if you were able to prepare a small project demoing the problem.

**Comment by chrisknapp98** [comment]
Sure, but give me some days! You can also wait to not waste your time in case my problem lays somewhere else and I don;t manage to reproduce it

**Comment by johnno1962** [comment]
Thanks! That would be very helpful; no hurry. By the way, I don't have Cocoapods installed on my machine but you should be able to replicate your problem by putting your superclasses in a framework target which is what Cocoapods does anyway.

**Comment by johnno1962** [comment]
Just a thought. Have you tried adding the injected() method to your TestViewController?
```Swift
    @objc func injected() {
        viewDidLoad()
    }

**Comment by johnno1962** [comment]
Hi, I've tried a few things with a test project and not been able to replicate this problem. If you get a change to produce a small example app that shows the problem but doesn't use Cocoapods and post it here or email it to me via github at johnholdsworth.com I can take a look at it for you.

**Comment by chrisknapp98** [comment]
> Just a thought. Have you tried adding the injected() method to your TestViewController?
> 
> ```swift
>     @objc func injected() {
>         viewDidLoad()
>     }
> ```

Yeah I tried that and it made no difference. It recognizes that I'd need to override it and when changing the extension from `UIViewController` to be on `TestViewController` instead, it still doesn't execute the viewDidLoad()

**Comment by chrisknapp98** [comment]
> Hi, I've tried a few things with a test project and not been able to replicate this problem. If you get a change to produce a small example app that shows the problem but doesn't use Cocoapods and post it here or email it to me via github at johnholdsworth.com I can take a look at it for you.

Just spent some hours vaguely recreating the setup first with just two modules and that worked as you have stated already. 
Then I tried to setup a comparable cocoapods environment and that also works fine. So the issue might be something different and I'll see if I casually find out what is causing it in the coming weeks.

So I guess we can close this issue for now and we'll see if I come back with a solution.

Thank you very much for your assistance!
