### ISSUE TITLE
Usage with pure Swift Package executable

### ISSUE THREAD

**Issue by robertjpayne** [johnno1962/InjectionIII#466]
We have a server side swift project (not Vapor) that we use Xcode for editing. I have the bundle loading and getting the correct log messages like:

```
💉 InjectionIII connected /Users/robertjpayne/Projects/sensemedical/*****
💉 Watching files under the directory /Users/robertjpayne/Projects/******
```

But the file watcher doesn't seem to ever trigger and reload when saving files. Our server code uses blocking IO and doesn't use SwiftNIO and doesn't have a Darwin-esque runloop going so I'm wondering if that is a requirement for the file watcher?

**Comment by johnno1962** [comment]
Hi, The file watcher needs a run loop to run on and by default uses the main run loop/queue which is probably being monopolised by your server. For vapor to work, when it detects a vapor symbol in the binary it switches to using it's own queue which I wonder if it should do all the time anyway as the injection code isn't particularly thread sensitive apart from the "sweep" of I've objects. I'll roll a new version of the app later today that tries this to see if it resolves your problem.

**Comment by johnno1962** [comment]
Hi Robert, Ive prepared a [new release candidate](https://github.com/johnno1962/InjectionIII/releases/tag/4.7.6RC9) that always uses its own queue on macOS for you to try. Let me know how you get on. It seems the best use case for InjectionIII on macOS is Web servers so I'd like to see this working for you.

**Comment by robertjpayne** [comment]
@johnno1962 it just crashes the app on launch:
<img width="781" alt="Screenshot 2023-11-14 at 10 35 50 AM" src="https://github.com/johnno1962/InjectionIII/assets/214288/a9584c51-a6ed-47e1-840a-5b641cc70f5b">

**Comment by johnno1962** [comment]
Your app or the InjectionIII app?

**Comment by robertjpayne** [comment]
Also for what it's worth we run on the main thread and block it with a loop that accepts requests from a socket and then processes them. All I/O is blocking.

I managed to get it working by moving our server code to a background thread and doing a run loop on the main thread with Mac App Store injection app:

```swift
        #if DEBUG && os(macOS)
        Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle")?.load()
        DispatchQueue.global().async {
            do {
                try self.run()
            } catch {
                print(error)
                exit(1)
            }
        }
        while true {
            RunLoop.current.run(until: Date.distantFuture)
        }
        #else
        try self.run()
        #endif
```

It's not ideal, while our app is fine with this I do know there is some parts that expect some access to the main queue (namely a database driver)

**Comment by johnno1962** [comment]
Interesting, are sure you loading /Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle and running the new version of the app in /Applications/InjectionIII.app.

**Comment by robertjpayne** [comment]
@johnno1962 ohhh I launched the app before I moved it into /Applications… it works!

Side note because I can't find it in the documentation -- is it possible to inject the contents of a swift struct function? It works if I change to a class but not a struct (it complains about -interpose).

It very well could be -interpose issues as it's not the easiest to fool the linker with a pure Swift Package project.

**Comment by robertjpayne** [comment]
It's all good was my bad flags! It works!! This is fantastic thanks again.

**Comment by johnno1962** [comment]
Yes, struct are fine but you need to add a linker option to your targets in the package:

    linkerSettings: [.unsafeFlags(["-Xlinker", "-interposable"],
            .when(platforms: [.macOS], configuration: .debug))]

**Comment by johnno1962** [comment]
OK, you're already onto it. Enjoy!
