### ISSUE TITLE
Injection does not integrate

### ISSUE THREAD

**Issue by johntheocs** [johnno1962/InjectionIII#469]
First, I want to thank you for this amazing tools. However, I have problems to start it. I downloaded Injection app from github and installed it without problems. I added the code to my project, but I cannot find "💉 InjectionIII connected" in the output when I run my app in the iPhone simulator. Also, I tried to start the Injection application on Mac, it is running which I can see from "ps", but I cannot find the icon from the systray. Don't know what's wrong. Also, I don't know if there is any log file of Injection. Any information will be appreciated.

macOS 14.1.2 
Xcode 15.0.1
M1X Chip

**Comment by johnno1962** [comment]
HI, the injection application runs on the menu bar at the top right of your screen if it is running. You no linger need to run the app though. Injection can run "standalone" inside the simulator. If you have loaded the bundle successfully you should see a message such as the following:
```
💉 HotReloading available for sources under [...

**Comment by johntheocs** [comment]
I cannot find "HotReloading" either. Also, I know it is not necessary to run the app. But when I run it, I cannot find the application icon on the menu bar there. Don't know what's wrong.

**Comment by johnno1962** [comment]
It will be a blue syringe not orange until you connect.

**Comment by johntheocs** [comment]
I see the icon now after quit Hidden Bar application. But Injection is still not connected. Can you help me figure out what's wrong? 

<img width="1144" alt="Screenshot 2023-12-01 at 8 00 48 PM" src="https://github.com/johnno1962/InjectionIII/assets/115430128/175711fb-f861-40a7-a8e3-f053182666ae">

**Comment by johntheocs** [comment]
Then what's the right way to do it?

**Comment by johnno1962** [comment]
Wrap it in a Dispatch.main.sync {}

**Comment by johntheocs** [comment]
I did, but still no luck. I listen to the notification in my base view controller. When injected, the method in the base view controller and the method in the sub view controller are both called. In the method, I call both "tableView.reloadData" and "[self.view setNeedsDisplay], still no UI change until I restart the application. What's wrong? I really need it working wholeheartedly. Thank you.

**Comment by johntheocs** [comment]
working now. Thank you.
