### ISSUE TITLE
not work for xcode( Version 10.0 (10A255)) 

### ISSUE THREAD

**Issue by xuhongfei** [johnno1962/InjectionIII#47]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found

**Comment by zenangst** [comment]
Hey @xuhongfei, because Swift is not AB stable yet we need to make a new version of Xcode for it to work. We are currently working on shipping a new app to the App Store but you can get the new version via direct download here: http://johnholdsworth.com/InjectionX.app.zip

**Comment by xuhongfei** [comment]
Got it. THX

**Comment by zhangferry** [comment]
I got this(xcode10 + InjectionX):

> Error loading /Applications/InjectionX.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionX.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Symbol not found: __T0SiMa
  Referenced from: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCoreAudio.dylib
  Expected in: /Users/zhangferry/Library/Developer/CoreSimulator/Devices/D38D1A9F-672F-4B42-85A7-726C967763D5/data/Containers/Bundle/Application/8D3B7455-5DDD-4834-84C1-62827E08876D/UITest.app/Frameworks/libswiftCore.dylib
 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCoreAudio.dylib

**Comment by johnno1962** [comment]
Hi, you need to change the path the the bundle in your AppDelegetae.swift to /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle

**Comment by zhangferry** [comment]
Thanks for your reply, I set the wrong path before. Now, I fix it!

**Comment by UOCecalero** [comment]
Same issue on AppCode 2019.3.7

Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found

**Comment by johnno1962** [comment]
Hi, Is this the app store version? Is your Xcode at the standard path /Applications/Xcode.app?

**Comment by UOCecalero** [comment]
I have many Xcode versions

**Comment by johnno1962** [comment]
Do you have one of these many Xcode’s at /Applications/Xcode.app or a link at that path to one? You can check where you’re trying to load from using `otool`.
```
otool -l  /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
```
At the end there should be an LC_PATH entry something like:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks for XCTest.framework

**Comment by UOCecalero** [comment]
All of them are at /Applications but none of them are downloaded from the store.

LC_PATH doesn't appear

**Comment by johnno1962** [comment]
Is this the App Store version of InjectionIII? If so, do you have an Xcode or a link to one at the path /Applications/Xcode.app?

**Comment by UOCecalero** [comment]
Yes, it is.

ls -la /Applications
drwxr-xr-x   3 esfds  staff    96 20 oct  2018 Xcode 10.1.app
drwxr-xr-x   3 esfds  staff    96 11 sep  2019 Xcode 11.0.app
drwxr-xr-x   3 esfds  staff    96 21 sep  2019 Xcode 11.1.app

I don't think so

**Comment by johnno1962** [comment]
For injection to work you must have an Xcode at the path /Applications/Xcode.app.

**Comment by UOCecalero** [comment]
ln -s /Applications/Xcode\ 10.1.app Xcode.app
Worked for me
