### ISSUE TITLE
Bug: Injection fails to connect when running on "My Mac (Designed for iPad)" if there is no iPhone connected (when using the copy_bundle.sh script).

### ISSUE THREAD

**Issue by oryonatan** [johnno1962/InjectionIII#470]
Got an odd bug:

When I have an iOS17 device connected to the my mac OS machine (MacOS 14.0, iOS 17.0.3) and have injection loaded using the copy_bundle.sh script, I can get Injection running when the target is the iPhone or the Mac.

When I disconnect the iPhone, Injection stops working also when running on `My Mac (Designed for iPad)` target.

Seems like we have some issue with the connection?

Using release 4.8.0.

**Comment by johnno1962** [comment]
Hi, I'm can't replicate that. If I disconnect the phone I still see the bundle broadcasting and connecting for `My Mac (Designed for iPad)`. Are you running the app??

**Comment by johnno1962** [comment]
A late night thought. I don't suppose your internal network NATs using a 10.*.*.* address. If so it would be excluded from the broadcasts as that would usually be the cellular connection. The real solution is to reinstate the isiOSAppOnMac code in ClientBoot.mm and bypass the broadcasting and use localhost here: https://github.com/johnno1962/HotReloading/blob/b9da1572fac91c23922351dff7ec11dc29959c9c/Sources/HotReloadingGuts/ClientBoot.mm#L84

**Comment by oryonatan** [comment]
well, seems like our  internal network is indeed using the `10.*.*.*` subnet.

**Comment by oryonatan** [comment]
regarding reinstating `isiOSAppOnMac` that seems to me like the correct solution ... but what is the proper thing do here? connect to `127.0.0.1`?

**Comment by oryonatan** [comment]
BTW, I've tried adding such code and recompiling, but it seems like when compiling (in XCode 15.1 at least) the generated app is smaller than the one in the 4.8 release, and does not contain the `maciOSInjection.bundle` file

**Comment by johnno1962** [comment]
You need to uncomment a line in build_bundles.sh to create the "maciOS" bundle for GitHub releases. Never mind, I've created a new release candidate 5.8.1 for you to try. Let me know if it fixed this hiccough.

**Comment by oryonatan** [comment]
4.8.1 works fine :)

**Comment by oryonatan** [comment]
tested on `My Mac (Designed for iPad)` and on an iPhone 12, both seems to work well.

**Comment by johnno1962** [comment]
Great. Ironically we've come full circle. This would have been the better fix for `My Mac (Designed for iPad)` problem in the original issue you raised a couple of months ago. 👍 I'll also think about uncommenting the maciOS bundle in the checked-in (non App Store) build.
