### ISSUE TITLE
Support for visionOS

### ISSUE THREAD

**Issue by Perjan** [johnno1962/InjectionIII#477]
Currently visionOS is not supported. I was wondering if there is any plan to support it?

If I run the app in the simulator, Xcode prints a warning like this
`Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection (82):  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 0x0109): tried: '/Users/perjanduro/Library/Developer/Xcode/DerivedData/MoneySpace-aksawvfkswfduugalzgqfgxexrtf/Build/Products/Debug-xrsimulator/iOSInjection' (no such file), '/Library/Developer/CoreSimulator/Volumes/xrOS_21N305/Library/Developer/CoreSimulator/Profiles/Runtimes/xrOS 1.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection/iOSInjection' (no such file), '/Library/Developer/CoreSimulator/Volumes/xrOS_21N305/Library/Developer/CoreSimulator/Profiles/Runtimes/xrOS 1.0.simruntime/Contents/Resources/RuntimeRoot/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection' (no such file), '/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection' (mach-o file (/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection), but incompatible platform (have 'iOS-sim', need 'xrOS-sim'))`

Thanks for this amazing tool. It has already saved me tons of time.

**Comment by johnno1962** [comment]
Hi, This is interesting. I thought I found you could use the iOSInjection.bundle in the past. Which version of Xcode is this? I'll add a new bundle to the build script. In the meantime you can add the https://github.com/johnno1962/HotReloading project which is InjectionIII as a swift package which seems to work. I'll get back to you about the bundle.

**Comment by Perjan** [comment]
I have the latest Xcode version, 15.2.
I am using the Inject package by [Krzysztof Zabłocki](https://www.merowing.info/).

**Comment by johnno1962** [comment]
I'm nearly at the point where I can make a release candidate supporting an xrOSInjection.bundle in the InjectionIII.app though Inject itself will need a minor change to switch to loading it. If you can hang till tomorrow then wait otherwise see how you go using the HotReloading project.

**Comment by Perjan** [comment]
I can wait until tomorrow, no worries ;), Looking forward to the new version. Please let me know when you release it. Thanks again John.

**Comment by johnno1962** [comment]
We're nearly there, the [new release candidat](https://github.com/johnno1962/InjectionIII/releases/tag/4.8.2RC1) is available and I have a fork of [Inject](https://github.com/johnno1962/Inject) you can use for now.

**Comment by johnno1962** [comment]
OK, Inject is merged you should just be able to "update package" once you've downloaded the app.

**Comment by johnno1962** [comment]
@Perjan, have you ever wanted to inject on a visionOS device? It may work. If you're interested I can talk you through it as I'm curious if it works myself. There is a new release candidate with support for this in theory and you should be able to follow the instructions in the project README for injection on an iOS device.

**Comment by johnno1962** [comment]
Ah, that rather puts a cap on that! When you get one let me know and we can try it out.

**Comment by johnno1962** [comment]
FYI, seems you could already inject on Vision PRO is you use the HotReloading project. https://github.com/johnno1962/InjectionIII/issues/490#issuecomment-1981141886
