### ISSUE TITLE
EXC_BAD_ACCESS after add var in swift class

### ISSUE THREAD

**Issue by happy201993** [johnno1962/InjectionIII#479]
![image](https://github.com/johnno1962/InjectionIII/assets/10241217/b2b61c41-b261-428b-92fe-2cf06433dfc5)

ViewController was coded by Objective-C, and create some AAATagItemModel and send to a swift view.

1. quit current ViewController.
2. add     var title2: String = ""    to this class, and i can see compile success in console
3. app was crashed when i enter ViewController again 
![image](https://github.com/johnno1962/InjectionIII/assets/10241217/f0ee3665-1198-4aba-a4d2-8c13dabddb5b)

**Comment by johnno1962** [comment]
Hi, you won't be able to add properties or make changes to memory layout of a class instance over the course of an injection by adding a property. Did you not receive a warning on the console about this? This includes adding/renaming class methods as it changes the layout of the "vtable" used for member function dispatch.

**Comment by happy201993** [comment]
您好，我已收到您的邮件，会尽快给您回复。

**Comment by happy201993** [comment]
> Hi, you won't be able to add properties or make changes to memory layout of a class instance over the course of an injection by adding a property. Did you not receive a warning on the console about this? This includes adding/renaming class methods as it changes the layout of the "vtable" used for member function dispatch.

OK, Thanks!
