### ISSUE TITLE
error: no such module 'FirebaseFirestoreInternalWrapper'

### ISSUE THREAD

**Issue by lockieluke** [johnno1962/InjectionIII#482]
I have a project that uses `FirebaseFirestore` whenever I make changes to my code when InjectionIII is running, it would complain about `FirebaseFirestoreInternalWrapper` being non-existent

The `FirebaseFirestore` module is only used in one file, I don't mind disabling hot reload for that particular file as I mostly just use hot reload for UI stuff

**Comment by lockieluke** [comment]
Currently using this to stop InjectionIII from complaining
```swift
// hacky way to get around "no such module: FirebaseFirestoreInternalWrapper" when hot reload is enabled
#if canImport(FirebaseFirestoreInternalWrapper)
import FirebaseFirestoreInternalWrapper
import FirebaseFirestore
#endif
```

**Comment by johnno1962** [comment]
Hi, Good news you're found a way to get up and running. Without access to the specifics of your project (which sounds quite complex) there is a limited amount I can do this end..

**Comment by lockieluke** [comment]
would there be a way to disable hot reload for some files

**Comment by johnno1962** [comment]
Other than not saving them or setting their permissions to be not writable? You can turn on/off the file watcher from the injection menu. When it is off you type ctrl-= to force the queued files through. There isn't a way to turn it off for individual files though.
