### ISSUE TITLE
EOF received from server..

### ISSUE THREAD

**Issue by skrew** [johnno1962/InjectionIII#486]
Hi,

In a project i have now most of the time this error:

```
💉 ⚠️ Server has rejected your connection. Are you running InjectionIII.app or start_daemon.sh from the right directory? ⚠️
💉 EOF received from server..
💉 InjectionIII disconnected.
```

Opening the logs in console app, it's more precise:

```
💉 InjectionIII *** Error: SALT or KEY invalid. Are you running start_daemon.sh or InjectionIII.app from the right directory?
``` 

Look like a cache problem ?

**Comment by johnno1962** [comment]
Hi, this is usually because you are running one version of the app but loading the bundle from another. There is a random "salt" generated for each build to prevent compatibility issues.

**Comment by skrew** [comment]
You are right, i'm launching injectionIII.app from CMD + SPACE, looks like it use another version (i think a version build from Xcode when you debug it on my mac). 
Running it directly from /Applications make it working.

Thanks 😅
