### ISSUE TITLE
Is there a way to make injected macOS app not become active when it's reloaded?

### ISSUE THREAD

**Issue by hboon** [johnno1962/InjectionIII#488]
Saving a source file triggers injection and makes the macOS app active, thus stealing focus from the editor, is there a way to disable that?

Rationale:

* I save quite frequently while editing, both because of habit, and because I use Neovim, saving triggers the prettifier + saving is triggered when the editor window loses focus (eg. if I look at docs). So this is causing many unwanted switching to the macOS app being active.
* clicking on the app makes it active anyway (or cmd+click if that's ennough) so there's few reasons to make it active automatically

**Comment by johnno1962** [comment]
Are you using the app? There is a menu item "Order Front". Make sure that's not selected.

**Comment by hboon** [comment]
Yes, I am. That fixes it. Thanks.
