### ISSUE TITLE
InjectionClient/Could not connect: Connection refused 🔥

### ISSUE THREAD

**Issue by arthurschiller** [johnno1962/InjectionIII#490]
Hi,

I finally wanted to implement Injection into my workflow. I think I've followed all the steps from readme but every time in run my project I get this console message:
`InjectionClient/Could not connect: Connection refused
🔥 Unable to connect to InjectionIII app, falling back to standalone HotReloading.`

`Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection (82):  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 0x0109): Symbol not found: _$sSS10SwiftTraceE11OffsetIndexO4lastyACSS_S2btcACmFWC`

Here are the steps I've taken:
1. Get InjectionIII App:
https://github.com/johnno1962/InjectionIII/releases

**2. Install Dependencies:**
https://github.com/johnno1962/HotReloading
https://github.com/krzysztofzablocki/Inject

**3. Add Linker (DEBUG) Flags:**
-Xlinker and -interposable

**4. Load Bundle on App Init**
#if DEBUG
#if os(visionOS)
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/xrOSInjection.bundle")?.load()
#elseif targetEnvironment(macCatalyst)
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle")?.load()
#else
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()
#endif
#endif

I've tested it with Xcode 15.2.0 and Xcode 15.3.0 Beta 2.
OS is Sonoma 14.1.2

It's probably something simple but I would appreciate any hints. Thank you!

**Comment by johnno1962** [comment]
Hi, the connection refused message is normal when you're not running the app. The other message happens when you have added the "HotReloading" Swift package at some point in the past and it picks up the wrong version of the SwiftTrace framework from derived data. You'll need to do a clean build to clear the wrong version out.

**Comment by arthurschiller** [comment]
> Hi, the connection refused message is normal when you're not running the app. The other message happens when you have added the "HotReloading" Swift package at some point in the past and it picks up the wrong version of the SwiftTrace framework from derived data. You'll need to do a clean build to clear the wrong version out.

Hi, thanks for the reply! What do you mean by "when you're not running the app"? Both the InjectionIII app and my projects app in the simulator are running and I selected the associated project directory.
I also tried resetting the Swift Package Manager Cache, cleaned the project, deleted Derived Data and restarted my machine. 🤔

**Comment by johnno1962** [comment]
Hmmm.. Remove https://github.com/johnno1962/HotReloading as a dependency. You either use that or the app bundles. If you use both at the same time you get this error.

**Comment by arthurschiller** [comment]
> Hmmm.. Remove https://github.com/johnno1962/HotReloading as a dependency. You either use that (rarely these days) or the app bundles. If you use both at the same time you get this error.

Ah interesting, I saw a video where someone did both and it seemed to work, so I thought that's the way to go. What setup would you recommend? Primarily I would like to use it with the visionOS simulator, the actual Vision Pro device and with a Mac (Catalyst) app.

I tried removing the HotReloading dependency but that yields in the same error (connection refused). If I load the bundle manually I get:
```
`Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection (82):  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 0x0109): Symbol not found: _$sSS10SwiftTraceE11OffsetIndexO4lastyACSS_S2btcACmFWC
  Referenced from: <6E51BEA0-FB33-3620-9771-2B52DA5CF83E> /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Expected in:     <B31C28E6-BD26-31E1-A706-046DFD36C763> /Users/arthurschiller/Library/Developer/Xcode/DerivedData/SGMaterial_Playground-cmnrfbyrdzlqugfcvcotswsakavf/Build/Products/Debug-iphonesimulator/PackageFrameworks/SwiftTrace.framework/SwiftTrace`
```

Very odd. Xcode is installed via Xcodes app(https://www.xcodes.app) if that has any relevance.

**Comment by johnno1962** [comment]
Ignore the "connection refused" if you are not using the app. If you have removed the HotReloading Package did you perform a build clean afterwards? If you have a visionOS device I'd be very interested in knowing if you were able to get that working. There is a release candidate which should have support for that. I can talk you through that once you're up and running.

**Comment by arthurschiller** [comment]
> Ignore the "connection refused" if you are not using the app. If you have removed the HotReloading Package did you perform a build clean afterwards? If you have a visionOS device I'd be very interested in knowing if you were able to get that working. There is a release candidate which should have support for that. I can talk you through that once you're up and running.

Thanks for your help again! :) Got it running now in the Simulator after removing the HotReloading package and doing a clean build. Very cool!
I am a little confused though: There is the standalone app (which I assume I can just use as such), the Inject swift package and then the HotReloading package. Which should I use when? Or are they just different wrappers with the same goal?
Currently I have the Injection 3 App running and use the Inject Swift Package.

In this video he is importing both packages and it seems to work, which got me confused:
https://www.loom.com/share/c3331721a6ff47b9a66b30e7b59c6afc

Device injection (on iOS) seems to be working mostly but fails during loading of .dylib:
💉 Connecting to <…>...
💉 InjectionIII connected <…>
💉 Watching files under the directory <…>
💉 Compiling <…>
💉 Selecting Xcode /Applications/Xcode-15.3.0-Beta.2.app/Contents/Developer
💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/0E0C77D6-6DCF-4858-BA77-146AC2BC4573/tmp/eval101.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval101.dylib' (no such file, not in dyld cache)

Yes, I have a visionOS device and would love to get it working there as well!

**Comment by arthurschiller** [comment]
Update: Got it running now on my Mac and Vision Pro :)
I switched to the HotReloading Package instead of Inject though. But weirdly on my iPhone I still get this dlopen error:
`🔥 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/89D3960F-D1CF-46F5-A331-994FBB129419/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file, not in dyld cache), '/private/var/mobile/Containers/Data/Application/89D3960F-D1CF-46F5-A331-994FBB129419/tmp/eval102.dylib' (code signature in <A0AFCA02-4C0E-319F-A389-D66F89DAA71C> '/private/var/mobile/Containers/Data/Application/89D3960F-D1CF-46F5-A331-994FBB129419/tmp/eval102.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/private/preboot/Cryptexes/OS/private/var/mobile/Containers/Data/Application/89D3960F-D1CF-46F5-A331-994FBB129419/tmp/eval102.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/89D3960F-D1CF-46F5-A331-994FBB129419/tmp/eval102.dylib' (code signature in <A0AFCA02-4C0E-319F-A389-D66F89DAA71C> '/private/var/mobile/Containers/Data/Application/89D3960F-D1CF-46F5-A331-994FBB129419/tmp/eval102.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
🔥 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/89D3960F-D1CF-46F5-A331-994FBB129419/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file, not in dyld cache),`

**Comment by johnno1962** [comment]
OK, so I've read you message properly now. You've got injection working on a Vision Pro! and now it doesn't work on the simulator? That is likely just a code signing problem new to Xcode 15.3 simulators. What configuration are you running at the moment? HotReloading in the simulator without the app? I've checked it and can't see a problem on my machine at the moment.

**Comment by arthurschiller** [comment]
> OK, so I've read your message properly now. You've got injection working on a Vision Pro! and now it doesn't work on a device? That is likely just a code signing problem. What configuration are you running at the moment? HotReloading on a device? I've checked it and can't see a problem on my machine at the moment.

Hi, so it's working on all the Simulators, my Mac and my Vision Pro (on device 🎊). The only time where I'm now getting this issue is on my physical iPhone 14 Pro device. Xcode Beta 15.3.0, Sonoma 14.1.2

I also now removed the HotReloading package and opted for just loading everything manually using the code generated by the Injection app when selecting -> Prepare Project
Still runs fine, only issue left is the dlopen (only!) on the physical iPhone device.

**Comment by arthurschiller** [comment]
Interestingly enough, on the physical Vision Pro device I could load the iOSInjection bundle and it still worked. Probably similar enough ->

`
// Running on Real Device
let resourceName: String
#if os(macOS) || targetEnvironment(macCatalyst)
resourceName = "macOSInjection"
#elseif os(visionOS)
resourceName = "iOSInjection" // seems to work without using xrOSInjection
#else
resourceName = "iOSInjection"
#endif
guard
    let bundlePath = Bundle.main.path(forResource: resourceName, ofType: "bundle"),
    let bundle = Bundle(path: bundlePath), bundle.load()
else {
    fatalError()
}
`

**Comment by johnno1962** [comment]
Very, very weird about the bundles. Where is that code you pasted in coming from? 

And visionOS is actually injecting now? That would be awesome! Not sure what's happening on the iOS device. I've seen the error you're seeing today whereas it's worked before. Trying to factor out between new Xcode, new iOS version etc. It should be code signing correctly.

**Comment by arthurschiller** [comment]
> Very, very weird about the bundles. Where is that code you pasted in coming from?
> 
> And visionOS is actually injecting now? That would be awesome! Not sure what's happening on the iOS device. I've seen the error you're seeing today whereas it's worked before. Trying to factor out between new Xcode, new iOS version, changes to InjectionIII etc. It should be code signing correctly.

Yeah visionOS works totally fine :) 
Video attached:
https://github.com/johnno1962/InjectionIII/assets/3637723/0d38006a-a4f2-49d0-b881-2582abc5c357

I can try it maybe with another iPhone.

**Comment by johnno1962** [comment]
Found the silly problem due to renaming a file which was taking out code signing and I'll release a new release candidate this evening. Thanks for checking all these things out!

**Comment by arthurschiller** [comment]
> Found the silly problem due to renaming a file which was taking out code signing and I'll release a new release candidate this evening. Thanks for checking all these things out!

Awesome, thanks so much for this project! Already seeing how this will greatly accelerate my workflow :)

**Comment by johnno1962** [comment]
I've updated the release candidate with this fix. You should find on-iOS device injection is working again. Thanks for the link to @gonchar's excellent video. I had no idea people had already got injection working on a visionOS device as it should!

**Comment by arthurschiller** [comment]
> I've updated the release candidate with this fix. You should find on-iOS device injection is working again. Thanks for the link to @gonchar's excellent video. I had no idea people had already got injection working on a visionOS device (as it should!)

Excellent, that did the trick! Thanks so much! :)

**Comment by johnno1962** [comment]
Thanks for raising the issue. It cleared up all sorts of things :)
