### ISSUE TITLE
Hello, I reported the error when I used the real machine to debug, looking forward to your answer, thank you

### ISSUE THREAD

**Issue by ljw215** [johnno1962/InjectionIII#491]
🔥 Loading .dylib ...
🔥 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval110.dylib' (no such file, not in dyld cache), '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (code signature in <0D786BDC-8C76-3027-B281-D2075855E0C5> '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/private/preboot/Cryptexes/OS/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (code signature in <0D786BDC-8C76-3027-B281-D2075855E0C5> '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
🔥 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval110.dylib' (no such file, not in dyld cache), '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (code signature in <0D786BDC-8C76-3027-B281-D2075855E0C5> '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/private/preboot/Cryptexes/OS/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (code signature in <0D786BDC-8C76-3027-B281-D2075855E0C5> '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)" UserInfo={NSLocalizedDescription=dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval110.dylib' (no such file, not in dyld cache), '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (code signature in <0D786BDC-8C76-3027-B281-D2075855E0C5> '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/private/preboot/Cryptexes/OS/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' (code signature in <0D786BDC-8C76-3027-B281-D2075855E0C5> '/private/var/mobile/Containers/Data/Application/2979CC53-B549-4569-B644-E5C0D36BBB02/tmp/eval110.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)}

**Comment by johnno1962** [comment]
Hi, Is this the new 4.8.3 release? There was a problem with some of the 4.8.3 release candidates.

**Comment by ljw215** [comment]
Which version should I use

**Comment by johnno1962** [comment]
The current 4.8.3 release which has build number 7999 which you can see if you hover the mouse over the "Quit InjectionIII" cell in the drop down menu.

**Comment by ljw215** [comment]
Didn't you say there was a problem with version 4.8.3? So I can still use 4.8.3? Thanks for your answer

**Comment by johnno1962** [comment]
There was a problem with the release candidates that was resolved before the final release. Can you download the current 4.8.3 version please and let me know it it doesn't solve the problem you're seeing.

**Comment by ljw215** [comment]
The latest version 4.8.3 is fine, thanks
