### ISSUE TITLE
Meaning of colors

### ISSUE THREAD

**Issue by JoeFerrucci** [johnno1962/InjectionIII#492]
I've noticed the menu bar icon changes colors...what does each mean? 
Thanks

**Comment by johnno1962** [comment]
HI, blue is idle/unconnected, orange is connected to a running app/ready to inject, green is compiling, yellow which isn't very easy to differentiate from orange means there was an error.

**Comment by JoeFerrucci** [comment]
> HI, blue is idle/unconnected, orange is connected to a running app/ready to inject, green is compiling, yellow which isn't very easy to differentiate from orange means there was an error.

thanks john. fwiw I find the yellow easy to differentiate. no complaints on the colors used.
