### ISSUE TITLE
It doesn't work on xcode 15.3 (15E204a)

### ISSUE THREAD

**Issue by jokerping** [johnno1962/InjectionIII#494]
![Uploading 截屏2024-03-22 19.43.54.png…]()

**Comment by jokerping** [comment]
💉 InjectionIII connected /Users/dxm/OCDemo2/OCDemo2.xcodeproj
💉 Watching files under the directory /Users/dxm/OCDemo2
💉 Compiling /Users/dxm/OCDemo2/OCDemo2/ViewController.m
💉 Loading .dylib ...
objc[4108]: Class ViewController is implemented in both /Users/dxm/Library/Developer/CoreSimulator/Devices/DE32E2BF-3BFF-453A-9012-125C181A3BE0/data/Containers/Bundle/Application/29C367B7-88F5-4BEB-B6D1-A3AD41905DEE/OCDemo2.app/OCDemo2 (0x104b8d048) and /Users/dxm/Library/Developer/CoreSimulator/Devices/DE32E2BF-3BFF-453A-9012-125C181A3BE0/data/Containers/Data/Application/467A613D-01FF-48E6-ABB3-EFB9565710F2/tmp/eval101.dylib (0x104dd0270). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ⬆️
💉 As class ViewController has an @objc injected() method, InjectionIII will perform a "sweep" of live instances to determine which objects to message. If this fails, subscribe to the notification "INJECTION_BUNDLE_NOTIFICATION" instead.
💉 (note: notification may not arrive on the main thread)
💉 Starting sweep [ViewController], []...
💉 Compiling /Users/dxm/OCDemo2/OCDemo2/ViewController.m
💉 Loading .dylib ...
objc[4108]: Class ViewController is implemented in both /Users/dxm/Library/Developer/CoreSimulator/Devices/DE32E2BF-3BFF-453A-9012-125C181A3BE0/data/Containers/Bundle/Application/29C367B7-88F5-4BEB-B6D1-A3AD41905DEE/OCDemo2.app/OCDemo2 (0x104b8d048) and /Users/dxm/Library/Developer/CoreSimulator/Devices/DE32E2BF-3BFF-453A-9012-125C181A3BE0/data/Containers/Data/Application/467A613D-01FF-48E6-ABB3-EFB9565710F2/tmp/eval102.dylib (0x104e5c250). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ⬆️
💉 Starting sweep [ViewController, ViewController], []...

**Comment by jokerping** [comment]
#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController


- (void)injected {
    [self viewDidLoad];
}

- (void)viewDidLoad {
    [super viewDidLoad];
//    self.view.backgroundColor = [UIColor orangeColor];
}


@end



in appdelegate

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    NSError *err;
    BOOL ok = [[NSBundle bundleWithPath:@"/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle"] loadAndReturnError:&err];
    NSLog(@"InjectionIII 加载%d,%@",ok,err);
    return YES;
}

**Comment by johnno1962** [comment]
Hi, What doesn't work exactly? Is injected not being called?

**Comment by jokerping** [comment]
> Hi, What doesn't work exactly? Is injected not being called?

Changes have not taken effect

but when I use this method ，it's ok


```objc
- (void)viewDidLoad {
    [super viewDidLoad];
    [[NSNotificationCenter defaultCenter] addObserverForName:@"INJECTION_BUNDLE_NOTIFICATION" object:nil queue:NSOperationQueue.mainQueue usingBlock:^(NSNotification * _Nonnull notification) {
        [self viewDidLoad];
    }];
    self.view.backgroundColor = [UIColor greenColor];
}
```

**Comment by johnno1962** [comment]
OK, notifications may be better for you. The sweep makes quite a few assumptions.

**Comment by jokerping** [comment]
When I use the real machine, the following error occurs

Broadcasting to 169.254.255.255 to locate InjectionIII host...
Broadcasting to 172.30.105.255 to locate InjectionIII host...
💉 Connecting to MacBook.local (169.254.178.39)...
💉 InjectionIII connected /Users/dxm/OCDemo2/OCDemo2.xcodeproj
💉 Watching files under the directory /Users/dxm/OCDemo2
💉 Compiling /Users/dxm/OCDemo2/OCDemo2/ViewController.m
💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval101.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00020590, codeBlobSize=0x00004ED0 for '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib')
💉 ⚠️ Loading .dylib has failed due to invalid code signing.
💉 Add the following as a Run Script/Build Phase:
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" "$EXPANDED_CODE_SIGN_IDENTITY"
💉 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval101.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00020590, codeBlobSize=0x00004ED0 for '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib')
💉 ⚠️ Loading .dylib has failed due to invalid code signing.
💉 Add the following as a Run Script/Build Phase:
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" "$EXPANDED_CODE_SIGN_IDENTITY"" UserInfo={NSLocalizedDescription=dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval101.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00020590, codeBlobSize=0x00004ED0 for '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval101.dylib')
💉 ⚠️ Loading .dylib has failed due to invalid code signing.
💉 Add the following as a Run Script/Build Phase:
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" "$EXPANDED_CODE_SIGN_IDENTITY"}
💉 Compiling /Users/dxm/OCDemo2/OCDemo2/ViewController.m
💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00020590, codeBlobSize=0x00004ED0 for '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib')
💉 ⚠️ Loading .dylib has failed due to invalid code signing.
💉 Add the following as a Run Script/Build Phase:
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" "$EXPANDED_CODE_SIGN_IDENTITY"
💉 ⚠️ Injection error: Error Domain=SwiftEval Code=-1 "dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00020590, codeBlobSize=0x00004ED0 for '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib')
💉 ⚠️ Loading .dylib has failed due to invalid code signing.
💉 Add the following as a Run Script/Build Phase:
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" "$EXPANDED_CODE_SIGN_IDENTITY"" UserInfo={NSLocalizedDescription=dlopen() error: dlopen(/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib, 0x0002): tried: '/usr/lib/system/introspection/eval102.dylib' (no such file), '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00020590, codeBlobSize=0x00004ED0 for '/private/var/mobile/Containers/Data/Application/DD739B1D-A1B0-418E-A2F0-60F203967EEE/tmp/eval102.dylib')
💉 ⚠️ Loading .dylib has failed due to invalid code signing.
💉 Add the following as a Run Script/Build Phase:
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" "$EXPANDED_CODE_SIGN_IDENTITY"}


in build phases 

 > script1 
``` shell
RESOURCES=/Applications/InjectionIII.app/Contents/Resources
if [ -f "$RESOURCES/copy_bundle.sh" ]; then
    "$RESOURCES/copy_bundle.sh"
fi
```

 > script2
``` shell
defaults write com.johnholdsworth.InjectionIII "$PROJECT_FILE_PATH" "$EXPANDED_CODE_SIGN_IDENTITY"

```

load bundle

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

//    NSError *err;
//    BOOL ok = [[NSBundle bundleWithPath:@"/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle"] loadAndReturnError:&err];
//    NSLog(@"InjectionIII 加载%d,%@",ok,err);
#ifdef DEBUG
    NSString *path = [[NSBundle mainBundle] pathForResource:@"iOSInjection" ofType:@"bundle"] ? : [[NSBundle mainBundle] pathForResource:@"macOSInjection" ofType:@"bundle"];
    if (path) {
        [NSBundle bundleWithPath:path].load;
    }
#endif
    
    return YES;
}

```

**Comment by jokerping** [comment]
i use 4.8.4RC3
