### ISSUE TITLE
Error when Start Injection

### ISSUE THREAD

**Issue by starFelix** [johnno1962/InjectionIII#5]
I try to `Start Injection`. But I get the error said that "The operation couldn’t be completed. (CFErrorDomainLaunchd error 4.)"

**Comment by johnno1962** [comment]
Seems to be a problem installing the “helper”. Is this High Sierra?

**Comment by starFelix** [comment]
No,it's macOS Sierra. I did't signing the app. Is it the problem?

**Comment by johnno1962** [comment]
I think you’ll need to sign the app and the “helper” program

**Comment by starFelix** [comment]
I have signed the app by my personal certificate. But I still have the error said "CFErrorDomainLaunchd error 2".

**Comment by johnno1962** [comment]
What about the helper target com.johnholdsworth.InjectionIII.Helper?
