### ISSUE TITLE
*** Could not locate containing project or it's logs. Have you customised the DerivedData path? ***

### ISSUE THREAD

**Issue by KirtyKumari** [johnno1962/InjectionIII#50]
Hi John,
I am trying to use latest injectionIII app that has been updated on Friday 28th Sept version 1.2.
I have created a sample Mac app project and its inside home directory , 
Injection and xCode both are in /Applications.
still I am getting below error whenever I save a file in my project.

*** Could not locate containing project or it's logs.
Have you customised the DerivedData path? ***

I really want to use this app to escape from the build time in latest xCode, Please help.

**Comment by KirtyKumari** [comment]
Hi John, 
I tried running the injection app using code also, 
In "InjectionServer.mm" file in runInBackground method the value of project file and derived logs were not proper, so I hardcoded the directory path. Now the injection is getting connected successfully.

But again in the findCompileCommand method in SwiftEval.swift 
the shell method is returning false as it is unable to locate the compile command.
That is what getting printed in client also "Could not locate compile command" , 

I have checked the previous issues regarding this and found the compilation mode should be set as "Incremental. But its already Incremental in my client project.

Please let me know if I am doing something wrong in setting up both the projects, or are there any other limitations that I am missing.

**Comment by KirtyKumari** [comment]
Hi @johnno1962 
This is the current project path.
**/Users/kirty-xxxxx/GitProjects/TaskViewApp**
xxxx are numeric characters 

But I tried changing it to 
**/Users/Shared/TaskViewApp** still I was getting the same issue.

**Comment by KirtyKumari** [comment]
I am afraid, it won't be possible. Will try to work this out and let you know. 
Thanks @johnno1962

**Comment by johnno1962** [comment]
You’ll have difficulty getting DerivedData working other than at the standard location. The message you’re seeing is coming from the InjectionBundle which makes it’s own attempt to find DerivedData in Swift which you need to patch. https://github.com/johnno1962/InjectionIII/blob/master/InjectionBundle/SwiftEval.swift#L514
