### ISSUE TITLE
Could not bind service socket: Address already in use

### ISSUE THREAD

**Issue by Daren-Wang** [johnno1962/InjectionIII#503]
Last login: Tue May  7 17:31:44 on ttys001
daren@darendeMacBook-Pro ~ % lsof | grep 8898
Injection  7556 daren    8u     IPv4 0x8055554b517fde21        0t0                 TCP localhost:8898 (LISTEN)
KonaSynth 95180 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
SecurityS 95192 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
Interacti 95194 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
LegacyPro 95195 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
PasscodeS 95198 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
WatchEnro 95203 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
AccountSu 95204 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
ManagedAp 95208 daren  txt       REG               1,23      84096              218898 /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accelerate.framework/Accelerate
daren@darendeMacBook-Pro ~ %

**Comment by cerupcat** [comment]
I also just started getting this using the latest version. https://github.com/johnno1962/InjectionIII/releases/tag/5.0.0

**Comment by johnno1962** [comment]
That would be most strange as very little has changed. If you downgrade the app does the problem go away?

**Comment by cerupcat** [comment]
> That would be most strange as very little has changed. If you downgrade the app does the problem go away?

Actually, it appears to be connected. I do get this message if I try to "Start Server", even if I stop it first. With that said, that doesn't appear to be an issue and it seems to be connecting correctly.

**Comment by johnno1962** [comment]
You don't need to "Start server", that's for something else which I'll be removing.
