### ISSUE TITLE
Is support arm mac???

### ISSUE THREAD

**Issue by jb522185660** [johnno1962/InjectionIII#504]
MacBook Air 13 inch 2024 M3

when I save the code, show this error 

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o /tmp/injection.o
1.	Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010665d108 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 40
1  swift-frontend           0x000000010665c058 llvm::sys::RunSignalHandlers() + 248
2  swift-frontend           0x000000010665d6c7 SignalHandler(int) + 311
3  libsystem_platform.dylib 0x00007ff817b26fdd _sigtramp + 29
4  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603370183364672
5  libsystem_c.dylib        0x00007ff817a1da39 abort + 126
6  swift-frontend           0x00000001003404a9 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*)::$_3::__invoke(void*, char const*, bool) + 761
7  swift-frontend           0x000000010658c402 llvm::report_fatal_error(llvm::Twine const&, bool) + 402
8  swift-frontend           0x000000010658c269 llvm::report_fatal_error(char const*, bool) + 41
9  swift-frontend           0x00000001044459a2 llvm::cas::getDefaultOnDiskCASPath() + 386
10 swift-frontend           0x0000000100511542 swift::ArgsToFrontendOptionsConverter::convert(llvm::SmallVectorImpl<std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>>*) + 15954
11 swift-frontend           0x000000010052e071 swift::CompilerInvocation::parseArgs(llvm::ArrayRef<char const*>, swift::DiagnosticEngine&, llvm::SmallVectorImpl<std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>>*, llvm::StringRef, llvm::StringRef) + 1345
12 swift-frontend           0x0000000100332aa0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 1440
13 swift-frontend           0x00000001002afa0e swift::mainEntry(int, char const**) + 5278
14 dyld                     0x0000000209c44366 start + 1942

**Comment by johnno1962** [comment]
Hi, yes it does normally. What version of Xcode is this? What is the deployment target? Are you using macros?

**Comment by jb522185660** [comment]
The same code in normally on intel mac, the Xcode version is 15.3, deployment target iOS 12, the simulator is iPhone 15 pro iOS 17.4, not using marcos

**Comment by johnno1962** [comment]
Could it be something to do with the path to the project? Avoid using ~/Downloads, ~/Documents etc.

**Comment by jb522185660** [comment]
hello, I have try to udpate the injectioniii on the latest version to 5.0.0 in github. It seem normal, but when I command + s to save(I have not modify the code),I crash by like that "Thread 1: EXC_BAD_ACCESS (code=1, address=0x7f868f376b00)"

**Comment by johnno1962** [comment]
What crashes? Your app or injection or the Swift compiler? I'm getting confused. And this crash is specific to the new version? Can you show the full trace?

**Comment by jb522185660** [comment]
Can I send you the email for the crash info?

**Comment by johnno1962** [comment]
Sure that would help a lot, github at johnholdsworth.com.

**Comment by jb522185660** [comment]
I have send you the email on github@johnholdsworth.com

**Comment by johnno1962** [comment]
Thanks for sending that through. I would have had no idea otherwise. Are you using Objective-C associated objects? I can't guarantee that would work over injection as the "key" would likely get injected.

**Comment by novolgit** [comment]
@jb522185660 have you implemented this properly?

**Comment by novolgit** [comment]
@jb522185660 have you implemented this https://github.com/johnno1962/InjectionIII?tab=readme-ov-file#how-to-use-it:~:text=%23if%20DEBUG%0ABundle,)%0A%23endif properly?

**Comment by jb522185660** [comment]
Hello , I downgrade to 4.6.5, It'w work normal.Thanks.
![截屏2024-05-13 21 35 38](https://github.com/johnno1962/InjectionIII/assets/3723116/9cd8abb1-1ad8-456c-bc5b-96066d6b569d)

**Comment by jb522185660** [comment]
Any one have the error, try this version.

**Comment by johnno1962** [comment]
Did you try any other versions? It would be very helpful to try to bisect down to where the regression was introduced.

**Comment by jb522185660** [comment]
My anther intel mac still using 4.6.5, so I copy the InjectionIII from intel mac to MacBook Air 13 inch 2024 M3.I have not try any other version.

**Comment by johnno1962** [comment]
Very strange, not that much has changed, if you get a chance to test a more recent version let me know.

**Comment by jb522185660** [comment]
I have try 4.8.4 yesterday, the issue still exist

**Comment by johnno1962** [comment]
There are a lot of versions between 4.6.5 and 4.8.4. If you could find the time to try them quickly, I'd really appreciate it. Otherwise it's very difficult without TeamViewing to try essentially the same thing to have much chance of finding the problem. All of the changes in the last year a minor but you never know what will trip you up.

**Comment by jb522185660** [comment]
How can I help identify the issue? Please provide suggestions at any time. I hope for improvements in future versions

**Comment by johnno1962** [comment]
As far as I understand you have a problem "Thread 1: EXC_BAD_ACCESS (code=1, address=0x7f868f376b00)" that exhibits with 5.0.0 but not 4.6.5. Could you try 4.7.0 or 4.8.0? https://github.com/johnno1962/InjectionIII/releases. I make a point of dropping frequent versions to be able to bracket when regressions crept in. Bisecting is where you try versions in the middle and if it still fails you try a version before that or if it works OK you try a version after that like a binary search.
