### ISSUE TITLE
often crash when a injected objc class dealloc

### ISSUE THREAD

**Issue by xinix909** [johnno1962/InjectionIII#508]
often crash when a injected objc class dealloc. the objc class implements a dealloc method
I use VisionPro simulator、Xcode 15.4

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
    frame #0: 0x00000001933b0e7c libswiftCore.dylib`swift_unknownObjectRetain + 16
  * frame #1: 0x00000001342a0544 SwiftTrace`SwiftTrace.Decorated.objcDecorate(signature="#2/dealloc", invocation=0x0000600003748480, self=0x00006000039f81a0) at SwiftArgs.swift:452:28
    frame #2: 0x000000013429d174 SwiftTrace`SwiftTrace.Decorated.exitDecorate(stack=SwiftTrace.SwiftTrace.ExitStack @ 0x000000016b264ef0, invocation=0x0000600003748480, self=0x00006000039f81a0) at SwiftArgs.swift:318:17
    frame #3: 0x00000001342cd764 SwiftTrace`SwiftTrace.Swizzle.onExit(stack=SwiftTrace.SwiftTrace.ExitStack @ 0x000000016b264ef0, invocation=0x0000600003748480, self=0x00006000039f81a0) at SwiftSwizzle.swift:264:38
    frame #4: 0x00000001342cc1d8 SwiftTrace`closure #1 in variable initialization expression of static SwiftTrace.Swizzle.onExit at SwiftSwizzle.swift:192:31
    frame #5: 0x00000001342cc28c SwiftTrace`@objc closure #1 in variable initialization expression of static SwiftTrace.Swizzle.onExit at <compiler-generated>:0
    frame #6: 0x00000001410a00c4

<img width="1544" alt="image" src="https://github.com/johnno1962/InjectionIII/assets/17949335/a1894582-84bf-43b7-818c-a51023496cca">

<img width="492" alt="image" src="https://github.com/johnno1962/InjectionIII/assets/17949335/92d1cd0a-dc69-455b-bd55-31b9c7229c73">

**Comment by xinix909** [comment]
I delete the code of dealloc method of the class，then no crash

**Comment by johnno1962** [comment]
Hi, thanks for the very informative bug report. I've updated the 5.0.1 release candidate if you want to try it out for me. The code you highlighted  in SwiftTrace was referring to an object after it was deallocated.

**Comment by xinix909** [comment]
> Hi, thanks for the very informative bug report. I've updated the 5.0.1 release candidate if you want to try it out for me. The code you highlighted in SwiftTrace was referring to an object after it was deallocated.

I'll try it, thank you

**Comment by xinix909** [comment]
no problem from 5.0.1 release

**Comment by johnno1962** [comment]
👍
