### ISSUE TITLE
INJECTION_BUNDLE_NOTIFICATION observer not called on InjectionX 

### ISSUE THREAD

**Issue by llinardos** [johnno1962/InjectionIII#51]
Looks like the "INJECTION_BUNDLE_NOTIFICATION" is not being fired on InjectionX.

I'm subscribing with:
```
    NotificationCenter.default.addObserver(self, selector: #selector(self.onInjected),
      name: NSNotification.Name(rawValue: "INJECTION_BUNDLE_NOTIFICATION"),
      object: nil)
```
but `onInjected` is never called.

* Version 1.2 (1171)
* "Injected" message is logged ok, so, injection is working ok.
* Same code is working ok with previous versions of injection on Xcode9.

**Comment by johnno1962** [comment]
There is a new version that works with Xcode 9/10 here: http://johnholdsworth.com/InjectionIII.app.zip. It requires you to change the bindle path to /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle when you are using it with Xcode 10. Would it be possible check to see if this new version notifies when you are using with Xcode 9?

**Comment by llinardos** [comment]
Solved!
Thanks!
