### ISSUE TITLE
It Didn't work 🥶

### ISSUE THREAD

**Issue by a7maad-ayman** [johnno1962/InjectionIII#510]
Hi there, i tried to integrate Injection in my app and every thing is ok but i still get 
<img width="471" alt="Screenshot 2024-07-03 at 11 43 12 AM" src="https://github.com/johnno1962/InjectionIII/assets/87352168/35b9ba9c-70a6-4c35-8e47-4e884e55b07b">

**Comment by johnno1962** [comment]
May be related to the "." in your user name. You might want to a try using the new [InjectionNext](https://github.com/johnno1962/InjectionNext) project.

**Comment by a7maad-ayman** [comment]
no it's not the problem I had create a dummy app in the same device and it worked well. 
`Note` : I run an xcworkspace

**Comment by johnno1962** [comment]
> You might want to try using the new [InjectionNext](https://github.com/johnno1962/InjectionNext) project.
