### ISSUE TITLE
 Class xxxxx is implemented in both A and B

### ISSUE THREAD

**Issue by samyi9426** [johnno1962/InjectionIII#512]
objc[81686]: Class xxxxx is implemented in both 
/Users/xxxx/Library/Developer/CoreSimulator/Devices/8A51C7D9-12D2-4CA6-8B0D-D41CB02AB877/data/Containers/Bundle/Application/B0DE2FF9-8DCB-4CF8-8FC2-3E1DD7B101F8/xx.app/xx (0x1052b3060) 
and /Users/xxxx/Library/Developer/CoreSimulator/Devices/8A51C7D9-12D2-4CA6-8B0D-D41CB02AB877/data/Containers/Data/Application/3B3297E5-155A-4E02-9F81-064751B1B8B4/tmp/eval101.dylib (0x173fcdb48). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ⬆️

**Comment by johnno1962** [comment]
You can ignore that message as it says. The implementation in the new class will be the one used.

**Comment by samyi9426** [comment]
thx a lot
