### ISSUE TITLE
when I changed my file , then type "ctrl+S" , why show me a error message

### ISSUE THREAD

**Issue by wrssssss56** [johnno1962/InjectionIII#515]
Hello, waiting for your reply。
This is the err message：
💉 InjectionIII connected /Users/ranwang/projectaaa/testrr/testrr.xcodeproj
💉 Watching files under the directory /Users/ranwang/projectaaa/testrr
💉 ⚠️ Could not locate compile command for "/Users/ranwang/projectaaa/testrr/testrr/abc.m" in /Users/ranwang/Library/Developer/Xcode/DerivedData/testrr-coeoenquxbufwxdqqujzkdasttea/Logs/Build/.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
5. The source file is an XCTest that has not been run yet.
6. Xcode has removed the build logs. Edit a file and re-run.
Try a build clean then rebuild to make logs available or
consult: "/Users/ranwang/Library/Containers/com.johnholdsworth.InjectionIII/Data/tmp/command.sh".

**Comment by johnno1962** [comment]
Hi, For this error, I recommend people try the new version of Injection, https://github.com/johnno1962/InjectionNext
