### ISSUE TITLE
does it support objective-c? 

### ISSUE THREAD

**Issue by bingchenqin** [johnno1962/InjectionIII#52]

**Comment by bingchenqin** [comment]
I think it supports it.
but, When I use CocoaPod import my project model,and I change the Model, the log always was 

*** Could not locate containing project or it's logs.
Have you customised the DerivedData path? ***

**Comment by zenangst** [comment]
@johnno1962 the current version should work with Objective-C right? I haven't been actively working on any Objective-C projects recently so I'm a bit unsure here 🤔
