### ISSUE TITLE
Bookmarking

### ISSUE THREAD

**Issue by ryanx2002** [johnno1962/InjectionIII#522]
Hey, running into an issue with newest Injection version:

Bookmarking failed for file:///Users/ryanx2002/Downloads/practice/, Error Domain=NSCocoaErrorDomain Code=256 "Failed to retrieve app-scope key" UserInfo={NSDebugDescription=Failed to retrieve app-scope key}

What could be the cause?

**Comment by krzysztofzablocki** [comment]
@johnno1962 I saw this on his machine and it was very weird, tried downloading new version of app, restarting etc. It got stuck on another project path that we opened initially and would never switch to new one, always throwing this error

**Comment by johnno1962** [comment]
Strange, What version of Xcode & InjectionIII is this?

**Comment by krzysztofzablocki** [comment]
Newest Injection from GitHub, I thought he had Mac App Store but we downloaded GH version and the issue happens there

**Comment by jgonibemobile** [comment]
i have exactly the same problem (osx 15.0.1, xcode 16.0 and injection 1.5.2)

**Comment by johnno1962** [comment]
I've verified switching projects is still working for me with osx 15.0 so I'm at a loss to explain what the problem might be here. Have you tried resetting the defaults .plist. Sometimes switching from sandboxed to un-sandboxed it can get confused.

rm ~/Library/Preferences/com.johnholdsworth.InjectionIII.plist ~//Library/Containers/com.johnholdsworth.InjectionIII/Data/Library/Preferences/com.johnholdsworth.InjectionIII.plist

**Comment by jgonibemobile** [comment]
I don't know why, but 1h later, the app works fine 🤷🏻‍♂️

**Comment by johnno1962** [comment]
Weird, what version is that? InjectionIII 1.5.2 is from 5 years ago!

**Comment by jgonibemobile** [comment]
5.0.2, excuse me

**Comment by Perjan** [comment]
Same here.
![CleanShot 2024-10-18 at 15 15 49@2x](https://github.com/user-attachments/assets/6c775980-a5dd-44fa-9dd4-6cb890d498a3)

**Comment by johnno1962** [comment]
Hi, this is on Sonoma? Which version of Xcode/the app?

**Comment by Perjan** [comment]
I have Sonoma and Xcode 16.

**Comment by johnno1962** [comment]
There doesn't seem to be a ready explanation for this. Any chance you would be prepared to switch to https://github.com/johnno1962/InjectionNext in the interim which shouldn't give you this problem.

**Comment by johnno1962** [comment]
I've uploaded a new release candidate that should at least make this error "go away" though I'm still not sure what the underlying problem is with Sequoia. https://github.com/johnno1962/InjectionIII/releases/tag/5.0.4RC1

**Comment by johnno1962** [comment]
Did anybody get a chance to try the new release candidate. It shouldn't report this error but does it still work?
