### ISSUE TITLE
Doesn't work with Cursor

### ISSUE THREAD

**Issue by michaello** [johnno1962/InjectionIII#524]
I tested 5.0.5 version and injection next 1.2.6 RC, Sequoia 15.2. Using https://github.com/krzysztofzablocki/Inject as lib injection. 

```
import SwiftUI
import Inject

struct ContentView: View {
    @ObserveInjection var inject
    var body: some View {
        Text("Hello, iOS App with!")
            .padding()
            .enableInjection()
    }
}
```

New project:
```
💉 InjectionIII connected /Users/mike/Developer/test-projects/TestInjection/TestInjection.xcodeproj
💉 Watching files under the directory /Users/mike/Developer/test-projects/TestInjection
💉 Compiling /Users/mike/Developer/test-projects/TestInjection/Sources/ContentView.swift
💉 ⚠️ Re-compilation failed (see: /Users/mike/Library/Developer/CoreSimulator/Devices/77C5CD15-928A-4A4A-81D1-FC70313DDA93/data/Containers/Data/Application/B86D0B80-E296-47D6-B4DA-EA73F826CB28/tmp/command.sh)
<unknown>:0: error: no such file or directory: '/Users/mike/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation'
<unknown>:0: error: stat cache file '/Users/mike/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.1-22B5045f-3d93aac3a03ebac1dd8474c5def773dc.sdkstatcache' not found
<unknown>:0: error: stat cache file '/Users/mike/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.1-22B5045f-3d93aac3a03ebac1dd8474c5def773dc.sdkstatcache' not found
```

**Comment by johnno1962** [comment]
Thanks for the report. Which Xcode is this? I should have access to a Sequoia host tomorrow to try to replicate.

**Comment by michaello** [comment]
Yup, same issue after Xcode build (works with Xcode)

**Comment by johnno1962** [comment]
Looks like I'll be trying the legend that is Cursor tomorrow.

**Comment by michaello** [comment]
Thank you for a hard work! 🙏

**Comment by johnno1962** [comment]
I may be getting back to you for pointers.. You used this article? https://x.com/Dimillian/status/1848731737578234102

**Comment by michaello** [comment]
I don't think so, but his article might resemble my setup.

**Comment by johnno1962** [comment]
I've been able to install Cursor and the new https://github.com/johnno1962/InjectionNext/releases/tag/1.2.6RC3 "works for me"™️ (though I improved logging a bit) and, according to another user InjectionIII 5.0.5 works https://github.com/johnno1962/InjectionNext/issues/28#issuecomment-2466303536. One problem I did have was you need to make sure the version of Xcode you built the project with is the same as that used by `xcode-select`. We really need to do something about having to xcodebuild the project all the time which is unnecessarily slow. I produced a script https://github.com/johnno1962/xcodemake which should speed things up but I'm unsure how to integrate it into `SpeedPad`. Any ideas @hyzyla, @wojciech-kulik?

**Comment by michaello** [comment]
this still doesn't work for me. i've built the project with the same xcode as I used in `xcode-select`. it's a beta of 16.1, but named `Xcode`, located in `/Applications/Xcode.app`.

**Comment by johnno1962** [comment]
Does injection(next) with Xcode work for for project or are you saying this problem is specific to Cursor which seems improbable. What Xcode version please.

**Comment by michaello** [comment]
InjectionIII: Works with my Xcode, doesn't work with Cursor.
InjectionNext: Works with my Xcode, doesn't work with Cursor:
```
🚀 Executing command:
open -a Simulator

🚀 Executing command:
xcrun simctl install DF57F334-B65E-4368-A6E0-EFD07757F9B8 /Users/mike/Library/Developer/Xcode/DerivedData/TestInjection2-aywxouhobqlgmbfiyitkgztzuday/Build/Products/Debug-iphonesimulator/TestInjection2.app

🚀 Executing command:
xcrun simctl launch --console-pty --terminate-running-process DF57F334-B65E-4368-A6E0-EFD07757F9B8 com.example.TestInjection2

🔥 InjectionNext: iPhoneSimulator connection to app established, waiting for commands.
🔥 Platform connected: iPhoneSimulator
```

I apply changes but no refresh, as opposed to Xcode.
Version: 16.1 (potentially RC)

**Comment by johnno1962** [comment]
Have you tried giving InjectionIII/Next "Full Disk Access"?

**Comment by michaello** [comment]
I'm afraid I can't do that due to security concerns when working on customer's machines. I'll test Xcode release version later.

**Comment by johnno1962** [comment]
Never-mind, I don't know if it would be acceptable build your own version of the app binary from source but that was just a suggestion. Anyway it doesn't seem to be the problem as I've upgraded my Mac and InjectionIII.Next seems to work for me with Cursor without it.

What would be useful to know if the current error is still the following is whether the file it mentions exist on your filesystem.
```
💉 ⚠️ Re-compilation failed (see: /Users/mike/Library/Developer/CoreSimulator/Devices/77C5CD15-928A-4A4A-81D1-FC70313DDA93/data/Containers/Data/Application/B86D0B80-E296-47D6-B4DA-EA73F826CB28/tmp/command.sh)
<unknown>:0: error: no such file or directory: '/Users/mike/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation'
<unknown>:0: error: stat cache file '/Users/mike/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.1-22B5045f-3d93aac3a03ebac1dd8474c5def773dc.sdkstatcache' not found
<unknown>:0: error: stat cache file '/Users/mike/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.1-22B5045f-3d93aac3a03ebac1dd8474c5def773dc.sdkstatcache' not found
```
If they don't exist it is extracting the wrong compile command for your project, if they do then I would suggest "Full Disk Access" may be required.

I've uploaded a new release candidate for Cursor https://github.com/johnno1962/InjectionNext/releases/tag/1.2.6RC4 which logs a little more the compilation fails and also avoids the log parsing if you use the app to launch Xcode and leave it running while using the "...or Watch Project" to start the file watcher to run with Cursor.

If that's confusing can you try the following:
* Download and run the new release candidate
* Use it to start you Xcode and edit a file
* Run up the simulator can check that injectionNext works.
* Use menu item "...or Watch Project" to start the file watcher.
* Open your project in Cursor, run your app and edit the same file and see if it injects.

This avoid the log parsing which for your project the fact both InjectionIII and InjectionNext when using the file watcher are not work is telling the same thing. See how you get on and let me know.

**Comment by johnno1962** [comment]
There's a new release candidate filtering out these problem options if you'd like to give it a try:
https://github.com/johnno1962/InjectionNext/releases/tag/1.2.6RC6

**Comment by michaello** [comment]
@johnno1962 yes!! This version works on my config now! You're an angel 😄
