### ISSUE TITLE
*** Could not locate containing project or it's logs. Have you customised the DerivedData path? ***

### ISSUE THREAD

**Issue by bingchenqin** [johnno1962/InjectionIII#53]
I never change my location, I use pod install my source code module, and change it, so

**Comment by zenangst** [comment]
@bingchenqin could you share some more information about what kind of class or file you are trying to inject?

**Comment by ooopscc** [comment]
I have the same problem. I use development pod too.
```
pod 'AAA', :path => '../AAA'
```
File tree maybe
```
.
├── Containing Project
└── AAA (development pod) (watching) # it seems that only one dir can be watching at the same time
```
I choose path to AAA to make InjectionIII to monitoring that dir, but it seems that it can not find the containing project, so is cocoapods development pod supported or I am configuring it wrong?

**Comment by zenangst** [comment]
Hey @ooopscc,

If you go outside of the scope of the project with your path, InjectionIII will be unable to monitor it for changes. What I tend to do when working with development pods is to create a directory inside of the project that I ignore in my global `.gitignore` file.

I create a directory called `_pods` and point my `podfile` to use that path.
By keeping the development pod inside the same directory, the file watcher picks up when those files are saved and reacts accordingly. Hope that helps!

**Comment by zenangst** [comment]
Yeah and note that you still pick the main project that the pod belongs to, otherwise it won’t work. To sum it up, the development pod should be a sub directory of the main project.

**Comment by ooopscc** [comment]
@zenangst Thanks for quick reply. I will try. But I wonder will a symlink work without move the dir? (I just tried, it seems not working at all)?

**Comment by zenangst** [comment]
@ooopscc If I remember correctly, symlinks will not work. I don't think they trigger FSEvents for the current scope, which means that it will not respond to file changes as the change didn't really take place in that directory. It is worth testing but I think this is a limitation of the file system. Might be some configuration options that we have overlooked to get it to work but still, it feels a bit niché to support it out-of-the-box. We shouldn't rule it out, it is just my initial gut reaction :)

**Comment by ooopscc** [comment]
Thanks, I will dig into the source code to find something and try. 😃

**Comment by zenangst** [comment]
@ooopscc the best way to tackle a problem, dig into the source code 😁 
Good luck and have fun 🤠

**Comment by LionWY** [comment]
same problem,
how to resolve?

**Comment by erduoniba** [comment]
@ooopscc 
same problem,
can you help me?

**Comment by zenangst** [comment]
@erduoniba hey mate, which version of the application are you currently using?

**Comment by ooopscc** [comment]
@erduoniba  try to update to the latest InjectionIII and make sure dev pods locate  in main project.

**Comment by erduoniba** [comment]
@zenangst i was download lastest InjectionIII project (commit id: e497fef0481e75f917df3d573684f9c70a8fede6) and build InjectionIII application.

**Comment by erduoniba** [comment]
@ooopscc what's "dev pods locate in main project"? this is all right?
![image](https://user-images.githubusercontent.com/6082855/71674885-6f6e8300-2db7-11ea-89de-1d3753947460.png)
