### ISSUE TITLE
Feature request: Toggle file watcher using keyboard shortcuts.

### ISSUE THREAD

**Issue by Fr3027** [johnno1962/InjectionIII#531]
Hi, thanks for your awesome work!

When I add a new property to a SwiftUI view and save the file, the app crashes because the memory layout has been modified. While this is understandable, it would be helpful if users could toggle the file watcher using a keyboard shortcut to prevent crash.
 After the code is rebuilt in Xcode, they could then re-enable the file watcher .

**Comment by johnno1962** [comment]
Hi, I'd accept a PR but I'd be reluctant to add another "Hot Key" for Injection as they are a global resource of the OS. You can do what you are looking for with the existing app by turning of file watching and it will queue up saved files until you type control-= which sends them through. This way you need to remember to save the file as well but at least it's all keyboard.

**Comment by Fr3027** [comment]
"The Control + = shortcut is exactly what I was looking for. Thank you!"
