### ISSUE TITLE
System Tray colours - what do the different colours indicate?

### ISSUE THREAD

**Issue by slum44** [johnno1962/InjectionIII#55]
Hi,

Am using the InjectionX.app, and looked around in the documentation but didn't see anything.

When I ran the QuickStart, the 'blue' colour was showing in the MacOS system tray the entire time.

I then applied Injection to a personal project, and the System Tray colour is orange.  I had trouble getting Injection working with my personal project, but after awhile of fighting I got it working.  I expected that the System Tray colour would revert back to Blue to indicate all is well but it did not (still orange).

So, just wondering what kind of message the system tray colour is trying to communicate?  Orange screenshot included

Thanks

![image](https://user-images.githubusercontent.com/3831939/46909212-e0194d80-cf2e-11e8-8cec-60c20b8785a3.png)

**Comment by johnno1962** [comment]
Hi, Blue means idle, orange means you have a connected app and green means busy. If it is orange but not updating check you have the correct project selected or the file watcher will not work.

**Comment by slum44** [comment]
Thanks vm for clarifying - much appreciated
