### ISSUE TITLE
Xcode10 NewDemoProject

### ISSUE THREAD

**Issue by dxd214** [johnno1962/InjectionIII#59]
objc[43094]: Class AppDelegate is implemented in both /Users/ios/Library/Developer/CoreSimulator/Devices/01520BA9-CE7B-4108-A995-2B06277CCF00/data/Containers/Bundle/Application/936AFE66-C017-4A77-BB70-059AE99A1C88/demo.app/demo (0x10ea06e90) and /Users/ios/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib (0x12c848bf0). One of the two will be used. Which one is undefined.

**Comment by dxd214** [comment]
*** Compiling /Users/ios/Desktop/demo/demo/AppDelegate.m ***
Loading .dylib - Ignore any duplicate class warning...
objc[43094]: Class AppDelegate is implemented in both /Users/ios/Library/Developer/CoreSimulator/Devices/01520BA9-CE7B-4108-A995-2B06277CCF00/data/Containers/Bundle/Application/936AFE66-C017-4A77-BB70-059AE99A1C88/demo.app/demo (0x10ea06e90) and /Users/ios/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib (0x12c848bf0). One of the two will be used. Which one is undefined.

**Comment by zenangst** [comment]
Hey @dxd214, are you subscribing to the notification in order to act on the injection in `AppDelegate.m` ?

**Comment by zenangst** [comment]
@dxd214 glad you solved it, cheers mate :)

**Comment by johnno1962** [comment]
GettingStarted.zip project will have to be updated when the majority of people are using Xcode 10.
