### ISSUE TITLE
Load bundle fail if serval Xcode exist.

### ISSUE THREAD

**Issue by starFelix** [johnno1962/InjectionIII#6]
If somebody had serval Xcode in Applications, he will get the error like below:
```
/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found
```
All the Xcode is download through Internet and not from AppStore.  At the beginning, I think maybe the  problem is the `Xcode-GM.app` should change it's name to `Xcode.app` . But I found it doesn't work.

**Comment by johnno1962** [comment]
I’ve pushed a change to include XCTest in iOSInjection.bundle which may solve this

**Comment by starFelix** [comment]
Are you sure you had included it? I had update the code, and I  found I would get this error whether there are one or more xcode.

**Comment by starFelix** [comment]
And I had read the commits today. I didn't find anything about XCTest.

**Comment by johnno1962** [comment]
There was a very small change to the InjectionBundle target to include XCTest.framework are you building from source or downloading the app?

**Comment by johnno1962** [comment]
There were a couple of problems which should be ironed out now in the download and on github.

**Comment by starFelix** [comment]
I had updated the project. And It works well in my project. I will try it on my friend's project tomorrow. He have serval xcode.

**Comment by starFelix** [comment]
It works well now. But I didn't know why rename the `Xcode.app` did not resolve this problem.

**Comment by johnno1962** [comment]
Can’t say. It was difficult getting the “rpath” right and testing it properly.
