### ISSUE TITLE
Issues using convenience init - Symbol not found ... Expected in: flat namespace

### ISSUE THREAD

**Issue by zenangst** [johnno1962/InjectionIII#62]
Stumbled upon an issue when using convenience initializers. I've added a small extension on `CABasicAnimation` (see example below) which adds a convenience init. When I use this extension in a view controller, that view controller will no longer be injected as it says the symbol cannot be resolved (see logs). If I revert back to using regular `CABasicAnimation`'s, everything works just fine.
I could make an animation factory as described here https://github.com/johnno1962/InjectionIII/issues/57#issuecomment-431399527 but I'm just curious to why this happens. Any ideas, @johnno1962 ?

### Example
```swift
import UIKit

public extension CABasicAnimation {
  public convenience init(property: String,
                          from fromValue: Any? = nil,
                          to toValue: Any? = nil,
                          withDuration duration: TimeInterval = 0.0) {
    self.init(keyPath: property)
    self.fromValue = fromValue
    self.toValue = toValue
    self.duration = duration
  }
}
```

### Logs
```fish
Loading .dylib - Ignore any duplicate class warning...
*** dlopen() error: dlopen(/Users/christofferwinterkvist/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval104.dylib, 2): Symbol not found: _$SSo16CABasicAnimationC21AppName_tvOS_StagingE8property4from2to12withDurationABSS_ypSgAHSdtcfcfA0_
  Referenced from: /Users/christofferwinterkvist/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval104.dylib
  Expected in: flat namespace
 in /Users/christofferwinterkvist/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval104.dylib ***
```

**Comment by johnno1962** [comment]
I’m sorry, without knowing more about your project I just don’t know. Is this in a framework subproject? Sometimes that can cause problems. With injection the golden rule is: If it works, it works. If it doesn’t move some stuff around between files until it does.

**Comment by zenangst** [comment]
Yeah, so the project uses Cocoapods, but all the source code that is failing to be injected is in the main project. I'm gonna try and tackle this myself when life allows; there are ways to work around it as I mentioned in my original post so don't put any effort on it if you are not feeling adventurous. I pinged you mainly to ping-pong some ideas and created the issues so that I don't forget :)

I'm gonna try the code in an example project in complete isolation to see if there isn't something wonky going on in the project itself. Anyway, thanks mate :)

**Comment by johnno1962** [comment]
Ping away. This issue last came up when someone was trying to inject a class that referred to symbols in a framework (which I think “pod” classes come in as). One solution was this project https://github.com/johnno1962/unhide though frankly it’s pretty unusable.

**Comment by spykr** [comment]
I was just coming here to open this issue myself, I get it with the following extension:

```swift
extension UILabel {
    public convenience init(color: UIColor, font: UIFont, alignment: NSTextAlignment = .left) {
        self.init()
        self.font = font
        self.textAlignment = alignment
        self.textColor = color
    }
}
```

The error:

```
*** dlopen() error: dlopen(/Users/UserName/Library/Containers/com.johnholdsworth.InjectionX/Data/eval102.dylib, 2): Symbol not found: _$SSo7UILabelC6AppNameE5color4font9alignmentABSo7UIColorC_So6UIFontCSo15NSTextAlignmentVtcfcfA1_
  Referenced from: /Users/UserName/Library/Containers/com.johnholdsworth.InjectionX/Data/eval102.dylib
  Expected in: flat namespace
 in /Users/UserName/Library/Containers/com.johnholdsworth.InjectionX/Data/eval102.dylib ***
```

**Comment by todanley** [comment]
> Just confirming what everyone found as well. I find that when calling methods and using the default parameters, Injection will fail to find the method.
> 
> Ex:
> 
> ```swift
> func refresh(animate: Bool = true) {
>     // ...
> }
> 
> // Injection works:
> refresh(animate: true)
> 
> // Injection fails:
> refresh()
> ```

Exactly the same issue I countered. Passing in an explicit parameter fixed the problem for me.

**Comment by runningskull** [comment]
Happening for me as well. It seems to happen if any code in the saved file hits a function with default parameters - nothing specific to view controllers or init's or the execution path of `injected()`.

A note for plain functions - it seems you can do a similar thing to the @spykr fix by defining signatures that overlap the original function signature and you don't have to rewrite your original function.
```swift
// original function stays the same
func myFunc(x, y=1, z=2) { ... }

// add signatures just for Injection
func myFunc(x) { return myFunc(x, y: 1, z: 2) }
func myFunc(x, y) { return myFunc(x, y: y, z: 2) }
func myFunc(x, z) { return myFunc(x, y: 2, z: z) }
```

**Comment by yonglefu** [comment]
same question
*** dlopen() error: dlopen(/Users/yongle/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval105.dylib, 2): Symbol not found:

**Comment by spnkr** [comment]
Yes, the problem is with default values for the initializers. @spykr's solution fixes it.
