### ISSUE TITLE
Carthage Problem

### ISSUE THREAD

**Issue by JeaSungLEE** [johnno1962/InjectionIII#64]
I want to apply injectionIII to my project.

Xcode10
Swift4.2

`Re-compilation failed error: no such module`
The above error is occurring.

I think I am having problems using Carthage and how can I fix it?

**Comment by JeaSungLEE** [comment]
I created a new project and run Injection to test it.
As above, another error is occurring. 

`objc[951]: Class _TtC5aaaff11AppDelegate is implemented in both /Users/JERCY/Library/Developer/CoreSimulator/Devices/59328DFC-B3EB-4AA7-900A-3326F5E5279E/data/Containers/Bundle/Application/FDC908EC-69FD-4B1A-972C-DB7EABF470E3/aaaff.app/aaaff (0x103da9360) and /Users/JERCY/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib (0x121ab11e0). One of the two will be used. Which one is undefined.`

I deleted the InjectionIII and reinstalled it, and tried to initialize the library folder, but I still get the above error. How can I fix it?
It is a new project that is not touched by ViewController and storyboard code.

**Comment by JeaSungLEE** [comment]
Hi The above problem was my project problem. I removed the framework from the project and re-imported it.

```Swift
     @objc func injected () {
     }
```
But now, when I save it in the ViewController with the above code, there is an error in appdelegate (there is no code in the injected function).
There is no other log, so I can not solve it. Do you have any guesses about why this crash happens?

Please refer to the picture below.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/13097922/47554740-fc60b580-d944-11e8-9cee-44786c359b24.png">

**Comment by JeaSungLEE** [comment]
`Problem reloading nib: *** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil`
And after rebuilding the storyboard, the above logs are shown. What's the problem with this?

**Comment by zenangst** [comment]
@JeaSungLEE with regard to the error message that you posted:

```
Problem reloading nib: *** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil
```

I dug into the code and found that in some scenarios, the injection method for storyboards cannot always resolve the currently visible view controller. I've made a PR to improve the search pattern for the current view controller on screen by adding a case for when you use a navigation controller.

You can find the PR here #76 

Mind sharing a bit more information about your applications view controller stack to see if it covers your scenario as well?

**Comment by zenangst** [comment]
@JeaSungLEE hey mate, do you still have these issues with the latest version of InjectionIII?

**Comment by JeaSungLEE** [comment]
Sorry to check this issue too late.
Tried it and it did not matter.
Thank you very much for giving a lot of care.

I will close the issue.
