### ISSUE TITLE
Trouble using the latest class for injection

### ISSUE THREAD

**Issue by zenangst** [johnno1962/InjectionIII#7]
Hey @johnno1962, I'm seeing some odd behavior when it comes to injecting a view in my application.
If I make a bunch of changes to a view and save, it looks like it jumps back and forwards between the old and the new version when saving. The console prints this message:

```
Loading /tmp/eval8.dylib. (Ignore any duplicate class warning)
objc[13219]: Class _TtC6APPNAME16HomeFeaturedView is implemented in both /Users/USERNAME/Library/Developer/CoreSimulator/Devices/A6B93370-670E-4F91-8872-86ED8976EB8C/data/Containers/Bundle/Application/43F0E90E-D203-424D-8B52-F81EF5436815/APPNAME/APPNAME (0x101350a90) and /tmp/eval8.dylib (0x127792680). One of the two will be used. Which one is undefined.
```

This is only a guess on my part but it seems like it cannot determine which of the class is the newest one, hence me getting variable results with what I see when the view (cell in this case) is being reloaded.

Any ideas on what could be the issue here?

**Comment by johnno1962** [comment]
This is probably to do with the instances isa. If it is a cell and created in a class that was injected this creates a hard reference to the class symbol which may or may not be the one you want. Best to keep cells and where they are created in separate files for they don’t get injected?

**Comment by zenangst** [comment]
Ah, what I tried to do was to make changes to the actual view and have the collection view for a new version of the view by reloading the index paths. I have made some changes to the framework that we use for rendering that might help to do what I want it to.

You might have some input if this is the best approach, you can find the PR for the framework here.

https://github.com/hyperoslo/Spots/pull/782/files

So, what the framework does when it receives the injection notification is to register the classes on the dequeuable view (table view or collection view) and then figure out which views are visible on screen, create index paths for them and finally call `reloadItems(at: indexPaths)`.

Does this some feasible to you to get injection built-in with the framework?

**Comment by zenangst** [comment]
I've been doing some more testing and I'm getting so varied results. I have one view that I can always injected and get the latest code injected as expected. The other view however only works to inject the first time then each time I save it, it will jump between the initial state and the first injection and completely ignores and other changes made to the view.

The views in question are both `UICollectionView`'s without any inheritance. The only difference that I saw was that one of the views has a delegate protocol in the same file. I tried to move that protocol to a separate file but it had no positive effect on the outcome.

**Comment by johnno1962** [comment]
Is this something which used to work in "Injection9"

**Comment by zenangst** [comment]
Now that you mention it, I didn't see these kinds of bugs before, but then again; different versions of Xcode and iOS/tvOS was used when testing it back then. I don't know how much that effects the outcome.

**Comment by johnno1962** [comment]
There could have been a difference. Is there any way you can answer this question easily?

**Comment by zenangst** [comment]
I can install the old version and see if it has the same outcome.
