### ISSUE TITLE
InjectionIll prevented clean uninstallation of Xcode 10

### ISSUE THREAD

**Issue by hrishidev** [johnno1962/InjectionIII#72]
I wanted to clean install Xcode 10.1 from OS X Mohave. Removed all files and data from library folders of Xcode 10.0. However, App Store was still showing Xcode as installed app and instead of showing it to install, Xcode was listed in updates.  After Investigation I realised that Injectionlll needs to be uninstalled as well. 
Can we trigger uninstallation of InjectionIII when Xcode is uninstalled? Or  script to uninstall Xcode along with InjectionIll?

**Comment by zenangst** [comment]
I don't completely follow here but you want to uninstall InjectionIII when Xcode is uninstalled? As in removed from your applications folder? If so, this is beyond the scope of the project and is limited by both sandboxing and how macOS works. Hope I didn't misunderstand anything here.

**Comment by zenangst** [comment]
@hrishidev care to elaborate a bit more on this?

**Comment by zenangst** [comment]
@hrishidev Well, when it comes to sandboxing, `InjectionIII` does not have permission to modify other applications. It can only write to its own sandbox (and a few exceptions, if you give it additional permissions).

This feels like an App Store caching issue than a problem with `InjectionIII` but there could be something that I'm not seeing here.

I found this that might be helpful: https://apple.stackexchange.com/questions/25333/app-store-thinks-apps-are-installed

**Comment by zenangst** [comment]
Closing this issue now, cheers! 😎
