### ISSUE TITLE
Initial setup question

### ISSUE THREAD

**Issue by robowen5mac** [johnno1962/InjectionIII#73]
Sorry for the newbie question, but I am working to install this tool on a machine for the first time and cannot get it to work. Running 10.13.6 or 10.14 with Xcode 10.1, I can download the InjectionIII application from the Mac App Store or from the link provided in this application. It run and creates the menu bar item with choices like Open Project, Open Recent and File Watcher (Run XProbe is greyed out). I downloaded the GettingStarted example from http://johnholdsworth.com/injection.html. If I try to open this project using the extensions Open project menu, the *.xcodeproject file is greyed out and selecting various levels of the project directory does not do anything, with and without Xcode open. The Menu icon remains blue no matter what I do and there are no options to Inject code, etc. I am guessing there is something I have wrong in my setup, but am at a loss. Any suggestions to get things started would be appreciated.

**Comment by zenangst** [comment]
Hey @robowen5mac, no questions are dumb, dumb is not asking questions :)

If you are using Xcode 10 on your machines, then you need to load the correct bundle when your application starts. I don't know which one is used in the getting started example but check the line `Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle")?.load()`.

So if you are using Xcode 10, you need to change this to `Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle")?.load()`.

Would you mind sharing any logs that you are getting when running the Xcode project, that usually helps to narrow things down :)

**Comment by robowen5mac** [comment]
Thanks. I updated the bundle path and no when the GettingStarted app launches , I am prompted to load the project directory and if I pick the top level directory, everything starts working. When I had read the install instructions I thought this set to load the bundle was optional:

>  Injection no longer requires you to change your project as for iOS is always available if you use the "Start Injection" menu (or type control-=) each time you start your app.
> 
> If you get tired of this or you want to develop 32 bit apps or tvOS or macOS you can and add one of the following to your applicationDidFinishLaunching:

Not sure if that is still the intended behaviour or if I misread things, but explicitly adding the call to load the bundle solved my issues.

**Comment by zenangst** [comment]
Hey mate, to clarify this a bit. The bundle can no longer be optional as it does some of the heavy liftings with InjectionIII. I think the statement/quote that you posted can come off as a bit confusing as it is legacy. When InjectionIII started to get distributed via the Mac App Store, @johnno1962 needs to change a bunch of things to abide by the sandboxing rules. One being, getting the user to grant permission to the Xcode project directory to give the file watcher access, and the bundle is needed in order to establish a connection between the iOS/tvOS/macOS app with the server (which is InjectionIII).

Hope that clarified it a tiny bit... or I might just have made things worse 😎

**Comment by robowen5mac** [comment]
Thanks. Appreciate the update and explanation. I would only suggest that the documentation be updated slightly to reflect the current requirements. Might save someone else some time in the future. Look forward to using this tool in my current project.

Sent from my iPhone, please forgive any typos.

On Nov 7, 2018, at 20:11, Christoffer Winterkvist <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey mate, to clarify this a bit. The bundle can no longer be optional as it does some of the heavy liftings with InjectionIII. I think the statement/quote that you posted can come off as a bit confusing as it is legacy. When InjectionIII started to get distributed via the Mac App Store, @johnno1962<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_johnno1962&d=DwMFaQ&c=UE1eNsedaKncO0Yl_u8bfw&r=Oe593mgUJNjEnc7SZG6tftllGlVQ8qinFhaiKvc32wI&m=evJa36Q6d4PP6hiyNQmJjNb0CFM1pEOk9JMLuKPceyQ&s=1JvOQOEddOI82XtOZQ3wfQHFjYG7GYMKXyjwwM8p-tk&e=> needs to change a bunch of things to abide by the sandboxing rules. One being, getting the user to grant permission to the Xcode project directory to give the file watcher access, and the bundle is needed in order to establish a connection between the iOS/tvOS/macOS app with the server (which is InjectionIII).

Hope that clarified it a tiny bit... or I might just have made things worse 😎

**Comment by zenangst** [comment]
@robowen5mac glad that the explanation help. Updating the README is... as always, on our todo list. Thanks for pointing it out!

**Comment by robowen5mac** [comment]
Thanks. Was just about to do a pull request, but see you already made the changes. Thanks for sorting it out so quickly.

**Comment by zenangst** [comment]
Closing this now ;)
