### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by pavm035** [johnno1962/InjectionIII#77]
** dlopen() error:dlopen(/Users/kumar.pavan/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib, 2): Symbol not found: _$SSo16UIViewControllerC13MyAppE11showPopover_11popoverSize10anchorView0I4Rect14arrowDirection15backgroundColor012shouldResizeF6Height10completionyAB_So6CGSizeVSo0A0CSo6CGRectVSo014UIPopoverArrowM0VSo7UIColorCSbyycSgtFfA3_
  Referenced from: /Users/kumar.pavan/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib
 in /Users/kumar.pavan/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib ***

**Comment by zenangst** [comment]
Hey @pavm035, mind sharing some more details about what you are trying to inject?

**Comment by pavm035** [comment]
I'm trying to use this in my existing project but for many view controllers i'm seeing above message but with different symbol missing in each controller

**Comment by pavm035** [comment]
@zenangst I'm not injecting anything instead trying out to test this plugin with my project and right now my controller just has 
`@objc func injected() {
        print("Hello")
    }`

**Comment by zenangst** [comment]
What kind of view controllers are you using?
Do they use generics or are any of the controllers annotated as final?

**Comment by zenangst** [comment]
At first glance, this looks similar to https://github.com/johnno1962/InjectionIII/issues/62

**Comment by pavm035** [comment]
@zenangst My View controller has some protocols and extensions and some methods with default parameters, also uses generics from base view controller but no final class... but some controllers is simple so they works fine

**Comment by johnno1962** [comment]
Is the method showPopover public?

**Comment by pavm035** [comment]
Thanks @zenangst  for your heads up i think in my case there are two problems 
1. Using default parameters
2. Generics 
i'm looking into similar approach mentioned in #62

**Comment by pavm035** [comment]
@johnno1962 Yes it's open method but the problem with default parameters it seems since that method has some default parameters hence causing issue

**Comment by jw10126121** [comment]
I had the same problem。
