### ISSUE TITLE
Duplicate Symbols found

### ISSUE THREAD

**Issue by pavm035** [johnno1962/InjectionIII#78]
objc[23642]: Class _TtC13Company18HomeViewController is implemented in both /Users/kumar.pavan/Library/Developer/CoreSimulator/Devices/8D170A74-292E-4696-B558-0A2263433E14/data/Containers/Bundle/Application/FD88D87D-63C1-4A7B-BF4E-5570BC025026/Company.app/CompanyApp (0x10bf65338) and /Users/kumar.pavan/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval104.dylib (0x149b6d590). One of the two will be used. Which one is undefined.

**Comment by zenangst** [comment]
These kinds of messages can be ignored and shouldn't affect injection. The reason for it being printed is because it is trying to load a class that is already apart of the project (which is what we want).
Do you see any negative effects in this particular case or does it work as intended?

**Comment by pavm035** [comment]
@zenangst Thanks for your quick reply but i haven't found any side effects from it but just wanted to know if there is any mysterious thing around this

**Comment by zenangst** [comment]
The messages are a bit vague I'm afraid, but if you scroll just above the message that you posted, there should be a message reading: `Loading .dylib - Ignore any duplicate class warning...`.
That comes from `InjectionIII` that the following message should be ignored.
Perhaps we could make that a bit more clear in future versions of the app, hope that clears things up :)

**Comment by pavm035** [comment]
@zenangst Thanks for the update

**Comment by johnno1962** [comment]
Seems like we should move the `Ignore any duplicate class warning.... ` part of the message until after the .dylib is loaded so people see it.

**Comment by zenangst** [comment]
I agree, I’ve also been playing with the idea to use the 💉 emoticon as a prefix to all log statements to make it clear who writes the message

**Comment by johnno1962** [comment]
You could try but some of the Objective-C code might object (It uses a printf() to avoid the timestamp)
