### ISSUE TITLE
Crash while injecting

### ISSUE THREAD

**Issue by pavm035** [johnno1962/InjectionIII#79]
MyProject/View/Bookmark/ItemBookmarkViewController.swift ***
objc[35468]: Class _TtC13MyProject26ItemBookmarkViewController is implemented in both ?? (0x7fea8302aa10) and ?? (0x7fea83b52010). One of the two will be used. Which one is undefined.
Injected 'MyProject.ItemBookmarkViewController'
<img width="549" alt="screen shot 2018-11-18 at 9 54 12" src="https://user-images.githubusercontent.com/6092412/48667409-2ce8d900-eb18-11e8-8d33-c2ddc343511b.png">

**Comment by zenangst** [comment]
@pavm035 a bit unsure about this one, looks similar to #68.

**Comment by zenangst** [comment]
@pavm035 you think you could provide me with an example project so that I can reproduce this and work on a fix?

**Comment by pavm035** [comment]
@zenangst Sorry It's my actual product but in example project it works fine i wonder this may not work with generics and default parameters methods

**Comment by zenangst** [comment]
Hey @pavm035, could you try this new version of `InjectionIII` to see if it doesn't work better for you.

https://www.dropbox.com/s/7stoecnf6uubno1/InjectionIII%20-%201.4%20Preview%202.zip?dl=0

**Comment by lcl2539** [comment]
Hello,I have the same problem.
Use new version can solve it
