### ISSUE TITLE
My project has no effect

### ISSUE THREAD

**Issue by kingsword** [johnno1962/InjectionIII#88]
I tried in my project but no effect, the injected method not called. But I copied the injected method and bundle load code to another project, it works fine. Can anyone give me some advice?
XCode 10.1, Objective-C

**Comment by zenangst** [comment]
Hey @kingsword,

Do you know if the bundle is loaded in the project where it does not work?
Do you get any log output when saving a file?
Would you mind sharing some code snippets from the class that you are trying to inject?

**Comment by zenangst** [comment]
@kingsword interesting, I haven't used `InjectionIII` with Objective-C in quite a while now.
It does look like it should work from all the log statements, except that the statement about the controller is missing.

I'm gonna try and investigate this further, stay tuned.

**Comment by kingsword** [comment]
@zenangst Thanks.

**Comment by zenangst** [comment]
@kingsword quick follow up. Life simply hasn't allowed me to test this yet. Sorry for the delay.
