### ISSUE TITLE
Injectionlll is damaged and can't be opened :/

### ISSUE THREAD

**Issue by s4cha** [johnno1962/InjectionIII#9]
Hi,

I'm having trouble  installing the binary listed in the README :/

<img width="459" alt="screen shot 2018-01-09 at 11 03 28" src="https://user-images.githubusercontent.com/1812953/34715393-d001eeca-f52c-11e7-9544-5bd8ccdeeadd.png">

I also tested on another computer with same result just to make sure :)

Cheers,

**Comment by johnno1962** [comment]
Odd, seems to be a problem with code signing. I've re-uploaded and get the same error even though unzipping the app on the local machine works fine. Can you try building from the repo while I look at it.

**Comment by s4cha** [comment]
@johnno1962 Sure, I need a Mac developer account right? (Only have an iOS one at the moment)

**Comment by johnno1962** [comment]
I’ve compared the zip and the uncompressed zip after download and everything is the same. The only solution seems to be to take it out of “quarantine”:

xattr -d com.apple.quarantine  /Users/johnholdsworth/Downloads/InjectionIII.app

**Comment by s4cha** [comment]
@johnno1962 works like a charm!
I am very excited about this new swift version, thank you so much for such a great piece of work :)
Have a fantastic year 2018 🍾
