### ISSUE TITLE
Running Injection with different XCode names.

### ISSUE THREAD

**Issue by gouen95** [johnno1962/InjectionIII#93]
I've been facing the same issue as the guy stated in the issue referenced below. Is there any workaround if I had to renamed my XCode so that I can keep the old copies and get Injection running?

[Issue #2 (comment-370702471)](https://github.com/johnno1962/InjectionIII/issues/2#issuecomment-370702471)

Thank you.

**Comment by johnno1962** [comment]
Hi, unfortunately, as Injection uses Swift you need to have Xcode at the default path.
