### ISSUE TITLE
XCode 10.1 - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by slum44** [johnno1962/InjectionIII#94]
Hi,

I have run into EXC_BAD_ACCESS on a project using XCode 10.1

I think it's directly related to XCode 10.1 as I have run the exact same codebase on XCode 10 and Injection works fine (I just upgraded to XCode 10.1 which is how I stumbled upon it).  After I uninstalled XCode 10.1 and went back to XCode 10, all is fine as well.

Below is the trace from EXC_BAD_ACCESS using XCode 10.1 from this codebase.

Any hints / suggestions on how to help track what's causing the issue?  I looked at previous GH issues with EXC_BAD_ACCESS but sadly didn't see anything that would be helpful with what I ran into

Thanks!

UIKitCore`UIApplicationMain:
    0x115514791 <+0>:   pushq  %rbp
    0x115514792 <+1>:   movq   %rsp, %rbp
    0x115514795 <+4>:   pushq  %r15
    0x115514797 <+6>:   pushq  %r14
    0x115514799 <+8>:   pushq  %r13
    0x11551479b <+10>:  pushq  %r12
    0x11551479d <+12>:  pushq  %rbx
    0x11551479e <+13>:  pushq  %rax
    0x11551479f <+14>:  movq   %rcx, %rbx
    0x1155147a2 <+17>:  movq   %rsi, -0x30(%rbp)
    0x1155147a6 <+21>:  movl   %edi, %r12d
    0x1155147a9 <+24>:  movq   0x892d10(%rip), %r13      ; (void *)0x000000010afadfa0: objc_retain
    0x1155147b0 <+31>:  movq   %rdx, %rdi
    0x1155147b3 <+34>:  callq  *%r13
    0x1155147b6 <+37>:  movq   %rax, %r14
    0x1155147b9 <+40>:  movq   %rbx, %rdi
    0x1155147bc <+43>:  callq  *%r13
    0x1155147bf <+46>:  movq   %rax, %r15
    0x1155147c2 <+49>:  movl   0xceb21c(%rip), %eax      ; _UIApplicationLinkedOnVersion
    0x1155147c8 <+55>:  testl  %eax, %eax
    0x1155147ca <+57>:  je     0x11551483f               ; <+174>
    0x1155147cc <+59>:  cmpl   $0x20100, %eax            ; imm = 0x20100 
    0x1155147d1 <+64>:  jb     0x1155147f7               ; <+102>
    0x1155147d3 <+66>:  callq  0x115a97a92               ; symbol stub for: objc_autoreleasePoolPush
    0x1155147d8 <+71>:  movq   %rax, %r13
    0x1155147db <+74>:  movl   %r12d, %edi
    0x1155147de <+77>:  movq   -0x30(%rbp), %rsi
    0x1155147e2 <+81>:  movq   %r14, %rdx
    0x1155147e5 <+84>:  movq   %r15, %rcx
    0x1155147e8 <+87>:  callq  0x115514869               ; _UIApplicationMainPreparations
    0x1155147ed <+92>:  movq   %r13, %rdi
    0x1155147f0 <+95>:  callq  0x115a97a8c               ; symbol stub for: objc_autoreleasePoolPop
    0x1155147f5 <+100>: jmp    0x115514809               ; <+120>
    0x1155147f7 <+102>: movl   %r12d, %edi
    0x1155147fa <+105>: movq   -0x30(%rbp), %rsi
    0x1155147fe <+109>: movq   %r14, %rdx
    0x115514801 <+112>: movq   %r15, %rcx
    0x115514804 <+115>: callq  0x115514869               ; _UIApplicationMainPreparations
    0x115514809 <+120>: movq   0xceb190(%rip), %rdi      ; UIApp
    0x115514810 <+127>: movq   0xc5f841(%rip), %rsi      ; "_run"
    0x115514817 <+134>: callq  *0x892c93(%rip)           ; (void *)0x000000010afb0d80: objc_msgSend
    0x11551481d <+140>: movq   0x892c94(%rip), %rbx      ; (void *)0x000000010afae010: objc_release
    0x115514824 <+147>: movq   %r15, %rdi
    0x115514827 <+150>: callq  *%rbx
    0x115514829 <+152>: movq   %r14, %rdi
    0x11551482c <+155>: callq  *%rbx
    0x11551482e <+157>: xorl   %eax, %eax
    0x115514830 <+159>: addq   $0x8, %rsp
    0x115514834 <+163>: popq   %rbx
    0x115514835 <+164>: popq   %r12
    0x115514837 <+166>: popq   %r13
    0x115514839 <+168>: popq   %r14
    0x11551483b <+170>: popq   %r15
    0x11551483d <+172>: popq   %rbp
    0x11551483e <+173>: retq   
    0x11551483f <+174>: cmpq   $-0x1, 0xce7cf9(%rip)     ; WebKitSetIsClassic + 7
    0x115514847 <+182>: jne    0x115514854               ; <+195>
    0x115514849 <+184>: movl   0xceb195(%rip), %eax      ; _UIApplicationLinkedOnVersion
    0x11551484f <+190>: jmp    0x1155147cc               ; <+59>
    0x115514854 <+195>: leaq   0xce7ce5(%rip), %rdi      ; _UIApplicationLinkedOnVersionOnce
    0x11551485b <+202>: leaq   0x8d489e(%rip), %rsi      ; __block_literal_global.1518
    0x115514862 <+209>: callq  0x115a977c2               ; symbol stub for: dispatch_once
    0x115514867 <+214>: jmp    0x115514849               ; <+184>

**Comment by johnno1962** [comment]
Hi, never seen this issue before. When does it crash? When you do the injection? Are you using an @objc injected() method?

**Comment by slum44** [comment]
Hello, correct it crashes when I save file + injection kicked off.

Yes, using @objc injected() and only change was going from XCode 10 to 10.1

To be more precise, I have 4x ViewControllers with @objc injected() implemented and all they do is  call viewDidLoad ie:

    @objc func injected() {
        viewDidLoad()
    }

Thanks

**Comment by johnno1962** [comment]
I’d suggest subscribing to INJECTION_BUNDLE_NOTIFICATION instead of injected().

**Comment by slum44** [comment]
Hello, sorry for the late reply - just been a bit busy.  I tried this and that worked a treat.  Thanks and thanks for your excellent project.
