### ISSUE TITLE
Inject storyboard: no such file or directory

### ISSUE THREAD

**Issue by acecilia** [johnno1962/InjectionIII#97]
I have InjectionIII up and running properly with code. When I edit a storyboard and save it, the injection stops working and the following line appears on the debug terminal:

```
/bin/bash: line 0: cd: /Users/andres/Library/Developer/Xcode/DerivedData/someRandomStringkiadjsflkasnf/Build/Products/Debug-iphonesimulator/App\ Name.app: No such file or directory
```

The following command executes without problems:

```
cd /Users/andres/Library/Developer/Xcode/DerivedData/someRandomStringkiadjsflkasnf/Build/Products/Debug-iphonesimulator/App\ Name.app
```

Note the app name has a space. Any idea of whats going on?
Thanks :)

**Comment by zenangst** [comment]
@acecilia hey mate, sorry for the delay. Have you tried removing the space from the target name to help out `InjectionIII` resolve the correct path?

**Comment by acecilia** [comment]
@zenangst I did not try, and at the moment I am not going to be able to give it a shot. Feel free to close the issue, thanks for the answer!
