### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by frostd17** [johnno1962/InjectionIII#99]
After saving changes in a swift file i get the following error: 

💉 *** Compiling path/file.swift ***
/bin/bash: App-Swift.h: No such file or directory
💉 *** Re-compilation failed (path/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
 ***

**Comment by acecilia** [comment]
See https://github.com/johnno1962/InjectionIII/issues/95. Your filename in the Xcode project has to be exactly the same (also capitals - very important!! -) as the path on disk. Compare the full path on disk of the file "App-Swift.h" with the full path on the Xcode project.

**Comment by zenangst** [comment]
@frostd17 did you manage to solve this?

**Comment by julestburt** [comment]
Solved. Thx. I found some of my class files which were referenced inside Xcode appeared to start with Capitals, yet when 'shown in the finder' the files were actually starting with a lower case letter. Renamed files - fixed!
